# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('component_updates', '0001_initial'),
        ('design', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='componentregistry',
            name='footer_template',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_entry', to='design.footertemplate'),
        ),
        migrations.AddField(
            model_name='componentregistry',
            name='header_template',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_entry', to='design.headertemplate'),
        ),
        migrations.AddField(
            model_name='componentregistry',
            name='theme',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_entry', to='design.theme'),
        ),
        migrations.AddField(
            model_name='componentdependency',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='component_updates.componentregistry'),
        ),
        migrations.AddField(
            model_name='componentdependency',
            name='depends_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='component_updates.componentregistry'),
        ),
        migrations.AddField(
            model_name='componentversion',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='component_updates.componentregistry'),
        ),
        migrations.AddField(
            model_name='componentversion',
            name='installed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_installations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platformupdate',
            name='initiated_by',
            field=models.ForeignKey(blank=True, help_text='Admin who initiated the update', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='componentregistry',
            name='update_channel',
            field=models.ForeignKey(blank=True, help_text='Update channel to follow', null=True, on_delete=django.db.models.deletion.SET_NULL, to='component_updates.updatechannel'),
        ),
        migrations.AddField(
            model_name='updatelog',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_logs', to='component_updates.componentregistry'),
        ),
        migrations.AddField(
            model_name='updatelog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_update_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='componentdependency',
            unique_together={('component', 'depends_on')},
        ),
        migrations.AlterUniqueTogether(
            name='componentversion',
            unique_together={('component', 'version')},
        ),
        migrations.AddIndex(
            model_name='platformupdate',
            index=models.Index(fields=['status', '-created_at'], name='component_u_status_3382ad_idx'),
        ),
        migrations.AddIndex(
            model_name='platformupdate',
            index=models.Index(fields=['-created_at'], name='component_u_created_3fbcaa_idx'),
        ),
        migrations.AddIndex(
            model_name='componentregistry',
            index=models.Index(fields=['component_type', 'slug'], name='component_u_compone_22265b_idx'),
        ),
        migrations.AddIndex(
            model_name='componentregistry',
            index=models.Index(fields=['update_available'], name='component_u_update__7db670_idx'),
        ),
        migrations.AddIndex(
            model_name='componentregistry',
            index=models.Index(fields=['auto_update'], name='component_u_auto_up_5f0e8a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='componentregistry',
            unique_together={('component_type', 'slug')},
        ),
        migrations.AddIndex(
            model_name='updatelog',
            index=models.Index(fields=['component', '-started_at'], name='component_u_compone_c139be_idx'),
        ),
        migrations.AddIndex(
            model_name='updatelog',
            index=models.Index(fields=['status'], name='component_u_status_f501d8_idx'),
        ),
        migrations.AddIndex(
            model_name='updatelog',
            index=models.Index(fields=['action'], name='component_u_action_b4c535_idx'),
        ),
    ]
