# Generated by Django 5.1.4 on 2026-03-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component_updates', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentregistry',
            name='component_type',
            field=models.CharField(choices=[('widget', 'Widget'), ('theme', 'Theme'), ('utility', 'Page Builder Utility'), ('element', 'Page Builder Element'), ('header_template', 'Header Template'), ('footer_template', 'Footer Template'), ('shipping_provider', 'Shipping Provider'), ('email_provider', 'Email Provider'), ('sms_provider', 'SMS Provider'), ('exchange_rate_provider', 'Exchange Rate Provider'), ('payment_provider', 'Payment Provider'), ('product_feed_provider', 'Product Feed Provider'), ('terminal_provider', 'Terminal Provider'), ('seo_generator_provider', 'SEO Generator Provider'), ('translation_provider', 'Translation Provider')], db_index=True, help_text='Type of component', max_length=50),
        ),
    ]
