# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('component_updates', '0002_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('pos_receipt', 'POS Receipt'), ('order_confirmation', 'Order Confirmation'), ('shipping_update', 'Shipping Update'), ('delivery_notification', 'Delivery Notification'), ('password_reset', 'Password Reset'), ('verification_code', 'Verification Code'), ('marketing', 'Marketing'), ('custom', 'Custom')], max_length=50, unique=True, verbose_name='Template Type')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('message', models.TextField(help_text='Message template. Use {variable} syntax for placeholders.', verbose_name='Message')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Template',
                'verbose_name_plural': 'SMS Templates',
                'ordering': ['template_type'],
            },
        ),
        migrations.CreateModel(
            name='SMSProviderAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_key', models.CharField(help_text='SMS/messaging service provider', max_length=50, verbose_name='Provider')),
                ('display_name', models.CharField(help_text='Friendly name for this account', max_length=100, verbose_name='Display Name')),
                ('credentials', models.BinaryField(help_text='Encrypted API credentials for this provider', verbose_name='Encrypted Credentials')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_default_sms', models.BooleanField(default=False, help_text='Use this account for sending SMS by default', verbose_name='Default SMS Account')),
                ('is_default_whatsapp', models.BooleanField(default=False, help_text='Use this account for sending WhatsApp messages by default', verbose_name='Default WhatsApp Account')),
                ('connection_status', models.CharField(choices=[('untested', 'Untested'), ('success', 'Connected'), ('failed', 'Connection Failed')], default='untested', max_length=20, verbose_name='Connection Status')),
                ('last_checked', models.DateTimeField(blank=True, null=True, verbose_name='Last Checked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(blank=True, help_text='Reference to installed provider component', limit_choices_to={'component_type': 'sms_provider'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_accounts', to='component_updates.componentregistry', verbose_name='Provider Component')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sms_accounts', to='sites.site')),
            ],
            options={
                'verbose_name': 'SMS Provider Account',
                'verbose_name_plural': 'SMS Provider Accounts',
                'ordering': ['-is_default_sms', '-is_default_whatsapp', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='SMSOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='sms', max_length=20, verbose_name='Message Type')),
                ('phone', models.CharField(help_text='Recipient phone number in E.164 format', max_length=20, verbose_name='Phone Number')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20, verbose_name='Status')),
                ('provider_message_id', models.CharField(blank=True, help_text='Message ID from the SMS provider', max_length=100, verbose_name='Provider Message ID')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('skip_reason', models.CharField(blank=True, help_text='Reason why SMS was skipped (e.g., user_preference_disabled, unsubscribed)', max_length=100, verbose_name='Skip Reason')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Retry Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True, verbose_name='Queued At')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sms_outbox', to='sites.site')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='sms_system.smsprovideraccount', verbose_name='Provider Account')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='sms_system.smstemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'SMS Outbox',
                'verbose_name_plural': 'SMS Outbox',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='sms_system__status_7fd556_idx'), models.Index(fields=['phone'], name='sms_system__phone_3fb35f_idx'), models.Index(fields=['provider_message_id'], name='sms_system__provide_5ba03a_idx')],
            },
        ),
    ]
