# Generated by Django 5.1.4 on 2026-03-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsoutbox',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('sandbox_logged', 'Sandbox Logged')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
