# Generated by Django 5.1.4 on 2026-03-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeometryAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g., "V-Neck Collar"', max_length=200, verbose_name='Label')),
                ('target_node', models.CharField(help_text='Which base model node to replace.', max_length=200, verbose_name='Target Node')),
                ('node_data', models.JSONField(blank=True, default=dict, help_text='Parsed node names from this GLB.', verbose_name='Node Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Geometry Asset',
                'verbose_name_plural': 'Geometry Assets',
            },
        ),
        migrations.CreateModel(
            name='NodeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('material_color', 'Material Color'), ('material_texture', 'Material Texture'), ('geometry_swap', 'Geometry Swap'), ('visibility', 'Visibility')], max_length=20, verbose_name='Action Type')),
                ('target_node', models.CharField(help_text='Scene graph node name from the parsed node tree.', max_length=200, verbose_name='Target Node')),
                ('action_data', models.JSONField(default=dict, help_text='Action-specific payload (color, texture URLs, GLB URL, visibility).', verbose_name='Action Data')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Node Mapping',
                'verbose_name_plural': 'Node Mappings',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SceneConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_tree', models.JSONField(blank=True, default=dict, help_text='Parsed scene graph from the GLB file (auto-populated).', verbose_name='Node Tree')),
                ('camera_orbit', models.CharField(default='0deg 75deg 2m', help_text='model-viewer camera-orbit attribute.', max_length=100, verbose_name='Camera Orbit')),
                ('camera_target', models.CharField(default='0m 0m 0m', help_text='model-viewer camera-target attribute.', max_length=100, verbose_name='Camera Target')),
                ('exposure', models.FloatField(default=1.0, verbose_name='Exposure')),
                ('shadow_intensity', models.FloatField(default=0.5, verbose_name='Shadow Intensity')),
                ('shadow_softness', models.FloatField(default=0.5, help_text='Shadow blur amount. 0 = sharp, 1 = soft.', verbose_name='Shadow Softness')),
                ('tone_mapping', models.CharField(default='commerce', help_text='Color grading algorithm. Commerce = vibrant, Neutral = accurate, ACES = cinematic.', max_length=20, verbose_name='Tone Mapping')),
                ('bloom_strength', models.FloatField(default=0.0, help_text='Glow intensity for emissive materials. 0 = off, 1-5 = subtle to dramatic.', verbose_name='Bloom Strength')),
                ('auto_rotate', models.BooleanField(default=True, verbose_name='Auto Rotate')),
                ('ar_enabled', models.BooleanField(default=True, help_text='Enable augmented reality viewing on supported devices.', verbose_name='AR Enabled')),
                ('background_color', models.CharField(default='#ffffff', help_text='Solid hex color or CSS gradient.', max_length=512, verbose_name='Background')),
                ('is_enabled', models.BooleanField(default=True, help_text='When disabled, the product uses the standard 2D configurator.', verbose_name='Enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '3D Scene Configuration',
                'verbose_name_plural': '3D Scene Configurations',
            },
        ),
        migrations.CreateModel(
            name='TextureAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g., "Red Leather"', max_length=200, verbose_name='Label')),
                ('texture_type', models.CharField(choices=[('base_color', 'Base Color'), ('normal', 'Normal Map'), ('roughness', 'Roughness Map'), ('metalness', 'Metalness Map'), ('ao', 'Ambient Occlusion'), ('emissive', 'Emissive Map')], max_length=20, verbose_name='Texture Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Texture Asset',
                'verbose_name_plural': 'Texture Assets',
            },
        ),
    ]
