# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('configurator_3d', '0001_initial'),
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geometryasset',
            name='media_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='geometry_usages', to='media_library.mediaasset', verbose_name='GLB File'),
        ),
        migrations.AddField(
            model_name='nodemapping',
            name='slot_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_mappings', to='catalog.configurationslotoption', verbose_name='Slot Option'),
        ),
        migrations.AddField(
            model_name='sceneconfig',
            name='base_model',
            field=models.ForeignKey(blank=True, help_text='The main GLB file containing the assembled 3D model.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scene_configs', to='media_library.mediaasset', verbose_name='Base 3D Model'),
        ),
        migrations.AddField(
            model_name='sceneconfig',
            name='environment_image',
            field=models.ForeignKey(blank=True, help_text='HDR environment map for image-based lighting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset', verbose_name='Environment Image'),
        ),
        migrations.AddField(
            model_name='sceneconfig',
            name='product',
            field=models.OneToOneField(limit_choices_to={'product_type': 'configurable'}, on_delete=django.db.models.deletion.CASCADE, related_name='scene_3d', to='catalog.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='sceneconfig',
            name='thumbnail',
            field=models.ForeignKey(blank=True, help_text='Preview screenshot captured from the 3D viewer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset', verbose_name='Thumbnail'),
        ),
        migrations.AddField(
            model_name='nodemapping',
            name='scene_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='configurator_3d.sceneconfig', verbose_name='Scene Config'),
        ),
        migrations.AddField(
            model_name='geometryasset',
            name='scene_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometry_assets', to='configurator_3d.sceneconfig', verbose_name='Scene Config'),
        ),
        migrations.AddField(
            model_name='textureasset',
            name='media_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='texture_usages', to='media_library.mediaasset', verbose_name='Texture Image'),
        ),
        migrations.AddField(
            model_name='textureasset',
            name='scene_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textures', to='configurator_3d.sceneconfig', verbose_name='Scene Config'),
        ),
        migrations.AddIndex(
            model_name='nodemapping',
            index=models.Index(fields=['scene_config', 'slot_option'], name='configurato_scene_c_1d1e22_idx'),
        ),
    ]
