# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
import uuid
import webhooks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='A friendly name to identify this webhook endpoint', max_length=255, verbose_name='name')),
                ('url', models.URLField(help_text='The URL that will receive webhook POST requests', max_length=2048, verbose_name='URL')),
                ('secret', models.CharField(default=webhooks.models.generate_webhook_secret, help_text='Secret key used for HMAC signature verification', max_length=64, verbose_name='secret')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this endpoint is currently receiving webhooks', verbose_name='active')),
                ('events', models.JSONField(default=list, help_text='List of event types this endpoint is subscribed to', verbose_name='subscribed events')),
                ('max_retries', models.PositiveIntegerField(default=5, help_text='Maximum number of retry attempts for failed deliveries', verbose_name='max retries')),
                ('timeout_seconds', models.PositiveIntegerField(default=30, help_text='Timeout in seconds for webhook requests', verbose_name='timeout (seconds)')),
                ('description', models.TextField(blank=True, help_text='Optional description of this webhook endpoint', verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('last_triggered_at', models.DateTimeField(blank=True, help_text='When this endpoint last received a webhook', null=True, verbose_name='last triggered')),
                ('consecutive_failures', models.PositiveIntegerField(default=0, help_text='Number of consecutive failed delivery attempts', verbose_name='consecutive failures')),
                ('is_disabled_by_failures', models.BooleanField(default=False, help_text='Whether this endpoint was auto-disabled due to failures', verbose_name='disabled by failures')),
            ],
            options={
                'verbose_name': 'webhook endpoint',
                'verbose_name_plural': 'webhook endpoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, help_text='The type of event that triggered this delivery', max_length=100, verbose_name='event type')),
                ('payload', models.JSONField(help_text='The JSON payload sent to the webhook endpoint', verbose_name='payload')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('response_status_code', models.PositiveIntegerField(blank=True, help_text='HTTP status code from the webhook receiver', null=True, verbose_name='response status code')),
                ('response_body', models.TextField(blank=True, help_text='Response body from the webhook receiver (truncated)', verbose_name='response body')),
                ('response_headers', models.JSONField(blank=True, default=dict, help_text='Response headers from the webhook receiver', verbose_name='response headers')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, help_text='Time taken for the webhook request in milliseconds', null=True, verbose_name='response time (ms)')),
                ('error_message', models.TextField(blank=True, help_text='Error message if delivery failed', verbose_name='error message')),
                ('attempt_count', models.PositiveIntegerField(default=0, help_text='Number of delivery attempts made', verbose_name='attempt count')),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, help_text='When the next retry attempt will be made', null=True, verbose_name='next retry at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When the webhook was successfully delivered', null=True, verbose_name='delivered at')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.webhookendpoint', verbose_name='endpoint')),
            ],
            options={
                'verbose_name': 'webhook delivery',
                'verbose_name_plural': 'webhook deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='webhooks_we_status_eb2625_idx'), models.Index(fields=['endpoint', 'created_at'], name='webhooks_we_endpoin_2b680e_idx'), models.Index(fields=['event_type', 'created_at'], name='webhooks_we_event_t_599af1_idx')],
            },
        ),
    ]
