# Generated by Django 5.1.4 on 2026-03-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('sandbox_blocked', 'Sandbox Blocked')], db_index=True, default='pending', max_length=20, verbose_name='status'),
        ),
    ]
