# Generated by Django 5.1.4 on 2026-05-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprovideraccount',
            name='available_payment_methods',
            field=models.JSONField(blank=True, default=dict, help_text='Payment methods available from provider API, organized by country. Use "_global" key for methods available regardless of country. Format: {"_global": ["card", "apple_pay"], "SG": ["card", "paynow"]}', verbose_name='available payment methods'),
        ),
        migrations.AlterField(
            model_name='paymentprovideraccount',
            name='enabled_payment_methods',
            field=models.JSONField(blank=True, default=dict, help_text='Payment methods enabled by merchant. Use "_global" for all countries, or per-country keys to override. Format: {"_global": ["card", "apple_pay"], "SG": ["card"]}', verbose_name='enabled payment methods'),
        ),
    ]
