# Generated by Django 5.1.4 on 2026-07-20 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_gift_cards_tax_exempt_by_default'),
        ('catalog', '0007_giftcard_issue_idempotency'),
        ('orders', '0004_add_gift_card_data'),
        ('payment_providers', '0003_add_tender_support'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='wallet',
            field=models.ForeignKey(blank=True, help_text='Customer wallet this tender draws on', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tender_transactions', to='wallet.customerwallet', verbose_name='wallet'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['wallet', 'status'], name='pp_txn_wallet_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tender_type', 'wallet'), _negated=True), ('wallet__isnull', False), _connector='OR'), name='pp_txn_wallet_tender_needs_wallet'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('tender_type', 'wallet'), ('wallet__isnull', True), _connector='OR'), name='pp_txn_wallet_only_on_wallet_tender'),
        ),
    ]
