# Generated by Django 5.1.4 on 2026-03-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasebackup',
            name='file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='databasebackup',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='systemupgrade',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preflight', 'Running Preflight Checks'), ('backup', 'Creating Backup'), ('draining', 'Draining Celery Tasks'), ('maintenance', 'Enabling Maintenance Mode'), ('pulling', 'Pulling New Images'), ('upgrading', 'Upgrading Containers'), ('migrating', 'Running Migrations'), ('finalizing', 'Finalizing'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolling_back', 'Rolling Back'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20),
        ),
    ]
