# Generated by Django 5.1.4 on 2026-03-13 13:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_databasebackup_file_path_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentbackup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('compressing', 'Compressing'), ('encrypting', 'Encrypting'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='RemoteStorageDestination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly name for this destination', max_length=200, verbose_name='destination name')),
                ('provider_type', models.CharField(choices=[('s3', 'Amazon S3 / S3-Compatible'), ('sftp', 'SFTP'), ('google_drive', 'Google Drive'), ('dropbox', 'Dropbox')], max_length=20, verbose_name='storage type')),
                ('credentials_encrypted', models.JSONField(default=dict, verbose_name='encrypted credentials')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='provider settings')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_default', models.BooleanField(default=False, help_text='Automatically upload all backups to this destination', verbose_name='default destination')),
                ('connection_status', models.CharField(choices=[('unknown', 'Unknown'), ('connected', 'Connected'), ('error', 'Error')], default='unknown', max_length=20)),
                ('connection_error', models.TextField(blank=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_upload_at', models.DateTimeField(blank=True, null=True)),
                ('last_upload_size', models.BigIntegerField(blank=True, null=True)),
                ('total_uploads', models.IntegerField(default=0)),
                ('total_bytes_uploaded', models.BigIntegerField(default=0)),
                ('retention_days', models.IntegerField(default=0, help_text='Delete remote backups older than this many days. 0 = keep forever.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remote Storage Destination',
                'verbose_name_plural': 'Remote Storage Destinations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='backupschedule',
            name='remote_destinations',
            field=models.ManyToManyField(blank=True, help_text='Upload scheduled backups to these destinations', related_name='backup_schedules', to='management.remotestoragedestination', verbose_name='remote destinations'),
        ),
        migrations.CreateModel(
            name='BackupRemoteUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('remote_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('progress_percent', models.IntegerField(default=0)),
                ('task_id', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_uploads', to='management.deploymentbackup')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='management.remotestoragedestination')),
            ],
            options={
                'verbose_name': 'Backup Remote Upload',
                'verbose_name_plural': 'Backup Remote Uploads',
                'ordering': ['-created_at'],
                'unique_together': {('backup', 'destination')},
            },
        ),
    ]
