# Generated by Django 5.1.4 on 2026-03-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remote_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupschedule',
            name='s3_bucket',
        ),
        migrations.RemoveField(
            model_name='backupschedule',
            name='s3_prefix',
        ),
        migrations.RemoveField(
            model_name='backupschedule',
            name='upload_to_s3',
        ),
        migrations.RemoveField(
            model_name='deploymentbackup',
            name='s3_path',
        ),
    ]
