# Generated by Django 5.1.4 on 2026-03-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_s3_stub_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemrestore',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirming', 'Awaiting Confirmation'), ('backup', 'Creating Safety Backup'), ('downloading', 'Downloading from Remote Storage'), ('decrypting', 'Decrypting'), ('extracting', 'Extracting'), ('restoring_db', 'Restoring Database'), ('restoring_media', 'Restoring Media'), ('restoring_config', 'Restoring Configuration'), ('post_restore', 'Running Post-Restore Tasks'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
