"""
Permission category definitions.

Each category maps to a set of Django model permissions at two levels:
- 'view': Read-only access (view_* permissions)
- 'full': Read + write + delete (view_*, add_*, change_*, delete_* permissions)

Merchants see these friendly categories instead of raw Django permissions.
When a StaffRole is saved, the selected categories are resolved to actual
Django Permission objects and synced to the linked Group.
"""

from django.utils.translation import gettext_lazy as _

PERMISSION_CATEGORIES = {
    "catalog": {
        "label": _("Product Catalog"),
        "icon": "fas fa-box-open",
        "description": _(
            "Products, categories, brands, attributes, stock, digital assets, and 3D configurator"
        ),
        "sort_order": 1,
        "permissions": {
            "view": [
                "catalog.view_product",
                "catalog.view_category",
                "catalog.view_brand",
                "catalog.view_collection",
                "catalog.view_productattribute",
                "catalog.view_attributevalue",
                "catalog.view_productimage",
                "catalog.view_productvariant",
                "catalog.view_productprice",
                "catalog.view_stockitem",
                "catalog.view_stockmovement",
                "catalog.view_warehouse",
                "catalog.view_salesregion",
                "catalog.view_digitalasset",
                "catalog.view_licenseprovider",
                "catalog.view_licensekey",
                "catalog.view_licensekeytemplate",
                "catalog.view_licensepool",
                "catalog.view_customizationoption",
                "catalog.view_bundleitem",
                "catalog.view_productreview",
                "catalog.view_giftcard",
                "catalog.view_giftcardtransaction",
                # 3D Configurator
                "configurator_3d.view_sceneconfig",
            ],
            "full": [
                "catalog.add_product",
                "catalog.change_product",
                "catalog.delete_product",
                "catalog.add_category",
                "catalog.change_category",
                "catalog.delete_category",
                "catalog.add_brand",
                "catalog.change_brand",
                "catalog.delete_brand",
                "catalog.add_collection",
                "catalog.change_collection",
                "catalog.delete_collection",
                "catalog.add_productattribute",
                "catalog.change_productattribute",
                "catalog.delete_productattribute",
                "catalog.add_attributevalue",
                "catalog.change_attributevalue",
                "catalog.delete_attributevalue",
                "catalog.add_productimage",
                "catalog.change_productimage",
                "catalog.delete_productimage",
                "catalog.add_productvariant",
                "catalog.change_productvariant",
                "catalog.delete_productvariant",
                "catalog.add_productprice",
                "catalog.change_productprice",
                "catalog.delete_productprice",
                "catalog.add_stockitem",
                "catalog.change_stockitem",
                "catalog.delete_stockitem",
                "catalog.add_stockmovement",
                "catalog.change_stockmovement",
                "catalog.add_warehouse",
                "catalog.change_warehouse",
                "catalog.delete_warehouse",
                "catalog.add_salesregion",
                "catalog.change_salesregion",
                "catalog.delete_salesregion",
                "catalog.add_digitalasset",
                "catalog.change_digitalasset",
                "catalog.delete_digitalasset",
                "catalog.change_licenseprovider",
                "catalog.change_licensekey",
                "catalog.change_licensekeytemplate",
                "catalog.change_licensepool",
                "catalog.add_customizationoption",
                "catalog.change_customizationoption",
                "catalog.delete_customizationoption",
                "catalog.add_bundleitem",
                "catalog.change_bundleitem",
                "catalog.delete_bundleitem",
                "catalog.change_productreview",
                "catalog.delete_productreview",
                "catalog.add_giftcard",
                "catalog.change_giftcard",
                # 3D Configurator
                "configurator_3d.add_sceneconfig",
                "configurator_3d.change_sceneconfig",
                "configurator_3d.delete_sceneconfig",
            ],
        },
    },
    "orders": {
        "label": _("Orders & Fulfillment"),
        "icon": "fas fa-shopping-cart",
        "description": _("Orders, refunds, returns, shipments, and shipping configuration"),
        "sort_order": 2,
        "permissions": {
            "view": [
                "orders.view_order",
                "orders.view_orderitem",
                "orders.view_ordernote",
                "orders.view_refund",
                "orders.view_returnrequest",
                "orders.view_address",
                "cart.view_cart",
                "cart.view_cartitem",
                "cart.view_shippingmethod",
                "cart.view_taxrate",
                "shipping.view_shipment",
                "shipping.view_provideraccount",
                "shipping.view_carrierpreset",
                "shipping.view_shippingpackage",
                "shipping.view_shippingzone",
                "shipping.view_shippingpromotion",
                "shipping.view_shippingratetable",
                "shipping.view_trackingevent",
                "shipping.view_webhooklog",
                "shipping.view_shippingcountry",
            ],
            "full": [
                "orders.change_order",
                "orders.add_ordernote",
                "orders.change_ordernote",
                "orders.add_refund",
                "orders.change_refund",
                "orders.add_returnrequest",
                "orders.change_returnrequest",
                "cart.change_cart",
                "cart.add_shippingmethod",
                "cart.change_shippingmethod",
                "cart.delete_shippingmethod",
                "cart.add_taxrate",
                "cart.change_taxrate",
                "cart.delete_taxrate",
                "shipping.add_shipment",
                "shipping.change_shipment",
                "shipping.add_provideraccount",
                "shipping.change_provideraccount",
                "shipping.add_carrierpreset",
                "shipping.change_carrierpreset",
                "shipping.add_shippingpackage",
                "shipping.change_shippingpackage",
                "shipping.add_shippingzone",
                "shipping.change_shippingzone",
                "shipping.delete_shippingzone",
                "shipping.add_shippingpromotion",
                "shipping.change_shippingpromotion",
                "shipping.delete_shippingpromotion",
                "shipping.add_shippingratetable",
                "shipping.change_shippingratetable",
                "shipping.delete_shippingratetable",
            ],
        },
    },
    "customers": {
        "label": _("Customers"),
        "icon": "fas fa-users",
        "description": _("Customer profiles, segments, analytics, and messages"),
        "sort_order": 3,
        "permissions": {
            "view": [
                "accounts.view_customerprofile",
                "customers.view_customersegment",
                "customers.view_customermetrics",
                "customers.view_customernote",
                "customers.view_abandonedcart",
                # Customer messages
                "admin_api.view_customermessage",
            ],
            "full": [
                "accounts.change_customerprofile",
                "customers.add_customersegment",
                "customers.change_customersegment",
                "customers.delete_customersegment",
                "customers.change_customermetrics",
                "customers.add_customernote",
                "customers.change_customernote",
                "customers.delete_customernote",
                # Customer messages
                "admin_api.change_customermessage",
            ],
        },
    },
    "content": {
        "label": _("Content & Pages"),
        "icon": "fas fa-file-alt",
        "description": _("Pages, blog posts, announcements, and forms"),
        "sort_order": 4,
        "permissions": {
            "view": [
                "page_builder.view_page",
                "page_builder.view_pagetemplate",
                "page_builder.view_element",
                "blog.view_blogpost",
                "blog.view_blogcategory",
                "blog.view_blogtag",
                "blog.view_blogsubscriber",
                "blog.view_blogsettings",
                "announcements.view_announcement",
                "form_builder.view_form",
                "form_builder.view_formresponse",
                "element_builder.view_customelement",
            ],
            "full": [
                "page_builder.add_page",
                "page_builder.change_page",
                "page_builder.delete_page",
                "page_builder.add_pagetemplate",
                "page_builder.change_pagetemplate",
                "page_builder.delete_pagetemplate",
                "page_builder.add_element",
                "page_builder.change_element",
                "page_builder.delete_element",
                "blog.add_blogpost",
                "blog.change_blogpost",
                "blog.delete_blogpost",
                "blog.add_blogcategory",
                "blog.change_blogcategory",
                "blog.delete_blogcategory",
                "blog.add_blogtag",
                "blog.change_blogtag",
                "blog.delete_blogtag",
                "blog.change_blogsettings",
                "announcements.add_announcement",
                "announcements.change_announcement",
                "announcements.delete_announcement",
                "form_builder.add_form",
                "form_builder.change_form",
                "form_builder.delete_form",
                "element_builder.add_customelement",
                "element_builder.change_customelement",
                "element_builder.delete_customelement",
            ],
        },
    },
    "design": {
        "label": _("Design & Theme"),
        "icon": "fas fa-paint-brush",
        "description": _("Themes, header/footer, branding, and design tokens"),
        "sort_order": 5,
        "permissions": {
            "view": [
                "design.view_theme",
                "design.view_themeinstallation",
                "design.view_headertemplate",
                "design.view_footertemplate",
                "design.view_menu",
                "design.view_widget",
                "design.view_designtoken",
                "design.view_globaldesignsettings",
                "design.view_customcss",
                "design.view_componentstore",
            ],
            "full": [
                "design.change_theme",
                "design.change_themeinstallation",
                "design.add_headertemplate",
                "design.change_headertemplate",
                "design.add_footertemplate",
                "design.change_footertemplate",
                "design.add_menu",
                "design.change_menu",
                "design.delete_menu",
                "design.change_widget",
                "design.add_designtoken",
                "design.change_designtoken",
                "design.delete_designtoken",
                "design.change_globaldesignsettings",
                "design.add_customcss",
                "design.change_customcss",
                "design.delete_customcss",
            ],
        },
    },
    "marketing": {
        "label": _("Marketing & Promotions"),
        "icon": "fas fa-bullhorn",
        "description": _(
            "Promotions, vouchers, affiliate, loyalty, referrals, product feeds, and SEO generation"
        ),
        "sort_order": 6,
        "permissions": {
            "view": [
                "catalog.view_promotion",
                "vouchers.view_vouchercode",
                "vouchers.view_voucherusage",
                "vouchers.view_giftcard",
                "affiliate.view_program",
                "affiliate.view_affiliate",
                "affiliate.view_commission",
                "affiliate.view_payout",
                "affiliate.view_affiliatesettings",
                "loyalty.view_loyaltymember",
                "loyalty.view_loyaltyreward",
                "loyalty.view_loyaltytier",
                "loyalty.view_loyaltycampaign",
                "loyalty.view_loyaltyrule",
                "loyalty.view_loyaltybadge",
                "referrals.view_referralprogram",
                "referrals.view_referralidentity",
                "referrals.view_referralreward",
                "social_sharing.view_socialshare",
                "social_sharing.view_socialsharingsettings",
                "product_feeds.view_feedprovideraccount",
                "product_feeds.view_feedsynclog",
                # SEO generation
                "seo_generator.view_seoprovideraccount",
            ],
            "full": [
                "catalog.add_promotion",
                "catalog.change_promotion",
                "catalog.delete_promotion",
                "vouchers.add_vouchercode",
                "vouchers.change_vouchercode",
                "vouchers.delete_vouchercode",
                "vouchers.add_giftcard",
                "vouchers.change_giftcard",
                "affiliate.change_program",
                "affiliate.add_program",
                "affiliate.change_affiliate",
                "affiliate.change_commission",
                "affiliate.change_payout",
                "affiliate.change_affiliatesettings",
                "loyalty.change_loyaltymember",
                "loyalty.add_loyaltyreward",
                "loyalty.change_loyaltyreward",
                "loyalty.delete_loyaltyreward",
                "loyalty.add_loyaltytier",
                "loyalty.change_loyaltytier",
                "loyalty.delete_loyaltytier",
                "loyalty.add_loyaltycampaign",
                "loyalty.change_loyaltycampaign",
                "loyalty.add_loyaltyrule",
                "loyalty.change_loyaltyrule",
                "loyalty.delete_loyaltyrule",
                "loyalty.add_loyaltybadge",
                "loyalty.change_loyaltybadge",
                "loyalty.delete_loyaltybadge",
                "referrals.add_referralprogram",
                "referrals.change_referralprogram",
                "social_sharing.change_socialsharingsettings",
                "product_feeds.add_feedprovideraccount",
                "product_feeds.change_feedprovideraccount",
                # SEO generation
                "seo_generator.add_seoprovideraccount",
                "seo_generator.change_seoprovideraccount",
            ],
        },
    },
    "media": {
        "label": _("Media Library"),
        "icon": "fas fa-images",
        "description": _("Images, videos, and other media assets"),
        "sort_order": 7,
        "permissions": {
            "view": [
                "media_library.view_mediaasset",
                "media_library.view_mediafolder",
                "media_library.view_tag",
                "media_library.view_imagesizepreset",
            ],
            "full": [
                "media_library.add_mediaasset",
                "media_library.change_mediaasset",
                "media_library.delete_mediaasset",
                "media_library.add_mediafolder",
                "media_library.change_mediafolder",
                "media_library.delete_mediafolder",
                "media_library.add_tag",
                "media_library.change_tag",
                "media_library.delete_tag",
                "media_library.add_imagesizepreset",
                "media_library.change_imagesizepreset",
            ],
        },
    },
    "email": {
        "label": _("Communications"),
        "icon": "fas fa-comment-dots",
        "description": _("Email accounts, SMS/WhatsApp providers, templates, and delivery logs"),
        "sort_order": 8,
        "permissions": {
            "view": [
                "email_system.view_emailaccount",
                "email_system.view_emailtemplate",
                "email_system.view_emailoutbox",
                "email_system.view_emailevent",
                # SMS / WhatsApp
                "sms_system.view_smsprovideraccount",
                "sms_system.view_smstemplate",
                "sms_system.view_smsoutbox",
            ],
            "full": [
                "email_system.add_emailaccount",
                "email_system.change_emailaccount",
                "email_system.add_emailtemplate",
                "email_system.change_emailtemplate",
                "email_system.change_emailoutbox",
                "email_system.delete_emailoutbox",
                # SMS / WhatsApp
                "sms_system.add_smsprovideraccount",
                "sms_system.change_smsprovideraccount",
                "sms_system.add_smstemplate",
                "sms_system.change_smstemplate",
                "sms_system.change_smsoutbox",
                "sms_system.delete_smsoutbox",
            ],
        },
    },
    "payments": {
        "label": _("Payments & Billing"),
        "icon": "fas fa-credit-card",
        "description": _("Payment providers, transactions, subscriptions, and payouts"),
        "sort_order": 9,
        "permissions": {
            "view": [
                "payment_providers.view_paymentprovideraccount",
                "payment_providers.view_paymenttransaction",
                "payment_providers.view_paymentwebhook",
                "payout_providers.view_payoutprovideraccount",
                "payout_providers.view_payoutwebhooklog",
                "subscriptions.view_subscriptionplan",
                "subscriptions.view_customersubscription",
                "subscriptions.view_billingcyclelog",
                "exchange_rates.view_exchangerateprovideraccount",
                "exchange_rates.view_exchangerate",
            ],
            "full": [
                "payment_providers.add_paymentprovideraccount",
                "payment_providers.change_paymentprovideraccount",
                "payout_providers.add_payoutprovideraccount",
                "payout_providers.change_payoutprovideraccount",
                "subscriptions.add_subscriptionplan",
                "subscriptions.change_subscriptionplan",
                "subscriptions.change_customersubscription",
                "exchange_rates.add_exchangerateprovideraccount",
                "exchange_rates.change_exchangerateprovideraccount",
            ],
        },
    },
    "search": {
        "label": _("Search"),
        "icon": "fas fa-search",
        "description": _("Search settings, synonyms, redirects, and analytics"),
        "sort_order": 10,
        "permissions": {
            "view": [
                "search.view_searchquery",
                "search.view_searchclick",
                "search.view_synonym",
                "search.view_searchredirect",
                "search.view_searchsettings",
                "search.view_searchengine",
            ],
            "full": [
                "search.add_synonym",
                "search.change_synonym",
                "search.delete_synonym",
                "search.add_searchredirect",
                "search.change_searchredirect",
                "search.delete_searchredirect",
                "search.change_searchsettings",
                "search.change_searchengine",
            ],
        },
    },
    "settings": {
        "label": _("Store Settings"),
        "icon": "fas fa-cog",
        "description": _("Site settings, geolocation, business rules, and webhooks"),
        "sort_order": 11,
        "permissions": {
            "view": [
                "core.view_sitesettings",
                "geoip.view_geolocation",
                "geoip.view_countrymapping",
                "geoip.view_businessrule",
                # Webhooks
                "webhooks.view_webhookendpoint",
                "webhooks.view_webhookdelivery",
            ],
            "full": [
                "core.change_sitesettings",
                "geoip.change_geolocation",
                "geoip.add_countrymapping",
                "geoip.change_countrymapping",
                "geoip.add_businessrule",
                "geoip.change_businessrule",
                "geoip.delete_businessrule",
                # Webhooks
                "webhooks.add_webhookendpoint",
                "webhooks.change_webhookendpoint",
                "webhooks.delete_webhookendpoint",
            ],
        },
    },
    "pos_admin": {
        "label": _("POS Management"),
        "icon": "fas fa-cash-register",
        "description": _("POS terminal configuration and shift management"),
        "sort_order": 12,
        "permissions": {
            "view": [
                "pos_app.view_posterminal",
                "pos_app.view_posshift",
                "pos_app.view_cashmovement",
                "pos_app.view_receipttemplate",
            ],
            "full": [
                "pos_app.add_posterminal",
                "pos_app.change_posterminal",
                "pos_app.delete_posterminal",
                "pos_app.change_posshift",
                "pos_app.change_receipttemplate",
            ],
        },
    },
    "users": {
        "label": _("Users & Roles"),
        "icon": "fas fa-user-shield",
        "description": _("Staff user accounts, roles, and API tokens"),
        "sort_order": 13,
        "permissions": {
            "view": [
                "auth.view_user",
                "auth.view_group",
                "core.view_apitoken",
            ],
            "full": [
                "auth.add_user",
                "auth.change_user",
                "auth.add_group",
                "auth.change_group",
                "core.add_apitoken",
                "core.change_apitoken",
                "core.delete_apitoken",
            ],
        },
    },
    "translations": {
        "label": _("Translation Service"),
        "icon": "fas fa-globe",
        "description": _("Translation providers, AI models, and translation metadata"),
        "sort_order": 14,
        "permissions": {
            "view": [
                "translations.view_translationprovider",
                "translations.view_translationmeta",
                "translations.view_installedmodel",
            ],
            "full": [
                "translations.change_translationprovider",
                "translations.change_translationmeta",
                "translations.change_installedmodel",
            ],
        },
    },
    "custom_fields": {
        "label": _("Custom Fields"),
        "icon": "fas fa-sliders-h",
        "description": _("Custom field groups and definitions for extending platform objects"),
        "sort_order": 15,
        "permissions": {
            "view": [
                "custom_fields.view_customfieldgroup",
                "custom_fields.view_customfielddefinition",
            ],
            "full": [
                "custom_fields.add_customfieldgroup",
                "custom_fields.change_customfieldgroup",
                "custom_fields.delete_customfieldgroup",
                "custom_fields.add_customfielddefinition",
                "custom_fields.change_customfielddefinition",
                "custom_fields.delete_customfielddefinition",
            ],
        },
    },
    "system": {
        "label": _("System & Updates"),
        "icon": "fas fa-server",
        "description": _(
            "Component registry, update channels, version tracking, and platform updates"
        ),
        "sort_order": 16,
        "permissions": {
            "view": [
                "component_updates.view_updatechannel",
                "component_updates.view_componentregistry",
                "component_updates.view_componentversion",
                "component_updates.view_componentdependency",
                "component_updates.view_updatelog",
                "component_updates.view_updateserverconfig",
                "component_updates.view_platformupdate",
            ],
            "full": [
                "component_updates.change_updatechannel",
                "component_updates.change_componentregistry",
                "component_updates.change_updateserverconfig",
            ],
        },
    },
}

# Mapping from sidebar menu group to permission categories
# Used by the sidebar template tag to determine visibility
SIDEBAR_CATEGORY_MAP = {
    "catalog": ["catalog"],
    "orders": ["orders"],
    "customers": ["customers"],
    "pos": ["pos_admin"],
    "search": ["search"],
    "marketing": ["marketing"],
    "content": ["content"],
    "design": ["design"],
    "settings": ["settings"],
    "payments": ["payments"],
    "email": ["email"],
    "users": ["users"],
    "media": ["media"],
    "translations": ["translations"],
    "custom_fields": ["custom_fields"],
    "system": ["system"],
}
