"""
Permission category definitions.

Each category maps to a set of Django model permissions at two levels:
- 'view': Read-only access (view_* permissions)
- 'full': Read + write + delete (view_*, add_*, change_*, delete_* permissions)

Merchants see these friendly categories instead of raw Django permissions.
When a StaffRole is saved, the selected categories are resolved to actual
Django Permission objects and synced to the linked Group.
"""

from django.utils.translation import gettext_lazy as _

PERMISSION_CATEGORIES = {
    "catalog": {
        "label": _("Product Catalog"),
        "icon": "fas fa-box-open",
        "description": _(
            "Products, categories, brands, attributes, stock, digital assets, and 3D configurator"
        ),
        "sort_order": 1,
        "permissions": {
            "view": [
                "catalog.view_product",
                "catalog.view_category",
                "catalog.view_brand",
                "catalog.view_collection",
                "catalog.view_productattribute",
                "catalog.view_attributevalue",
                "catalog.view_productimage",
                "catalog.view_productvariant",
                "catalog.view_productprice",
                "catalog.view_stockitem",
                "catalog.view_stockmovement",
                "catalog.view_warehouse",
                "catalog.view_salesregion",
                "catalog.view_digitalasset",
                "catalog.view_licenseprovider",
                "catalog.view_licensekey",
                "catalog.view_licensekeytemplate",
                "catalog.view_licensepool",
                "catalog.view_customizationoption",
                "catalog.view_bundleitem",
                "catalog.view_productreview",
                "catalog.view_giftcard",
                "catalog.view_giftcardtransaction",
                # 3D Configurator
                "configurator_3d.view_sceneconfig",
                "catalog.view_booking",
                "catalog.view_bookingwaitlist",
                "catalog.view_compatibilityrule",
                "catalog.view_configurationpreset",
                "catalog.view_configurationslot",
                "catalog.view_configurationslotoption",
                "catalog.view_digitaldownload",
                "catalog.view_externallicensesync",
                "catalog.view_pricecharmingrule",
                "catalog.view_productregionvisibility",
                "catalog.view_producttag",
                "catalog.view_stockdisplaysettings",
                "catalog.view_stocknotification",
                "customizable_product.view_clipartasset",
                "customizable_product.view_clipartcategory",
                "customizable_product.view_customfont",
                "customizable_product.view_designsnapshot",
                "customizable_product.view_productdesignconfig",
                "customizable_product.view_saveddesign",
            ],
            "full": [
                "catalog.add_product",
                "catalog.change_product",
                "catalog.delete_product",
                "catalog.add_category",
                "catalog.change_category",
                "catalog.delete_category",
                "catalog.add_brand",
                "catalog.change_brand",
                "catalog.delete_brand",
                "catalog.add_collection",
                "catalog.change_collection",
                "catalog.delete_collection",
                "catalog.add_productattribute",
                "catalog.change_productattribute",
                "catalog.delete_productattribute",
                "catalog.add_attributevalue",
                "catalog.change_attributevalue",
                "catalog.delete_attributevalue",
                "catalog.add_productimage",
                "catalog.change_productimage",
                "catalog.delete_productimage",
                "catalog.add_productvariant",
                "catalog.change_productvariant",
                "catalog.delete_productvariant",
                "catalog.add_productprice",
                "catalog.change_productprice",
                "catalog.delete_productprice",
                "catalog.add_stockitem",
                "catalog.change_stockitem",
                "catalog.delete_stockitem",
                "catalog.add_stockmovement",
                "catalog.change_stockmovement",
                "catalog.add_warehouse",
                "catalog.change_warehouse",
                "catalog.delete_warehouse",
                "catalog.add_salesregion",
                "catalog.change_salesregion",
                "catalog.delete_salesregion",
                "catalog.add_digitalasset",
                "catalog.change_digitalasset",
                "catalog.delete_digitalasset",
                "catalog.change_licenseprovider",
                "catalog.change_licensekey",
                "catalog.change_licensekeytemplate",
                "catalog.change_licensepool",
                "catalog.add_customizationoption",
                "catalog.change_customizationoption",
                "catalog.delete_customizationoption",
                "catalog.add_bundleitem",
                "catalog.change_bundleitem",
                "catalog.delete_bundleitem",
                "catalog.change_productreview",
                "catalog.delete_productreview",
                "catalog.add_giftcard",
                "catalog.change_giftcard",
                # 3D Configurator
                "configurator_3d.add_sceneconfig",
                "configurator_3d.change_sceneconfig",
                "configurator_3d.delete_sceneconfig",
                "catalog.add_booking",
                "catalog.change_booking",
                "catalog.delete_booking",
                "catalog.add_bookingwaitlist",
                "catalog.change_bookingwaitlist",
                "catalog.delete_bookingwaitlist",
                "catalog.add_compatibilityrule",
                "catalog.change_compatibilityrule",
                "catalog.delete_compatibilityrule",
                "catalog.add_configurationpreset",
                "catalog.change_configurationpreset",
                "catalog.delete_configurationpreset",
                "catalog.add_configurationslot",
                "catalog.change_configurationslot",
                "catalog.delete_configurationslot",
                "catalog.add_configurationslotoption",
                "catalog.change_configurationslotoption",
                "catalog.delete_configurationslotoption",
                "catalog.add_digitaldownload",
                "catalog.change_digitaldownload",
                "catalog.delete_digitaldownload",
                "catalog.add_externallicensesync",
                "catalog.change_externallicensesync",
                "catalog.delete_externallicensesync",
                "catalog.add_pricecharmingrule",
                "catalog.change_pricecharmingrule",
                "catalog.delete_pricecharmingrule",
                "catalog.add_productregionvisibility",
                "catalog.change_productregionvisibility",
                "catalog.delete_productregionvisibility",
                "catalog.add_producttag",
                "catalog.change_producttag",
                "catalog.delete_producttag",
                "catalog.add_stockdisplaysettings",
                "catalog.change_stockdisplaysettings",
                "catalog.delete_stockdisplaysettings",
                "catalog.add_stocknotification",
                "catalog.change_stocknotification",
                "catalog.delete_stocknotification",
                "customizable_product.add_clipartasset",
                "customizable_product.change_clipartasset",
                "customizable_product.delete_clipartasset",
                "customizable_product.add_clipartcategory",
                "customizable_product.change_clipartcategory",
                "customizable_product.delete_clipartcategory",
                "customizable_product.add_customfont",
                "customizable_product.change_customfont",
                "customizable_product.delete_customfont",
                "customizable_product.add_designsnapshot",
                "customizable_product.change_designsnapshot",
                "customizable_product.delete_designsnapshot",
                "customizable_product.add_productdesignconfig",
                "customizable_product.change_productdesignconfig",
                "customizable_product.delete_productdesignconfig",
                "customizable_product.add_saveddesign",
                "customizable_product.change_saveddesign",
                "customizable_product.delete_saveddesign",
            ],
        },
    },
    "orders": {
        "label": _("Orders & Fulfillment"),
        "icon": "fas fa-shopping-cart",
        "description": _("Orders, refunds, returns, shipments, and shipping configuration"),
        "sort_order": 2,
        "permissions": {
            "view": [
                "orders.view_order",
                "orders.view_orderitem",
                "orders.view_ordernote",
                "orders.view_refund",
                "orders.view_returnrequest",
                "orders.view_address",
                "cart.view_cart",
                "cart.view_cartitem",
                "cart.view_shippingmethod",
                "cart.view_taxrate",
                "shipping.view_shipment",
                "shipping.view_provideraccount",
                "shipping.view_carrierpreset",
                "shipping.view_shippingpackage",
                "shipping.view_shippingzone",
                "shipping.view_shippingpromotion",
                "shipping.view_shippingratetable",
                "shipping.view_trackingevent",
                "shipping.view_webhooklog",
                "shipping.view_shippingcountry",
            ],
            "full": [
                "orders.change_order",
                "orders.add_ordernote",
                "orders.change_ordernote",
                "orders.add_refund",
                "orders.change_refund",
                "orders.add_returnrequest",
                "orders.change_returnrequest",
                "cart.change_cart",
                "cart.add_shippingmethod",
                "cart.change_shippingmethod",
                "cart.delete_shippingmethod",
                "cart.add_taxrate",
                "cart.change_taxrate",
                "cart.delete_taxrate",
                "shipping.add_shipment",
                "shipping.change_shipment",
                "shipping.add_provideraccount",
                "shipping.change_provideraccount",
                "shipping.add_carrierpreset",
                "shipping.change_carrierpreset",
                "shipping.add_shippingpackage",
                "shipping.change_shippingpackage",
                "shipping.add_shippingzone",
                "shipping.change_shippingzone",
                "shipping.delete_shippingzone",
                "shipping.add_shippingpromotion",
                "shipping.change_shippingpromotion",
                "shipping.delete_shippingpromotion",
                "shipping.add_shippingratetable",
                "shipping.change_shippingratetable",
                "shipping.delete_shippingratetable",
                "shipping.add_shippingcountry",
                "shipping.change_shippingcountry",
                "shipping.delete_shippingcountry",
            ],
        },
    },
    "customers": {
        "label": _("Customers"),
        "icon": "fas fa-users",
        "description": _("Customer profiles, segments, analytics, and messages"),
        "sort_order": 3,
        "permissions": {
            "view": [
                "accounts.view_customerprofile",
                "customers.view_customersegment",
                "customers.view_customermetrics",
                "customers.view_customernote",
                "customers.view_abandonedcart",
                # Customer messages
                "admin_api.view_customermessage",
                "accounts.view_communicationpreference",
                "accounts.view_preferencechangelog",
                "cart.view_wishlist",
                "cart.view_wishlistitem",
            ],
            "full": [
                "accounts.change_customerprofile",
                "customers.add_customersegment",
                "customers.change_customersegment",
                "customers.delete_customersegment",
                "customers.change_customermetrics",
                "customers.add_customernote",
                "customers.change_customernote",
                "customers.delete_customernote",
                # Customer messages
                "admin_api.change_customermessage",
                "accounts.add_communicationpreference",
                "accounts.change_communicationpreference",
                "accounts.delete_communicationpreference",
                "accounts.add_preferencechangelog",
                "accounts.change_preferencechangelog",
                "accounts.delete_preferencechangelog",
                "cart.add_wishlist",
                "cart.change_wishlist",
                "cart.delete_wishlist",
                "cart.add_wishlistitem",
                "cart.change_wishlistitem",
                "cart.delete_wishlistitem",
            ],
        },
    },
    "content": {
        "label": _("Content & Pages"),
        "icon": "fas fa-file-alt",
        "description": _("Pages, blog posts, announcements, and forms"),
        "sort_order": 4,
        "permissions": {
            "view": [
                "page_builder.view_page",
                "page_builder.view_pagetemplate",
                "page_builder.view_element",
                "blog.view_blogpost",
                "blog.view_blogcategory",
                "blog.view_blogtag",
                "blog.view_blogsubscriber",
                "blog.view_blogsettings",
                "announcements.view_announcement",
                "form_builder.view_form",
                "form_builder.view_formresponse",
                "element_builder.view_customelement",
                "blog.view_blogpostautoshare",
                "blog.view_socialconnectoraccount",
                "form_builder.view_formfield",
                "form_builder.view_formstep",
                "page_builder.view_elementtemplate",
            ],
            "full": [
                "page_builder.add_page",
                "page_builder.change_page",
                "page_builder.delete_page",
                "page_builder.add_pagetemplate",
                "page_builder.change_pagetemplate",
                "page_builder.delete_pagetemplate",
                "page_builder.add_element",
                "page_builder.change_element",
                "page_builder.delete_element",
                "blog.add_blogpost",
                "blog.change_blogpost",
                "blog.delete_blogpost",
                "blog.add_blogcategory",
                "blog.change_blogcategory",
                "blog.delete_blogcategory",
                "blog.add_blogtag",
                "blog.change_blogtag",
                "blog.delete_blogtag",
                "blog.change_blogsettings",
                "announcements.add_announcement",
                "announcements.change_announcement",
                "announcements.delete_announcement",
                "form_builder.add_form",
                "form_builder.change_form",
                "form_builder.delete_form",
                "element_builder.add_customelement",
                "element_builder.change_customelement",
                "element_builder.delete_customelement",
                "blog.add_blogpostautoshare",
                "blog.change_blogpostautoshare",
                "blog.delete_blogpostautoshare",
                "blog.add_socialconnectoraccount",
                "blog.change_socialconnectoraccount",
                "blog.delete_socialconnectoraccount",
                "form_builder.add_formfield",
                "form_builder.change_formfield",
                "form_builder.delete_formfield",
                "form_builder.add_formstep",
                "form_builder.change_formstep",
                "form_builder.delete_formstep",
                "page_builder.add_elementtemplate",
                "page_builder.change_elementtemplate",
                "page_builder.delete_elementtemplate",
            ],
        },
    },
    "design": {
        "label": _("Design & Theme"),
        "icon": "fas fa-paint-brush",
        "description": _("Themes, header/footer, branding, and design tokens"),
        "sort_order": 5,
        "permissions": {
            "view": [
                "design.view_theme",
                "design.view_themeinstallation",
                "design.view_headertemplate",
                "design.view_footertemplate",
                "design.view_menu",
                "design.view_widget",
                "design.view_designtoken",
                "design.view_globaldesignsettings",
                "design.view_customcss",
                "design.view_componentstore",
                "design.view_componentstyle",
                "design.view_componentvalidationreport",
                "design.view_menuitem",
                "design.view_pagetier",
                "design.view_themeasset",
                "design.view_themebranding",
            ],
            "full": [
                "design.change_theme",
                "design.change_themeinstallation",
                "design.add_headertemplate",
                "design.change_headertemplate",
                "design.add_footertemplate",
                "design.change_footertemplate",
                "design.add_menu",
                "design.change_menu",
                "design.delete_menu",
                "design.change_widget",
                "design.add_designtoken",
                "design.change_designtoken",
                "design.delete_designtoken",
                "design.change_globaldesignsettings",
                "design.add_customcss",
                "design.change_customcss",
                "design.delete_customcss",
                "design.add_componentstyle",
                "design.change_componentstyle",
                "design.delete_componentstyle",
                "design.add_componentvalidationreport",
                "design.change_componentvalidationreport",
                "design.delete_componentvalidationreport",
                "design.add_menuitem",
                "design.change_menuitem",
                "design.delete_menuitem",
                "design.add_pagetier",
                "design.change_pagetier",
                "design.delete_pagetier",
                "design.add_themeasset",
                "design.change_themeasset",
                "design.delete_themeasset",
                "design.add_themebranding",
                "design.change_themebranding",
                "design.delete_themebranding",
            ],
        },
    },
    "marketing": {
        "label": _("Marketing & Promotions"),
        "icon": "fas fa-bullhorn",
        "description": _(
            "Promotions, vouchers, affiliate, loyalty, referrals, product feeds, and SEO generation"
        ),
        "sort_order": 6,
        "permissions": {
            "view": [
                "catalog.view_promotion",
                "vouchers.view_vouchercode",
                "vouchers.view_voucherusage",
                "vouchers.view_giftcard",
                "affiliate.view_program",
                "affiliate.view_affiliate",
                "affiliate.view_commission",
                "affiliate.view_payout",
                "affiliate.view_affiliatesettings",
                "loyalty.view_loyaltymember",
                "loyalty.view_loyaltyreward",
                "loyalty.view_loyaltytier",
                "loyalty.view_loyaltycampaign",
                "loyalty.view_loyaltyrule",
                "loyalty.view_loyaltybadge",
                "referrals.view_referralprogram",
                "referrals.view_referralidentity",
                "referrals.view_referralreward",
                "social_sharing.view_socialshare",
                "social_sharing.view_socialsharingsettings",
                "product_feeds.view_feedprovideraccount",
                "product_feeds.view_feedsynclog",
                # SEO generation
                "seo_generator.view_seoprovideraccount",
                "loyalty.view_loyaltybalance",
                "loyalty.view_loyaltycampaignexecution",
                "loyalty.view_loyaltymemberbadge",
                "loyalty.view_loyaltyredemption",
                "loyalty.view_loyaltysegment",
                "loyalty.view_loyaltysegmentmembership",
                "loyalty.view_loyaltytransaction",
                "referrals.view_referralattribution",
                "referrals.view_referralevent",
                "affiliate.view_affiliateprogrammembership",
                "affiliate.view_affiliatereportsettings",
                "affiliate.view_click",
                "affiliate.view_link",
                "social_sharing.view_sharecount",
                "product_feeds.view_productfeed",
                "vouchers.view_appliedvoucher",
                "vouchers.view_voucherrestriction",
            ],
            "full": [
                "catalog.add_promotion",
                "catalog.change_promotion",
                "catalog.delete_promotion",
                "vouchers.add_vouchercode",
                "vouchers.change_vouchercode",
                "vouchers.delete_vouchercode",
                "vouchers.add_giftcard",
                "vouchers.change_giftcard",
                "affiliate.change_program",
                "affiliate.add_program",
                "affiliate.change_affiliate",
                "affiliate.change_commission",
                "affiliate.change_payout",
                "affiliate.change_affiliatesettings",
                "loyalty.change_loyaltymember",
                "loyalty.add_loyaltyreward",
                "loyalty.change_loyaltyreward",
                "loyalty.delete_loyaltyreward",
                "loyalty.add_loyaltytier",
                "loyalty.change_loyaltytier",
                "loyalty.delete_loyaltytier",
                "loyalty.add_loyaltycampaign",
                "loyalty.change_loyaltycampaign",
                "loyalty.add_loyaltyrule",
                "loyalty.change_loyaltyrule",
                "loyalty.delete_loyaltyrule",
                "loyalty.add_loyaltybadge",
                "loyalty.change_loyaltybadge",
                "loyalty.delete_loyaltybadge",
                "referrals.add_referralprogram",
                "referrals.change_referralprogram",
                "social_sharing.change_socialsharingsettings",
                "product_feeds.add_feedprovideraccount",
                "product_feeds.change_feedprovideraccount",
                # SEO generation
                "seo_generator.add_seoprovideraccount",
                "seo_generator.change_seoprovideraccount",
                "loyalty.add_loyaltybalance",
                "loyalty.change_loyaltybalance",
                "loyalty.delete_loyaltybalance",
                "loyalty.add_loyaltycampaignexecution",
                "loyalty.change_loyaltycampaignexecution",
                "loyalty.delete_loyaltycampaignexecution",
                "loyalty.add_loyaltymemberbadge",
                "loyalty.change_loyaltymemberbadge",
                "loyalty.delete_loyaltymemberbadge",
                "loyalty.add_loyaltyredemption",
                "loyalty.change_loyaltyredemption",
                "loyalty.delete_loyaltyredemption",
                "loyalty.add_loyaltysegment",
                "loyalty.change_loyaltysegment",
                "loyalty.delete_loyaltysegment",
                "loyalty.add_loyaltysegmentmembership",
                "loyalty.change_loyaltysegmentmembership",
                "loyalty.delete_loyaltysegmentmembership",
                "loyalty.add_loyaltytransaction",
                "loyalty.change_loyaltytransaction",
                "loyalty.delete_loyaltytransaction",
                "referrals.add_referralattribution",
                "referrals.change_referralattribution",
                "referrals.delete_referralattribution",
                "referrals.add_referralevent",
                "referrals.change_referralevent",
                "referrals.delete_referralevent",
                "affiliate.add_affiliateprogrammembership",
                "affiliate.change_affiliateprogrammembership",
                "affiliate.delete_affiliateprogrammembership",
                "affiliate.add_affiliatereportsettings",
                "affiliate.change_affiliatereportsettings",
                "affiliate.delete_affiliatereportsettings",
                "affiliate.add_click",
                "affiliate.change_click",
                "affiliate.delete_click",
                "affiliate.add_link",
                "affiliate.change_link",
                "affiliate.delete_link",
                "social_sharing.add_sharecount",
                "social_sharing.change_sharecount",
                "social_sharing.delete_sharecount",
                "product_feeds.add_productfeed",
                "product_feeds.change_productfeed",
                "product_feeds.delete_productfeed",
                "vouchers.add_appliedvoucher",
                "vouchers.change_appliedvoucher",
                "vouchers.delete_appliedvoucher",
                "vouchers.add_voucherrestriction",
                "vouchers.change_voucherrestriction",
                "vouchers.delete_voucherrestriction",
            ],
        },
    },
    "analytics": {
        "label": _("Insights & Analytics"),
        "icon": "fas fa-chart-pie",
        "description": _("Revenue attribution and store insight dashboards"),
        "sort_order": 7,
        "permissions": {
            "view": [
                "attribution.view_attribution",
                "attribution.view_touchpoint",
                "attribution.view_campaign",
                "attribution.view_visitorthread",
                "attribution.view_attributionsettings",
            ],
            "full": [
                "attribution.add_campaign",
                "attribution.change_campaign",
                "attribution.delete_campaign",
                "attribution.change_attributionsettings",
            ],
        },
    },
    "media": {
        "label": _("Media Library"),
        "icon": "fas fa-images",
        "description": _("Images, videos, and other media assets"),
        "sort_order": 8,
        "permissions": {
            "view": [
                "media_library.view_mediaasset",
                "media_library.view_mediafolder",
                "media_library.view_tag",
                "media_library.view_imagesizepreset",
            ],
            "full": [
                "media_library.add_mediaasset",
                "media_library.change_mediaasset",
                "media_library.delete_mediaasset",
                "media_library.add_mediafolder",
                "media_library.change_mediafolder",
                "media_library.delete_mediafolder",
                "media_library.add_tag",
                "media_library.change_tag",
                "media_library.delete_tag",
                "media_library.add_imagesizepreset",
                "media_library.change_imagesizepreset",
            ],
        },
    },
    "email": {
        "label": _("Communications"),
        "icon": "fas fa-comment-dots",
        "description": _("Email accounts, SMS/WhatsApp providers, templates, and delivery logs"),
        "sort_order": 9,
        "permissions": {
            "view": [
                "email_system.view_emailaccount",
                "email_system.view_emailtemplate",
                "email_system.view_emailoutbox",
                "email_system.view_emailevent",
                # SMS / WhatsApp
                "sms_system.view_smsprovideraccount",
                "sms_system.view_smstemplate",
                "sms_system.view_smsoutbox",
                "email_system.view_scheduledemail",
            ],
            "full": [
                "email_system.add_emailaccount",
                "email_system.change_emailaccount",
                "email_system.add_emailtemplate",
                "email_system.change_emailtemplate",
                "email_system.change_emailoutbox",
                "email_system.delete_emailoutbox",
                # SMS / WhatsApp
                "sms_system.add_smsprovideraccount",
                "sms_system.change_smsprovideraccount",
                "sms_system.add_smstemplate",
                "sms_system.change_smstemplate",
                "sms_system.change_smsoutbox",
                "sms_system.delete_smsoutbox",
                "email_system.add_scheduledemail",
                "email_system.change_scheduledemail",
                "email_system.delete_scheduledemail",
            ],
        },
    },
    "payments": {
        "label": _("Payments & Billing"),
        "icon": "fas fa-credit-card",
        "description": _("Payment providers, transactions, subscriptions, and payouts"),
        "sort_order": 10,
        "permissions": {
            "view": [
                "payment_providers.view_paymentprovideraccount",
                "payment_providers.view_paymenttransaction",
                "payment_providers.view_paymentwebhook",
                "payout_providers.view_payoutprovideraccount",
                "payout_providers.view_payoutwebhooklog",
                "subscriptions.view_subscriptionplan",
                "subscriptions.view_customersubscription",
                "subscriptions.view_billingcyclelog",
                "exchange_rates.view_exchangerateprovideraccount",
                "exchange_rates.view_exchangerate",
                "payment_providers.view_paymentintent",
                "wallet.view_customerwallet",
                "wallet.view_wallettransaction",
                "subscriptions.view_customersubscriptionaddon",
                "subscriptions.view_paymenttoken",
                "subscriptions.view_planaddon",
                "subscriptions.view_planpricingtier",
                "subscriptions.view_subscriptiondiscount",
            ],
            "full": [
                "payment_providers.add_paymentprovideraccount",
                "payment_providers.change_paymentprovideraccount",
                "payout_providers.add_payoutprovideraccount",
                "payout_providers.change_payoutprovideraccount",
                "subscriptions.add_subscriptionplan",
                "subscriptions.change_subscriptionplan",
                "subscriptions.change_customersubscription",
                "exchange_rates.add_exchangerateprovideraccount",
                "exchange_rates.change_exchangerateprovideraccount",
                "payment_providers.add_paymentintent",
                "payment_providers.change_paymentintent",
                "payment_providers.delete_paymentintent",
                "wallet.add_customerwallet",
                "wallet.change_customerwallet",
                "wallet.delete_customerwallet",
                "wallet.add_wallettransaction",
                "wallet.change_wallettransaction",
                "wallet.delete_wallettransaction",
                "subscriptions.add_customersubscriptionaddon",
                "subscriptions.change_customersubscriptionaddon",
                "subscriptions.delete_customersubscriptionaddon",
                "subscriptions.add_paymenttoken",
                "subscriptions.change_paymenttoken",
                "subscriptions.delete_paymenttoken",
                "subscriptions.add_planaddon",
                "subscriptions.change_planaddon",
                "subscriptions.delete_planaddon",
                "subscriptions.add_planpricingtier",
                "subscriptions.change_planpricingtier",
                "subscriptions.delete_planpricingtier",
                "subscriptions.add_subscriptiondiscount",
                "subscriptions.change_subscriptiondiscount",
                "subscriptions.delete_subscriptiondiscount",
            ],
        },
    },
    "search": {
        "label": _("Search"),
        "icon": "fas fa-search",
        "description": _("Search settings, synonyms, redirects, and analytics"),
        "sort_order": 11,
        "permissions": {
            "view": [
                "search.view_searchquery",
                "search.view_searchclick",
                "search.view_synonym",
                "search.view_searchredirect",
                "search.view_searchsettings",
                "search.view_searchengine",
            ],
            "full": [
                "search.add_synonym",
                "search.change_synonym",
                "search.delete_synonym",
                "search.add_searchredirect",
                "search.change_searchredirect",
                "search.delete_searchredirect",
                "search.change_searchsettings",
                "search.change_searchengine",
            ],
        },
    },
    "settings": {
        "label": _("Store Settings"),
        "icon": "fas fa-cog",
        "description": _("Site settings, geolocation, business rules, and webhooks"),
        "sort_order": 12,
        "permissions": {
            "view": [
                "core.view_sitesettings",
                "geoip.view_geolocation",
                "geoip.view_countrymapping",
                "geoip.view_businessrule",
                # Webhooks
                "webhooks.view_webhookendpoint",
                "webhooks.view_webhookdelivery",
                "accounts.view_oauthprovidersettings",
                "exchange_rates.view_exchangeratehistory",
                "exchange_rates.view_manualexchangerate",
                "catalog.view_webhooksubscription",
                "shipping.view_location",
            ],
            "full": [
                "core.change_sitesettings",
                "geoip.change_geolocation",
                "geoip.add_countrymapping",
                "geoip.change_countrymapping",
                "geoip.add_businessrule",
                "geoip.change_businessrule",
                "geoip.delete_businessrule",
                # Webhooks
                "webhooks.add_webhookendpoint",
                "webhooks.change_webhookendpoint",
                "webhooks.delete_webhookendpoint",
                "accounts.add_oauthprovidersettings",
                "accounts.change_oauthprovidersettings",
                "accounts.delete_oauthprovidersettings",
                "exchange_rates.add_exchangeratehistory",
                "exchange_rates.change_exchangeratehistory",
                "exchange_rates.delete_exchangeratehistory",
                "exchange_rates.add_manualexchangerate",
                "exchange_rates.change_manualexchangerate",
                "exchange_rates.delete_manualexchangerate",
                "catalog.add_webhooksubscription",
                "catalog.change_webhooksubscription",
                "catalog.delete_webhooksubscription",
                "shipping.add_location",
                "shipping.change_location",
                "shipping.delete_location",
            ],
        },
    },
    "pos_admin": {
        "label": _("POS Management"),
        "icon": "fas fa-cash-register",
        "description": _("POS terminal configuration and shift management"),
        "sort_order": 13,
        "permissions": {
            "view": [
                "pos_app.view_posterminal",
                "pos_app.view_posshift",
                "pos_app.view_cashmovement",
                "pos_app.view_receipttemplate",
                "pos_app.view_posstaffdiscount",
                "pos_app.view_posterminalprovider",
                "pos_app.view_posterminalreader",
                "pos_app.view_promoslide",
                "pos_app.view_storegroup",
                "pos_app.view_terminallockevent",
            ],
            "full": [
                "pos_app.add_posterminal",
                "pos_app.change_posterminal",
                "pos_app.delete_posterminal",
                "pos_app.change_posshift",
                "pos_app.change_receipttemplate",
                "pos_app.add_posstaffdiscount",
                "pos_app.change_posstaffdiscount",
                "pos_app.delete_posstaffdiscount",
                "pos_app.add_posterminalprovider",
                "pos_app.change_posterminalprovider",
                "pos_app.delete_posterminalprovider",
                "pos_app.add_posterminalreader",
                "pos_app.change_posterminalreader",
                "pos_app.delete_posterminalreader",
                "pos_app.add_promoslide",
                "pos_app.change_promoslide",
                "pos_app.delete_promoslide",
                "pos_app.add_storegroup",
                "pos_app.change_storegroup",
                "pos_app.delete_storegroup",
                "pos_app.add_terminallockevent",
                "pos_app.change_terminallockevent",
                "pos_app.delete_terminallockevent",
            ],
        },
    },
    "users": {
        "label": _("Users & Roles"),
        "icon": "fas fa-user-shield",
        "description": _("Staff user accounts, roles, and API tokens"),
        "sort_order": 14,
        "permissions": {
            "view": [
                "auth.view_user",
                "auth.view_group",
                "core.view_apitoken",
                "accounts.view_staffmember",
                "staff_roles.view_staffrole",
                "admin_api.view_staffinvitation",
            ],
            "full": [
                "auth.add_user",
                "auth.change_user",
                "auth.add_group",
                "auth.change_group",
                "core.add_apitoken",
                "core.change_apitoken",
                "core.delete_apitoken",
                "accounts.add_staffmember",
                "accounts.change_staffmember",
                "accounts.delete_staffmember",
                "staff_roles.add_staffrole",
                "staff_roles.change_staffrole",
                "staff_roles.delete_staffrole",
                "admin_api.add_staffinvitation",
                "admin_api.change_staffinvitation",
                "admin_api.delete_staffinvitation",
            ],
        },
    },
    "translations": {
        "label": _("Translation Service"),
        "icon": "fas fa-globe",
        "description": _("Translation providers, AI models, and translation metadata"),
        "sort_order": 15,
        "permissions": {
            "view": [
                "translations.view_translationprovider",
                "translations.view_translationmeta",
                "translations.view_installedmodel",
                "translations.view_translationprovideraccount",
            ],
            "full": [
                "translations.change_translationprovider",
                "translations.change_translationmeta",
                "translations.change_installedmodel",
                "translations.add_translationprovideraccount",
                "translations.change_translationprovideraccount",
                "translations.delete_translationprovideraccount",
            ],
        },
    },
    "custom_fields": {
        "label": _("Custom Fields"),
        "icon": "fas fa-sliders-h",
        "description": _("Custom field groups and definitions for extending platform objects"),
        "sort_order": 16,
        "permissions": {
            "view": [
                "custom_fields.view_customfieldgroup",
                "custom_fields.view_customfielddefinition",
            ],
            "full": [
                "custom_fields.add_customfieldgroup",
                "custom_fields.change_customfieldgroup",
                "custom_fields.delete_customfieldgroup",
                "custom_fields.add_customfielddefinition",
                "custom_fields.change_customfielddefinition",
                "custom_fields.delete_customfielddefinition",
            ],
        },
    },
    "system": {
        "label": _("System & Updates"),
        "icon": "fas fa-server",
        "description": _(
            "Component registry, update channels, version tracking, and platform updates"
        ),
        "sort_order": 17,
        "permissions": {
            "view": [
                "component_updates.view_updatechannel",
                "component_updates.view_componentregistry",
                "component_updates.view_componentversion",
                "component_updates.view_componentdependency",
                "component_updates.view_updatelog",
                "component_updates.view_updateserverconfig",
                "component_updates.view_platformupdate",
            ],
            "full": [
                "component_updates.change_updatechannel",
                "component_updates.change_componentregistry",
                "component_updates.change_updateserverconfig",
            ],
        },
    },
}

# Mapping from sidebar menu group to permission categories
# Used by the sidebar template tag to determine visibility
SIDEBAR_CATEGORY_MAP = {
    "catalog": ["catalog"],
    "orders": ["orders"],
    "customers": ["customers"],
    "pos": ["pos_admin"],
    "search": ["search"],
    "insights": ["analytics"],
    "marketing": ["marketing"],
    "content": ["content"],
    "design": ["design"],
    "settings": ["settings"],
    "payments": ["payments"],
    "email": ["email"],
    "users": ["users"],
    "media": ["media"],
    "translations": ["translations"],
    "custom_fields": ["custom_fields"],
    "system": ["system"],
}
