# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_code', models.CharField(help_text='Unique identifier for this affiliate', max_length=20, unique=True, verbose_name='affiliate code')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='company name')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('payment_email', models.EmailField(help_text='Email for PayPal or other payment methods', max_length=254, verbose_name='payment email')),
                ('payment_method', models.CharField(choices=[('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], default='paypal', max_length=50, verbose_name='payment method')),
                ('bank_account_holder', models.CharField(blank=True, help_text='Name as it appears on the bank account', max_length=255, verbose_name='account holder name')),
                ('bank_account_number', models.CharField(blank=True, help_text='Bank account number (encrypted in database)', max_length=50, verbose_name='account number')),
                ('bank_routing_code', models.CharField(blank=True, help_text='Bank routing/sort code (ABA, BSB, etc.)', max_length=50, verbose_name='routing code')),
                ('bank_swift_code', models.CharField(blank=True, help_text='Bank SWIFT/BIC code for international transfers', max_length=11, verbose_name='SWIFT/BIC code')),
                ('bank_country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code (e.g., US, GB, AU)', max_length=2, verbose_name='bank country')),
                ('bank_currency', models.CharField(blank=True, help_text='ISO 4217 currency code (e.g., USD, GBP, EUR)', max_length=3, verbose_name='account currency')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'affiliate',
                'verbose_name_plural': 'affiliates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateProgramMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this membership', verbose_name='notes')),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='applied at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
            ],
            options={
                'verbose_name': 'program membership',
                'verbose_name_plural': 'program memberships',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_report_enabled', models.BooleanField(default=True, help_text='Send monthly performance reports to affiliates', verbose_name='enable monthly reports')),
                ('monthly_report_day', models.PositiveIntegerField(default=1, help_text='Day of month to send reports (1-28)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='report send day')),
                ('monthly_report_hour', models.PositiveIntegerField(default=9, help_text='Hour (UTC) to send reports (0-23)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='report send hour')),
                ('include_top_orders_count', models.PositiveIntegerField(default=5, help_text='Number of top orders to include in report (1-20)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='top orders count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Affiliate Report Settings',
                'verbose_name_plural': 'Affiliate Report Settings',
            },
        ),
        migrations.CreateModel(
            name='AffiliateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Join Our Affiliate Program', help_text='Main heading on the affiliate landing page', max_length=200, verbose_name='hero title')),
                ('hero_subtitle', models.TextField(default='Earn commissions by promoting our products. Join thousands of successful affiliates!', help_text='Subheading text below the main title', verbose_name='hero subtitle')),
                ('features_title', models.CharField(default='Why Join Our Affiliate Program?', help_text='Title for the features section', max_length=200, verbose_name='features section title')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of features. Each feature has: icon, title, description', verbose_name='features')),
                ('how_it_works_title', models.CharField(default='How It Works', help_text='Title for the how it works section', max_length=200, verbose_name='how it works title')),
                ('steps', models.JSONField(blank=True, default=list, help_text='List of steps. Each step has: title, description', verbose_name='steps')),
                ('cta_title', models.CharField(default='Ready to Start Earning?', help_text='Call-to-action section title', max_length=200, verbose_name='CTA title')),
                ('cta_description', models.TextField(default='Join our affiliate program today and start earning commissions!', help_text='Call-to-action section description', verbose_name='CTA description')),
                ('allow_guest_registration', models.BooleanField(default=True, help_text='Allow new users to register an account during affiliate signup', verbose_name='allow guest registration')),
                ('terms_url', models.URLField(blank=True, help_text='Link to affiliate terms & conditions page', verbose_name='terms & conditions URL')),
                ('require_approval', models.BooleanField(default=True, help_text='If enabled, new affiliates must be approved before they can access the dashboard', verbose_name='require approval')),
                ('welcome_message', models.TextField(blank=True, help_text='Message shown to newly registered affiliates', verbose_name='welcome message')),
                ('translations', models.JSONField(blank=True, default=dict, help_text='Translations for content in different languages', verbose_name='translations')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'affiliate settings',
                'verbose_name_plural': 'affiliate settings',
            },
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('referrer', models.URLField(blank=True, verbose_name='referrer')),
                ('session_id', models.CharField(db_index=True, max_length=255, verbose_name='session ID')),
                ('cookie_value', models.CharField(help_text='Unique cookie for attribution', max_length=255, unique=True, verbose_name='cookie value')),
                ('clicked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='clicked at')),
            ],
            options={
                'verbose_name': 'click',
                'verbose_name_plural': 'clicks',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount')),
                ('currency', models.CharField(blank=True, help_text='Currency of the commission amount (from order)', max_length=3, verbose_name='currency')),
                ('amount_base', models.DecimalField(blank=True, decimal_places=2, help_text="Commission amount in store's base currency", max_digits=10, null=True, verbose_name='base currency amount')),
                ('base_currency', models.CharField(blank=True, help_text="Store's base currency at time of commission", max_length=3, verbose_name='base currency')),
                ('exchange_rate_used', models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate used to compute amount_base', max_digits=18, null=True, verbose_name='exchange rate used')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
            ],
            options={
                'verbose_name': 'commission',
                'verbose_name_plural': 'commissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_code', models.CharField(help_text='Unique tracking code', max_length=32, unique=True, verbose_name='link code')),
                ('destination_url', models.URLField(help_text='Where this link redirects to', verbose_name='destination URL')),
                ('label', models.CharField(blank=True, help_text='Optional label for organizing links', max_length=200, verbose_name='label')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'tracking link',
                'verbose_name_plural': 'tracking links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount')),
                ('method', models.CharField(max_length=50, verbose_name='payment method')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('reference', models.CharField(blank=True, help_text='Payment reference/transaction ID', max_length=255, verbose_name='reference')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('provider_reference', models.CharField(blank=True, help_text='External reference ID from the payout provider', max_length=255, verbose_name='provider reference')),
                ('provider_response', models.JSONField(blank=True, default=dict, help_text='Full API response from the payout provider', verbose_name='provider response')),
                ('currency', models.CharField(default='USD', help_text='Currency code for this payout', max_length=3, verbose_name='currency')),
                ('amount_base', models.DecimalField(blank=True, decimal_places=2, help_text="Payout amount in store's base currency", max_digits=10, null=True, verbose_name='base currency amount')),
                ('base_currency', models.CharField(blank=True, help_text="Store's base currency at time of payout", max_length=3, verbose_name='base currency')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
            ],
            options={
                'verbose_name': 'payout',
                'verbose_name_plural': 'payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this affiliate program', max_length=200, verbose_name='program name')),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='Program description for affiliates', verbose_name='description')),
                ('commission_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20, verbose_name='commission type')),
                ('commission_value', models.DecimalField(decimal_places=2, help_text='Percentage (0-100) or fixed amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='commission value')),
                ('cookie_lifetime_days', models.IntegerField(default=30, help_text='How long to track clicks (1-365 days)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='cookie lifetime days')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20, verbose_name='status')),
                ('auto_approve_affiliates', models.BooleanField(default=False, help_text='Automatically approve new affiliate applications', verbose_name='auto-approve affiliates')),
                ('minimum_payout', models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum balance required for payout', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='minimum payout')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'affiliate program',
                'verbose_name_plural': 'affiliate programs',
                'ordering': ['-created_at'],
            },
        ),
    ]
