# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliate', '0001_initial'),
        ('form_builder', '0001_initial'),
        ('payout_providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='preferred_payout_provider',
            field=models.ForeignKey(blank=True, help_text='Override automatic provider selection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliates', to='payout_providers.payoutprovideraccount', verbose_name='preferred payout provider'),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='affiliateprogrammembership',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.affiliate', verbose_name='affiliate'),
        ),
        migrations.AddField(
            model_name='affiliatesettings',
            name='registration_form',
            field=models.ForeignKey(blank=True, help_text='Custom registration form. If blank, uses default fields.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_settings', to='form_builder.form', verbose_name='registration form'),
        ),
        migrations.AddField(
            model_name='commission',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='affiliate.affiliate', verbose_name='affiliate'),
        ),
        migrations.AddField(
            model_name='commission',
            name='click',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='affiliate.click', verbose_name='click'),
        ),
    ]
