# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliate', '0002_initial'),
        ('orders', '0001_initial'),
        ('payout_providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_commissions', to='orders.order', verbose_name='order'),
        ),
        migrations.AddField(
            model_name='link',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='affiliate.affiliate', verbose_name='affiliate'),
        ),
        migrations.AddField(
            model_name='click',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='affiliate.link', verbose_name='link'),
        ),
        migrations.AddField(
            model_name='payout',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='affiliate.affiliate', verbose_name='affiliate'),
        ),
        migrations.AddField(
            model_name='payout',
            name='commissions',
            field=models.ManyToManyField(help_text='Commissions included in this payout', related_name='payouts', to='affiliate.commission', verbose_name='commissions'),
        ),
        migrations.AddField(
            model_name='payout',
            name='provider_account',
            field=models.ForeignKey(blank=True, help_text='Payout provider account used to process this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='payout_providers.payoutprovideraccount', verbose_name='provider account'),
        ),
        migrations.AddField(
            model_name='program',
            name='merchant',
            field=models.ForeignKey(help_text='Program owner/merchant', on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_programs', to=settings.AUTH_USER_MODEL, verbose_name='merchant'),
        ),
        migrations.AddField(
            model_name='link',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='affiliate.program', verbose_name='program'),
        ),
        migrations.AddField(
            model_name='commission',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='affiliate.program', verbose_name='program'),
        ),
        migrations.AddField(
            model_name='affiliateprogrammembership',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.program', verbose_name='program'),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='programs',
            field=models.ManyToManyField(related_name='affiliates', through='affiliate.AffiliateProgramMembership', to='affiliate.program', verbose_name='programs'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['link', 'clicked_at'], name='affiliate_c_link_id_9f40d7_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['ip_address', 'clicked_at'], name='affiliate_c_ip_addr_63b1d6_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['session_id'], name='affiliate_c_session_501203_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['affiliate', 'status'], name='affiliate_p_affilia_d23ec0_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status', 'created_at'], name='affiliate_p_status_302ee0_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['merchant', 'status'], name='affiliate_p_merchan_579104_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['slug'], name='affiliate_p_slug_57e32a_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['link_code'], name='affiliate_l_link_co_6b98d3_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['affiliate', 'program'], name='affiliate_l_affilia_ffb0e1_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['affiliate', 'status'], name='affiliate_c_affilia_0a38c6_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['program', 'status'], name='affiliate_c_program_1b8879_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['status', 'created_at'], name='affiliate_c_status_9df018_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='affiliateprogrammembership',
            unique_together={('affiliate', 'program')},
        ),
        migrations.AddIndex(
            model_name='affiliate',
            index=models.Index(fields=['affiliate_code'], name='affiliate_a_affilia_2e11ac_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliate',
            index=models.Index(fields=['status'], name='affiliate_a_status_da3926_idx'),
        ),
    ]
