# Generated by Django 5.1.4 on 2026-03-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSOProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(default='SSO', help_text="Display name for the SSO button, e.g. 'Microsoft', 'Okta', 'Google Workspace'", max_length=100, verbose_name='Provider Name')),
                ('oidc_discovery_url', models.URLField(blank=True, help_text='OpenID Connect discovery endpoint (e.g. https://login.microsoftonline.com/{tenant}/v2.0/.well-known/openid-configuration)', max_length=500, verbose_name='OIDC Discovery URL')),
                ('oidc_authorization_endpoint', models.URLField(blank=True, max_length=500, verbose_name='Authorization Endpoint')),
                ('oidc_token_endpoint', models.URLField(blank=True, max_length=500, verbose_name='Token Endpoint')),
                ('oidc_userinfo_endpoint', models.URLField(blank=True, max_length=500, verbose_name='UserInfo Endpoint')),
                ('oidc_jwks_endpoint', models.URLField(blank=True, max_length=500, verbose_name='JWKS Endpoint')),
                ('oidc_end_session_endpoint', models.URLField(blank=True, help_text='Used for single sign-out (optional)', max_length=500, verbose_name='End Session Endpoint')),
                ('oidc_client_id', models.CharField(blank=True, help_text='Application/Client ID from your identity provider', max_length=255, verbose_name='Client ID')),
                ('oidc_client_secret_encrypted', models.BinaryField(blank=True, default=b'', verbose_name='Client Secret (Encrypted)')),
                ('claim_email', models.CharField(default='email', help_text='OIDC claim field for user email address', max_length=100, verbose_name='Email Claim')),
                ('claim_first_name', models.CharField(default='given_name', help_text='OIDC claim field for first name', max_length=100, verbose_name='First Name Claim')),
                ('claim_last_name', models.CharField(default='family_name', help_text='OIDC claim field for last name', max_length=100, verbose_name='Last Name Claim')),
                ('claim_groups', models.CharField(blank=True, default='groups', help_text='OIDC claim field for group memberships (leave blank to disable group mapping)', max_length=100, verbose_name='Groups Claim')),
                ('staff_groups', models.TextField(blank=True, help_text='Comma-separated group names or IDs that grant staff status', verbose_name='Staff Groups')),
                ('superuser_groups', models.TextField(blank=True, help_text='Comma-separated group names or IDs that grant superuser status', verbose_name='Superuser Groups')),
                ('oidc_scopes', models.CharField(default='openid email profile', help_text='Space-separated OIDC scopes to request', max_length=500, verbose_name='OIDC Scopes')),
                ('auto_create_users', models.BooleanField(default=False, help_text='Automatically create a Django user account when an SSO user signs in for the first time', verbose_name='Auto-Create Users')),
                ('restrict_to_staff', models.BooleanField(default=True, help_text='Only allow existing staff users to sign in via SSO. Disable to allow SSO user auto-creation.', verbose_name='Restrict to Staff')),
            ],
            options={
                'verbose_name': 'SSO Provider Configuration',
                'verbose_name_plural': 'SSO Provider Configuration',
            },
        ),
    ]
