# Generated by Django 5.1.4 on 2026-05-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_sso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssoproviderconfig',
            name='auto_create_users',
            field=models.BooleanField(default=False, help_text='Automatically create a user account when an SSO user signs in for the first time', verbose_name='Auto-Create Users'),
        ),
    ]
