# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('component_updates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutProviderAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('paypal', 'PayPal'), ('airwallex', 'Airwallex'), ('wise', 'Wise')], help_text='The payout provider service', max_length=50, verbose_name='Provider Type')),
                ('name', models.CharField(help_text='A friendly name for this account (e.g., "Primary PayPal")', max_length=100, verbose_name='Account Name')),
                ('credentials_encrypted', models.JSONField(blank=True, default=dict, help_text='Encrypted API credentials (never stored in plain text)', verbose_name='Credentials')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Provider-specific configuration settings', verbose_name='Settings')),
                ('supported_methods', models.JSONField(blank=True, default=list, help_text='List of payout methods this account supports', verbose_name='Supported Methods')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this provider account is active', verbose_name='Active')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default provider for its supported methods', verbose_name='Default')),
                ('connection_status', models.CharField(choices=[('untested', 'Untested'), ('connected', 'Connected'), ('failed', 'Connection Failed'), ('invalid_credentials', 'Invalid Credentials')], default='untested', max_length=30, verbose_name='Connection Status')),
                ('last_tested_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Tested')),
                ('last_error_message', models.TextField(blank=True, default='', help_text='Last connection error message', verbose_name='Last Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('component', models.ForeignKey(blank=True, help_text='Installed provider component from the component registry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_provider_accounts', to='component_updates.componentregistry')),
            ],
            options={
                'verbose_name': 'Payout Provider Account',
                'verbose_name_plural': 'Payout Provider Accounts',
                'ordering': ['-is_default', '-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PayoutWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(help_text='Provider that sent the webhook', max_length=50, verbose_name='Provider Type')),
                ('event_type', models.CharField(help_text='Type of webhook event', max_length=100, verbose_name='Event Type')),
                ('event_id', models.CharField(blank=True, default='', help_text="Provider's unique event identifier", max_length=255, verbose_name='Event ID')),
                ('payload', models.JSONField(default=dict, help_text='Full webhook payload', verbose_name='Payload')),
                ('headers', models.JSONField(default=dict, help_text='Request headers', verbose_name='Headers')),
                ('signature_valid', models.BooleanField(help_text='Whether signature verification passed', null=True, verbose_name='Signature Valid')),
                ('processed', models.BooleanField(default=False, help_text='Whether the webhook was successfully processed', verbose_name='Processed')),
                ('processing_error', models.TextField(blank=True, default='', help_text='Error message if processing failed', verbose_name='Processing Error')),
                ('payout_reference', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Payout Reference')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Received')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('provider_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='payout_providers.payoutprovideraccount')),
            ],
            options={
                'verbose_name': 'Payout Webhook Log',
                'verbose_name_plural': 'Payout Webhook Logs',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['provider_type', 'event_type'], name='payout_prov_provide_90d499_idx'), models.Index(fields=['event_id'], name='payout_prov_event_i_4695c2_idx')],
            },
        ),
    ]
