# Generated by Django 5.2.16 on 2026-07-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component_updates', '0005_alter_componentregistry_component_type'),
        ('payout_providers', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payoutprovideraccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('provider_type',), name='unique_default_payout_provider_per_type'),
        ),
    ]
