# Generated by Django 5.1.4 on 2026-03-05 04:48

import developer_portal.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_slug', models.CharField(db_index=True, max_length=200)),
                ('component_name', models.CharField(max_length=200)),
                ('current_version', models.CharField(blank=True, max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('component_type', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=500)),
                ('pricing_model', models.CharField(blank=True, default='free', max_length=10)),
                ('price_eur', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('downloads_total', models.PositiveIntegerField(default=0)),
                ('downloads_period', models.PositiveIntegerField(default=0, help_text='Downloads in the last N days (see period_days)')),
                ('period_days', models.PositiveIntegerField(default=30)),
                ('versions_count', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Component Analytics',
                'verbose_name_plural': 'Component Analytics',
                'ordering': ['-downloads_total'],
            },
        ),
        migrations.CreateModel(
            name='ComponentReviewMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_slug', models.CharField(db_index=True, max_length=200)),
                ('component_name', models.CharField(blank=True, max_length=200)),
                ('upgrade_server_review_id', models.PositiveIntegerField(db_index=True, help_text='ID of the ComponentReview on the upgrade server')),
                ('rating', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField(blank=True)),
                ('author_name', models.CharField(max_length=100)),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('review_created_at', models.DateTimeField()),
                ('developer_response', models.TextField(blank=True)),
                ('developer_response_at', models.DateTimeField(blank=True, null=True)),
                ('response_synced', models.BooleanField(default=True, help_text='Whether the response has been synced to the upgrade server')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the developer has seen this review')),
                ('notification_sent_at', models.DateTimeField(blank=True, help_text='When the notification email was sent for this review', null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Component Review',
                'verbose_name_plural': 'Component Reviews',
                'ordering': ['-review_created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComponentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component_type', models.CharField(db_index=True, default='theme', help_text='Component type slug (e.g. theme, widget, payment_provider)', max_length=50)),
                ('component_slug', models.SlugField(help_text='Component identifier slug (from manifest)', max_length=200)),
                ('component_name', models.CharField(help_text='Display name of the component', max_length=200)),
                ('version', models.CharField(help_text='Semantic version (e.g., 1.0.0)', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description for marketplace listing')),
                ('changelog', models.TextField(blank=True, help_text='What changed in this version')),
                ('package_file', models.FileField(help_text='Component ZIP package', upload_to='developer/submissions/%Y/%m/')),
                ('package_checksum', models.CharField(blank=True, help_text='SHA-256 checksum of the package file', max_length=64)),
                ('package_size_bytes', models.BigIntegerField(default=0)),
                ('manifest_data', models.JSONField(blank=True, default=dict, help_text='Extracted manifest.json content')),
                ('validation_status', models.CharField(choices=[('pending', 'Pending Validation'), ('validating', 'Validating'), ('passed', 'Validation Passed'), ('failed', 'Validation Failed')], db_index=True, default='pending', max_length=20)),
                ('validation_results', models.JSONField(blank=True, default=dict, help_text='Detailed validation output')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Revision Requested')], db_index=True, default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from the reviewer (visible to developer)')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('upgrade_server_component_slug', models.CharField(blank=True, help_text='Component slug on the upgrade server', max_length=200)),
                ('upgrade_server_version_id', models.IntegerField(blank=True, help_text='ComponentVersion ID on the upgrade server', null=True)),
                ('pricing_model', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Base price in EUR (0 for free components). Marketplace prices in other currencies are derived from exchange rates.', max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Component Submission',
                'verbose_name_plural': 'Component Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ComponentVersionMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_slug', models.CharField(db_index=True, max_length=200)),
                ('version', models.CharField(max_length=20)),
                ('channel', models.CharField(default='stable', max_length=20)),
                ('changelog', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('package_size_bytes', models.BigIntegerField(default=0)),
                ('breaking_changes', models.BooleanField(default=False)),
                ('security_update', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Component Version',
                'verbose_name_plural': 'Component Versions',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyDownloadStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('downloads', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Daily Download Stat',
                'verbose_name_plural': 'Daily Download Stats',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DeveloperLicenseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('license_type', models.CharField(choices=[('shop', 'Spwig Shop'), ('pos', 'Spwig POS'), ('both', 'Shop + POS')], default='both', help_text='Which products this license covers', max_length=20)),
                ('reason', models.TextField(help_text='Why do you need a development license?')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (shown to developer on rejection)')),
                ('license_key', models.CharField(blank=True, help_text='Populated from the LicenseKey generated via digital product flow', max_length=64)),
                ('license_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Developer License Request',
                'verbose_name_plural': 'Developer License Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_slug', models.SlugField(help_text='Unique identifier for your developer profile (used in URLs)', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Public display name for your developer profile', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Short description about you or your company')),
                ('website', models.URLField(blank=True, help_text='Your website or portfolio URL')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (visible to developer)')),
                ('upgrade_server_author_slug', models.CharField(blank=True, help_text='Slug of the Author record on the upgrade server', max_length=200)),
                ('logo_url', models.CharField(blank=True, default='', help_text='Logo URL from upgrade server (used when no local logo uploaded)', max_length=500)),
                ('api_key', models.CharField(default=developer_portal.models.generate_api_key, help_text='API key for programmatic submissions', max_length=64, unique=True)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('payout_method', models.CharField(blank=True, choices=[('airwallex', 'Bank Transfer (Airwallex)'), ('paypal', 'PayPal')], help_text='Preferred payout method', max_length=20)),
                ('payout_details', models.JSONField(blank=True, default=dict, help_text='Bank details (Airwallex) or PayPal email')),
                ('review_notification_preference', models.CharField(choices=[('immediate', 'Immediately'), ('daily', 'Daily digest'), ('weekly', 'Weekly digest'), ('none', 'No notifications')], default='immediate', help_text='How often to receive review notifications', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Developer Profile',
                'verbose_name_plural': 'Developer Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('comment', 'Comment'), ('approve', 'Approved'), ('reject', 'Rejected'), ('request_revision', 'Revision Requested'), ('validation_passed', 'Automated Validation Passed'), ('validation_failed', 'Automated Validation Failed')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Submission Review',
                'verbose_name_plural': 'Submission Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
