# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developer_portal', '0001_initial'),
        ('media_library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='componentsubmission',
            name='preview_images',
            field=models.ManyToManyField(blank=True, help_text='Screenshots and preview images', related_name='+', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='componentsubmission',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='componentsubmission',
            name='thumbnail',
            field=models.ForeignKey(blank=True, help_text='Thumbnail image for marketplace listing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset'),
        ),
    ]
