# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developer_portal', '0002_initial'),
        ('media_library', '0002_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='developerlicenserequest',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Auto-generated order for the dev license product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AddField(
            model_name='developerlicenserequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Developer logo or avatar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='developerlicenserequest',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_requests', to='developer_portal.developerprofile'),
        ),
        migrations.AddField(
            model_name='dailydownloadstat',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_download_stats', to='developer_portal.developerprofile'),
        ),
        migrations.AddField(
            model_name='componentversionmirror',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_versions', to='developer_portal.developerprofile'),
        ),
        migrations.AddField(
            model_name='componentsubmission',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='developer_portal.developerprofile'),
        ),
        migrations.AddField(
            model_name='componentreviewmirror',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_reviews', to='developer_portal.developerprofile'),
        ),
        migrations.AddField(
            model_name='componentanalytics',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_analytics', to='developer_portal.developerprofile'),
        ),
        migrations.AddField(
            model_name='submissionreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissionreview',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='developer_portal.componentsubmission'),
        ),
        migrations.AlterUniqueTogether(
            name='dailydownloadstat',
            unique_together={('developer', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='componentversionmirror',
            unique_together={('developer', 'component_slug', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='componentsubmission',
            unique_together={('component_slug', 'version', 'component_type')},
        ),
        migrations.AlterUniqueTogether(
            name='componentreviewmirror',
            unique_together={('developer', 'upgrade_server_review_id')},
        ),
        migrations.AlterUniqueTogether(
            name='componentanalytics',
            unique_together={('developer', 'component_slug')},
        ),
    ]
