# Generated by Django 5.1.4 on 2026-03-10 07:29

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer_portal', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developerlicenserequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Developer License', 'verbose_name_plural': 'Developer Licenses'},
        ),
        migrations.AddField(
            model_name='developerlicenserequest',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Whether this is the free developer license'),
        ),
        migrations.AddField(
            model_name='developerlicenserequest',
            name='setup_token',
            field=models.TextField(blank=True, help_text='JWT setup token for installation activation (from update server)'),
        ),
        migrations.AddField(
            model_name='developerlicenserequest',
            name='setup_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the setup token expires', null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company or organization name', max_length=200),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='Country of residence or business', max_length=2),
        ),
        migrations.AlterField(
            model_name='developerlicenserequest',
            name='license_key',
            field=models.CharField(blank=True, help_text='License key from the update server', max_length=64),
        ),
        migrations.AlterField(
            model_name='developerlicenserequest',
            name='reason',
            field=models.TextField(blank=True, default='', help_text='Why do you need a development license?'),
        ),
    ]
