# Generated by Django 5.1.4 on 2026-03-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer_portal', '0004_developer_license_auto_provisioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerlicenserequest',
            name='setup_token_id',
            field=models.UUIDField(blank=True, help_text='Setup token UUID on the update server (needed for regeneration)', null=True),
        ),
    ]
