# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('design', '0001_initial'),
        ('page_builder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='page_reference',
            field=models.ForeignKey(blank=True, help_text="Page to link to (when item_type is 'page')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='page_builder.page'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='design.menuitem'),
        ),
        migrations.AddIndex(
            model_name='pagetier',
            index=models.Index(fields=['page_type'], name='design_page_page_ty_cb96f1_idx'),
        ),
        migrations.AddIndex(
            model_name='pagetier',
            index=models.Index(fields=['tier'], name='design_page_tier_ab05dc_idx'),
        ),
        migrations.AddField(
            model_name='theme',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='globaldesignsettings',
            name='active_theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_sites', to='design.theme'),
        ),
        migrations.AddField(
            model_name='designtoken',
            name='theme',
            field=models.ForeignKey(blank=True, help_text='Associated theme (only for theme-level tokens)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design_tokens', to='design.theme', verbose_name='Theme'),
        ),
        migrations.AddField(
            model_name='componentstore',
            name='source_theme',
            field=models.ForeignKey(blank=True, help_text='Theme that bundled this component (if component came from a theme package)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundled_components', to='design.theme'),
        ),
        migrations.AddField(
            model_name='themeasset',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='design.theme'),
        ),
        migrations.AddField(
            model_name='themebranding',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.theme'),
        ),
        migrations.AddField(
            model_name='themeinstallation',
            name='installed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='themeinstallation',
            name='previous_theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='design.theme'),
        ),
        migrations.AddField(
            model_name='themeinstallation',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.theme'),
        ),
        migrations.AddField(
            model_name='tiercomponentpermission',
            name='component',
            field=models.ForeignKey(help_text='Component being whitelisted', on_delete=django.db.models.deletion.CASCADE, related_name='tier_permissions', to='design.componentstore', verbose_name='Component'),
        ),
        migrations.AddField(
            model_name='tiercomponentpermission',
            name='tier',
            field=models.ForeignKey(help_text='Page tier this permission applies to', on_delete=django.db.models.deletion.CASCADE, related_name='component_permissions', to='design.pagetier', verbose_name='Page Tier'),
        ),
        migrations.AddField(
            model_name='widget',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='widgetplacement',
            name='footer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widget_placements', to='design.footertemplate'),
        ),
        migrations.AddField(
            model_name='widgetplacement',
            name='header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widget_placements', to='design.headertemplate'),
        ),
        migrations.AddField(
            model_name='widgetplacement',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='design.widget'),
        ),
        migrations.AddIndex(
            model_name='componentvalidationreport',
            index=models.Index(fields=['component', '-validated_at'], name='design_comp_compone_449870_idx'),
        ),
        migrations.AddIndex(
            model_name='componentvalidationreport',
            index=models.Index(fields=['is_valid'], name='design_comp_is_vali_3c8b02_idx'),
        ),
        migrations.AddIndex(
            model_name='devsession',
            index=models.Index(fields=['token'], name='design_dev__token_e19d37_idx'),
        ),
        migrations.AddIndex(
            model_name='devsession',
            index=models.Index(fields=['is_active', '-created_at'], name='design_dev__is_acti_f02621_idx'),
        ),
        migrations.AddIndex(
            model_name='devsession',
            index=models.Index(fields=['user', '-created_at'], name='design_dev__user_id_fb140d_idx'),
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['slug', '-version'], name='design_them_slug_2ff9e3_idx'),
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['is_active', 'is_default'], name='design_them_is_acti_1322b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='theme',
            unique_together={('slug', 'version')},
        ),
        migrations.AddIndex(
            model_name='designtoken',
            index=models.Index(fields=['name'], name='design_desi_name_44b083_idx'),
        ),
        migrations.AddIndex(
            model_name='designtoken',
            index=models.Index(fields=['token_type'], name='design_desi_token_t_75d4e1_idx'),
        ),
        migrations.AddIndex(
            model_name='designtoken',
            index=models.Index(fields=['source'], name='design_desi_source_f46ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='designtoken',
            index=models.Index(fields=['priority_level'], name='design_desi_priorit_346941_idx'),
        ),
        migrations.AddIndex(
            model_name='designtoken',
            index=models.Index(fields=['priority_level', 'name'], name='design_desi_priorit_b1355a_idx'),
        ),
        migrations.AddConstraint(
            model_name='designtoken',
            constraint=models.UniqueConstraint(condition=models.Q(('source__in', ['brand_builder', 'system'])), fields=('name', 'source'), name='unique_global_token'),
        ),
        migrations.AddConstraint(
            model_name='designtoken',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'theme')), fields=('name', 'source', 'theme'), name='unique_theme_token'),
        ),
        migrations.AddConstraint(
            model_name='designtoken',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'component')), fields=('name', 'source', 'component'), name='unique_component_token'),
        ),
        migrations.AddIndex(
            model_name='componentstore',
            index=models.Index(fields=['component_type'], name='design_comp_compone_8266a8_idx'),
        ),
        migrations.AddIndex(
            model_name='componentstore',
            index=models.Index(fields=['review_status'], name='design_comp_review__6ec06c_idx'),
        ),
        migrations.AddIndex(
            model_name='componentstore',
            index=models.Index(fields=['author'], name='design_comp_author_4b8ebb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='themeasset',
            unique_together={('theme', 'path')},
        ),
        migrations.AlterUniqueTogether(
            name='tiercomponentpermission',
            unique_together={('tier', 'component')},
        ),
        migrations.AddConstraint(
            model_name='widgetplacement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('footer__isnull', True), ('header__isnull', False)), models.Q(('footer__isnull', False), ('header__isnull', True)), _connector='OR'), name='placement_either_header_or_footer'),
        ),
    ]
