# Generated by Django 5.1.4 on 2026-03-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Translations for widget config text by language code'),
        ),
    ]
