# Generated by Django 5.1.4 on 2026-03-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_widget_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetemplateconfig',
            name='blog_list_options',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration options for the blog list template.', verbose_name='Blog List Options'),
        ),
        migrations.AddField(
            model_name='pagetemplateconfig',
            name='blog_list_template',
            field=models.CharField(choices=[('grid', 'Grid'), ('list', 'List'), ('magazine', 'Magazine'), ('minimal', 'Minimal')], default='grid', help_text='The blog listing page layout.', max_length=30, verbose_name='Blog List Template'),
        ),
        migrations.AddField(
            model_name='pagetemplateconfig',
            name='blog_post_options',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration options for the blog post template.', verbose_name='Blog Post Options'),
        ),
        migrations.AddField(
            model_name='pagetemplateconfig',
            name='blog_post_template',
            field=models.CharField(choices=[('classic', 'Classic'), ('minimal', 'Minimal'), ('magazine', 'Magazine'), ('full_width', 'Full Width')], default='classic', help_text='The default blog post detail layout. Individual posts can override this.', max_length=30, verbose_name='Blog Post Template'),
        ),
    ]
