# Generated by Django 5.2.16 on 2026-08-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_pagetemplateconfig_blog_list_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('logo', 'Logo'), ('menu', 'Navigation Menu'), ('search', 'Search Bar'), ('cart', 'Mini Cart'), ('account', 'Account Menu'), ('language', 'Language Selector'), ('currency', 'Currency Selector'), ('ship_to', 'Ship-To Selector'), ('social', 'Social Media Links'), ('newsletter', 'Newsletter Signup'), ('contact', 'Contact Information'), ('text', 'Text/HTML Block'), ('links', 'Link List'), ('payment', 'Payment Methods'), ('trust_badges', 'Trust Badges'), ('announcement', 'Announcement Bar'), ('loyalty_balance', 'Loyalty Points Balance'), ('loyalty_tier_badge', 'Loyalty Tier Badge'), ('site_variable', 'Site Variable'), ('custom', 'Custom Widget')], max_length=50),
        ),
    ]
