# Generated by Django 5.2.16 on 2026-08-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_alter_widget_widget_type'),
        ('visibility', '0002_move_content_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='rule_groups',
            field=models.ManyToManyField(blank=True, help_text='Advanced visibility rules for conditional display', related_name='menu_items', to='visibility.rulegroup'),
        ),
        migrations.AddField(
            model_name='widgetplacement',
            name='rule_groups',
            field=models.ManyToManyField(blank=True, help_text='Advanced visibility rules for conditional display', related_name='widget_placements', to='visibility.rulegroup'),
        ),
    ]
