# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('page_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cookie_page',
            field=models.ForeignKey(blank=True, help_text="Your store's cookie policy", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='page_builder.page', verbose_name='Cookie Policy Page'),
        ),
    ]
