# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('media_library', '0002_initial'),
        ('page_builder', '0001_initial'),
        ('shipping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_manual_carrier',
            field=models.ForeignKey(blank=True, help_text='Default carrier for manual tracking entry (e.g., DHL Express, FedEx)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_site', to='shipping.carrierpreset', verbose_name='Default Manual Carrier'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_shipping_provider',
            field=models.ForeignKey(blank=True, help_text='Default API provider for shipping label generation (e.g., Easyship, ShipEngine)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_site', to='shipping.provideraccount', verbose_name='Default Shipping Provider'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_404_page',
            field=models.ForeignKey(blank=True, help_text="Custom page for 'page not found' errors", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='page_builder.page', verbose_name='404 Error Page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_500_page',
            field=models.ForeignKey(blank=True, help_text='Custom page for server errors', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='page_builder.page', verbose_name='500 Error Page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ForeignKey(blank=True, help_text='Select a favicon from the media library (recommended: 32x32 or 16x16 pixels, ICO, PNG, or SVG format)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favicon_for_site', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_page',
            field=models.ForeignKey(blank=True, help_text='The main landing page of your store', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='page_builder.page', verbose_name='Home Page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_page',
            field=models.ForeignKey(blank=True, help_text='Custom page displayed when maintenance mode is enabled. Edit this page in Page Builder to customize the maintenance experience.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='page_builder.page', verbose_name='Maintenance Page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_page',
            field=models.ForeignKey(blank=True, help_text="Your store's privacy policy", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='page_builder.page', verbose_name='Privacy Policy Page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='returns_page',
            field=models.ForeignKey(blank=True, help_text='Return and refund policies', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='page_builder.page', verbose_name='Returns Policy Page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shipping_page',
            field=models.ForeignKey(blank=True, help_text='Shipping policies and delivery information', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='page_builder.page', verbose_name='Shipping Information Page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ForeignKey(blank=True, help_text='Select a logo from the media library. Recommended: PNG or SVG format. Horizontal logos work best (max 400px wide). SVG files scale perfectly to any size.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_logo_for_site', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_page',
            field=models.ForeignKey(blank=True, help_text="Your store's terms of service/use", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='page_builder.page', verbose_name='Terms of Use Page'),
        ),
        migrations.AddIndex(
            model_name='supportedcurrency',
            index=models.Index(fields=['is_active', 'order'], name='core_suppor_is_acti_815d97_idx'),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='apitoken',
            index=models.Index(fields=['token', 'is_active'], name='core_apitok_token_41df02_idx'),
        ),
        migrations.AddIndex(
            model_name='apitoken',
            index=models.Index(fields=['token_type', 'is_active'], name='core_apitok_token_t_b81cab_idx'),
        ),
        migrations.AddIndex(
            model_name='bugreport',
            index=models.Index(fields=['status', '-created_at'], name='core_bugrep_status_091220_idx'),
        ),
        migrations.AddIndex(
            model_name='cookieconsentlog',
            index=models.Index(fields=['-timestamp'], name='consent_log_time'),
        ),
        migrations.AddIndex(
            model_name='cookieconsentlog',
            index=models.Index(fields=['user', '-timestamp'], name='consent_log_user_time'),
        ),
        migrations.AddIndex(
            model_name='cookieconsentlog',
            index=models.Index(fields=['session_key', '-timestamp'], name='consent_log_sess_time'),
        ),
        migrations.AddIndex(
            model_name='errorreport',
            index=models.Index(fields=['status', '-last_seen'], name='core_errorr_status_d21867_idx'),
        ),
        migrations.AddIndex(
            model_name='errorreport',
            index=models.Index(fields=['fingerprint', 'status'], name='core_errorr_fingerp_45a536_idx'),
        ),
        migrations.AddIndex(
            model_name='helptopic',
            index=models.Index(fields=['component', 'is_published'], name='core_helpto_compone_8955e4_idx'),
        ),
        migrations.AddIndex(
            model_name='helptopic',
            index=models.Index(fields=['slug'], name='core_helpto_slug_f42618_idx'),
        ),
        migrations.AddIndex(
            model_name='helpsearchindex',
            index=models.Index(fields=['topic', 'language'], name='core_helpse_topic_i_ccde98_idx'),
        ),
        migrations.AddIndex(
            model_name='helpsearchindex',
            index=models.Index(fields=['language', 'indexed_at'], name='core_helpse_languag_a5adda_idx'),
        ),
        migrations.AddIndex(
            model_name='helpview',
            index=models.Index(fields=['topic', 'viewed_at'], name='core_helpvi_topic_i_c0b45d_idx'),
        ),
        migrations.AddIndex(
            model_name='trusteddevice',
            index=models.Index(fields=['user', 'is_revoked'], name='core_truste_user_id_e29178_idx'),
        ),
        migrations.AddIndex(
            model_name='trusteddevice',
            index=models.Index(fields=['device_token_hash', 'is_revoked'], name='core_truste_device__f33c95_idx'),
        ),
        migrations.AddIndex(
            model_name='trusteddevice',
            index=models.Index(fields=['expires_at'], name='core_truste_expires_8f9114_idx'),
        ),
    ]
