# Generated by Django 5.1.4 on 2026-03-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admin_password_login_enabled',
            field=models.BooleanField(default=True, help_text='Allow password-based login on the admin page. Disable to enforce SSO-only access.', verbose_name='Allow Password Login'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_sso_enabled',
            field=models.BooleanField(default=False, help_text='Show enterprise SSO button on the admin login page', verbose_name='Enable SSO for Admin Login'),
        ),
    ]
