# Generated by Django 5.1.4 on 2026-03-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_admin_password_login_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseRevocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=255)),
                ('grace_expires_at', models.DateTimeField(help_text='Shop continues operating until this date')),
                ('acknowledged', models.BooleanField(default=False, help_text='Merchant dismissed the warning banner')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AlterField(
            model_name='cookieconsentlog',
            name='session_key',
            field=models.CharField(blank=True, default='', help_text='Session key for anonymous visitors', max_length=40, verbose_name='Session Key'),
        ),
    ]
