# Generated by Django 5.1.4 on 2026-03-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_license_revocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesBellEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('sale', 'Sale'), ('refund', 'Refund'), ('developer_signup', 'Developer Signup')], db_index=True, max_length=20)),
                ('subtype', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('product', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
