# Generated by Django 5.1.4 on 2026-03-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sales_bell_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='allow_backorders_by_default',
            field=models.BooleanField(default=False, help_text='Allow customers to order products even when out of stock (new products inherit this setting)', verbose_name='Allow Backorders by Default'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_reorder_lead_days',
            field=models.PositiveIntegerField(default=14, help_text='Default number of days it takes to receive restock from supplier', verbose_name='Default Reorder Lead Time (Days)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='document_logo_width',
            field=models.PositiveIntegerField(default=200, help_text='Width of the logo in generated PDF documents (invoices, packing slips). Height scales proportionally.', verbose_name='Document Logo Width (px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_footer_text',
            field=models.TextField(blank=True, help_text='Custom text displayed at the bottom of generated invoices (e.g., payment terms, thank you message)', verbose_name='Invoice Footer Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='low_stock_alert_frequency',
            field=models.CharField(choices=[('realtime', 'Real-time (on each stock change)'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Summary')], default='daily', help_text='How often to send low stock alert notifications', max_length=10, verbose_name='Low Stock Alert Frequency'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='packing_slip_footer_text',
            field=models.TextField(blank=True, help_text='Custom text displayed at the bottom of packing slips (e.g., return instructions)', verbose_name='Packing Slip Footer Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='safety_stock_multiplier',
            field=models.FloatField(default=1.5, help_text='Multiplier applied to velocity for safety stock calculation (e.g., 1.5 means 50%% buffer)', verbose_name='Safety Stock Multiplier'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Business tax identification number shown on invoices', max_length=50, verbose_name='Tax ID / VAT Number'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='velocity_calculation_window_days',
            field=models.PositiveIntegerField(default=30, help_text='Number of days to look back when calculating product sales velocity', verbose_name='Velocity Calculation Window (Days)'),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='token_type',
            field=models.CharField(choices=[('help_system', 'Help System'), ('integration', 'External Integration'), ('webhook', 'Webhook'), ('custom', 'Custom'), ('sync', 'Instance Sync')], default='custom', help_text='Type/purpose of this token', max_length=50, verbose_name='Token Type'),
        ),
    ]
