# Generated by Django 5.1.4 on 2026-03-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_allow_backorders_by_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_delivery_mode',
            field=models.CharField(choices=[('live', 'Live - Deliver emails normally'), ('paused', 'Paused - Hold emails for later delivery'), ('log_only', 'Log Only - Record emails but never deliver')], default='live', help_text="Controls how outgoing emails are handled. 'Live' delivers normally. 'Paused' holds emails until you switch back to Live. 'Log Only' records emails in the outbox for review but never sends them.", max_length=10, verbose_name='Email Delivery Mode'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_test_redirect_address',
            field=models.EmailField(blank=True, help_text='When set, ALL outgoing emails are redirected to this address instead of the real recipient. Useful for testing email templates and flows. Leave blank to send to actual recipients.', max_length=254, verbose_name='Test Redirect Email'),
        ),
    ]
