# Generated by Django 5.1.4 on 2026-03-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_email_delivery_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sandbox_email_whitelist',
            field=models.JSONField(blank=True, default=list, help_text='In sandbox mode, only emails to these addresses will be delivered. All other emails are logged but never sent. The admin email is always included automatically. Maximum 10 addresses.', verbose_name='Sandbox Email Whitelist'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sandbox_sms_whitelist',
            field=models.JSONField(blank=True, default=list, help_text='In sandbox mode, only SMS messages to these phone numbers will be sent. All other messages are logged but never delivered. Use E.164 format (e.g., +1234567890). Maximum 5 numbers.', verbose_name='Sandbox SMS Whitelist'),
        ),
    ]
