# Generated by Django 5.1.4 on 2026-03-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sandbox_whitelists'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='max_devices_per_user',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of mobile devices each staff member can have registered simultaneously. Set to 0 for unlimited devices.', verbose_name='Maximum Devices Per User'),
        ),
    ]
