# Generated by Django 5.1.4 on 2026-07-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_max_devices_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='public_gift_card_balance_enabled',
            field=models.BooleanField(default=True, help_text='Let anyone check a gift card balance by entering its code, without signing in. Recipients usually have no account, so this is on by default and rate limited. Turn it off if you would rather customers contacted you for balances.'),
        ),
    ]
