# Generated by Django 5.1.7 on 2026-07-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_public_gift_card_balance_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='scopes',
            field=models.JSONField(blank=True, default=dict, help_text='Which admin APIs this token may call and at what level. Empty means the token cannot reach any scoped API.', verbose_name='API Scopes'),
        ),
    ]
