# Generated by Django 5.2.16 on 2026-08-15 14:00

from django.db import migrations, models


def preserve_sms_verification_behaviour(apps, schema_editor):
    """Keep existing installs on the pre-change (always verify) behaviour.

    Before this change ``require_sms_verification`` was never read and
    ``should_send_sms`` unconditionally required a verified phone. Existing rows
    therefore hold the old default (False), which — now that the flag is honoured
    — would silently drop the verification requirement. Flip them to True so the
    observable behaviour is unchanged; merchants can opt out afterwards in admin.
    """
    SiteSettings = apps.get_model("core", "SiteSettings")
    SiteSettings.objects.filter(require_sms_verification=False).update(
        require_sms_verification=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_apitoken_scopes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='require_sms_verification',
            field=models.BooleanField(default=True, help_text='Require customers to verify their phone with a one-time code before any SMS is sent to them (recommended for TCPA compliance). When off, an SMS opt-in alone is enough to start sending.', verbose_name='Require SMS Verification'),
        ),
        migrations.RunPython(
            preserve_sms_verification_behaviour,
            migrations.RunPython.noop,
        ),
    ]
