# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loyalty', '0001_initial'),
        ('media_library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltybadge',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Custom badge image from media library. If provided, this takes priority over icon.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge_uses', to='media_library.mediaasset'),
        ),
        migrations.CreateModel(
            name='LoyaltyBalance',
            fields=[
                ('member', models.OneToOneField(help_text='Loyalty member this balance belongs to', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='balance', serialize=False, to='loyalty.loyaltymember')),
                ('available_points', models.IntegerField(default=0, help_text='Currently available points for redemption', validators=[django.core.validators.MinValueValidator(0)])),
                ('pending_points', models.IntegerField(default=0, help_text='Points earned but not yet available (pending refund window)', validators=[django.core.validators.MinValueValidator(0)])),
                ('lifetime_earned', models.IntegerField(default=0, help_text='Total points earned over lifetime (including expired/redeemed)', validators=[django.core.validators.MinValueValidator(0)])),
                ('lifetime_redeemed', models.IntegerField(default=0, help_text='Total points redeemed over lifetime', validators=[django.core.validators.MinValueValidator(0)])),
                ('lifetime_expired', models.IntegerField(default=0, help_text='Total points expired over lifetime', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_earned_at', models.DateTimeField(blank=True, help_text='Last time points were earned', null=True)),
                ('last_redeemed_at', models.DateTimeField(blank=True, help_text='Last time points were redeemed', null=True)),
                ('last_recalculated_at', models.DateTimeField(auto_now=True, help_text='Last time balance was recalculated from ledger')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loyalty Balance',
                'verbose_name_plural': 'Loyalty Balances',
            },
        ),
        migrations.AddField(
            model_name='loyaltymember',
            name='customer',
            field=models.OneToOneField(help_text='Customer enrolled in loyalty program', on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loyaltycampaign',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loyaltycampaignexecution',
            name='campaign',
            field=models.ForeignKey(help_text='Campaign being executed', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='loyalty.loyaltycampaign'),
        ),
        migrations.AddField(
            model_name='loyaltycampaignexecution',
            name='member',
            field=models.ForeignKey(help_text='Member receiving campaign', on_delete=django.db.models.deletion.CASCADE, related_name='campaign_executions', to='loyalty.loyaltymember'),
        ),
        migrations.AddField(
            model_name='loyaltymemberbadge',
            name='badge',
            field=models.ForeignKey(help_text='Badge that was earned', on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='loyalty.loyaltybadge'),
        ),
        migrations.AddField(
            model_name='loyaltymemberbadge',
            name='member',
            field=models.ForeignKey(help_text='Member who earned the badge', on_delete=django.db.models.deletion.CASCADE, related_name='badges_earned', to='loyalty.loyaltymember'),
        ),
        migrations.AddField(
            model_name='loyaltyredemption',
            name='member',
            field=models.ForeignKey(help_text='Member who redeemed the reward', on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='loyalty.loyaltymember'),
        ),
    ]
