# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('loyalty', '0002_initial'),
        ('orders', '0001_initial'),
        ('vouchers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyredemption',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order where redemption was applied', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_redemptions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='loyaltyredemption',
            name='voucher_code',
            field=models.ForeignKey(blank=True, help_text='Generated voucher code (for discount rewards)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_redemptions', to='vouchers.vouchercode'),
        ),
        migrations.AddField(
            model_name='loyaltyreward',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product to award (for product rewards)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_rewards', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='loyaltyredemption',
            name='reward',
            field=models.ForeignKey(help_text='Reward that was redeemed', on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='loyalty.loyaltyreward'),
        ),
        migrations.AddField(
            model_name='loyaltyrule',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who created this rule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_rules_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loyaltysegment',
            index=models.Index(fields=['criteria_type', 'is_active'], name='loyalty_loy_criteri_8cbc33_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltysegment',
            index=models.Index(fields=['last_calculated_at'], name='loyalty_loy_last_ca_c1e8e8_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltysegment',
            index=models.Index(fields=['slug'], name='loyalty_loy_slug_3d74ec_idx'),
        ),
        migrations.AddField(
            model_name='loyaltycampaign',
            name='target_segment',
            field=models.ForeignKey(blank=True, help_text='Target customer segment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='loyalty.loyaltysegment'),
        ),
        migrations.AddField(
            model_name='loyaltysegmentmembership',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='User who manually assigned member (null for automated)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loyaltysegmentmembership',
            name='member',
            field=models.ForeignKey(help_text='Member in this segment', on_delete=django.db.models.deletion.CASCADE, related_name='segment_memberships', to='loyalty.loyaltymember'),
        ),
        migrations.AddField(
            model_name='loyaltysegmentmembership',
            name='segment',
            field=models.ForeignKey(help_text='Segment this membership belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='loyalty.loyaltysegment'),
        ),
        migrations.AddIndex(
            model_name='loyaltytier',
            index=models.Index(fields=['rank', 'is_active'], name='loyalty_loy_rank_09f4da_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltytier',
            index=models.Index(fields=['min_spend'], name='loyalty_loy_min_spe_c62ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltytier',
            index=models.Index(fields=['min_orders'], name='loyalty_loy_min_ord_37a6d9_idx'),
        ),
        migrations.AddField(
            model_name='loyaltyrule',
            name='allowed_tiers',
            field=models.ManyToManyField(blank=True, help_text='Tiers this rule applies to (empty = all tiers)', related_name='applicable_rules', to='loyalty.loyaltytier'),
        ),
        migrations.AddField(
            model_name='loyaltyreward',
            name='required_tier',
            field=models.ForeignKey(blank=True, help_text='Minimum tier required to redeem (null = all tiers)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusive_rewards', to='loyalty.loyaltytier'),
        ),
        migrations.AddField(
            model_name='loyaltymember',
            name='current_tier',
            field=models.ForeignKey(blank=True, help_text='Current tier membership', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='loyalty.loyaltytier'),
        ),
        migrations.AddField(
            model_name='loyaltycampaign',
            name='target_tiers',
            field=models.ManyToManyField(blank=True, help_text='Limit campaign to specific tiers', related_name='campaigns', to='loyalty.loyaltytier'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who created this transaction (for manual adjustments)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='member',
            field=models.ForeignKey(help_text='Loyalty member this transaction belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='loyalty.loyaltymember'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='reversal_of',
            field=models.ForeignKey(blank=True, help_text='Original transaction being reversed (for revoke transactions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='loyalty.loyaltytransaction'),
        ),
        migrations.AddField(
            model_name='loyaltyredemption',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Associated points transaction (deduction)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='loyalty.loyaltytransaction'),
        ),
        migrations.AddField(
            model_name='loyaltymemberbadge',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Associated points transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge_awards', to='loyalty.loyaltytransaction'),
        ),
        migrations.AddIndex(
            model_name='loyaltybadge',
            index=models.Index(fields=['criteria_type', 'is_active', 'auto_award'], name='loyalty_loy_criteri_495f21_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltybadge',
            index=models.Index(fields=['display_order'], name='loyalty_loy_display_fce69b_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltybadge',
            index=models.Index(fields=['auto_award', 'is_active'], name='loyalty_loy_auto_aw_ef291d_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltybalance',
            index=models.Index(fields=['available_points'], name='loyalty_loy_availab_eb5257_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltybalance',
            index=models.Index(fields=['last_earned_at'], name='loyalty_loy_last_ea_ecf515_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltycampaignexecution',
            index=models.Index(fields=['campaign', 'member'], name='loyalty_loy_campaig_428c71_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltycampaignexecution',
            index=models.Index(fields=['status', 'triggered_at'], name='loyalty_loy_status_18722a_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltycampaignexecution',
            index=models.Index(fields=['next_step_at'], name='loyalty_loy_next_st_a48f49_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltycampaignexecution',
            index=models.Index(fields=['campaign', 'status'], name='loyalty_loy_campaig_c88ed8_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltysegmentmembership',
            index=models.Index(fields=['segment', 'assigned_at'], name='loyalty_loy_segment_013eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltysegmentmembership',
            index=models.Index(fields=['member', 'assigned_at'], name='loyalty_loy_member__d58e64_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loyaltysegmentmembership',
            unique_together={('segment', 'member')},
        ),
        migrations.AddIndex(
            model_name='loyaltyrule',
            index=models.Index(fields=['rule_type', 'is_active'], name='loyalty_loy_rule_ty_6a2cd3_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyrule',
            index=models.Index(fields=['priority', 'is_active'], name='loyalty_loy_priorit_059bcc_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyrule',
            index=models.Index(fields=['scope', 'is_active'], name='loyalty_loy_scope_4c99c4_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyrule',
            index=models.Index(fields=['start_date', 'end_date'], name='loyalty_loy_start_d_52da3a_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyreward',
            index=models.Index(fields=['reward_type', 'is_active'], name='loyalty_loy_reward__891c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyreward',
            index=models.Index(fields=['is_active', 'featured'], name='loyalty_loy_is_acti_0002d6_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyreward',
            index=models.Index(fields=['points_cost'], name='loyalty_loy_points__875cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyreward',
            index=models.Index(fields=['start_date', 'end_date'], name='loyalty_loy_start_d_defe09_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyreward',
            index=models.Index(fields=['display_order'], name='loyalty_loy_display_3e0cdd_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltymember',
            index=models.Index(fields=['customer', 'is_active'], name='loyalty_loy_custome_1c442c_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltymember',
            index=models.Index(fields=['enrolled_at'], name='loyalty_loy_enrolle_83b227_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltymember',
            index=models.Index(fields=['current_tier'], name='loyalty_loy_current_91ce1e_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltycampaign',
            index=models.Index(fields=['status', 'is_active'], name='loyalty_loy_status_8d3dda_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltycampaign',
            index=models.Index(fields=['campaign_type', 'is_active'], name='loyalty_loy_campaig_d8ec32_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltycampaign',
            index=models.Index(fields=['trigger_event'], name='loyalty_loy_trigger_e7edd7_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltycampaign',
            index=models.Index(fields=['start_date', 'end_date'], name='loyalty_loy_start_d_9c89d3_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltycampaign',
            index=models.Index(fields=['slug'], name='loyalty_loy_slug_7df36e_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['member', 'transaction_type'], name='loyalty_loy_member__bdde29_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['member', 'status'], name='loyalty_loy_member__88df17_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['member', 'created_at'], name='loyalty_loy_member__ffe734_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['transaction_type', 'created_at'], name='loyalty_loy_transac_7a8030_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['expires_at'], name='loyalty_loy_expires_5f9117_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['related_object_type', 'related_object_id'], name='loyalty_loy_related_ddf977_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyredemption',
            index=models.Index(fields=['member', 'status'], name='loyalty_loy_member__f85c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyredemption',
            index=models.Index(fields=['reward', 'status'], name='loyalty_loy_reward__b1f806_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyredemption',
            index=models.Index(fields=['status', 'created_at'], name='loyalty_loy_status_c03a15_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyredemption',
            index=models.Index(fields=['redemption_code'], name='loyalty_loy_redempt_dbbab8_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyredemption',
            index=models.Index(fields=['expires_at'], name='loyalty_loy_expires_288e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltymemberbadge',
            index=models.Index(fields=['member', 'earned_at'], name='loyalty_loy_member__6ae5d1_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltymemberbadge',
            index=models.Index(fields=['badge', 'earned_at'], name='loyalty_loy_badge_i_fbe0e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loyaltymemberbadge',
            unique_together={('member', 'badge')},
        ),
    ]
