# Generated by Django 5.1.4 on 2026-03-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltymember',
            name='grace_period_started_at',
            field=models.DateTimeField(blank=True, help_text='When member first fell below tier threshold (for grace period tracking)', null=True),
        ),
    ]
