"""
Management command to seed comprehensive country mappings
Covers ALL 195+ countries with correct currency and language data
"""

from django.core.management.base import BaseCommand

from geoip.models import CountryMapping


class Command(BaseCommand):
    help = "Seed comprehensive country mappings with currency and language data for all countries"

    # Complete list of all world countries (~195 total)
    # Data source: ISO 3166-1, Unicode CLDR, and official government sources
    COUNTRIES = [
        # A
        {
            "code": "AF",
            "name": "Afghanistan",
            "currency": "AFN",
            "language": "fa",
            "timezone": "Asia/Kabul",
        },
        {
            "code": "AL",
            "name": "Albania",
            "currency": "ALL",
            "language": "sq",
            "timezone": "Europe/Tirane",
        },
        {
            "code": "DZ",
            "name": "Algeria",
            "currency": "DZD",
            "language": "ar",
            "timezone": "Africa/Algiers",
        },
        {
            "code": "AD",
            "name": "Andorra",
            "currency": "EUR",
            "language": "ca",
            "timezone": "Europe/Andorra",
            "eu": False,
        },
        {
            "code": "AO",
            "name": "Angola",
            "currency": "AOA",
            "language": "pt",
            "timezone": "Africa/Luanda",
        },
        {
            "code": "AG",
            "name": "Antigua and Barbuda",
            "currency": "XCD",
            "language": "en",
            "timezone": "America/Antigua",
        },
        {
            "code": "AR",
            "name": "Argentina",
            "currency": "ARS",
            "language": "es",
            "timezone": "America/Argentina/Buenos_Aires",
        },
        {
            "code": "AM",
            "name": "Armenia",
            "currency": "AMD",
            "language": "hy",
            "timezone": "Asia/Yerevan",
        },
        {
            "code": "AU",
            "name": "Australia",
            "currency": "AUD",
            "language": "en",
            "timezone": "Australia/Sydney",
        },
        {
            "code": "AT",
            "name": "Austria",
            "currency": "EUR",
            "language": "de",
            "timezone": "Europe/Vienna",
            "eu": True,
        },
        {
            "code": "AZ",
            "name": "Azerbaijan",
            "currency": "AZN",
            "language": "az",
            "timezone": "Asia/Baku",
        },
        # B
        {
            "code": "BS",
            "name": "Bahamas",
            "currency": "BSD",
            "language": "en",
            "timezone": "America/Nassau",
        },
        {
            "code": "BH",
            "name": "Bahrain",
            "currency": "BHD",
            "language": "ar",
            "timezone": "Asia/Bahrain",
        },
        {
            "code": "BD",
            "name": "Bangladesh",
            "currency": "BDT",
            "language": "bn",
            "timezone": "Asia/Dhaka",
        },
        {
            "code": "BB",
            "name": "Barbados",
            "currency": "BBD",
            "language": "en",
            "timezone": "America/Barbados",
        },
        {
            "code": "BY",
            "name": "Belarus",
            "currency": "BYN",
            "language": "be",
            "timezone": "Europe/Minsk",
        },
        {
            "code": "BE",
            "name": "Belgium",
            "currency": "EUR",
            "language": "nl",
            "timezone": "Europe/Brussels",
            "eu": True,
        },
        {
            "code": "BZ",
            "name": "Belize",
            "currency": "BZD",
            "language": "en",
            "timezone": "America/Belize",
        },
        {
            "code": "BJ",
            "name": "Benin",
            "currency": "XOF",
            "language": "fr",
            "timezone": "Africa/Porto-Novo",
        },
        {
            "code": "BT",
            "name": "Bhutan",
            "currency": "BTN",
            "language": "dz",
            "timezone": "Asia/Thimphu",
        },
        {
            "code": "BO",
            "name": "Bolivia",
            "currency": "BOB",
            "language": "es",
            "timezone": "America/La_Paz",
        },
        {
            "code": "BA",
            "name": "Bosnia and Herzegovina",
            "currency": "BAM",
            "language": "bs",
            "timezone": "Europe/Sarajevo",
        },
        {
            "code": "BW",
            "name": "Botswana",
            "currency": "BWP",
            "language": "en",
            "timezone": "Africa/Gaborone",
        },
        {
            "code": "BR",
            "name": "Brazil",
            "currency": "BRL",
            "language": "pt",
            "timezone": "America/Sao_Paulo",
        },
        {
            "code": "BN",
            "name": "Brunei",
            "currency": "BND",
            "language": "ms",
            "timezone": "Asia/Brunei",
        },
        {
            "code": "BG",
            "name": "Bulgaria",
            "currency": "BGN",
            "language": "bg",
            "timezone": "Europe/Sofia",
            "eu": True,
        },
        {
            "code": "BF",
            "name": "Burkina Faso",
            "currency": "XOF",
            "language": "fr",
            "timezone": "Africa/Ouagadougou",
        },
        {
            "code": "BI",
            "name": "Burundi",
            "currency": "BIF",
            "language": "fr",
            "timezone": "Africa/Bujumbura",
        },
        # C
        {
            "code": "KH",
            "name": "Cambodia",
            "currency": "KHR",
            "language": "km",
            "timezone": "Asia/Phnom_Penh",
        },
        {
            "code": "CM",
            "name": "Cameroon",
            "currency": "XAF",
            "language": "fr",
            "timezone": "Africa/Douala",
        },
        {
            "code": "CA",
            "name": "Canada",
            "currency": "CAD",
            "language": "en",
            "timezone": "America/Toronto",
        },
        {
            "code": "CV",
            "name": "Cape Verde",
            "currency": "CVE",
            "language": "pt",
            "timezone": "Atlantic/Cape_Verde",
        },
        {
            "code": "CF",
            "name": "Central African Republic",
            "currency": "XAF",
            "language": "fr",
            "timezone": "Africa/Bangui",
        },
        {
            "code": "TD",
            "name": "Chad",
            "currency": "XAF",
            "language": "fr",
            "timezone": "Africa/Ndjamena",
        },
        {
            "code": "CL",
            "name": "Chile",
            "currency": "CLP",
            "language": "es",
            "timezone": "America/Santiago",
        },
        {
            "code": "CN",
            "name": "China",
            "currency": "CNY",
            "language": "zh-hans",
            "timezone": "Asia/Shanghai",
        },
        {
            "code": "CO",
            "name": "Colombia",
            "currency": "COP",
            "language": "es",
            "timezone": "America/Bogota",
        },
        {
            "code": "KM",
            "name": "Comoros",
            "currency": "KMF",
            "language": "ar",
            "timezone": "Indian/Comoro",
        },
        {
            "code": "CG",
            "name": "Congo",
            "currency": "XAF",
            "language": "fr",
            "timezone": "Africa/Brazzaville",
        },
        {
            "code": "CD",
            "name": "Congo (DRC)",
            "currency": "CDF",
            "language": "fr",
            "timezone": "Africa/Kinshasa",
        },
        {
            "code": "CR",
            "name": "Costa Rica",
            "currency": "CRC",
            "language": "es",
            "timezone": "America/Costa_Rica",
        },
        {
            "code": "HR",
            "name": "Croatia",
            "currency": "EUR",
            "language": "hr",
            "timezone": "Europe/Zagreb",
            "eu": True,
        },
        {
            "code": "CU",
            "name": "Cuba",
            "currency": "CUP",
            "language": "es",
            "timezone": "America/Havana",
        },
        {
            "code": "CY",
            "name": "Cyprus",
            "currency": "EUR",
            "language": "el",
            "timezone": "Asia/Nicosia",
            "eu": True,
        },
        {
            "code": "CZ",
            "name": "Czech Republic",
            "currency": "CZK",
            "language": "cs",
            "timezone": "Europe/Prague",
            "eu": True,
        },
        # D
        {
            "code": "DK",
            "name": "Denmark",
            "currency": "DKK",
            "language": "da",
            "timezone": "Europe/Copenhagen",
            "eu": True,
        },
        {
            "code": "DJ",
            "name": "Djibouti",
            "currency": "DJF",
            "language": "fr",
            "timezone": "Africa/Djibouti",
        },
        {
            "code": "DM",
            "name": "Dominica",
            "currency": "XCD",
            "language": "en",
            "timezone": "America/Dominica",
        },
        {
            "code": "DO",
            "name": "Dominican Republic",
            "currency": "DOP",
            "language": "es",
            "timezone": "America/Santo_Domingo",
        },
        # E
        {
            "code": "EC",
            "name": "Ecuador",
            "currency": "USD",
            "language": "es",
            "timezone": "America/Guayaquil",
        },
        {
            "code": "EG",
            "name": "Egypt",
            "currency": "EGP",
            "language": "ar",
            "timezone": "Africa/Cairo",
        },
        {
            "code": "SV",
            "name": "El Salvador",
            "currency": "USD",
            "language": "es",
            "timezone": "America/El_Salvador",
        },
        {
            "code": "GQ",
            "name": "Equatorial Guinea",
            "currency": "XAF",
            "language": "es",
            "timezone": "Africa/Malabo",
        },
        {
            "code": "ER",
            "name": "Eritrea",
            "currency": "ERN",
            "language": "ti",
            "timezone": "Africa/Asmara",
        },
        {
            "code": "EE",
            "name": "Estonia",
            "currency": "EUR",
            "language": "et",
            "timezone": "Europe/Tallinn",
            "eu": True,
        },
        {
            "code": "SZ",
            "name": "Eswatini",
            "currency": "SZL",
            "language": "en",
            "timezone": "Africa/Mbabane",
        },
        {
            "code": "ET",
            "name": "Ethiopia",
            "currency": "ETB",
            "language": "am",
            "timezone": "Africa/Addis_Ababa",
        },
        # F
        {
            "code": "FJ",
            "name": "Fiji",
            "currency": "FJD",
            "language": "en",
            "timezone": "Pacific/Fiji",
        },
        {
            "code": "FI",
            "name": "Finland",
            "currency": "EUR",
            "language": "fi",
            "timezone": "Europe/Helsinki",
            "eu": True,
        },
        {
            "code": "FR",
            "name": "France",
            "currency": "EUR",
            "language": "fr",
            "timezone": "Europe/Paris",
            "eu": True,
        },
        # G
        {
            "code": "GA",
            "name": "Gabon",
            "currency": "XAF",
            "language": "fr",
            "timezone": "Africa/Libreville",
        },
        {
            "code": "GM",
            "name": "Gambia",
            "currency": "GMD",
            "language": "en",
            "timezone": "Africa/Banjul",
        },
        {
            "code": "GE",
            "name": "Georgia",
            "currency": "GEL",
            "language": "ka",
            "timezone": "Asia/Tbilisi",
        },
        {
            "code": "DE",
            "name": "Germany",
            "currency": "EUR",
            "language": "de",
            "timezone": "Europe/Berlin",
            "eu": True,
        },
        {
            "code": "GH",
            "name": "Ghana",
            "currency": "GHS",
            "language": "en",
            "timezone": "Africa/Accra",
        },
        {
            "code": "GR",
            "name": "Greece",
            "currency": "EUR",
            "language": "el",
            "timezone": "Europe/Athens",
            "eu": True,
        },
        {
            "code": "GD",
            "name": "Grenada",
            "currency": "XCD",
            "language": "en",
            "timezone": "America/Grenada",
        },
        {
            "code": "GT",
            "name": "Guatemala",
            "currency": "GTQ",
            "language": "es",
            "timezone": "America/Guatemala",
        },
        {
            "code": "GN",
            "name": "Guinea",
            "currency": "GNF",
            "language": "fr",
            "timezone": "Africa/Conakry",
        },
        {
            "code": "GW",
            "name": "Guinea-Bissau",
            "currency": "XOF",
            "language": "pt",
            "timezone": "Africa/Bissau",
        },
        {
            "code": "GY",
            "name": "Guyana",
            "currency": "GYD",
            "language": "en",
            "timezone": "America/Guyana",
        },
        # H
        {
            "code": "HT",
            "name": "Haiti",
            "currency": "HTG",
            "language": "fr",
            "timezone": "America/Port-au-Prince",
        },
        {
            "code": "HN",
            "name": "Honduras",
            "currency": "HNL",
            "language": "es",
            "timezone": "America/Tegucigalpa",
        },
        {
            "code": "HK",
            "name": "Hong Kong",
            "currency": "HKD",
            "language": "zh-hant",
            "timezone": "Asia/Hong_Kong",
        },
        {
            "code": "HU",
            "name": "Hungary",
            "currency": "HUF",
            "language": "hu",
            "timezone": "Europe/Budapest",
            "eu": True,
        },
        # I
        {
            "code": "IS",
            "name": "Iceland",
            "currency": "ISK",
            "language": "is",
            "timezone": "Atlantic/Reykjavik",
        },
        {
            "code": "IN",
            "name": "India",
            "currency": "INR",
            "language": "hi",
            "timezone": "Asia/Kolkata",
        },
        {
            "code": "ID",
            "name": "Indonesia",
            "currency": "IDR",
            "language": "id",
            "timezone": "Asia/Jakarta",
        },
        {
            "code": "IR",
            "name": "Iran",
            "currency": "IRR",
            "language": "fa",
            "timezone": "Asia/Tehran",
        },
        {
            "code": "IQ",
            "name": "Iraq",
            "currency": "IQD",
            "language": "ar",
            "timezone": "Asia/Baghdad",
        },
        {
            "code": "IE",
            "name": "Ireland",
            "currency": "EUR",
            "language": "en",
            "timezone": "Europe/Dublin",
            "eu": True,
        },
        {
            "code": "IL",
            "name": "Israel",
            "currency": "ILS",
            "language": "he",
            "timezone": "Asia/Jerusalem",
        },
        {
            "code": "IT",
            "name": "Italy",
            "currency": "EUR",
            "language": "it",
            "timezone": "Europe/Rome",
            "eu": True,
        },
        {
            "code": "CI",
            "name": "Ivory Coast",
            "currency": "XOF",
            "language": "fr",
            "timezone": "Africa/Abidjan",
        },
        # J
        {
            "code": "JM",
            "name": "Jamaica",
            "currency": "JMD",
            "language": "en",
            "timezone": "America/Jamaica",
        },
        {
            "code": "JP",
            "name": "Japan",
            "currency": "JPY",
            "language": "ja",
            "timezone": "Asia/Tokyo",
        },
        {
            "code": "JO",
            "name": "Jordan",
            "currency": "JOD",
            "language": "ar",
            "timezone": "Asia/Amman",
        },
        # K
        {
            "code": "KZ",
            "name": "Kazakhstan",
            "currency": "KZT",
            "language": "kk",
            "timezone": "Asia/Almaty",
        },
        {
            "code": "KE",
            "name": "Kenya",
            "currency": "KES",
            "language": "sw",
            "timezone": "Africa/Nairobi",
        },
        {
            "code": "KI",
            "name": "Kiribati",
            "currency": "AUD",
            "language": "en",
            "timezone": "Pacific/Tarawa",
        },
        {
            "code": "KW",
            "name": "Kuwait",
            "currency": "KWD",
            "language": "ar",
            "timezone": "Asia/Kuwait",
        },
        {
            "code": "KG",
            "name": "Kyrgyzstan",
            "currency": "KGS",
            "language": "ky",
            "timezone": "Asia/Bishkek",
        },
        {
            "code": "KP",
            "name": "North Korea",
            "currency": "KPW",
            "language": "ko",
            "timezone": "Asia/Pyongyang",
        },
        {
            "code": "KR",
            "name": "South Korea",
            "currency": "KRW",
            "language": "ko",
            "timezone": "Asia/Seoul",
        },
        # L
        {
            "code": "LA",
            "name": "Laos",
            "currency": "LAK",
            "language": "lo",
            "timezone": "Asia/Vientiane",
        },
        {
            "code": "LV",
            "name": "Latvia",
            "currency": "EUR",
            "language": "lv",
            "timezone": "Europe/Riga",
            "eu": True,
        },
        {
            "code": "LB",
            "name": "Lebanon",
            "currency": "LBP",
            "language": "ar",
            "timezone": "Asia/Beirut",
        },
        {
            "code": "LS",
            "name": "Lesotho",
            "currency": "LSL",
            "language": "en",
            "timezone": "Africa/Maseru",
        },
        {
            "code": "LR",
            "name": "Liberia",
            "currency": "LRD",
            "language": "en",
            "timezone": "Africa/Monrovia",
        },
        {
            "code": "LY",
            "name": "Libya",
            "currency": "LYD",
            "language": "ar",
            "timezone": "Africa/Tripoli",
        },
        {
            "code": "LI",
            "name": "Liechtenstein",
            "currency": "CHF",
            "language": "de",
            "timezone": "Europe/Vaduz",
        },
        {
            "code": "LT",
            "name": "Lithuania",
            "currency": "EUR",
            "language": "lt",
            "timezone": "Europe/Vilnius",
            "eu": True,
        },
        {
            "code": "LU",
            "name": "Luxembourg",
            "currency": "EUR",
            "language": "fr",
            "timezone": "Europe/Luxembourg",
            "eu": True,
        },
        # M
        {
            "code": "MG",
            "name": "Madagascar",
            "currency": "MGA",
            "language": "mg",
            "timezone": "Indian/Antananarivo",
        },
        {
            "code": "MW",
            "name": "Malawi",
            "currency": "MWK",
            "language": "en",
            "timezone": "Africa/Blantyre",
        },
        {
            "code": "MY",
            "name": "Malaysia",
            "currency": "MYR",
            "language": "ms",
            "timezone": "Asia/Kuala_Lumpur",
        },
        {
            "code": "MV",
            "name": "Maldives",
            "currency": "MVR",
            "language": "dv",
            "timezone": "Indian/Maldives",
        },
        {
            "code": "ML",
            "name": "Mali",
            "currency": "XOF",
            "language": "fr",
            "timezone": "Africa/Bamako",
        },
        {
            "code": "MT",
            "name": "Malta",
            "currency": "EUR",
            "language": "mt",
            "timezone": "Europe/Malta",
            "eu": True,
        },
        {
            "code": "MH",
            "name": "Marshall Islands",
            "currency": "USD",
            "language": "en",
            "timezone": "Pacific/Majuro",
        },
        {
            "code": "MR",
            "name": "Mauritania",
            "currency": "MRU",
            "language": "ar",
            "timezone": "Africa/Nouakchott",
        },
        {
            "code": "MU",
            "name": "Mauritius",
            "currency": "MUR",
            "language": "en",
            "timezone": "Indian/Mauritius",
        },
        {
            "code": "MX",
            "name": "Mexico",
            "currency": "MXN",
            "language": "es",
            "timezone": "America/Mexico_City",
        },
        {
            "code": "FM",
            "name": "Micronesia",
            "currency": "USD",
            "language": "en",
            "timezone": "Pacific/Pohnpei",
        },
        {
            "code": "MD",
            "name": "Moldova",
            "currency": "MDL",
            "language": "ro",
            "timezone": "Europe/Chisinau",
        },
        {
            "code": "MC",
            "name": "Monaco",
            "currency": "EUR",
            "language": "fr",
            "timezone": "Europe/Monaco",
        },
        {
            "code": "MN",
            "name": "Mongolia",
            "currency": "MNT",
            "language": "mn",
            "timezone": "Asia/Ulaanbaatar",
        },
        {
            "code": "ME",
            "name": "Montenegro",
            "currency": "EUR",
            "language": "sr",
            "timezone": "Europe/Podgorica",
        },
        {
            "code": "MA",
            "name": "Morocco",
            "currency": "MAD",
            "language": "ar",
            "timezone": "Africa/Casablanca",
        },
        {
            "code": "MZ",
            "name": "Mozambique",
            "currency": "MZN",
            "language": "pt",
            "timezone": "Africa/Maputo",
        },
        {
            "code": "MM",
            "name": "Myanmar",
            "currency": "MMK",
            "language": "my",
            "timezone": "Asia/Yangon",
        },
        # N
        {
            "code": "NA",
            "name": "Namibia",
            "currency": "NAD",
            "language": "en",
            "timezone": "Africa/Windhoek",
        },
        {
            "code": "NR",
            "name": "Nauru",
            "currency": "AUD",
            "language": "en",
            "timezone": "Pacific/Nauru",
        },
        {
            "code": "NP",
            "name": "Nepal",
            "currency": "NPR",
            "language": "ne",
            "timezone": "Asia/Kathmandu",
        },
        {
            "code": "NL",
            "name": "Netherlands",
            "currency": "EUR",
            "language": "nl",
            "timezone": "Europe/Amsterdam",
            "eu": True,
        },
        {
            "code": "NZ",
            "name": "New Zealand",
            "currency": "NZD",
            "language": "en",
            "timezone": "Pacific/Auckland",
        },
        {
            "code": "NI",
            "name": "Nicaragua",
            "currency": "NIO",
            "language": "es",
            "timezone": "America/Managua",
        },
        {
            "code": "NE",
            "name": "Niger",
            "currency": "XOF",
            "language": "fr",
            "timezone": "Africa/Niamey",
        },
        {
            "code": "NG",
            "name": "Nigeria",
            "currency": "NGN",
            "language": "en",
            "timezone": "Africa/Lagos",
        },
        {
            "code": "MK",
            "name": "North Macedonia",
            "currency": "MKD",
            "language": "mk",
            "timezone": "Europe/Skopje",
        },
        {
            "code": "NO",
            "name": "Norway",
            "currency": "NOK",
            "language": "no",
            "timezone": "Europe/Oslo",
        },
        # O
        {
            "code": "OM",
            "name": "Oman",
            "currency": "OMR",
            "language": "ar",
            "timezone": "Asia/Muscat",
        },
        # P
        {
            "code": "PK",
            "name": "Pakistan",
            "currency": "PKR",
            "language": "ur",
            "timezone": "Asia/Karachi",
        },
        {
            "code": "PW",
            "name": "Palau",
            "currency": "USD",
            "language": "en",
            "timezone": "Pacific/Palau",
        },
        {
            "code": "PA",
            "name": "Panama",
            "currency": "PAB",
            "language": "es",
            "timezone": "America/Panama",
        },
        {
            "code": "PG",
            "name": "Papua New Guinea",
            "currency": "PGK",
            "language": "en",
            "timezone": "Pacific/Port_Moresby",
        },
        {
            "code": "PY",
            "name": "Paraguay",
            "currency": "PYG",
            "language": "es",
            "timezone": "America/Asuncion",
        },
        {
            "code": "PE",
            "name": "Peru",
            "currency": "PEN",
            "language": "es",
            "timezone": "America/Lima",
        },
        {
            "code": "PH",
            "name": "Philippines",
            "currency": "PHP",
            "language": "tl",
            "timezone": "Asia/Manila",
        },
        {
            "code": "PL",
            "name": "Poland",
            "currency": "PLN",
            "language": "pl",
            "timezone": "Europe/Warsaw",
            "eu": True,
        },
        {
            "code": "PT",
            "name": "Portugal",
            "currency": "EUR",
            "language": "pt",
            "timezone": "Europe/Lisbon",
            "eu": True,
        },
        # Q
        {
            "code": "QA",
            "name": "Qatar",
            "currency": "QAR",
            "language": "ar",
            "timezone": "Asia/Qatar",
        },
        # R
        {
            "code": "RO",
            "name": "Romania",
            "currency": "RON",
            "language": "ro",
            "timezone": "Europe/Bucharest",
            "eu": True,
        },
        {
            "code": "RU",
            "name": "Russia",
            "currency": "RUB",
            "language": "ru",
            "timezone": "Europe/Moscow",
        },
        {
            "code": "RW",
            "name": "Rwanda",
            "currency": "RWF",
            "language": "rw",
            "timezone": "Africa/Kigali",
        },
        # S
        {
            "code": "KN",
            "name": "Saint Kitts and Nevis",
            "currency": "XCD",
            "language": "en",
            "timezone": "America/St_Kitts",
        },
        {
            "code": "LC",
            "name": "Saint Lucia",
            "currency": "XCD",
            "language": "en",
            "timezone": "America/St_Lucia",
        },
        {
            "code": "VC",
            "name": "Saint Vincent and the Grenadines",
            "currency": "XCD",
            "language": "en",
            "timezone": "America/St_Vincent",
        },
        {
            "code": "WS",
            "name": "Samoa",
            "currency": "WST",
            "language": "sm",
            "timezone": "Pacific/Apia",
        },
        {
            "code": "SM",
            "name": "San Marino",
            "currency": "EUR",
            "language": "it",
            "timezone": "Europe/San_Marino",
        },
        {
            "code": "ST",
            "name": "Sao Tome and Principe",
            "currency": "STN",
            "language": "pt",
            "timezone": "Africa/Sao_Tome",
        },
        {
            "code": "SA",
            "name": "Saudi Arabia",
            "currency": "SAR",
            "language": "ar",
            "timezone": "Asia/Riyadh",
        },
        {
            "code": "SN",
            "name": "Senegal",
            "currency": "XOF",
            "language": "fr",
            "timezone": "Africa/Dakar",
        },
        {
            "code": "RS",
            "name": "Serbia",
            "currency": "RSD",
            "language": "sr",
            "timezone": "Europe/Belgrade",
        },
        {
            "code": "SC",
            "name": "Seychelles",
            "currency": "SCR",
            "language": "fr",
            "timezone": "Indian/Mahe",
        },
        {
            "code": "SL",
            "name": "Sierra Leone",
            "currency": "SLL",
            "language": "en",
            "timezone": "Africa/Freetown",
        },
        {
            "code": "SG",
            "name": "Singapore",
            "currency": "SGD",
            "language": "en",
            "timezone": "Asia/Singapore",
        },
        {
            "code": "SK",
            "name": "Slovakia",
            "currency": "EUR",
            "language": "sk",
            "timezone": "Europe/Bratislava",
            "eu": True,
        },
        {
            "code": "SI",
            "name": "Slovenia",
            "currency": "EUR",
            "language": "sl",
            "timezone": "Europe/Ljubljana",
            "eu": True,
        },
        {
            "code": "SB",
            "name": "Solomon Islands",
            "currency": "SBD",
            "language": "en",
            "timezone": "Pacific/Guadalcanal",
        },
        {
            "code": "SO",
            "name": "Somalia",
            "currency": "SOS",
            "language": "so",
            "timezone": "Africa/Mogadishu",
        },
        {
            "code": "ZA",
            "name": "South Africa",
            "currency": "ZAR",
            "language": "en",
            "timezone": "Africa/Johannesburg",
        },
        {
            "code": "SS",
            "name": "South Sudan",
            "currency": "SSP",
            "language": "en",
            "timezone": "Africa/Juba",
        },
        {
            "code": "ES",
            "name": "Spain",
            "currency": "EUR",
            "language": "es",
            "timezone": "Europe/Madrid",
            "eu": True,
        },
        {
            "code": "LK",
            "name": "Sri Lanka",
            "currency": "LKR",
            "language": "si",
            "timezone": "Asia/Colombo",
        },
        {
            "code": "SD",
            "name": "Sudan",
            "currency": "SDG",
            "language": "ar",
            "timezone": "Africa/Khartoum",
        },
        {
            "code": "SR",
            "name": "Suriname",
            "currency": "SRD",
            "language": "nl",
            "timezone": "America/Paramaribo",
        },
        {
            "code": "SE",
            "name": "Sweden",
            "currency": "SEK",
            "language": "sv",
            "timezone": "Europe/Stockholm",
            "eu": True,
        },
        {
            "code": "CH",
            "name": "Switzerland",
            "currency": "CHF",
            "language": "de",
            "timezone": "Europe/Zurich",
        },
        {
            "code": "SY",
            "name": "Syria",
            "currency": "SYP",
            "language": "ar",
            "timezone": "Asia/Damascus",
        },
        # T
        {
            "code": "TW",
            "name": "Taiwan",
            "currency": "TWD",
            "language": "zh-hant",
            "timezone": "Asia/Taipei",
        },
        {
            "code": "TJ",
            "name": "Tajikistan",
            "currency": "TJS",
            "language": "tg",
            "timezone": "Asia/Dushanbe",
        },
        {
            "code": "TZ",
            "name": "Tanzania",
            "currency": "TZS",
            "language": "sw",
            "timezone": "Africa/Dar_es_Salaam",
        },
        {
            "code": "TH",
            "name": "Thailand",
            "currency": "THB",
            "language": "th",
            "timezone": "Asia/Bangkok",
        },
        {
            "code": "TL",
            "name": "Timor-Leste",
            "currency": "USD",
            "language": "pt",
            "timezone": "Asia/Dili",
        },
        {
            "code": "TG",
            "name": "Togo",
            "currency": "XOF",
            "language": "fr",
            "timezone": "Africa/Lome",
        },
        {
            "code": "TO",
            "name": "Tonga",
            "currency": "TOP",
            "language": "to",
            "timezone": "Pacific/Tongatapu",
        },
        {
            "code": "TT",
            "name": "Trinidad and Tobago",
            "currency": "TTD",
            "language": "en",
            "timezone": "America/Port_of_Spain",
        },
        {
            "code": "TN",
            "name": "Tunisia",
            "currency": "TND",
            "language": "ar",
            "timezone": "Africa/Tunis",
        },
        {
            "code": "TR",
            "name": "Turkey",
            "currency": "TRY",
            "language": "tr",
            "timezone": "Europe/Istanbul",
        },
        {
            "code": "TM",
            "name": "Turkmenistan",
            "currency": "TMT",
            "language": "tk",
            "timezone": "Asia/Ashgabat",
        },
        {
            "code": "TV",
            "name": "Tuvalu",
            "currency": "AUD",
            "language": "en",
            "timezone": "Pacific/Funafuti",
        },
        # U
        {
            "code": "UG",
            "name": "Uganda",
            "currency": "UGX",
            "language": "en",
            "timezone": "Africa/Kampala",
        },
        {
            "code": "UA",
            "name": "Ukraine",
            "currency": "UAH",
            "language": "uk",
            "timezone": "Europe/Kiev",
        },
        {
            "code": "AE",
            "name": "United Arab Emirates",
            "currency": "AED",
            "language": "ar",
            "timezone": "Asia/Dubai",
        },
        {
            "code": "GB",
            "name": "United Kingdom",
            "currency": "GBP",
            "language": "en",
            "timezone": "Europe/London",
        },
        {
            "code": "US",
            "name": "United States",
            "currency": "USD",
            "language": "en",
            "timezone": "America/New_York",
        },
        {
            "code": "UY",
            "name": "Uruguay",
            "currency": "UYU",
            "language": "es",
            "timezone": "America/Montevideo",
        },
        {
            "code": "UZ",
            "name": "Uzbekistan",
            "currency": "UZS",
            "language": "uz",
            "timezone": "Asia/Tashkent",
        },
        # V
        {
            "code": "VU",
            "name": "Vanuatu",
            "currency": "VUV",
            "language": "bi",
            "timezone": "Pacific/Efate",
        },
        {
            "code": "VA",
            "name": "Vatican City",
            "currency": "EUR",
            "language": "it",
            "timezone": "Europe/Vatican",
        },
        {
            "code": "VE",
            "name": "Venezuela",
            "currency": "VES",
            "language": "es",
            "timezone": "America/Caracas",
        },
        {
            "code": "VN",
            "name": "Vietnam",
            "currency": "VND",
            "language": "vi",
            "timezone": "Asia/Ho_Chi_Minh",
        },
        # Y
        {
            "code": "YE",
            "name": "Yemen",
            "currency": "YER",
            "language": "ar",
            "timezone": "Asia/Aden",
        },
        # Z
        {
            "code": "ZM",
            "name": "Zambia",
            "currency": "ZMW",
            "language": "en",
            "timezone": "Africa/Lusaka",
        },
        {
            "code": "ZW",
            "name": "Zimbabwe",
            "currency": "ZWL",
            "language": "en",
            "timezone": "Africa/Harare",
        },
    ]

    def handle(self, *args, **options):
        created_count = 0
        updated_count = 0

        self.stdout.write("=" * 80)
        self.stdout.write("Seeding comprehensive country mappings...")
        self.stdout.write(f"Total countries to process: {len(self.COUNTRIES)}")
        self.stdout.write("=" * 80 + "\n")

        for country_data in self.COUNTRIES:
            mapping, created = CountryMapping.objects.update_or_create(
                country_code=country_data["code"],
                defaults={
                    "country_name": country_data["name"],
                    "default_currency": country_data["currency"],
                    "default_language": country_data["language"],
                    "timezone": country_data["timezone"],
                    "uses_metric": True,  # All countries except US use metric
                    "is_eu_member": country_data.get("eu", False),
                    "is_active": True,
                    "date_format": "YYYY-MM-DD",  # ISO standard
                },
            )

            if created:
                created_count += 1
                if created_count % 20 == 0:
                    self.stdout.write(
                        f"  Progress: {created_count}/{len(self.COUNTRIES)} created..."
                    )
            else:
                updated_count += 1

        # Set US to imperial
        CountryMapping.objects.filter(country_code="US").update(uses_metric=False)

        total_mappings = CountryMapping.objects.filter(is_active=True).count()

        self.stdout.write("\n" + "=" * 80)
        self.stdout.write(self.style.SUCCESS("✅ Country mapping seed complete!"))
        self.stdout.write(f"   Created: {created_count}")
        self.stdout.write(f"   Updated: {updated_count}")
        self.stdout.write(f"   Total active mappings: {total_mappings}")
        self.stdout.write(f"   Coverage: {len(self.COUNTRIES)} countries")
        self.stdout.write("=" * 80 + "\n")

        # Show sample of SEA countries
        self.stdout.write("\nSample SEA Countries:")
        for country in CountryMapping.objects.filter(
            country_code__in=["SG", "MY", "TH", "ID", "PH", "VN"]
        ):
            self.stdout.write(
                f"  {country.country_code}: {country.country_name} → {country.default_currency} / {country.default_language}"
            )
