# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Referral Program', help_text='Internal name for this referral program', max_length=120, verbose_name='Program Name')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused')], default='draft', help_text='Program status: draft, active, or paused', max_length=10, verbose_name='Status')),
                ('reward_config', models.JSONField(blank=True, default=dict, help_text='Reward types, amounts, and double-sided settings. Example: {"referrer": {"kind": "credit", "amount": 10}, "referee": {"kind": "discount", "amount": 10}}', verbose_name='Reward Configuration')),
                ('eligibility_rules', models.JSONField(blank=True, default=dict, help_text='Rules like minimum order value, new customers only, exclude staff, etc.', verbose_name='Eligibility Rules')),
                ('timing_config', models.JSONField(blank=True, default=dict, help_text='When to issue rewards: signup, first purchase, post-refund window, etc.', verbose_name='Timing Configuration')),
                ('caps_config', models.JSONField(blank=True, default=dict, help_text='Monthly/lifetime caps per referrer, maximum reward amounts, etc.', verbose_name='Caps & Limits')),
                ('tracking_config', models.JSONField(blank=True, default=dict, help_text='Cookie TTL, attribution method (last-touch), tracking window, etc.', verbose_name='Tracking Configuration')),
                ('fraud_policy', models.JSONField(blank=True, default=dict, help_text='Fraud detection thresholds and rules (strict/balanced/lenient)', verbose_name='Fraud Policy')),
                ('terms_and_conditions', models.TextField(blank=True, default='', help_text='Legal T&Cs shown to customers (supports Markdown)', verbose_name='Terms & Conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Referral Program',
                'verbose_name_plural': 'Referral Program',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Unique token used in referral links', max_length=32, unique=True, verbose_name='Referral Token')),
                ('qr_code', models.ImageField(blank=True, help_text='Generated QR code for this referral link', null=True, upload_to='referrals/qr_codes/', verbose_name='QR Code')),
                ('total_clicks', models.PositiveIntegerField(default=0, help_text='Total number of referral link clicks', verbose_name='Total Clicks')),
                ('total_signups', models.PositiveIntegerField(default=0, help_text='Total number of signups from referrals', verbose_name='Total Signups')),
                ('total_conversions', models.PositiveIntegerField(default=0, help_text='Total number of successful referral conversions', verbose_name='Total Conversions')),
                ('total_rewards_earned', models.DecimalField(decimal_places=2, default=0, help_text='Total value of rewards earned from referrals', max_digits=12, verbose_name='Total Rewards Earned')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_identity', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Referral Identity',
                'verbose_name_plural': 'Referral Identities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('click', 'Click'), ('signup', 'Signup'), ('order', 'Order'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reward_issued', 'Reward Issued'), ('reward_redeemed', 'Reward Redeemed')], db_index=True, max_length=24, verbose_name='Event Type')),
                ('ip_address', models.CharField(blank=True, default='', help_text='Hashed IP address of the visitor (for privacy)', max_length=64, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, default='', help_text='Browser user agent string', verbose_name='User Agent')),
                ('device_fingerprint', models.CharField(blank=True, db_index=True, default='', help_text='Hashed device fingerprint for fraud detection', max_length=64, verbose_name='Device Fingerprint')),
                ('referrer_url', models.URLField(blank=True, default='', help_text='HTTP referrer header', max_length=500, verbose_name='Referrer URL')),
                ('landing_url', models.URLField(blank=True, default='', help_text='URL where the visitor landed', max_length=500, verbose_name='Landing URL')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event data (utm params, browser info, etc.)', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_events', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_events', to='orders.order', verbose_name='Order')),
                ('referrer_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='referrals.referralidentity', verbose_name='Referrer Identity')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='referrals.referralprogram', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Referral Event',
                'verbose_name_plural': 'Referral Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', max_length=24, verbose_name='Status')),
                ('rejection_reason', models.CharField(blank=True, choices=[('self_referral', 'Self Referral'), ('not_new_customer', 'Not New Customer'), ('below_minimum', 'Below Minimum Order Value'), ('disposable_email', 'Disposable Email'), ('cap_exceeded', 'Cap Exceeded'), ('fraud_risk', 'Fraud Risk'), ('order_refunded', 'Order Refunded'), ('order_cancelled', 'Order Cancelled'), ('manual_rejection', 'Manual Rejection'), ('other', 'Other')], db_index=True, default='', max_length=64, verbose_name='Rejection Reason')),
                ('rejection_notes', models.TextField(blank=True, default='', help_text='Additional notes about why this was rejected', verbose_name='Rejection Notes')),
                ('validation_data', models.JSONField(blank=True, default=dict, help_text='Results from fraud detection and validation checks', verbose_name='Validation Data')),
                ('risk_score', models.PositiveSmallIntegerField(default=0, help_text='Calculated fraud risk score (0-100)', verbose_name='Risk Score')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('first_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_attribution', to='orders.order', verbose_name='First Order')),
                ('referee_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_by', to=settings.AUTH_USER_MODEL, verbose_name='Referee Customer')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin user who approved/rejected this attribution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attributions', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('referrer_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to='referrals.referralidentity', verbose_name='Referrer Identity')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='referrals.referralprogram', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Referral Attribution',
                'verbose_name_plural': 'Referral Attributions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('referrer', 'Referrer'), ('referee', 'Referee')], default='referrer', max_length=10, verbose_name='Recipient Type')),
                ('kind', models.CharField(choices=[('credit', 'Store Credit'), ('coupon', 'Coupon Code'), ('percent', 'Percentage Discount'), ('perk', 'Exclusive Perk')], db_index=True, max_length=24, verbose_name='Reward Kind')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('XUA', 'ADB Unit of Account'), ('AFN', 'Afghan Afghani'), ('AFA', 'Afghan Afghani (1927–2002)'), ('ALL', 'Albanian Lek'), ('ALK', 'Albanian Lek (1946–1965)'), ('DZD', 'Algerian Dinar'), ('ADP', 'Andorran Peseta'), ('AOA', 'Angolan Kwanza'), ('AOK', 'Angolan Kwanza (1977–1991)'), ('AON', 'Angolan New Kwanza (1990–2000)'), ('AOR', 'Angolan Readjusted Kwanza (1995–1999)'), ('ARA', 'Argentine Austral'), ('ARS', 'Argentine Peso'), ('ARM', 'Argentine Peso (1881–1970)'), ('ARP', 'Argentine Peso (1983–1985)'), ('ARL', 'Argentine Peso Ley (1970–1983)'), ('AMD', 'Armenian Dram'), ('AWG', 'Aruban Florin'), ('AUD', 'Australian Dollar'), ('ATS', 'Austrian Schilling'), ('AZN', 'Azerbaijani Manat'), ('AZM', 'Azerbaijani Manat (1993–2006)'), ('BSD', 'Bahamian Dollar'), ('BHD', 'Bahraini Dinar'), ('BDT', 'Bangladeshi Taka'), ('BBD', 'Barbadian Dollar'), ('BYN', 'Belarusian Ruble'), ('BYB', 'Belarusian Ruble (1994–1999)'), ('BYR', 'Belarusian Ruble (2000–2016)'), ('BEF', 'Belgian Franc'), ('BEC', 'Belgian Franc (convertible)'), ('BEL', 'Belgian Franc (financial)'), ('BZD', 'Belize Dollar'), ('BMD', 'Bermudan Dollar'), ('BTN', 'Bhutanese Ngultrum'), ('BOB', 'Bolivian Boliviano'), ('BOL', 'Bolivian Boliviano (1863–1963)'), ('BOV', 'Bolivian Mvdol'), ('BOP', 'Bolivian Peso'), ('VED', 'Bolívar Soberano'), ('BAM', 'Bosnia-Herzegovina Convertible Mark'), ('BAD', 'Bosnia-Herzegovina Dinar (1992–1994)'), ('BAN', 'Bosnia-Herzegovina New Dinar (1994–1997)'), ('BWP', 'Botswanan Pula'), ('BRC', 'Brazilian Cruzado (1986–1989)'), ('BRZ', 'Brazilian Cruzeiro (1942–1967)'), ('BRE', 'Brazilian Cruzeiro (1990–1993)'), ('BRR', 'Brazilian Cruzeiro (1993–1994)'), ('BRN', 'Brazilian New Cruzado (1989–1990)'), ('BRB', 'Brazilian New Cruzeiro (1967–1986)'), ('BRL', 'Brazilian Real'), ('GBP', 'British Pound'), ('BND', 'Brunei Dollar'), ('BGL', 'Bulgarian Hard Lev'), ('BGN', 'Bulgarian Lev'), ('BGO', 'Bulgarian Lev (1879–1952)'), ('BGM', 'Bulgarian Socialist Lev'), ('BUK', 'Burmese Kyat'), ('BIF', 'Burundian Franc'), ('XPF', 'CFP Franc'), ('KHR', 'Cambodian Riel'), ('CAD', 'Canadian Dollar'), ('CVE', 'Cape Verdean Escudo'), ('KYD', 'Cayman Islands Dollar'), ('XAF', 'Central African CFA Franc'), ('CLE', 'Chilean Escudo'), ('CLP', 'Chilean Peso'), ('CLF', 'Chilean Unit of Account (UF)'), ('CNX', 'Chinese People’s Bank Dollar'), ('CNY', 'Chinese Yuan'), ('CNH', 'Chinese Yuan (offshore)'), ('COP', 'Colombian Peso'), ('COU', 'Colombian Real Value Unit'), ('KMF', 'Comorian Franc'), ('CDF', 'Congolese Franc'), ('CRC', 'Costa Rican Colón'), ('HRD', 'Croatian Dinar'), ('HRK', 'Croatian Kuna'), ('CUC', 'Cuban Convertible Peso'), ('CUP', 'Cuban Peso'), ('CYP', 'Cypriot Pound'), ('CZK', 'Czech Koruna'), ('CSK', 'Czechoslovak Hard Koruna'), ('DKK', 'Danish Krone'), ('DJF', 'Djiboutian Franc'), ('DOP', 'Dominican Peso'), ('NLG', 'Dutch Guilder'), ('XCD', 'East Caribbean Dollar'), ('DDM', 'East German Mark'), ('ECS', 'Ecuadorian Sucre'), ('ECV', 'Ecuadorian Unit of Constant Value'), ('EGP', 'Egyptian Pound'), ('GQE', 'Equatorial Guinean Ekwele'), ('ERN', 'Eritrean Nakfa'), ('EEK', 'Estonian Kroon'), ('ETB', 'Ethiopian Birr'), ('EUR', 'Euro'), ('XBA', 'European Composite Unit'), ('XEU', 'European Currency Unit'), ('XBB', 'European Monetary Unit'), ('XBC', 'European Unit of Account (XBC)'), ('XBD', 'European Unit of Account (XBD)'), ('FKP', 'Falkland Islands Pound'), ('FJD', 'Fijian Dollar'), ('FIM', 'Finnish Markka'), ('FRF', 'French Franc'), ('XFO', 'French Gold Franc'), ('XFU', 'French UIC-Franc'), ('GMD', 'Gambian Dalasi'), ('GEK', 'Georgian Kupon Larit'), ('GEL', 'Georgian Lari'), ('DEM', 'German Mark'), ('GHS', 'Ghanaian Cedi'), ('GHC', 'Ghanaian Cedi (1979–2007)'), ('GIP', 'Gibraltar Pound'), ('XAU', 'Gold'), ('GRD', 'Greek Drachma'), ('GTQ', 'Guatemalan Quetzal'), ('GWP', 'Guinea-Bissau Peso'), ('GNF', 'Guinean Franc'), ('GNS', 'Guinean Syli'), ('GYD', 'Guyanaese Dollar'), ('HTG', 'Haitian Gourde'), ('HNL', 'Honduran Lempira'), ('HKD', 'Hong Kong Dollar'), ('HUF', 'Hungarian Forint'), ('IMP', 'IMP'), ('ISK', 'Icelandic Króna'), ('ISJ', 'Icelandic Króna (1918–1981)'), ('INR', 'Indian Rupee'), ('IDR', 'Indonesian Rupiah'), ('IRR', 'Iranian Rial'), ('IQD', 'Iraqi Dinar'), ('IEP', 'Irish Pound'), ('ILS', 'Israeli New Shekel'), ('ILP', 'Israeli Pound'), ('ILR', 'Israeli Shekel (1980–1985)'), ('ITL', 'Italian Lira'), ('JMD', 'Jamaican Dollar'), ('JPY', 'Japanese Yen'), ('JOD', 'Jordanian Dinar'), ('KZT', 'Kazakhstani Tenge'), ('KES', 'Kenyan Shilling'), ('KWD', 'Kuwaiti Dinar'), ('KGS', 'Kyrgystani Som'), ('LAK', 'Laotian Kip'), ('LVL', 'Latvian Lats'), ('LVR', 'Latvian Ruble'), ('LBP', 'Lebanese Pound'), ('LSL', 'Lesotho Loti'), ('LRD', 'Liberian Dollar'), ('LYD', 'Libyan Dinar'), ('LTL', 'Lithuanian Litas'), ('LTT', 'Lithuanian Talonas'), ('LUL', 'Luxembourg Financial Franc'), ('LUC', 'Luxembourgian Convertible Franc'), ('LUF', 'Luxembourgian Franc'), ('MOP', 'Macanese Pataca'), ('MKD', 'Macedonian Denar'), ('MKN', 'Macedonian Denar (1992–1993)'), ('MGA', 'Malagasy Ariary'), ('MGF', 'Malagasy Franc'), ('MWK', 'Malawian Kwacha'), ('MYR', 'Malaysian Ringgit'), ('MVR', 'Maldivian Rufiyaa'), ('MVP', 'Maldivian Rupee (1947–1981)'), ('MLF', 'Malian Franc'), ('MTL', 'Maltese Lira'), ('MTP', 'Maltese Pound'), ('MRU', 'Mauritanian Ouguiya'), ('MRO', 'Mauritanian Ouguiya (1973–2017)'), ('MUR', 'Mauritian Rupee'), ('MXV', 'Mexican Investment Unit'), ('MXN', 'Mexican Peso'), ('MXP', 'Mexican Silver Peso (1861–1992)'), ('MDC', 'Moldovan Cupon'), ('MDL', 'Moldovan Leu'), ('MCF', 'Monegasque Franc'), ('MNT', 'Mongolian Tugrik'), ('MAD', 'Moroccan Dirham'), ('MAF', 'Moroccan Franc'), ('MZE', 'Mozambican Escudo'), ('MZN', 'Mozambican Metical'), ('MZM', 'Mozambican Metical (1980–2006)'), ('MMK', 'Myanmar Kyat'), ('NAD', 'Namibian Dollar'), ('NPR', 'Nepalese Rupee'), ('ANG', 'Netherlands Antillean Guilder'), ('TWD', 'New Taiwan Dollar'), ('NZD', 'New Zealand Dollar'), ('NIO', 'Nicaraguan Córdoba'), ('NIC', 'Nicaraguan Córdoba (1988–1991)'), ('NGN', 'Nigerian Naira'), ('KPW', 'North Korean Won'), ('NOK', 'Norwegian Krone'), ('OMR', 'Omani Rial'), ('PKR', 'Pakistani Rupee'), ('XPD', 'Palladium'), ('PAB', 'Panamanian Balboa'), ('PGK', 'Papua New Guinean Kina'), ('PYG', 'Paraguayan Guarani'), ('PEI', 'Peruvian Inti'), ('PEN', 'Peruvian Sol'), ('PES', 'Peruvian Sol (1863–1965)'), ('PHP', 'Philippine Peso'), ('XPT', 'Platinum'), ('PLN', 'Polish Zloty'), ('PLZ', 'Polish Zloty (1950–1995)'), ('PTE', 'Portuguese Escudo'), ('GWE', 'Portuguese Guinea Escudo'), ('QAR', 'Qatari Riyal'), ('XRE', 'RINET Funds'), ('RHD', 'Rhodesian Dollar'), ('RON', 'Romanian Leu'), ('ROL', 'Romanian Leu (1952–2006)'), ('RUB', 'Russian Ruble'), ('RUR', 'Russian Ruble (1991–1998)'), ('RWF', 'Rwandan Franc'), ('SVC', 'Salvadoran Colón'), ('WST', 'Samoan Tala'), ('SAR', 'Saudi Riyal'), ('RSD', 'Serbian Dinar'), ('CSD', 'Serbian Dinar (2002–2006)'), ('SCR', 'Seychellois Rupee'), ('SLE', 'Sierra Leonean Leone'), ('SLL', 'Sierra Leonean Leone (1964—2022)'), ('XAG', 'Silver'), ('SGD', 'Singapore Dollar'), ('SKK', 'Slovak Koruna'), ('SIT', 'Slovenian Tolar'), ('SBD', 'Solomon Islands Dollar'), ('SOS', 'Somali Shilling'), ('ZAR', 'South African Rand'), ('ZAL', 'South African Rand (financial)'), ('KRH', 'South Korean Hwan (1953–1962)'), ('KRW', 'South Korean Won'), ('KRO', 'South Korean Won (1945–1953)'), ('SSP', 'South Sudanese Pound'), ('SUR', 'Soviet Rouble'), ('ESP', 'Spanish Peseta'), ('ESA', 'Spanish Peseta (A account)'), ('ESB', 'Spanish Peseta (convertible account)'), ('XDR', 'Special Drawing Rights'), ('LKR', 'Sri Lankan Rupee'), ('SHP', 'St. Helena Pound'), ('XSU', 'Sucre'), ('SDD', 'Sudanese Dinar (1992–2007)'), ('SDG', 'Sudanese Pound'), ('SDP', 'Sudanese Pound (1957–1998)'), ('SRD', 'Surinamese Dollar'), ('SRG', 'Surinamese Guilder'), ('SZL', 'Swazi Lilangeni'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('SYP', 'Syrian Pound'), ('STN', 'São Tomé & Príncipe Dobra'), ('STD', 'São Tomé & Príncipe Dobra (1977–2017)'), ('TVD', 'TVD'), ('TJR', 'Tajikistani Ruble'), ('TJS', 'Tajikistani Somoni'), ('TZS', 'Tanzanian Shilling'), ('XTS', 'Testing Currency Code'), ('THB', 'Thai Baht'), ('TPE', 'Timorese Escudo'), ('TOP', 'Tongan Paʻanga'), ('TTD', 'Trinidad & Tobago Dollar'), ('TND', 'Tunisian Dinar'), ('TRY', 'Turkish Lira'), ('TRL', 'Turkish Lira (1922–2005)'), ('TMT', 'Turkmenistani Manat'), ('TMM', 'Turkmenistani Manat (1993–2009)'), ('USD', 'US Dollar'), ('USN', 'US Dollar (Next day)'), ('USS', 'US Dollar (Same day)'), ('UGX', 'Ugandan Shilling'), ('UGS', 'Ugandan Shilling (1966–1987)'), ('UAH', 'Ukrainian Hryvnia'), ('UAK', 'Ukrainian Karbovanets'), ('AED', 'United Arab Emirates Dirham'), ('UYW', 'Uruguayan Nominal Wage Index Unit'), ('UYU', 'Uruguayan Peso'), ('UYP', 'Uruguayan Peso (1975–1993)'), ('UYI', 'Uruguayan Peso (Indexed Units)'), ('UZS', 'Uzbekistani Som'), ('VUV', 'Vanuatu Vatu'), ('VES', 'Venezuelan Bolívar'), ('VEB', 'Venezuelan Bolívar (1871–2008)'), ('VEF', 'Venezuelan Bolívar (2008–2018)'), ('VND', 'Vietnamese Dong'), ('VNN', 'Vietnamese Dong (1978–1985)'), ('CHE', 'WIR Euro'), ('CHW', 'WIR Franc'), ('XOF', 'West African CFA Franc'), ('YDD', 'Yemeni Dinar'), ('YER', 'Yemeni Rial'), ('YUN', 'Yugoslavian Convertible Dinar (1990–1992)'), ('YUD', 'Yugoslavian Hard Dinar (1966–1990)'), ('YUM', 'Yugoslavian New Dinar (1994–2002)'), ('YUR', 'Yugoslavian Reformed Dinar (1992–1993)'), ('ZWN', 'ZWN'), ('ZRN', 'Zairean New Zaire (1993–1998)'), ('ZRZ', 'Zairean Zaire (1971–1993)'), ('ZMW', 'Zambian Kwacha'), ('ZMK', 'Zambian Kwacha (1968–2012)'), ('ZWD', 'Zimbabwean Dollar (1980–2008)'), ('ZWR', 'Zimbabwean Dollar (2008)'), ('ZWL', 'Zimbabwean Dollar (2009)')], default='USD', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', help_text='Reward amount (for credit, coupon value, or cap)', max_digits=12, verbose_name='Amount')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage discount (for percent kind)', max_digits=5, null=True, verbose_name='Percentage')),
                ('description', models.CharField(blank=True, default='', help_text='Description of the reward or perk', max_length=255, verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=24, verbose_name='Status')),
                ('wallet_transaction_id', models.BigIntegerField(blank=True, help_text='ID of wallet transaction if reward is store credit', null=True, verbose_name='Wallet Transaction ID')),
                ('voucher_code_id', models.BigIntegerField(blank=True, help_text='ID of voucher code if reward is a coupon', null=True, verbose_name='Voucher Code ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('issued_at', models.DateTimeField(blank=True, help_text='When the reward was issued to the customer', null=True, verbose_name='Issued At')),
                ('redeemed_at', models.DateTimeField(blank=True, help_text='When the reward was redeemed', null=True, verbose_name='Redeemed At')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Expiry date for unredeemed rewards', null=True, verbose_name='Expires At')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked At')),
                ('revocation_reason', models.TextField(blank=True, default='', verbose_name='Revocation Reason')),
                ('attribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='referrals.referralattribution', verbose_name='Attribution')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_rewards', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='referrals.referralprogram', verbose_name='Program')),
                ('referrer_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards_earned', to='referrals.referralidentity', verbose_name='Referrer Identity')),
            ],
            options={
                'verbose_name': 'Issued Reward',
                'verbose_name_plural': 'Issued Rewards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='referralidentity',
            index=models.Index(fields=['token'], name='referrals_r_token_0a0d13_idx'),
        ),
        migrations.AddIndex(
            model_name='referralidentity',
            index=models.Index(fields=['customer'], name='referrals_r_custome_4a7648_idx'),
        ),
        migrations.AddIndex(
            model_name='referralevent',
            index=models.Index(fields=['event_type', 'created_at'], name='referrals_r_event_t_568eec_idx'),
        ),
        migrations.AddIndex(
            model_name='referralevent',
            index=models.Index(fields=['referrer_identity', 'event_type'], name='referrals_r_referre_756745_idx'),
        ),
        migrations.AddIndex(
            model_name='referralevent',
            index=models.Index(fields=['customer', 'event_type'], name='referrals_r_custome_12faca_idx'),
        ),
        migrations.AddIndex(
            model_name='referralevent',
            index=models.Index(fields=['device_fingerprint'], name='referrals_r_device__543e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='referralattribution',
            index=models.Index(fields=['status', 'created_at'], name='referrals_r_status_da93bb_idx'),
        ),
        migrations.AddIndex(
            model_name='referralattribution',
            index=models.Index(fields=['referrer_identity', 'status'], name='referrals_r_referre_274846_idx'),
        ),
        migrations.AddIndex(
            model_name='referralattribution',
            index=models.Index(fields=['referee_customer'], name='referrals_r_referee_8b878f_idx'),
        ),
        migrations.AddIndex(
            model_name='referralattribution',
            index=models.Index(fields=['first_order'], name='referrals_r_first_o_5fb5d2_idx'),
        ),
        migrations.AddIndex(
            model_name='referralattribution',
            index=models.Index(fields=['rejection_reason'], name='referrals_r_rejecti_0a5e22_idx'),
        ),
        migrations.AddIndex(
            model_name='referralattribution',
            index=models.Index(fields=['risk_score'], name='referrals_r_risk_sc_4a5135_idx'),
        ),
        migrations.AddIndex(
            model_name='referralreward',
            index=models.Index(fields=['status', 'created_at'], name='referrals_r_status_ab838a_idx'),
        ),
        migrations.AddIndex(
            model_name='referralreward',
            index=models.Index(fields=['customer', 'status'], name='referrals_r_custome_ef158b_idx'),
        ),
        migrations.AddIndex(
            model_name='referralreward',
            index=models.Index(fields=['kind', 'status'], name='referrals_r_kind_5d016b_idx'),
        ),
        migrations.AddIndex(
            model_name='referralreward',
            index=models.Index(fields=['expires_at'], name='referrals_r_expires_39ce02_idx'),
        ),
        migrations.AddIndex(
            model_name='referralreward',
            index=models.Index(fields=['recipient_type', 'status'], name='referrals_r_recipie_a78a8a_idx'),
        ),
    ]
