# Generated by Django 5.1.4 on 2026-03-17 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralreward',
            name='wallet_transaction_id',
        ),
        migrations.AddField(
            model_name='referralreward',
            name='wallet_transaction',
            field=models.ForeignKey(blank=True, help_text='Linked wallet transaction if reward is store credit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_rewards', to='wallet.wallettransaction', verbose_name='Wallet Transaction'),
        ),
    ]
