"""
Import translated seed element strings from JSON and generate Python translation data.

Usage:
    python manage.py import_seed_translations seed_strings_translated.json

Input: A JSON file produced by `extract_seed_strings` with `translations` added
to each element by a translation system.

Output: Generates `_element_translations.py` with the ELEMENT_TRANSLATIONS dict
used by `seed_page_elements.py` to apply pre-baked translations during seeding.
"""

import json
import os

from django.core.management.base import BaseCommand, CommandError


class Command(BaseCommand):
    help = "Import translated seed strings from JSON and generate _element_translations.py"

    def add_arguments(self, parser):
        parser.add_argument(
            "input_file",
            help="Path to translated JSON file",
        )
        parser.add_argument(
            "--output",
            "-o",
            default=None,
            help="Output Python file path (default: _element_translations.py in same directory)",
        )
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Print stats without writing file",
        )

    def handle(self, *args, **options):
        input_path = options["input_file"]

        if not os.path.exists(input_path):
            self.stderr.write(self.style.ERROR(f"File not found: {input_path}"))
            return

        with open(input_path, encoding="utf-8") as f:
            data = json.load(f)

        # Determine output path
        output_path = options["output"]
        if not output_path:
            output_path = os.path.join(
                os.path.dirname(os.path.abspath(__file__)),
                "_element_translations.py",
            )

        metadata = data.get("metadata", {})
        target_languages = metadata.get("target_languages", [])

        # Build translations dict
        translations = {}
        stats = {
            "pages": 0,
            "elements": 0,
            "languages": set(),
        }
        validation_errors = []

        pages = data.get("pages", {})
        for page_slug, page_data in pages.items():
            stats["pages"] += 1
            for element in page_data.get("elements", []):
                element_name = element.get("element_name", "")
                element_fields = element.get("fields", {})
                element_translations = element.get("translations", {})
                key = f"{page_slug}:{element_name}"

                # Validate full language and field coverage against metadata.
                missing_languages = []
                missing_fields = []
                for lang in target_languages:
                    lang_translation = element_translations.get(lang)
                    if not lang_translation:
                        missing_languages.append(lang)
                        continue
                    for field in element_fields:
                        if field not in lang_translation:
                            missing_fields.append(f"{lang}.{field}")

                if missing_languages:
                    validation_errors.append(
                        f"{key}: missing languages: {', '.join(sorted(missing_languages))}"
                    )
                if missing_fields:
                    validation_errors.append(
                        f"{key}: missing translated fields: {', '.join(sorted(missing_fields))}"
                    )

                translations[key] = element_translations
                stats["elements"] += 1
                stats["languages"].update(element_translations.keys())

        if options["dry_run"]:
            self.stdout.write(f"Pages: {stats['pages']}")
            self.stdout.write(f"Elements: {stats['elements']}")
            self.stdout.write(f"Languages: {', '.join(sorted(stats['languages']))}")
            if validation_errors:
                self.stdout.write(
                    self.style.WARNING(f"Validation errors: {len(validation_errors)}")
                )
                for error in validation_errors:
                    self.stdout.write(f"  {error}")
            return

        if validation_errors:
            raise CommandError(
                "Incomplete translations detected; aborting without writing:\n"
                + "\n".join(f"  {error}" for error in validation_errors)
            )

        # Generate Python file
        self._write_python_file(output_path, translations)

        self.stdout.write(
            self.style.SUCCESS(
                f"Generated {output_path} with {stats['elements']} elements "
                f"in {len(stats['languages'])} languages"
            )
        )

    def _write_python_file(self, output_path, translations):
        """Write the _element_translations.py file."""
        lines = [
            '"""',
            "Pre-baked translations for seeded page builder elements.",
            "",
            "Generated by: python manage.py import_seed_translations",
            "Do not edit manually - regenerate from translated JSON.",
            "",
            "Keys use page_slug:element_name format for disambiguation.",
            '"""',
            "",
            "",
            "ELEMENT_TRANSLATIONS = {",
        ]

        for key in sorted(translations.keys()):
            lang_dict = translations[key]
            lines.append(f"    {key!r}: {{")
            for lang_code in sorted(lang_dict.keys()):
                fields = lang_dict[lang_code]
                lines.append(f"        {lang_code!r}: {fields!r},")
            lines.append("    },")

        lines.append("}")
        lines.append("")

        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
