"""
Global carrier presets for manual shipping.

This file contains 200 pre-configured carrier presets across 54 countries.
Generated from validated global carrier data.
"""

from django.utils.translation import gettext_lazy as _

CARRIER_PRESETS = [
    {
        "slug": "ninjavan-sg",
        "name": "Ninja Van",
        "country_of_operation": "SG",
        "tracking_url_template": "https://ninjavan.co/track?{tracking_number}",
        "description": _("Ninja Van - Singapore shipping service"),
        "is_system": True,
    },
    {
        "slug": "singpost",
        "name": "SingPost",
        "country_of_operation": "SG",
        "tracking_url_template": "https://www.singpost.com/track-items?track-numbers={tracking_number}",
        "description": _("SingPost - Singapore shipping service"),
        "is_system": True,
    },
    {
        "slug": "jtexpress-sg",
        "name": "J&T Express (SG)",
        "country_of_operation": "SG",
        "tracking_url_template": "https://www.jtexpress.sg/track?trackingNo={tracking_number}",
        "description": _("J&T Express (SG) - Singapore shipping service"),
        "is_system": True,
    },
    {
        "slug": "qxpress",
        "name": "Qxpress",
        "country_of_operation": "SG",
        "tracking_url_template": "https://www.qxpress.net/Customer/PopupTraceParcels?trackingno={tracking_number}",
        "description": _("Qxpress - Singapore shipping service"),
        "is_system": True,
    },
    {
        "slug": "dhl-sg",
        "name": "DHL Express",
        "country_of_operation": "SG",
        "tracking_url_template": "https://www.dhl.com/global-en/home/tracking/tracking-express.html?tracking-id={tracking_number}",
        "description": _("DHL Express - Singapore shipping service"),
        "is_system": True,
    },
    {
        "slug": "fedex-sg",
        "name": "FedEx",
        "country_of_operation": "SG",
        "tracking_url_template": "https://www.fedex.com/fedextrack/?tracknumbers={tracking_number}",
        "description": _("FedEx - Singapore shipping service"),
        "is_system": True,
    },
    {
        "slug": "ups-sg",
        "name": "UPS",
        "country_of_operation": "SG",
        "tracking_url_template": "https://www.ups.com/track?tracknum={tracking_number}",
        "description": _("UPS - Singapore shipping service"),
        "is_system": True,
    },
    {
        "slug": "aramex-sg",
        "name": "Aramex",
        "country_of_operation": "SG",
        "tracking_url_template": "https://www.aramex.com/track/shipments/{tracking_number}",
        "description": _("Aramex - Singapore shipping service"),
        "is_system": True,
    },
    {
        "slug": "poslaju",
        "name": "Pos Laju (Pos Malaysia)",
        "country_of_operation": "MY",
        "tracking_url_template": "https://www.pos.com.my/track-trace?trackingNo={tracking_number}",
        "description": _("Pos Laju (Pos Malaysia) - Malaysia shipping service"),
        "is_system": True,
    },
    {
        "slug": "jtexpress-my",
        "name": "J&T Express (MY)",
        "country_of_operation": "MY",
        "tracking_url_template": "https://www.jtexpress.my/track?trackingNo={tracking_number}",
        "description": _("J&T Express (MY) - Malaysia shipping service"),
        "is_system": True,
    },
    {
        "slug": "ninjavan-my",
        "name": "Ninja Van (MY)",
        "country_of_operation": "MY",
        "tracking_url_template": "https://ninjavan.co/track?{tracking_number}",
        "description": _("Ninja Van (MY) - Malaysia shipping service"),
        "is_system": True,
    },
    {
        "slug": "citylink",
        "name": "City-Link Express",
        "country_of_operation": "MY",
        "tracking_url_template": "https://www.citylinkexpress.com/track?waybill={tracking_number}",
        "description": _("City-Link Express - Malaysia shipping service"),
        "is_system": True,
    },
    {
        "slug": "gdex",
        "name": "GDex",
        "country_of_operation": "MY",
        "tracking_url_template": "https://www.gdexpress.com/track?consignmentNo={tracking_number}",
        "description": _("GDex - Malaysia shipping service"),
        "is_system": True,
    },
    {
        "slug": "jne",
        "name": "JNE",
        "country_of_operation": "ID",
        "tracking_url_template": "https://www.jne.co.id/en/tracking/trace?awb={tracking_number}",
        "description": _("JNE - Indonesia shipping service"),
        "is_system": True,
    },
    {
        "slug": "pos-indonesia",
        "name": "Pos Indonesia",
        "country_of_operation": "ID",
        "tracking_url_template": "https://www.posindonesia.co.id/id/tracking?resi={tracking_number}",
        "description": _("Pos Indonesia - Indonesia shipping service"),
        "is_system": True,
    },
    {
        "slug": "tiki-id",
        "name": "TIKI",
        "country_of_operation": "ID",
        "tracking_url_template": "https://www.tiki.id/id/layanan/cek-resi?noresi={tracking_number}",
        "description": _("TIKI - Indonesia shipping service"),
        "is_system": True,
    },
    {
        "slug": "jtexpress-id",
        "name": "J&T Express (ID)",
        "country_of_operation": "ID",
        "tracking_url_template": "https://jet.co.id/track?awb={tracking_number}",
        "description": _("J&T Express (ID) - Indonesia shipping service"),
        "is_system": True,
    },
    {
        "slug": "sicepat",
        "name": "SiCepat",
        "country_of_operation": "ID",
        "tracking_url_template": "https://www.sicepat.com/checkAwb?awb={tracking_number}",
        "description": _("SiCepat - Indonesia shipping service"),
        "is_system": True,
    },
    {
        "slug": "lbc",
        "name": "LBC Express",
        "country_of_operation": "PH",
        "tracking_url_template": "https://track.lbcexpress.com/?referenceNo={tracking_number}",
        "description": _("LBC Express - Philippines shipping service"),
        "is_system": True,
    },
    {
        "slug": "2go",
        "name": "2GO",
        "country_of_operation": "PH",
        "tracking_url_template": "https://supplychain.2go.com.ph/CustomerSupport/etrace/index.asp?trackingNo={tracking_number}",
        "description": _("2GO - Philippines shipping service"),
        "is_system": True,
    },
    {
        "slug": "jtexpress-ph",
        "name": "J&T Express (PH)",
        "country_of_operation": "PH",
        "tracking_url_template": "https://www.jtexpress.ph/track?trackingNo={tracking_number}",
        "description": _("J&T Express (PH) - Philippines shipping service"),
        "is_system": True,
    },
    {
        "slug": "ninjavan-ph",
        "name": "Ninja Van (PH)",
        "country_of_operation": "PH",
        "tracking_url_template": "https://ninjavan.co/track?{tracking_number}",
        "description": _("Ninja Van (PH) - Philippines shipping service"),
        "is_system": True,
    },
    {
        "slug": "jrs",
        "name": "JRS Express",
        "country_of_operation": "PH",
        "tracking_url_template": "https://www.jrs-express.com/track/?tracking={tracking_number}",
        "description": _("JRS Express - Philippines shipping service"),
        "is_system": True,
    },
    {
        "slug": "thailand-post",
        "name": "Thailand Post",
        "country_of_operation": "TH",
        "tracking_url_template": "https://track.thailandpost.co.th/?barcode={tracking_number}",
        "description": _("Thailand Post - Thailand shipping service"),
        "is_system": True,
    },
    {
        "slug": "kerry-th",
        "name": "Kerry Express (TH)",
        "country_of_operation": "TH",
        "tracking_url_template": "https://th.kerryexpress.com/en/track/?track={tracking_number}",
        "description": _("Kerry Express (TH) - Thailand shipping service"),
        "is_system": True,
    },
    {
        "slug": "jtexpress-th",
        "name": "J&T Express (TH)",
        "country_of_operation": "TH",
        "tracking_url_template": "https://www.jtexpress.co.th/index/tracking?billcode={tracking_number}",
        "description": _("J&T Express (TH) - Thailand shipping service"),
        "is_system": True,
    },
    {
        "slug": "flash-th",
        "name": "Flash Express (TH)",
        "country_of_operation": "TH",
        "tracking_url_template": "https://www.flashexpress.co.th/tracking/?se={tracking_number}",
        "description": _("Flash Express (TH) - Thailand shipping service"),
        "is_system": True,
    },
    {
        "slug": "ninjavan-th",
        "name": "Ninja Van (TH)",
        "country_of_operation": "TH",
        "tracking_url_template": "https://ninjavan.co/track?{tracking_number}",
        "description": _("Ninja Van (TH) - Thailand shipping service"),
        "is_system": True,
    },
    {
        "slug": "vnpost",
        "name": "Vietnam Post (VNPost)",
        "country_of_operation": "VN",
        "tracking_url_template": "https://www.vnpost.vn/en-us/dinh-vi/buu-pham?Key={tracking_number}",
        "description": _("Vietnam Post (VNPost) - Vietnam shipping service"),
        "is_system": True,
    },
    {
        "slug": "viettel-post",
        "name": "Viettel Post",
        "country_of_operation": "VN",
        "tracking_url_template": "https://viettelpost.com.vn/tra-cuu-hanh-trinh-don/?ordertracking={tracking_number}",
        "description": _("Viettel Post - Vietnam shipping service"),
        "is_system": True,
    },
    {
        "slug": "ghn",
        "name": "GHN",
        "country_of_operation": "VN",
        "tracking_url_template": "https://ghn.vn/nhan-hang/tracking/{tracking_number}",
        "description": _("GHN - Vietnam shipping service"),
        "is_system": True,
    },
    {
        "slug": "ghtk",
        "name": "GHTK",
        "country_of_operation": "VN",
        "tracking_url_template": "https://i.ghtk.vn/services/shipment/{tracking_number}",
        "description": _("GHTK - Vietnam shipping service"),
        "is_system": True,
    },
    {
        "slug": "jtexpress-vn",
        "name": "J&T Express (VN)",
        "country_of_operation": "VN",
        "tracking_url_template": "https://jtexpress.vn/track?id={tracking_number}",
        "description": _("J&T Express (VN) - Vietnam shipping service"),
        "is_system": True,
    },
    {
        "slug": "india-post",
        "name": "India Post",
        "country_of_operation": "IN",
        "tracking_url_template": "https://www.indiapost.gov.in/vas/Pages/TrackConsignment.aspx?consignment={tracking_number}",
        "description": _("India Post - India shipping service"),
        "is_system": True,
    },
    {
        "slug": "bluedart",
        "name": "Blue Dart",
        "country_of_operation": "IN",
        "tracking_url_template": "https://www.bluedart.com/track?trackNo={tracking_number}",
        "description": _("Blue Dart - India shipping service"),
        "is_system": True,
    },
    {
        "slug": "dtdc",
        "name": "DTDC",
        "country_of_operation": "IN",
        "tracking_url_template": "https://www.dtdc.in/tracking.asp?cnno={tracking_number}",
        "description": _("DTDC - India shipping service"),
        "is_system": True,
    },
    {
        "slug": "delhivery",
        "name": "Delhivery",
        "country_of_operation": "IN",
        "tracking_url_template": "https://www.delhivery.com/track/package/{tracking_number}",
        "description": _("Delhivery - India shipping service"),
        "is_system": True,
    },
    {
        "slug": "ecom-express",
        "name": "Ecom Express",
        "country_of_operation": "IN",
        "tracking_url_template": "https://ecomexpress.in/tracking/?awb_field={tracking_number}",
        "description": _("Ecom Express - India shipping service"),
        "is_system": True,
    },
    {
        "slug": "xpressbees",
        "name": "XpressBees",
        "country_of_operation": "IN",
        "tracking_url_template": "https://www.xpressbees.com/track?awb={tracking_number}",
        "description": _("XpressBees - India shipping service"),
        "is_system": True,
    },
    {
        "slug": "japan-post",
        "name": "Japan Post",
        "country_of_operation": "JP",
        "tracking_url_template": "https://trackings.post.japanpost.jp/services/srv/search/direct?reqCodeNo1={tracking_number}",
        "description": _("Japan Post - Japan shipping service"),
        "is_system": True,
    },
    {
        "slug": "yamato",
        "name": "Yamato Transport (Kuroneko)",
        "country_of_operation": "JP",
        "tracking_url_template": "https://track.kuronekoyamato.co.jp/tracking/?number11={tracking_number}",
        "description": _("Yamato Transport (Kuroneko) - Japan shipping service"),
        "is_system": True,
    },
    {
        "slug": "sagawa",
        "name": "Sagawa Express",
        "country_of_operation": "JP",
        "tracking_url_template": "https://k2k.sagawa-exp.co.jp/p/sagawa/web/okurijosearch.do?okurijoNo={tracking_number}",
        "description": _("Sagawa Express - Japan shipping service"),
        "is_system": True,
    },
    {
        "slug": "dhl-jp",
        "name": "DHL Express",
        "country_of_operation": "JP",
        "tracking_url_template": "https://www.dhl.com/global-en/home/tracking/tracking-express.html?tracking-id={tracking_number}",
        "description": _("DHL Express - Japan shipping service"),
        "is_system": True,
    },
    {
        "slug": "fedex-jp",
        "name": "FedEx",
        "country_of_operation": "JP",
        "tracking_url_template": "https://www.fedex.com/fedextrack/?tracknumbers={tracking_number}",
        "description": _("FedEx - Japan shipping service"),
        "is_system": True,
    },
    {
        "slug": "korea-post",
        "name": "Korea Post",
        "country_of_operation": "KR",
        "tracking_url_template": "https://service.epost.go.kr/trace.RetrieveDomRigiTraceList.comm?sid1={tracking_number}",
        "description": _("Korea Post - South Korea shipping service"),
        "is_system": True,
    },
    {
        "slug": "cj-logistics",
        "name": "CJ Logistics",
        "country_of_operation": "KR",
        "tracking_url_template": "https://www.cjlogistics.com/en/tool/parcel/tracking?gnbInvcNo={tracking_number}",
        "description": _("CJ Logistics - South Korea shipping service"),
        "is_system": True,
    },
    {
        "slug": "lotte-logistics",
        "name": "Lotte Global Logistics",
        "country_of_operation": "KR",
        "tracking_url_template": "https://www.lotteglogis.com/home/reservation/tracking/linkView?InvNo={tracking_number}",
        "description": _("Lotte Global Logistics - South Korea shipping service"),
        "is_system": True,
    },
    {
        "slug": "hanjin",
        "name": "Hanjin",
        "country_of_operation": "KR",
        "tracking_url_template": "https://www.hanjin.com/kor/CMS/DeliveryMgr/ShipmentTracking.do?billno={tracking_number}",
        "description": _("Hanjin - South Korea shipping service"),
        "is_system": True,
    },
    {
        "slug": "auspost",
        "name": "Australia Post",
        "country_of_operation": "AU",
        "tracking_url_template": "https://auspost.com.au/mypost/track/#/details/{tracking_number}",
        "description": _("Australia Post - Australia shipping service"),
        "is_system": True,
    },
    {
        "slug": "startrack",
        "name": "StarTrack",
        "country_of_operation": "AU",
        "tracking_url_template": "https://startrack.com.au/track/details/{tracking_number}",
        "description": _("StarTrack - Australia shipping service"),
        "is_system": True,
    },
    {
        "slug": "couriersplease",
        "name": "CouriersPlease",
        "country_of_operation": "AU",
        "tracking_url_template": "https://www.couriersplease.com.au/tools-track?consignmentNumber={tracking_number}",
        "description": _("CouriersPlease - Australia shipping service"),
        "is_system": True,
    },
    {
        "slug": "toll",
        "name": "Toll",
        "country_of_operation": "AU",
        "tracking_url_template": "https://www.tollgroup.com/tools/mytoll?ConsignmentNumber={tracking_number}",
        "description": _("Toll - Australia shipping service"),
        "is_system": True,
    },
    {
        "slug": "sendle",
        "name": "Sendle",
        "country_of_operation": "AU",
        "tracking_url_template": "https://track.sendle.com/tracking?ref={tracking_number}",
        "description": _("Sendle - Australia shipping service"),
        "is_system": True,
    },
    {
        "slug": "aramex-au",
        "name": "Aramex (AU)",
        "country_of_operation": "AU",
        "tracking_url_template": "https://www.aramex.com.au/tools/track?l={tracking_number}",
        "description": _("Aramex (AU) - Australia shipping service"),
        "is_system": True,
    },
    {
        "slug": "nz-post",
        "name": "NZ Post",
        "country_of_operation": "NZ",
        "tracking_url_template": "https://www.nzpost.co.nz/tools/tracking?trackid={tracking_number}",
        "description": _("NZ Post - New Zealand shipping service"),
        "is_system": True,
    },
    {
        "slug": "aramex-nz",
        "name": "Aramex (NZ / Fastway)",
        "country_of_operation": "NZ",
        "tracking_url_template": "https://www.aramex.co.nz/tools/track?l={tracking_number}",
        "description": _("Aramex (NZ / Fastway) - New Zealand shipping service"),
        "is_system": True,
    },
    {
        "slug": "posthaste",
        "name": "Post Haste",
        "country_of_operation": "NZ",
        "tracking_url_template": "https://www.posthaste.co.nz/track/track.php?ticket={tracking_number}",
        "description": _("Post Haste - New Zealand shipping service"),
        "is_system": True,
    },
    {
        "slug": "pbt",
        "name": "PBT",
        "country_of_operation": "NZ",
        "tracking_url_template": "https://www.pbt.co.nz/track?ticket={tracking_number}",
        "description": _("PBT - New Zealand shipping service"),
        "is_system": True,
    },
    {
        "slug": "usps",
        "name": "USPS",
        "country_of_operation": "US",
        "tracking_url_template": "https://tools.usps.com/go/TrackConfirmAction?tLabels={tracking_number}",
        "description": _("USPS - United States shipping service"),
        "is_system": True,
    },
    {
        "slug": "ups-us",
        "name": "UPS",
        "country_of_operation": "US",
        "tracking_url_template": "https://www.ups.com/track?tracknum={tracking_number}",
        "description": _("UPS - United States shipping service"),
        "is_system": True,
    },
    {
        "slug": "fedex-us",
        "name": "FedEx",
        "country_of_operation": "US",
        "tracking_url_template": "https://www.fedex.com/fedextrack/?tracknumbers={tracking_number}",
        "description": _("FedEx - United States shipping service"),
        "is_system": True,
    },
    {
        "slug": "dhl-ecommerce",
        "name": "DHL eCommerce",
        "country_of_operation": "US",
        "tracking_url_template": "https://www.dhl.com/us-en/home/tracking/tracking-ecommerce.html?tracking-id={tracking_number}",
        "description": _("DHL eCommerce - United States shipping service"),
        "is_system": True,
    },
    {
        "slug": "ontrac",
        "name": "OnTrac",
        "country_of_operation": "US",
        "tracking_url_template": "https://www.ontrac.com/tracking?tracking={tracking_number}",
        "description": _("OnTrac - United States shipping service"),
        "is_system": True,
    },
    {
        "slug": "pitney-bowes",
        "name": "Pitney Bowes",
        "country_of_operation": "US",
        "tracking_url_template": "https://www.pitneybowes.com/us/shipping-and-mailing/track-a-package.html?trackingnumber={tracking_number}",
        "description": _("Pitney Bowes - United States shipping service"),
        "is_system": True,
    },
    {
        "slug": "canada-post",
        "name": "Canada Post",
        "country_of_operation": "CA",
        "tracking_url_template": "https://www.canadapost-postescanada.ca/track-reperage/en#/details/{tracking_number}",
        "description": _("Canada Post - Canada shipping service"),
        "is_system": True,
    },
    {
        "slug": "purolator",
        "name": "Purolator",
        "country_of_operation": "CA",
        "tracking_url_template": "https://www.purolator.com/en/shipping/tracker?pin={tracking_number}",
        "description": _("Purolator - Canada shipping service"),
        "is_system": True,
    },
    {
        "slug": "canpar",
        "name": "Canpar",
        "country_of_operation": "CA",
        "tracking_url_template": "https://www.canpar.com/en/track/track?reference={tracking_number}",
        "description": _("Canpar - Canada shipping service"),
        "is_system": True,
    },
    {
        "slug": "intelcom",
        "name": "Intelcom",
        "country_of_operation": "CA",
        "tracking_url_template": "https://intelcom.ca/en/tracking/{tracking_number}",
        "description": _("Intelcom - Canada shipping service"),
        "is_system": True,
    },
    {
        "slug": "ups-ca",
        "name": "UPS",
        "country_of_operation": "CA",
        "tracking_url_template": "https://www.ups.com/track?tracknum={tracking_number}",
        "description": _("UPS - Canada shipping service"),
        "is_system": True,
    },
    {
        "slug": "fedex-ca",
        "name": "FedEx",
        "country_of_operation": "CA",
        "tracking_url_template": "https://www.fedex.com/fedextrack/?tracknumbers={tracking_number}",
        "description": _("FedEx - Canada shipping service"),
        "is_system": True,
    },
    {
        "slug": "royal-mail",
        "name": "Royal Mail",
        "country_of_operation": "GB",
        "tracking_url_template": "https://www.royalmail.com/track-your-item#/tracking-results/{tracking_number}",
        "description": _("Royal Mail - United Kingdom shipping service"),
        "is_system": True,
    },
    {
        "slug": "parcelforce",
        "name": "Parcelforce",
        "country_of_operation": "GB",
        "tracking_url_template": "https://www.parcelforce.com/track-and-trace?trackNumber={tracking_number}",
        "description": _("Parcelforce - United Kingdom shipping service"),
        "is_system": True,
    },
    {
        "slug": "dpd-uk",
        "name": "DPD (UK)",
        "country_of_operation": "GB",
        "tracking_url_template": "https://www.dpd.co.uk/service/?parcel={tracking_number}",
        "description": _("DPD (UK) - United Kingdom shipping service"),
        "is_system": True,
    },
    {
        "slug": "evri",
        "name": "Evri (Hermes)",
        "country_of_operation": "GB",
        "tracking_url_template": "https://www.evri.com/track/parcel/{tracking_number}",
        "description": _("Evri (Hermes) - United Kingdom shipping service"),
        "is_system": True,
    },
    {
        "slug": "yodel",
        "name": "Yodel",
        "country_of_operation": "GB",
        "tracking_url_template": "https://www.yodel.co.uk/track/{tracking_number}",
        "description": _("Yodel - United Kingdom shipping service"),
        "is_system": True,
    },
    {
        "slug": "dhl-de",
        "name": "DHL Paket / Deutsche Post",
        "country_of_operation": "DE",
        "tracking_url_template": "https://www.dhl.de/en/privatkunden/dhl-sendungsverfolgung.html?piececode={tracking_number}",
        "description": _("DHL Paket / Deutsche Post - Germany shipping service"),
        "is_system": True,
    },
    {
        "slug": "dpd-de",
        "name": "DPD (DE)",
        "country_of_operation": "DE",
        "tracking_url_template": "https://www.dpd.com/de/de/empfangen/sendungsverfolgung/?parcelNumber={tracking_number}",
        "description": _("DPD (DE) - Germany shipping service"),
        "is_system": True,
    },
    {
        "slug": "hermes-de",
        "name": "Hermes (DE)",
        "country_of_operation": "DE",
        "tracking_url_template": "https://www.myhermes.de/empfangen/sendungsverfolgung/?trackingNumber={tracking_number}",
        "description": _("Hermes (DE) - Germany shipping service"),
        "is_system": True,
    },
    {
        "slug": "gls-de",
        "name": "GLS (DE)",
        "country_of_operation": "DE",
        "tracking_url_template": "https://gls-group.eu/DE/de/paketverfolgung?match={tracking_number}",
        "description": _("GLS (DE) - Germany shipping service"),
        "is_system": True,
    },
    {
        "slug": "colissimo",
        "name": "Colissimo (La Poste)",
        "country_of_operation": "FR",
        "tracking_url_template": "https://www.laposte.fr/outils/suivre-vos-envois?code={tracking_number}",
        "description": _("Colissimo (La Poste) - France shipping service"),
        "is_system": True,
    },
    {
        "slug": "chronopost",
        "name": "Chronopost",
        "country_of_operation": "FR",
        "tracking_url_template": "https://www.chronopost.fr/fr/suivi-colis?numero={tracking_number}",
        "description": _("Chronopost - France shipping service"),
        "is_system": True,
    },
    {
        "slug": "mondial-relay",
        "name": "Mondial Relay",
        "country_of_operation": "FR",
        "tracking_url_template": "https://www.mondialrelay.fr/suivi-de-colis/?code={tracking_number}",
        "description": _("Mondial Relay - France shipping service"),
        "is_system": True,
    },
    {
        "slug": "dpd-fr",
        "name": "DPD (FR)",
        "country_of_operation": "FR",
        "tracking_url_template": "https://www.dpd.fr/tracking?search={tracking_number}",
        "description": _("DPD (FR) - France shipping service"),
        "is_system": True,
    },
    {
        "slug": "gls-fr",
        "name": "GLS (FR)",
        "country_of_operation": "FR",
        "tracking_url_template": "https://gls-group.eu/FR/fr/suivi-colis?match={tracking_number}",
        "description": _("GLS (FR) - France shipping service"),
        "is_system": True,
    },
    {
        "slug": "correos-es",
        "name": "Correos",
        "country_of_operation": "ES",
        "tracking_url_template": "https://www.correos.es/es/en/tools/tracking?tracking-number={tracking_number}",
        "description": _("Correos - Spain shipping service"),
        "is_system": True,
    },
    {
        "slug": "seur",
        "name": "SEUR",
        "country_of_operation": "ES",
        "tracking_url_template": "https://www.seur.com/livetracking/pages/seguimiento-online.do?segOnlineIdentificador={tracking_number}",
        "description": _("SEUR - Spain shipping service"),
        "is_system": True,
    },
    {
        "slug": "mrw",
        "name": "MRW",
        "country_of_operation": "ES",
        "tracking_url_template": "https://www.mrw.es/en/tracking?trackingNumber={tracking_number}",
        "description": _("MRW - Spain shipping service"),
        "is_system": True,
    },
    {
        "slug": "gls-es",
        "name": "GLS (ES)",
        "country_of_operation": "ES",
        "tracking_url_template": "https://gls-group.eu/ES/en/parcel-tracking?match={tracking_number}",
        "description": _("GLS (ES) - Spain shipping service"),
        "is_system": True,
    },
    {
        "slug": "nacex",
        "name": "NACEX",
        "country_of_operation": "ES",
        "tracking_url_template": "https://www.nacex.es/seguimiento?codigo={tracking_number}",
        "description": _("NACEX - Spain shipping service"),
        "is_system": True,
    },
    {
        "slug": "poste-italiane",
        "name": "Poste Italiane",
        "country_of_operation": "IT",
        "tracking_url_template": "https://www.poste.it/cerca/index.html#/risultati-spedizioni/{tracking_number}",
        "description": _("Poste Italiane - Italy shipping service"),
        "is_system": True,
    },
    {
        "slug": "sda",
        "name": "SDA",
        "country_of_operation": "IT",
        "tracking_url_template": "https://www.sda.it/wps/portal/ricercaspedizioni?searchType=tracking&trackingNumber={tracking_number}",
        "description": _("SDA - Italy shipping service"),
        "is_system": True,
    },
    {
        "slug": "brt",
        "name": "BRT (Bartolini)",
        "country_of_operation": "IT",
        "tracking_url_template": "https://www.brt.it/it/tracking?shipmentID={tracking_number}",
        "description": _("BRT (Bartolini) - Italy shipping service"),
        "is_system": True,
    },
    {
        "slug": "gls-it",
        "name": "GLS (IT)",
        "country_of_operation": "IT",
        "tracking_url_template": "https://gls-group.eu/IT/en/parcel-tracking?match={tracking_number}",
        "description": _("GLS (IT) - Italy shipping service"),
        "is_system": True,
    },
    {
        "slug": "postnl",
        "name": "PostNL",
        "country_of_operation": "NL",
        "tracking_url_template": "https://www.postnl.nl/en/track-trace/?barcodes={tracking_number}",
        "description": _("PostNL - Netherlands shipping service"),
        "is_system": True,
    },
    {
        "slug": "dhl-nl",
        "name": "DHL Parcel (NL)",
        "country_of_operation": "NL",
        "tracking_url_template": "https://www.dhlparcel.nl/en/track-and-trace?tt={tracking_number}",
        "description": _("DHL Parcel (NL) - Netherlands shipping service"),
        "is_system": True,
    },
    {
        "slug": "dpd-nl",
        "name": "DPD (NL)",
        "country_of_operation": "NL",
        "tracking_url_template": "https://www.dpd.com/nl/en/track-parcel/?parcelNumber={tracking_number}",
        "description": _("DPD (NL) - Netherlands shipping service"),
        "is_system": True,
    },
    {
        "slug": "gls-nl",
        "name": "GLS (NL)",
        "country_of_operation": "NL",
        "tracking_url_template": "https://gls-group.eu/NL/en/parcel-tracking?match={tracking_number}",
        "description": _("GLS (NL) - Netherlands shipping service"),
        "is_system": True,
    },
    {
        "slug": "bpost",
        "name": "bpost",
        "country_of_operation": "BE",
        "tracking_url_template": "https://track.bpost.be/btr/web/#/search?itemCode={tracking_number}",
        "description": _("bpost - Belgium shipping service"),
        "is_system": True,
    },
    {
        "slug": "postnl-be",
        "name": "PostNL (BE)",
        "country_of_operation": "BE",
        "tracking_url_template": "https://www.postnl.be/en/track-trace/?barcodes={tracking_number}",
        "description": _("PostNL (BE) - Belgium shipping service"),
        "is_system": True,
    },
    {
        "slug": "dpd-be",
        "name": "DPD (BE)",
        "country_of_operation": "BE",
        "tracking_url_template": "https://www.dpd.com/be/en/track-parcel/?parcelNumber={tracking_number}",
        "description": _("DPD (BE) - Belgium shipping service"),
        "is_system": True,
    },
    {
        "slug": "gls-be",
        "name": "GLS (BE)",
        "country_of_operation": "BE",
        "tracking_url_template": "https://gls-group.eu/BE/en/parcel-tracking?match={tracking_number}",
        "description": _("GLS (BE) - Belgium shipping service"),
        "is_system": True,
    },
    {
        "slug": "postnord-se",
        "name": "PostNord (SE)",
        "country_of_operation": "SE",
        "tracking_url_template": "https://www.postnord.se/en/our-tools/track-and-trace?shipmentId={tracking_number}",
        "description": _("PostNord (SE) - Sweden shipping service"),
        "is_system": True,
    },
    {
        "slug": "schenker-se",
        "name": "DB Schenker (SE)",
        "country_of_operation": "SE",
        "tracking_url_template": "https://www.dbschenker.com/se-en/e-services/track-and-trace/parcel?ref={tracking_number}",
        "description": _("DB Schenker (SE) - Sweden shipping service"),
        "is_system": True,
    },
    {
        "slug": "dhl-se",
        "name": "DHL Freight (SE)",
        "country_of_operation": "SE",
        "tracking_url_template": "https://www.dhl.com/se-en/home/tracking.html?tracking-id={tracking_number}",
        "description": _("DHL Freight (SE) - Sweden shipping service"),
        "is_system": True,
    },
    {
        "slug": "bring-se",
        "name": "Bring (SE)",
        "country_of_operation": "SE",
        "tracking_url_template": "https://tracking.bring.se/tracking/{tracking_number}",
        "description": _("Bring (SE) - Sweden shipping service"),
        "is_system": True,
    },
    {
        "slug": "budbee",
        "name": "Budbee",
        "country_of_operation": "SE",
        "tracking_url_template": "https://budbee.com/track/{tracking_number}",
        "description": _("Budbee - Sweden shipping service"),
        "is_system": True,
    },
    {
        "slug": "bring-no",
        "name": "Posten/Bring (NO)",
        "country_of_operation": "NO",
        "tracking_url_template": "https://www.posten.no/en/tracking?trackingNumber={tracking_number}",
        "description": _("Posten/Bring (NO) - Norway shipping service"),
        "is_system": True,
    },
    {
        "slug": "helthjem",
        "name": "Helthjem",
        "country_of_operation": "NO",
        "tracking_url_template": "https://sporing.helthjem.no/{tracking_number}",
        "description": _("Helthjem - Norway shipping service"),
        "is_system": True,
    },
    {
        "slug": "postnord-no",
        "name": "PostNord (NO)",
        "country_of_operation": "NO",
        "tracking_url_template": "https://www.postnord.no/en/our-tools/track-and-trace?shipmentId={tracking_number}",
        "description": _("PostNord (NO) - Norway shipping service"),
        "is_system": True,
    },
    {
        "slug": "postnord-dk",
        "name": "PostNord (DK)",
        "country_of_operation": "DK",
        "tracking_url_template": "https://www.postnord.dk/en/tools/track?shipmentId={tracking_number}",
        "description": _("PostNord (DK) - Denmark shipping service"),
        "is_system": True,
    },
    {
        "slug": "gls-dk",
        "name": "GLS (DK)",
        "country_of_operation": "DK",
        "tracking_url_template": "https://gls-group.eu/DK/da/track-parcel?match={tracking_number}",
        "description": _("GLS (DK) - Denmark shipping service"),
        "is_system": True,
    },
    {
        "slug": "dao-dk",
        "name": "DAO",
        "country_of_operation": "DK",
        "tracking_url_template": "https://www.dao.as/track-and-trace?trackid={tracking_number}",
        "description": _("DAO - Denmark shipping service"),
        "is_system": True,
    },
    {
        "slug": "posti",
        "name": "Posti",
        "country_of_operation": "FI",
        "tracking_url_template": "https://www.posti.fi/en/tracking?trackingcode={tracking_number}",
        "description": _("Posti - Finland shipping service"),
        "is_system": True,
    },
    {
        "slug": "matkahuolto",
        "name": "Matkahuolto",
        "country_of_operation": "FI",
        "tracking_url_template": "https://www.matkahuolto.fi/en/track-and-trace?shipmentId={tracking_number}",
        "description": _("Matkahuolto - Finland shipping service"),
        "is_system": True,
    },
    {
        "slug": "schenker-fi",
        "name": "DB Schenker (FI)",
        "country_of_operation": "FI",
        "tracking_url_template": "https://www.dbschenker.com/fi-en/e-services/track-and-trace/parcel?ref={tracking_number}",
        "description": _("DB Schenker (FI) - Finland shipping service"),
        "is_system": True,
    },
    {
        "slug": "posturinn",
        "name": "Iceland Post (Pósturinn)",
        "country_of_operation": "",
        "tracking_url_template": "https://www.postur.is/en/individuals/track-and-trace?tracking={tracking_number}",
        "description": _("Iceland Post (Pósturinn) - Iceland shipping service"),
        "is_system": True,
    },
    {
        "slug": "poczta-polska",
        "name": "Poczta Polska",
        "country_of_operation": "PL",
        "tracking_url_template": "https://emonitoring.poczta-polska.pl/?numer={tracking_number}",
        "description": _("Poczta Polska - Poland shipping service"),
        "is_system": True,
    },
    {
        "slug": "inpost-pl",
        "name": "InPost",
        "country_of_operation": "PL",
        "tracking_url_template": "https://inpost.pl/sledzenie-przesylek?number={tracking_number}",
        "description": _("InPost - Poland shipping service"),
        "is_system": True,
    },
    {
        "slug": "dpd-pl",
        "name": "DPD (PL)",
        "country_of_operation": "PL",
        "tracking_url_template": "https://track.dpd.pl/pl?parcelNumber={tracking_number}",
        "description": _("DPD (PL) - Poland shipping service"),
        "is_system": True,
    },
    {
        "slug": "gls-pl",
        "name": "GLS (PL)",
        "country_of_operation": "PL",
        "tracking_url_template": "https://gls-group.eu/PL/pl/sledzenie-przesylki?match={tracking_number}",
        "description": _("GLS (PL) - Poland shipping service"),
        "is_system": True,
    },
    {
        "slug": "ceska-posta",
        "name": "Česká pošta",
        "country_of_operation": "CZ",
        "tracking_url_template": "https://www.postaonline.cz/trackandtrace/-/zasilka/cislo?parcelNumbers={tracking_number}",
        "description": _("Česká pošta - Czech Republic shipping service"),
        "is_system": True,
    },
    {
        "slug": "ppl-cz",
        "name": "PPL",
        "country_of_operation": "CZ",
        "tracking_url_template": "https://www.ppl.cz/en/sledovani-zasilky?parcel={tracking_number}",
        "description": _("PPL - Czech Republic shipping service"),
        "is_system": True,
    },
    {
        "slug": "packeta-cz",
        "name": "Zásilkovna (Packeta)",
        "country_of_operation": "CZ",
        "tracking_url_template": "https://www.packeta.cz/sledovani-zasilky?trackingNumber={tracking_number}",
        "description": _("Zásilkovna (Packeta) - Czech Republic shipping service"),
        "is_system": True,
    },
    {
        "slug": "dpd-cz",
        "name": "DPD (CZ)",
        "country_of_operation": "CZ",
        "tracking_url_template": "https://www.dpd.com/cz/en/track-parcel/?parcelNumber={tracking_number}",
        "description": _("DPD (CZ) - Czech Republic shipping service"),
        "is_system": True,
    },
    {
        "slug": "slovenska-posta",
        "name": "Slovenská pošta",
        "country_of_operation": "SK",
        "tracking_url_template": "https://tandt.posta.sk/en?barcode={tracking_number}",
        "description": _("Slovenská pošta - Slovakia shipping service"),
        "is_system": True,
    },
    {
        "slug": "packeta-sk",
        "name": "Packeta (SK)",
        "country_of_operation": "SK",
        "tracking_url_template": "https://tracking.packeta.com/en/tracking?number={tracking_number}",
        "description": _("Packeta (SK) - Slovakia shipping service"),
        "is_system": True,
    },
    {
        "slug": "dpd-sk",
        "name": "DPD (SK)",
        "country_of_operation": "SK",
        "tracking_url_template": "https://www.dpd.com/sk/en/track-parcel/?parcelNumber={tracking_number}",
        "description": _("DPD (SK) - Slovakia shipping service"),
        "is_system": True,
    },
    {
        "slug": "magyar-posta",
        "name": "Magyar Posta",
        "country_of_operation": "HU",
        "tracking_url_template": "https://www.posta.hu/nyomkovetes?pid={tracking_number}",
        "description": _("Magyar Posta - Hungary shipping service"),
        "is_system": True,
    },
    {
        "slug": "gls-hu",
        "name": "GLS (HU)",
        "country_of_operation": "HU",
        "tracking_url_template": "https://gls-group.eu/HU/hu/csomagkovetes?match={tracking_number}",
        "description": _("GLS (HU) - Hungary shipping service"),
        "is_system": True,
    },
    {
        "slug": "dpd-hu",
        "name": "DPD (HU)",
        "country_of_operation": "HU",
        "tracking_url_template": "https://www.dpd.com/hu/en/track-parcel/?parcelNumber={tracking_number}",
        "description": _("DPD (HU) - Hungary shipping service"),
        "is_system": True,
    },
    {
        "slug": "foxpost",
        "name": "Foxpost",
        "country_of_operation": "HU",
        "tracking_url_template": "https://foxpost.hu/csomagkovetes?code={tracking_number}",
        "description": _("Foxpost - Hungary shipping service"),
        "is_system": True,
    },
    {
        "slug": "posta-romana",
        "name": "Poșta Română",
        "country_of_operation": "RO",
        "tracking_url_template": "https://posta-romana.ro/track-trace.html?awb={tracking_number}",
        "description": _("Poșta Română - Romania shipping service"),
        "is_system": True,
    },
    {
        "slug": "fan-courier",
        "name": "Fan Courier",
        "country_of_operation": "RO",
        "tracking_url_template": "https://www.fancourier.ro/awb-tracking/?xawb={tracking_number}",
        "description": _("Fan Courier - Romania shipping service"),
        "is_system": True,
    },
    {
        "slug": "urgent-cargus",
        "name": "Urgent Cargus",
        "country_of_operation": "RO",
        "tracking_url_template": "https://www.urgentcargus.ro/en/awb-tracking?awb={tracking_number}",
        "description": _("Urgent Cargus - Romania shipping service"),
        "is_system": True,
    },
    {
        "slug": "sameday-ro",
        "name": "Sameday",
        "country_of_operation": "RO",
        "tracking_url_template": "https://sameday.ro/awb-tracking?awb={tracking_number}",
        "description": _("Sameday - Romania shipping service"),
        "is_system": True,
    },
    {
        "slug": "econt",
        "name": "Econt",
        "country_of_operation": "BG",
        "tracking_url_template": "https://www.econt.com/en/track-shipment?shipmentNumber={tracking_number}",
        "description": _("Econt - Bulgaria shipping service"),
        "is_system": True,
    },
    {
        "slug": "speedy",
        "name": "Speedy",
        "country_of_operation": "BG",
        "tracking_url_template": "https://www.speedy.bg/en/track-shipment?shipmentNumber={tracking_number}",
        "description": _("Speedy - Bulgaria shipping service"),
        "is_system": True,
    },
    {
        "slug": "bulgarian-posts",
        "name": "Bulgarian Posts",
        "country_of_operation": "BG",
        "tracking_url_template": "https://www.bgpost.bg/en/IPS?barcode={tracking_number}",
        "description": _("Bulgarian Posts - Bulgaria shipping service"),
        "is_system": True,
    },
    {
        "slug": "elta",
        "name": "ELTA Hellenic Post",
        "country_of_operation": "GR",
        "tracking_url_template": "https://www.elta.gr/track?barcode={tracking_number}",
        "description": _("ELTA Hellenic Post - Greece shipping service"),
        "is_system": True,
    },
    {
        "slug": "acs-courier",
        "name": "ACS Courier",
        "country_of_operation": "GR",
        "tracking_url_template": "https://www.acscourier.net/en/track?code={tracking_number}",
        "description": _("ACS Courier - Greece shipping service"),
        "is_system": True,
    },
    {
        "slug": "geniki",
        "name": "Geniki Taxydromiki",
        "country_of_operation": "GR",
        "tracking_url_template": "https://www.taxydromiki.com/en/track?number={tracking_number}",
        "description": _("Geniki Taxydromiki - Greece shipping service"),
        "is_system": True,
    },
    {
        "slug": "speedex-gr",
        "name": "Speedex",
        "country_of_operation": "GR",
        "tracking_url_template": "https://www.speedex.gr/track?code={tracking_number}",
        "description": _("Speedex - Greece shipping service"),
        "is_system": True,
    },
    {
        "slug": "hrvatska-posta",
        "name": "Hrvatska pošta",
        "country_of_operation": "HR",
        "tracking_url_template": "https://posiljka.posta.hr/en?broj={tracking_number}",
        "description": _("Hrvatska pošta - Croatia shipping service"),
        "is_system": True,
    },
    {
        "slug": "dpd-hr",
        "name": "DPD (HR)",
        "country_of_operation": "HR",
        "tracking_url_template": "https://www.dpd.com/hr/en/track-parcel/?parcelNumber={tracking_number}",
        "description": _("DPD (HR) - Croatia shipping service"),
        "is_system": True,
    },
    {
        "slug": "gls-hr",
        "name": "GLS (HR)",
        "country_of_operation": "HR",
        "tracking_url_template": "https://gls-group.eu/HR/hr/pracenje-posiljke?match={tracking_number}",
        "description": _("GLS (HR) - Croatia shipping service"),
        "is_system": True,
    },
    {
        "slug": "posta-slovenije",
        "name": "Pošta Slovenije",
        "country_of_operation": "SI",
        "tracking_url_template": "https://sledenje.posta.si/en/Item/Details/{tracking_number}",
        "description": _("Pošta Slovenije - Slovenia shipping service"),
        "is_system": True,
    },
    {
        "slug": "dpd-si",
        "name": "DPD (SI)",
        "country_of_operation": "SI",
        "tracking_url_template": "https://www.dpd.com/si/en/track-parcel/?parcelNumber={tracking_number}",
        "description": _("DPD (SI) - Slovenia shipping service"),
        "is_system": True,
    },
    {
        "slug": "gls-si",
        "name": "GLS (SI)",
        "country_of_operation": "SI",
        "tracking_url_template": "https://gls-group.eu/SI/sl/sledenje-posiljk?match={tracking_number}",
        "description": _("GLS (SI) - Slovenia shipping service"),
        "is_system": True,
    },
    {
        "slug": "omniva",
        "name": "Omniva",
        "country_of_operation": "",
        "tracking_url_template": "https://www.omniva.ee/eng/track?barcode={tracking_number}",
        "description": _("Omniva - Estonia shipping service"),
        "is_system": True,
    },
    {
        "slug": "dpd-ee",
        "name": "DPD (EE)",
        "country_of_operation": "",
        "tracking_url_template": "https://www.dpd.com/ee/en/track-parcel/?parcelNumber={tracking_number}",
        "description": _("DPD (EE) - Estonia shipping service"),
        "is_system": True,
    },
    {
        "slug": "smartpost-ee",
        "name": "Itella SmartPOST",
        "country_of_operation": "",
        "tracking_url_template": "https://my.smartpost.ee/#!/search?query={tracking_number}",
        "description": _("Itella SmartPOST - Estonia shipping service"),
        "is_system": True,
    },
    {
        "slug": "latvijas-pasts",
        "name": "Latvijas Pasts",
        "country_of_operation": "",
        "tracking_url_template": "https://pasts.lv/en/track?barcode={tracking_number}",
        "description": _("Latvijas Pasts - Latvia shipping service"),
        "is_system": True,
    },
    {
        "slug": "dpd-lv",
        "name": "DPD (LV)",
        "country_of_operation": "",
        "tracking_url_template": "https://www.dpd.com/lv/en/track-parcel/?parcelNumber={tracking_number}",
        "description": _("DPD (LV) - Latvia shipping service"),
        "is_system": True,
    },
    {
        "slug": "venipak-lv",
        "name": "Venipak (LV)",
        "country_of_operation": "",
        "tracking_url_template": "https://www.venipak.lv/en/track-and-trace?tracking={tracking_number}",
        "description": _("Venipak (LV) - Latvia shipping service"),
        "is_system": True,
    },
    {
        "slug": "lietuvos-pastas",
        "name": "Lietuvos Paštas",
        "country_of_operation": "",
        "tracking_url_template": "https://www.post.lt/en/help/parcel-search?barcode={tracking_number}",
        "description": _("Lietuvos Paštas - Lithuania shipping service"),
        "is_system": True,
    },
    {
        "slug": "dpd-lt",
        "name": "DPD (LT)",
        "country_of_operation": "",
        "tracking_url_template": "https://www.dpd.com/lt/en/track-parcel/?parcelNumber={tracking_number}",
        "description": _("DPD (LT) - Lithuania shipping service"),
        "is_system": True,
    },
    {
        "slug": "omniva-lt",
        "name": "Omniva (LT)",
        "country_of_operation": "",
        "tracking_url_template": "https://www.omniva.lt/verslui/siuntu_sekimas?barcode={tracking_number}",
        "description": _("Omniva (LT) - Lithuania shipping service"),
        "is_system": True,
    },
    {
        "slug": "venipak-lt",
        "name": "Venipak (LT)",
        "country_of_operation": "",
        "tracking_url_template": "https://venipak.lt/en/parcel-tracking?code={tracking_number}",
        "description": _("Venipak (LT) - Lithuania shipping service"),
        "is_system": True,
    },
    {
        "slug": "correios-br",
        "name": "Correios",
        "country_of_operation": "BR",
        "tracking_url_template": "https://tracking.correios.com.br/app/index.php?objetos={tracking_number}",
        "description": _("Correios - Brazil shipping service"),
        "is_system": True,
    },
    {
        "slug": "jadlog",
        "name": "Jadlog",
        "country_of_operation": "BR",
        "tracking_url_template": "https://www.jadlog.com.br/tracking?cte={tracking_number}",
        "description": _("Jadlog - Brazil shipping service"),
        "is_system": True,
    },
    {
        "slug": "total-express",
        "name": "Total Express",
        "country_of_operation": "BR",
        "tracking_url_template": "https://www.totalexpress.com.br/tracking?pedido={tracking_number}",
        "description": _("Total Express - Brazil shipping service"),
        "is_system": True,
    },
    {
        "slug": "azul-cargo",
        "name": "Azul Cargo",
        "country_of_operation": "BR",
        "tracking_url_template": "https://www.azulcargo.com.br/tracking?awb={tracking_number}",
        "description": _("Azul Cargo - Brazil shipping service"),
        "is_system": True,
    },
    {
        "slug": "estafeta",
        "name": "Estafeta",
        "country_of_operation": "MX",
        "tracking_url_template": "https://www.estafeta.com/Herramientas/Rastreo?guia={tracking_number}",
        "description": _("Estafeta - Mexico shipping service"),
        "is_system": True,
    },
    {
        "slug": "paquetexpress",
        "name": "Paquetexpress",
        "country_of_operation": "MX",
        "tracking_url_template": "https://www.paquetexpress.com.mx/rastreo-de-envios?guia={tracking_number}",
        "description": _("Paquetexpress - Mexico shipping service"),
        "is_system": True,
    },
    {
        "slug": "redpack",
        "name": "Redpack",
        "country_of_operation": "MX",
        "tracking_url_template": "https://www.redpack.com.mx/rastreo-de-envios?guia={tracking_number}",
        "description": _("Redpack - Mexico shipping service"),
        "is_system": True,
    },
    {
        "slug": "correos-mx",
        "name": "Correos de México",
        "country_of_operation": "MX",
        "tracking_url_template": "https://www.correosdemexico.gob.mx/SSLServicios/SeguimientoEnvio/Seguimiento.aspx?numeroGuia={tracking_number}",
        "description": _("Correos de México - Mexico shipping service"),
        "is_system": True,
    },
    {
        "slug": "correo-argentino",
        "name": "Correo Argentino",
        "country_of_operation": "AR",
        "tracking_url_template": "https://www.correoargentino.com.ar/formularios/ondnc?numero={tracking_number}",
        "description": _("Correo Argentino - Argentina shipping service"),
        "is_system": True,
    },
    {
        "slug": "andreani",
        "name": "Andreani",
        "country_of_operation": "AR",
        "tracking_url_template": "https://seguimiento.andreani.com/?trackingNumber={tracking_number}",
        "description": _("Andreani - Argentina shipping service"),
        "is_system": True,
    },
    {
        "slug": "oca",
        "name": "OCA",
        "country_of_operation": "AR",
        "tracking_url_template": "https://www.oca.com.ar/Trackings/Trackings/Consultar?numeroguia={tracking_number}",
        "description": _("OCA - Argentina shipping service"),
        "is_system": True,
    },
    {
        "slug": "correos-chile",
        "name": "CorreosChile",
        "country_of_operation": "CL",
        "tracking_url_template": "https://www.correos.cl/web/guest/seguimiento-en-linea?codigos={tracking_number}",
        "description": _("CorreosChile - Chile shipping service"),
        "is_system": True,
    },
    {
        "slug": "chilexpress",
        "name": "Chilexpress",
        "country_of_operation": "CL",
        "tracking_url_template": "https://www.chilexpress.cl/Views/ChilexpressCL/Resultado-busqueda.aspx?DATA={tracking_number}",
        "description": _("Chilexpress - Chile shipping service"),
        "is_system": True,
    },
    {
        "slug": "starken",
        "name": "Starken (Turbus)",
        "country_of_operation": "CL",
        "tracking_url_template": "https://www.starken.cl/seguimiento?codigo={tracking_number}",
        "description": _("Starken (Turbus) - Chile shipping service"),
        "is_system": True,
    },
    {
        "slug": "472",
        "name": "Servicios Postales Nacionales (4-72)",
        "country_of_operation": "CO",
        "tracking_url_template": "https://www.4-72.com.co/seguimiento/?numero={tracking_number}",
        "description": _("Servicios Postales Nacionales (4-72) - Colombia shipping service"),
        "is_system": True,
    },
    {
        "slug": "coordinadora",
        "name": "Coordinadora",
        "country_of_operation": "CO",
        "tracking_url_template": "https://www.coordinadora.com/portafolio-de-servicios/rastrear-guias/?guia={tracking_number}",
        "description": _("Coordinadora - Colombia shipping service"),
        "is_system": True,
    },
    {
        "slug": "servientrega-co",
        "name": "Servientrega",
        "country_of_operation": "CO",
        "tracking_url_template": "https://www.servientrega.com/wps/portal/servientrega/rastreo-envios?numero={tracking_number}",
        "description": _("Servientrega - Colombia shipping service"),
        "is_system": True,
    },
    {
        "slug": "serpost",
        "name": "Serpost",
        "country_of_operation": "PE",
        "tracking_url_template": "https://clientes.serpost.com.pe/prj_online/Web_BusquedaCP.aspx?strSearch={tracking_number}",
        "description": _("Serpost - Peru shipping service"),
        "is_system": True,
    },
    {
        "slug": "olva",
        "name": "Olva Courier",
        "country_of_operation": "PE",
        "tracking_url_template": "https://www.olvacourier.com/Tracking?guia={tracking_number}",
        "description": _("Olva Courier - Peru shipping service"),
        "is_system": True,
    },
    {
        "slug": "courier-guy",
        "name": "The Courier Guy",
        "country_of_operation": "ZA",
        "tracking_url_template": "https://www.thecourierguy.co.za/tracking?waybill={tracking_number}",
        "description": _("The Courier Guy - South Africa shipping service"),
        "is_system": True,
    },
    {
        "slug": "aramex-za",
        "name": "Aramex (ZA)",
        "country_of_operation": "ZA",
        "tracking_url_template": "https://www.aramex.co.za/track?l={tracking_number}",
        "description": _("Aramex (ZA) - South Africa shipping service"),
        "is_system": True,
    },
    {
        "slug": "fastway-za",
        "name": "Fastway (ZA)",
        "country_of_operation": "ZA",
        "tracking_url_template": "https://www.fastway.co.za/our-services/track-your-parcel/?track=1&label={tracking_number}",
        "description": _("Fastway (ZA) - South Africa shipping service"),
        "is_system": True,
    },
    {
        "slug": "dawn-wing",
        "name": "Dawn Wing",
        "country_of_operation": "ZA",
        "tracking_url_template": "https://www.dawnwing.co.za/track?waybill={tracking_number}",
        "description": _("Dawn Wing - South Africa shipping service"),
        "is_system": True,
    },
    {
        "slug": "nipost",
        "name": "NIPOST",
        "country_of_operation": "",
        "tracking_url_template": "https://www.nipost.gov.ng/Track/Track.aspx?item={tracking_number}",
        "description": _("NIPOST - Nigeria shipping service"),
        "is_system": True,
    },
    {
        "slug": "giglogistics",
        "name": "GIG Logistics",
        "country_of_operation": "",
        "tracking_url_template": "https://giglogistics.com/track?ref={tracking_number}",
        "description": _("GIG Logistics - Nigeria shipping service"),
        "is_system": True,
    },
    {
        "slug": "posta-kenya",
        "name": "Posta Kenya",
        "country_of_operation": "",
        "tracking_url_template": "https://www.posta.co.ke/track-and-trace?barCode={tracking_number}",
        "description": _("Posta Kenya - Kenya shipping service"),
        "is_system": True,
    },
    {
        "slug": "g4s-ke",
        "name": "G4S Kenya",
        "country_of_operation": "",
        "tracking_url_template": "https://g4s-delivery.com/track?awb={tracking_number}",
        "description": _("G4S Kenya - Kenya shipping service"),
        "is_system": True,
    },
    {
        "slug": "egypt-post",
        "name": "Egypt Post",
        "country_of_operation": "EG",
        "tracking_url_template": "https://epg.gov.eg/track/?barcode={tracking_number}",
        "description": _("Egypt Post - Egypt shipping service"),
        "is_system": True,
    },
    {
        "slug": "aramex-eg",
        "name": "Aramex (EG)",
        "country_of_operation": "EG",
        "tracking_url_template": "https://www.aramex.com/track/shipments/{tracking_number}",
        "description": _("Aramex (EG) - Egypt shipping service"),
        "is_system": True,
    },
    {
        "slug": "poste-maroc",
        "name": "Barid Al-Maghrib (Poste Maroc)",
        "country_of_operation": "",
        "tracking_url_template": "https://amana-colis.poste.ma/e-trackings?barcodes={tracking_number}",
        "description": _("Barid Al-Maghrib (Poste Maroc) - Morocco shipping service"),
        "is_system": True,
    },
    {
        "slug": "amana",
        "name": "Amana",
        "country_of_operation": "",
        "tracking_url_template": "https://amana-colis.poste.ma/e-trackings?barcodes={tracking_number}",
        "description": _("Amana - Morocco shipping service"),
        "is_system": True,
    },
    {
        "slug": "emirates-post",
        "name": "Emirates Post",
        "country_of_operation": "AE",
        "tracking_url_template": "https://www.emiratespost.ae/track?a={tracking_number}",
        "description": _("Emirates Post - UAE shipping service"),
        "is_system": True,
    },
    {
        "slug": "aramex-ae",
        "name": "Aramex",
        "country_of_operation": "AE",
        "tracking_url_template": "https://www.aramex.com/track/shipments/{tracking_number}",
        "description": _("Aramex - UAE shipping service"),
        "is_system": True,
    },
    {
        "slug": "dhl-ae",
        "name": "DHL Express",
        "country_of_operation": "AE",
        "tracking_url_template": "https://www.dhl.com/global-en/home/tracking/tracking-express.html?tracking-id={tracking_number}",
        "description": _("DHL Express - UAE shipping service"),
        "is_system": True,
    },
    {
        "slug": "spl",
        "name": "Saudi Post (SPL)",
        "country_of_operation": "SA",
        "tracking_url_template": "https://splonline.com.sa/en/shipments/#/track-shipment?shipmentNumber={tracking_number}",
        "description": _("Saudi Post (SPL) - Saudi Arabia shipping service"),
        "is_system": True,
    },
    {
        "slug": "smsa",
        "name": "SMSA Express",
        "country_of_operation": "SA",
        "tracking_url_template": "https://www.smsaexpress.com/track?awb={tracking_number}",
        "description": _("SMSA Express - Saudi Arabia shipping service"),
        "is_system": True,
    },
    {
        "slug": "aramex-sa",
        "name": "Aramex",
        "country_of_operation": "SA",
        "tracking_url_template": "https://www.aramex.com/track/shipments/{tracking_number}",
        "description": _("Aramex - Saudi Arabia shipping service"),
        "is_system": True,
    },
    {
        "slug": "israel-post",
        "name": "Israel Post",
        "country_of_operation": "IL",
        "tracking_url_template": "https://mypost.israelpost.co.il/itemtrace?itemcode={tracking_number}",
        "description": _("Israel Post - Israel shipping service"),
        "is_system": True,
    },
    {
        "slug": "hfd",
        "name": "HFD",
        "country_of_operation": "IL",
        "tracking_url_template": "https://www.hfd.co.il/tracking?waybill={tracking_number}",
        "description": _("HFD - Israel shipping service"),
        "is_system": True,
    },
    {
        "slug": "qatar-post",
        "name": "Qatar Post",
        "country_of_operation": "",
        "tracking_url_template": "https://www.qatarpost.qa/track?barcode={tracking_number}",
        "description": _("Qatar Post - Qatar shipping service"),
        "is_system": True,
    },
    {
        "slug": "kuwait-post",
        "name": "Kuwait Post",
        "country_of_operation": "",
        "tracking_url_template": "https://track.moc.gov.kw/?trackcode={tracking_number}",
        "description": _("Kuwait Post - Kuwait shipping service"),
        "is_system": True,
    },
    {
        "slug": "bahrain-post",
        "name": "Bahrain Post",
        "country_of_operation": "",
        "tracking_url_template": "https://www.bahrain.bh/wps/portal/Portal/trackconsignment?trackno={tracking_number}",
        "description": _("Bahrain Post - Bahrain shipping service"),
        "is_system": True,
    },
]
