"""
NGINX Service for Domain & SSL

Generates NGINX configuration files from Python templates.
Writes to the bind-mounted nginx/conf.d directory so the NGINX
container picks them up on reload.
"""

import logging
import os

logger = logging.getLogger(__name__)

# Path inside the shop/celery container where nginx conf.d is mounted
NGINX_CONF_DIR = os.environ.get("NGINX_CONF_DIR", "/app/nginx_conf")


def write_http_config(domain, server_ip=None):
    """
    Write an HTTP-only NGINX server block for the given domain.
    Includes ACME challenge location for future SSL provisioning.
    """
    server_name = domain if domain else "_"
    config = f"""# Spwig NGINX configuration — generated by domain_ssl
# Domain: {domain or "IP-only"}

server {{
    listen 80;
    server_name {server_name};

    # ACME challenge for Let's Encrypt
    location /.well-known/acme-challenge/ {{
        root /var/www/certbot;
        try_files $uri =404;
    }}

    location /static/ {{
        proxy_pass http://shop:8000;
        proxy_set_header Host $host;
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }}

    location /media/ {{
        alias /var/www/media/;
        expires 30d;
        add_header Cache-Control "public";
        access_log off;
    }}

    location / {{
        proxy_pass http://shop:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
        client_max_body_size 100m;
    }}
}}
"""
    _write_config("default.conf", config)
    logger.info("Wrote HTTP-only NGINX config for %s", domain or "IP")
    return True


def write_ssl_config(domain, ssl_mode="letsencrypt", cert_path="/etc/nginx/certs"):
    """
    Write an HTTPS NGINX server block for the given domain.
    HTTP block redirects to HTTPS with ACME challenge pass-through.

    Args:
        domain: FQDN for the server_name directive (required)
        ssl_mode: SSL mode string — controls OCSP and HSTS behaviour
        cert_path: Path to certificate files inside the NGINX container
    """
    if not domain:
        raise ValueError("Domain is required for SSL configuration")

    # OCSP stapling only works with publicly-trusted CA-signed certs
    skip_ocsp = ssl_mode in ("self_signed", "cloudflare_origin")
    ocsp_block = ""
    if not skip_ocsp:
        ocsp_block = """
    # OCSP stapling
    ssl_stapling on;
    ssl_stapling_verify on;"""

    # HSTS without preload — preload is irreversible and dangerous
    # for merchants who may later switch back to HTTP
    hsts_header = 'Strict-Transport-Security "max-age=63072000; includeSubDomains" always'

    config = f"""# Spwig NGINX configuration — generated by domain_ssl
# Domain: {domain} (SSL)

# HTTP → HTTPS redirect with ACME challenge support
server {{
    listen 80;
    server_name {domain};

    # ACME challenge for certificate renewal
    location /.well-known/acme-challenge/ {{
        root /var/www/certbot;
        try_files $uri =404;
    }}

    location / {{
        return 301 https://$host$request_uri;
    }}
}}

# HTTPS server
server {{
    listen 443 ssl;
    http2 on;
    server_name {domain};

    ssl_certificate {cert_path}/fullchain.pem;
    ssl_certificate_key {cert_path}/privkey.pem;

    # Modern SSL configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;

    # HSTS
    add_header {hsts_header};
{ocsp_block}

    location /static/ {{
        proxy_pass http://shop:8000;
        proxy_set_header Host $host;
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }}

    location /media/ {{
        alias /var/www/media/;
        expires 30d;
        add_header Cache-Control "public";
        access_log off;
    }}

    location / {{
        proxy_pass http://shop:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
        client_max_body_size 100m;
    }}
}}
"""
    _write_config("default.conf", config)
    logger.info("Wrote SSL NGINX config for %s", domain)
    return True


def _write_config(filename, content):
    """Write a config file to the NGINX conf.d directory."""
    os.makedirs(NGINX_CONF_DIR, exist_ok=True)
    filepath = os.path.join(NGINX_CONF_DIR, filename)
    with open(filepath, "w") as f:
        f.write(content)
    return filepath
