# Generated by Django 5.1.4 on 2026-03-05 04:48

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_variant', models.CharField(choices=[('default', 'Default'), ('minimal', 'Minimal'), ('detailed', 'Detailed'), ('compact', 'Compact'), ('featured', 'Featured'), ('custom', 'Custom')], default='default', help_text='Choose how this content is displayed', max_length=20)),
                ('css_classes', models.JSONField(blank=True, default=dict, help_text="Custom CSS classes: {'container': 'my-container', 'title': 'my-title'}")),
                ('layout_config', models.JSONField(blank=True, default=dict, help_text='Layout settings: grid columns, spacing, alignment, etc.')),
                ('style_overrides', models.JSONField(blank=True, default=dict, help_text='Override colors, fonts, spacing for this item')),
                ('responsive_config', models.JSONField(blank=True, default=dict, help_text='Mobile/tablet/desktop specific settings')),
                ('inherit_parent_theme', models.BooleanField(default=True, help_text='Whether to inherit styling from parent category/theme')),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Custom field values defined by the merchant', verbose_name='custom fields')),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='Original customer ID from source platform (WooCommerce, Shopify, etc.)', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, help_text='Business or company name for B2B customers', max_length=200, verbose_name='Company Name')),
                ('tax_number', models.CharField(blank=True, help_text='Business tax identification number or VAT registration number', max_length=50, verbose_name='Tax ID / VAT Number')),
                ('is_business_customer', models.BooleanField(default=False, help_text='Check if this is a business/B2B customer account', verbose_name='Business Customer')),
                ('dashboard_layout', models.CharField(choices=[('default', 'Default Layout'), ('compact', 'Compact View'), ('detailed', 'Detailed View'), ('minimal', 'Minimal View'), ('cards', 'Card Layout')], default='default', help_text='Customer dashboard layout preference', max_length=20)),
                ('show_order_history', models.BooleanField(default=True)),
                ('show_wishlist', models.BooleanField(default=True)),
                ('show_recent_products', models.BooleanField(default=True)),
                ('show_recommendations', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OAuthProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('apple', 'Apple'), ('microsoft', 'Microsoft')], help_text='OAuth provider type', max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=False, help_text='Enable this provider for customer authentication')),
                ('display_name', models.CharField(help_text='Display name shown on login button', max_length=100)),
                ('button_order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('custom_scopes', models.JSONField(blank=True, default=list, help_text='Additional OAuth scopes (JSON array)')),
                ('is_configured', models.BooleanField(default=False, editable=False, help_text='Whether OAuth credentials are configured')),
                ('configuration_notes', models.TextField(blank=True, help_text='Setup notes or troubleshooting information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OAuth Provider Setting',
                'verbose_name_plural': 'OAuth Provider Settings',
                'ordering': ['button_order', 'provider'],
            },
        ),
        migrations.CreateModel(
            name='PreferenceChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the change occurred', verbose_name='Timestamp')),
                ('action', models.CharField(db_index=True, help_text='Description of the change (e.g., "email_marketing.enable")', max_length=100, verbose_name='Action')),
                ('old_value', models.JSONField(default=dict, help_text='Previous state before the change', verbose_name='Old Value')),
                ('new_value', models.JSONField(default=dict, help_text='New state after the change', verbose_name='New Value')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the change was made', null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, default='', help_text='Browser user agent string', max_length=500, verbose_name='User Agent')),
                ('source', models.CharField(choices=[('user', 'User'), ('registration', 'Registration'), ('checkout', 'Checkout'), ('api', 'API'), ('admin', 'Admin'), ('verification', 'Email Verification'), ('unsubscribe', 'Unsubscribe Link'), ('system', 'System')], help_text='Where the change originated from', max_length=20, verbose_name='Source')),
                ('notes', models.TextField(blank=True, help_text='Additional context or notes about the change', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Preference Change Log',
                'verbose_name_plural': 'Preference Change Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', accounts.models.StaffMemberManager()),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, help_text='Master toggle for all email communications', verbose_name='Email enabled')),
                ('sms_enabled', models.BooleanField(default=False, help_text='Master toggle for all SMS communications (opt-in required)', verbose_name='SMS enabled')),
                ('email_transactional', models.BooleanField(default=True, help_text='Order confirmations, shipping updates, account security emails', verbose_name='Transactional emails')),
                ('email_marketing', models.BooleanField(default=False, help_text='Newsletters, promotions, product recommendations (opt-in required)', verbose_name='Marketing emails')),
                ('sms_transactional', models.BooleanField(default=False, help_text='Order and shipping notifications via SMS (opt-in required)', verbose_name='Transactional SMS')),
                ('sms_marketing', models.BooleanField(default=False, help_text='Marketing messages via SMS (opt-in required)', verbose_name='Marketing SMS')),
                ('app_preferences', models.JSONField(blank=True, default=dict, help_text='App-specific communication preferences stored as JSON. Example: {"blog": {"enabled": true, "frequency": "weekly"}, "loyalty": {"points_earned": true, "tier_changes": true}}', verbose_name='App preferences')),
                ('email_verified', models.BooleanField(default=False, help_text='Whether marketing email address has been verified via double opt-in', verbose_name='Email verified')),
                ('email_verified_at', models.DateTimeField(blank=True, help_text='Timestamp when email was verified', null=True, verbose_name='Email verified at')),
                ('sms_verified', models.BooleanField(default=False, help_text='Whether SMS number has been verified', verbose_name='SMS verified')),
                ('sms_verified_at', models.DateTimeField(blank=True, help_text='Timestamp when SMS number was verified', null=True, verbose_name='SMS verified at')),
                ('sms_verification_code', models.CharField(blank=True, default='', help_text='6-digit OTP code for SMS verification', max_length=6, verbose_name='SMS verification code')),
                ('sms_verification_sent_at', models.DateTimeField(blank=True, help_text='When the verification code was sent', null=True, verbose_name='SMS verification sent at')),
                ('sms_verification_attempts', models.PositiveIntegerField(default=0, help_text='Number of failed verification attempts', verbose_name='SMS verification attempts')),
                ('consent_source', models.CharField(choices=[('registration', 'Account Registration'), ('checkout', 'Checkout Process'), ('preference_center', 'Preference Center'), ('api', 'API'), ('admin', 'Admin Override'), ('migration', 'Data Migration')], default='registration', help_text="How the user's consent was obtained", max_length=50, verbose_name='Consent source')),
                ('consent_ip', models.GenericIPAddressField(blank=True, help_text='IP address when consent was given (GDPR requirement)', null=True, verbose_name='Consent IP address')),
                ('consent_user_agent', models.TextField(blank=True, help_text='Browser user agent when consent was given (GDPR requirement)', verbose_name='Consent user agent')),
                ('consent_timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When consent was originally given (GDPR requirement)', verbose_name='Consent timestamp')),
                ('unsubscribe_token', models.CharField(blank=True, help_text='Unique token for one-click unsubscribe links', max_length=64, unique=True, verbose_name='Unsubscribe token')),
                ('language_code', models.CharField(default='en', help_text='Preferred language for communications (ISO 639-1)', max_length=10, verbose_name='Language code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Communication Preference',
                'verbose_name_plural': 'Communication Preferences',
            },
        ),
    ]
