# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('design', '0002_initial'),
        ('migration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='migration_job',
            field=models.ForeignKey(blank=True, help_text='Migration job that imported this customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_customers', to='migration.migrationjob'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='preferred_theme',
            field=models.ForeignKey(blank=True, help_text="Customer's preferred site theme", null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.theme'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preferencechangelog',
            name='preference',
            field=models.ForeignKey(help_text='Communication preference that was changed', on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='accounts.communicationpreference', verbose_name='Preference'),
        ),
        migrations.AddField(
            model_name='preferencechangelog',
            name='user',
            field=models.ForeignKey(help_text='User whose preference was changed', on_delete=django.db.models.deletion.CASCADE, related_name='preference_changes', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='communicationpreference',
            index=models.Index(fields=['user'], name='accounts_co_user_id_1b9f52_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationpreference',
            index=models.Index(fields=['unsubscribe_token'], name='accounts_co_unsubsc_378336_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationpreference',
            index=models.Index(fields=['email_verified', 'email_marketing'], name='accounts_co_email_v_2cb3c6_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationpreference',
            index=models.Index(fields=['sms_verified', 'sms_marketing'], name='accounts_co_sms_ver_91918b_idx'),
        ),
        migrations.AddIndex(
            model_name='preferencechangelog',
            index=models.Index(fields=['user', '-timestamp'], name='pref_log_user_time'),
        ),
        migrations.AddIndex(
            model_name='preferencechangelog',
            index=models.Index(fields=['action', '-timestamp'], name='pref_log_action_time'),
        ),
        migrations.AddIndex(
            model_name='preferencechangelog',
            index=models.Index(fields=['preference', '-timestamp'], name='pref_log_pref_time'),
        ),
        migrations.AddIndex(
            model_name='preferencechangelog',
            index=models.Index(fields=['-timestamp'], name='pref_log_time'),
        ),
    ]
