[program:spwig]
command=/opt/venv/bin/gunicorn core.asgi:application --bind 0.0.0.0:8000 --workers %(ENV_GUNICORN_WORKERS)s --worker-class uvicorn.workers.UvicornWorker
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
user=spwig
priority=10
startsecs=5
stopwaitsecs=30
environment=PYTHONUNBUFFERED="1",PATH="/opt/venv/bin:%(ENV_PATH)s"
