[program:postfix]
command=/usr/sbin/postfix -c /etc/postfix start-fg
autostart=true
autorestart=true
stdout_logfile=/app/logs/postfix-stdout.log
stderr_logfile=/app/logs/postfix-stderr.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile_backups=3
user=root
priority=1
startsecs=5
stopwaitsecs=10
