# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_user_configured', models.BooleanField(default=False, help_text='Admin user account has been properly configured')),
                ('site_info_completed', models.BooleanField(default=False, help_text='Basic site information (name, URL, description) completed')),
                ('contact_info_completed', models.BooleanField(default=False, help_text='Contact information (emails, phone) completed')),
                ('business_address_completed', models.BooleanField(default=False, help_text='Business address information completed')),
                ('currency_locale_completed', models.BooleanField(default=False, help_text='Currency and locale settings configured')),
                ('payment_methods_configured', models.BooleanField(default=False, help_text='Payment provider setup has been acknowledged')),
                ('ecommerce_settings_completed', models.BooleanField(default=False, help_text='Core e-commerce settings have been configured')),
                ('favicon_uploaded', models.BooleanField(default=False, help_text='Site favicon has been uploaded')),
                ('seo_settings_completed', models.BooleanField(default=False, help_text='SEO meta tags have been configured')),
                ('social_media_completed', models.BooleanField(default=False, help_text='Social media links have been added')),
                ('email_settings_completed', models.BooleanField(default=False, help_text='Email notification settings configured')),
                ('setup_started_at', models.DateTimeField(blank=True, help_text='When the setup wizard was first started', null=True)),
                ('setup_completed_at', models.DateTimeField(blank=True, help_text='When the essential setup was completed', null=True)),
                ('last_step_completed', models.CharField(blank=True, help_text='Last setup step that was completed', max_length=50)),
                ('wizard_skipped', models.BooleanField(default=False, help_text='User chose to skip the setup wizard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('setup_completed_by', models.ForeignKey(blank=True, help_text='User who completed the setup process', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_completed', to=settings.AUTH_USER_MODEL)),
                ('setup_started_by', models.ForeignKey(blank=True, help_text='User who started the setup process', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Setup Progress',
                'verbose_name_plural': 'Setup Progress',
            },
        ),
    ]
