# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('component_updates', '0002_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOProviderAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_key', models.CharField(blank=True, help_text="Built-in provider key (e.g., 'deterministic'). Used when component is null.", max_length=100, verbose_name='Provider Key')),
                ('name', models.CharField(help_text='Friendly name for this provider account', max_length=255, verbose_name='Account Name')),
                ('credentials', models.BinaryField(blank=True, help_text='Encrypted API credentials for this provider', null=True, verbose_name='Encrypted Credentials')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this provider account is active', verbose_name='Active')),
                ('is_primary', models.BooleanField(default=False, help_text='Use this provider as primary source for SEO generation', verbose_name='Primary Provider')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Priority for fallback chain (lower = higher priority)', verbose_name='Priority')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Provider-specific settings and configuration', verbose_name='Provider Settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(blank=True, help_text='SEO provider component from update system (null for built-in)', limit_choices_to={'component_type': 'seo_generator_provider'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seo_provider_accounts', to='component_updates.componentregistry', verbose_name='Provider Component')),
                ('site', models.ForeignKey(default=1, help_text='Site this provider account belongs to', on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'SEO Provider Account',
                'verbose_name_plural': 'SEO Provider Accounts',
                'ordering': ['-is_primary', 'priority', 'name'],
                'indexes': [models.Index(fields=['site', 'is_active'], name='seo_generat_site_id_b1ba79_idx'), models.Index(fields=['is_primary'], name='seo_generat_is_prim_18e22b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('site', 'is_primary'), name='unique_primary_seo_provider')],
            },
        ),
    ]
