# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='image_asset',
            field=models.ForeignKey(blank=True, help_text='Category image from media library', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_category_images', to='media_library.mediaasset'),
        ),
    ]
