# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_initial'),
        ('component_updates', '0002_initial'),
        ('media_library', '0002_initial'),
        ('migration', '0001_initial'),
        ('page_builder', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='migration_job',
            field=models.ForeignKey(blank=True, help_text='Migration job that imported this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_blog_categories', to='migration.migrationjob'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.blogcategory'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_page',
            field=models.OneToOneField(blank=True, help_text='Page containing the post content layout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_post', to='page_builder.page'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image',
            field=models.ForeignKey(blank=True, help_text='Featured image from media library', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_featured_images', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='migration_job',
            field=models.ForeignKey(blank=True, help_text='Migration job that imported this post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_blog_posts', to='migration.migrationjob'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Open Graph image for social sharing (defaults to featured image)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_og_images', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='blogpostautoshare',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_shares', to='blog.blogpost'),
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogsubscriber',
            name='subscribed_categories',
            field=models.ManyToManyField(blank=True, help_text='Categories to receive notifications for (empty = all)', related_name='subscribers', to='blog.blogcategory'),
        ),
        migrations.AddField(
            model_name='blogsubscriber',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='migration_job',
            field=models.ForeignKey(blank=True, help_text='Migration job that imported this tag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_blog_tags', to='migration.migrationjob'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.blogtag'),
        ),
        migrations.AddField(
            model_name='socialconnectoraccount',
            name='component',
            field=models.ForeignKey(blank=True, help_text='Installed social connector component from registry', null=True, on_delete=django.db.models.deletion.SET_NULL, to='component_updates.componentregistry'),
        ),
        migrations.AddField(
            model_name='socialconnectoraccount',
            name='connected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_social_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialconnectoraccount',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='site'),
        ),
        migrations.AddField(
            model_name='blogpostautoshare',
            name='social_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_shares', to='blog.socialconnectoraccount'),
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['slug'], name='blog_blogca_slug_465e50_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['is_active'], name='blog_blogca_is_acti_1e2171_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['sort_order'], name='blog_blogca_sort_or_3abb74_idx'),
        ),
        migrations.AddIndex(
            model_name='blogsubscriber',
            index=models.Index(fields=['email'], name='blog_blogsu_email_e31da4_idx'),
        ),
        migrations.AddIndex(
            model_name='blogsubscriber',
            index=models.Index(fields=['verification_status', 'is_active'], name='blog_blogsu_verific_0d3989_idx'),
        ),
        migrations.AddIndex(
            model_name='blogsubscriber',
            index=models.Index(fields=['notification_frequency', 'is_active'], name='blog_blogsu_notific_74e637_idx'),
        ),
        migrations.AddIndex(
            model_name='blogsubscriber',
            index=models.Index(fields=['unsubscribe_token'], name='blog_blogsu_unsubsc_d9afca_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='blog_blogpo_slug_361555_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', '-published_at'], name='blog_blogpo_status_c0e87f_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_featured'], name='blog_blogpo_is_feat_aa3e07_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['-is_pinned', '-published_at'], name='blog_blogpo_is_pinn_7f1429_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['category', 'status'], name='blog_blogpo_categor_2e8dab_idx'),
        ),
        migrations.AddIndex(
            model_name='socialconnectoraccount',
            index=models.Index(fields=['site', 'provider_key', 'status'], name='blog_social_site_id_f9f028_idx'),
        ),
        migrations.AddIndex(
            model_name='socialconnectoraccount',
            index=models.Index(fields=['access_token_expires_at'], name='blog_social_access__b10399_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialconnectoraccount',
            constraint=models.UniqueConstraint(fields=('site', 'provider_key', 'platform_account_id'), name='unique_social_connector_account'),
        ),
        migrations.AddIndex(
            model_name='blogpostautoshare',
            index=models.Index(fields=['status', 'scheduled_at'], name='blog_blogpo_status_e63d84_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpostautoshare',
            index=models.Index(fields=['status', 'next_retry_at'], name='blog_blogpo_status_5845a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='blogpostautoshare',
            constraint=models.UniqueConstraint(fields=('post', 'social_account'), name='unique_post_social_account'),
        ),
    ]
