# Generated by Django 5.1.4 on 2026-03-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='page_template',
            field=models.CharField(blank=True, choices=[('', 'Use site default'), ('classic', 'Classic'), ('minimal', 'Minimal'), ('magazine', 'Magazine'), ('full_width', 'Full Width')], default='', help_text='Override the site-wide blog post template for this post.', max_length=30, verbose_name='Post Template'),
        ),
    ]
