# Generated by Django 5.2.17 on 2026-08-25 03:49

import django.db.models.deletion
import email_marketing.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('email_system', '0009_alter_emailtemplate_template_type'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this object has been soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this object was soft deleted', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=200, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('kind', models.CharField(choices=[('dynamic', 'Dynamic (rules)'), ('static', 'Static (fixed list)')], default='dynamic', max_length=16, verbose_name='kind')),
                ('rules', models.JSONField(blank=True, default=dict, help_text='Rule tree evaluated for dynamic segments.', verbose_name='rules')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('cached_count', models.PositiveIntegerField(default=0, verbose_name='cached member count')),
                ('last_built_at', models.DateTimeField(blank=True, null=True, verbose_name='last built at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_segments', to='sites.site', verbose_name='site')),
            ],
            options={
                'verbose_name': 'segment',
                'verbose_name_plural': 'segments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this object has been soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this object was soft deleted', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('preview_text', models.CharField(blank=True, help_text='Preheader shown after the subject in most inboxes.', max_length=255, verbose_name='preview text')),
                ('message_type', models.CharField(choices=[('newsletter', 'Newsletter'), ('promotional_offers', 'Promotional offers'), ('product_recommendations', 'Product recommendations'), ('back_in_stock', 'Back in stock')], default='newsletter', help_text='Consent category this campaign is sent under.', max_length=32, verbose_name='message type')),
                ('content_tree', models.JSONField(blank=True, default=dict, help_text='Block tree authored by the visual builder (reserved).', verbose_name='content tree')),
                ('html_content', models.TextField(blank=True, help_text='MJML source rendered to email-safe HTML at send time.', verbose_name='MJML content')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused'), ('failed', 'Failed')], db_index=True, default='draft', max_length=16, verbose_name='status')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='scheduled for')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='total recipients')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='sent')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='failed')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='skipped')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('from_account', models.ForeignKey(blank=True, help_text='Sending account; the default account is used when unset.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='email_system.emailaccount', verbose_name='from account')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to='sites.site', verbose_name='site')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='email_marketing.segment', verbose_name='segment')),
            ],
            options={
                'verbose_name': 'campaign',
                'verbose_name_plural': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this object has been soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this object was soft deleted', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email')),
                ('status', models.CharField(choices=[('active', 'Active'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('pending', 'Pending confirmation')], db_index=True, default='active', max_length=16, verbose_name='status')),
                ('source', models.CharField(choices=[('signup', 'Storefront signup'), ('import', 'Import'), ('order', 'Order'), ('manual', 'Added manually'), ('api', 'API')], default='manual', max_length=16, verbose_name='source')),
                ('language_code', models.CharField(blank=True, help_text="Preferred language for campaigns, e.g. 'en', 'es'.", max_length=10, verbose_name='language')),
                ('marketing_opt_in', models.BooleanField(default=False, help_text='Whether an anonymous subscriber has opted into marketing email.', verbose_name='marketing opt-in')),
                ('marketing_verified', models.BooleanField(default=False, help_text='Double opt-in confirmed (anonymous subscribers).', verbose_name='opt-in verified')),
                ('verification_token', models.CharField(blank=True, max_length=64, verbose_name='verification token')),
                ('consent_source', models.CharField(blank=True, max_length=32, verbose_name='consent source')),
                ('consent_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='consent IP')),
                ('consent_user_agent', models.TextField(blank=True, verbose_name='consent user agent')),
                ('consent_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='consent timestamp')),
                ('unsubscribe_token', models.CharField(default=email_marketing.models.generate_token, editable=False, max_length=64, unique=True, verbose_name='unsubscribe token')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='last sent at')),
                ('last_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='last opened at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_subscribers', to='sites.site', verbose_name='site')),
                ('user', models.ForeignKey(blank=True, help_text='The customer account, when this subscriber is a registered user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_subscriber', to=settings.AUTH_USER_MODEL, verbose_name='linked user')),
            ],
            options={
                'verbose_name': 'subscriber',
                'verbose_name_plural': 'subscribers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='segment',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Explicit membership for static segments.', related_name='segments', to='email_marketing.subscriber', verbose_name='members'),
        ),
        migrations.CreateModel(
            name='CampaignSend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant', models.CharField(blank=True, max_length=32, verbose_name='A/B variant')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=16, verbose_name='status')),
                ('skip_reason', models.CharField(blank=True, max_length=100, verbose_name='skip reason')),
                ('opened', models.BooleanField(default=False, verbose_name='opened')),
                ('clicked', models.BooleanField(default=False, verbose_name='clicked')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='opened at')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='clicked at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='email_marketing.campaign', verbose_name='campaign')),
                ('outbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_send', to='email_system.emailoutbox', verbose_name='outbox entry')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_sends', to='email_marketing.subscriber', verbose_name='subscriber')),
            ],
            options={
                'verbose_name': 'campaign send',
                'verbose_name_plural': 'campaign sends',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['site', 'status'], name='email_marke_site_id_799e40_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'scheduled_for'], name='email_marke_status_3e1f67_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['site', 'status'], name='email_marke_site_id_1e6524_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['unsubscribe_token'], name='email_marke_unsubsc_f508ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.UniqueConstraint(fields=('site', 'email'), name='uniq_subscriber_site_email'),
        ),
        migrations.AddConstraint(
            model_name='segment',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='uniq_segment_site_slug'),
        ),
        migrations.AddIndex(
            model_name='campaignsend',
            index=models.Index(fields=['campaign', 'status'], name='email_marke_campaig_df1dbe_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignsend',
            constraint=models.UniqueConstraint(fields=('campaign', 'subscriber'), name='uniq_campaignsend_campaign_subscriber'),
        ),
    ]
