# Generated by Django 5.2.17 on 2026-08-25 05:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignsend',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=16, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='CampaignBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_type', models.CharField(max_length=64, verbose_name='block type')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='content')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='email_marketing.campaign', verbose_name='campaign')),
            ],
            options={
                'verbose_name': 'campaign block',
                'verbose_name_plural': 'campaign blocks',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['campaign', 'order'], name='email_marke_campaig_ddc3df_idx')],
            },
        ),
    ]
