# Generated by Django 5.2.17 on 2026-08-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_marketing', '0002_alter_campaignsend_status_campaignblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('broadcast', 'Broadcast'), ('recurring', 'Recurring')], db_index=True, default='broadcast', help_text='Broadcast sends once; recurring sends on a schedule.', max_length=16, verbose_name='campaign type'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='last_content_sent_at',
            field=models.DateTimeField(blank=True, help_text="Watermark for 'since last send' dynamic blocks — e.g. a Blog Posts block set to only include posts published after this time. Updated each time the campaign (or a recurring occurrence) finishes sending.", null=True, verbose_name='last content sent at'),
        ),
    ]
