# Generated by Django 5.2.17 on 2026-08-26 02:44

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_marketing', '0003_campaign_campaign_type_campaign_last_content_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='For a recurring occurrence, the template it was spawned from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='email_marketing.campaign', verbose_name='recurring template'),
        ),
        migrations.CreateModel(
            name='CampaignSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cadence', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=16, verbose_name='cadence')),
                ('interval', models.PositiveSmallIntegerField(default=1, help_text='Every N cadence units (e.g. every 2 weeks).', verbose_name='interval')),
                ('weekday', models.PositiveSmallIntegerField(blank=True, help_text='0=Monday … 6=Sunday (weekly).', null=True, verbose_name='weekday')),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='1–28 (monthly).', null=True, verbose_name='day of month')),
                ('send_time', models.TimeField(default=datetime.time(9, 0), verbose_name='send time')),
                ('timezone', models.CharField(default='UTC', help_text='IANA name, e.g. Europe/London.', max_length=64, verbose_name='timezone')),
                ('freshness_policy', models.CharField(choices=[('skip', 'Skip this send'), ('send_partial', 'Send anyway (omit empty blocks)'), ('hold', "Hold and send late when there's new content")], default='skip', max_length=16, verbose_name='no-new-content policy')),
                ('hold_days', models.PositiveSmallIntegerField(default=3, help_text='For the hold policy: how long to wait for new content before giving up.', verbose_name='hold window (days)')),
                ('hold_until', models.DateTimeField(blank=True, null=True, verbose_name='holding until')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='next run at')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='last run at')),
                ('occurrences_sent', models.PositiveIntegerField(default=0, verbose_name='occurrences sent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='email_marketing.campaign', verbose_name='campaign')),
            ],
            options={
                'verbose_name': 'campaign schedule',
                'verbose_name_plural': 'campaign schedules',
                'indexes': [models.Index(fields=['is_active', 'next_run_at'], name='email_marke_is_acti_8a286b_idx')],
            },
        ),
    ]
