# Generated by Django 5.2.17 on 2026-08-26 05:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_marketing', '0004_campaign_parent_campaignschedule'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this object has been soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this object was soft deleted', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('trigger_event', models.CharField(choices=[('customer_signup', 'Customer signs up'), ('order_placed', 'Order is placed'), ('first_order', 'First order is placed')], db_index=True, help_text='The lifecycle event that starts this journey for a subscriber.', max_length=32, verbose_name='trigger')),
                ('once_per_subscriber', models.BooleanField(default=True, help_text='Enroll each subscriber at most once, ever (e.g. a welcome series).', verbose_name='once per subscriber')),
                ('cooldown_days', models.PositiveSmallIntegerField(default=0, help_text='When re-enrollment is allowed, the minimum days between enrollments.', verbose_name='re-enrollment cooldown (days)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused')], db_index=True, default='draft', max_length=16, verbose_name='status')),
                ('enrolled_count', models.PositiveIntegerField(default=0, verbose_name='enrolled')),
                ('completed_count', models.PositiveIntegerField(default=0, verbose_name='completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_journeys', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_journeys', to='sites.site', verbose_name='site')),
                ('target_segment', models.ForeignKey(blank=True, help_text='If set, only subscribers in this segment are enrolled.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journeys', to='email_marketing.segment', verbose_name='only for segment')),
            ],
            options={
                'verbose_name': 'journey',
                'verbose_name_plural': 'journeys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JourneyEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_step', models.PositiveSmallIntegerField(default=0, verbose_name='current step')),
                ('next_step_at', models.DateTimeField(db_index=True, help_text='When the current step is due.', verbose_name='next step at')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=16, verbose_name='status')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='email_marketing.journey', verbose_name='journey')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_enrollments', to='email_marketing.subscriber', verbose_name='subscriber')),
            ],
            options={
                'verbose_name': 'journey enrollment',
                'verbose_name_plural': 'journey enrollments',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='JourneyStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='order')),
                ('delay_value', models.PositiveSmallIntegerField(default=0, help_text='How long to wait before this step, measured from the previous step.', verbose_name='wait')),
                ('delay_unit', models.CharField(choices=[('hours', 'hours'), ('days', 'days')], default='days', max_length=8, verbose_name='wait unit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('campaign', models.ForeignKey(help_text='The email to send at this step (designed in the visual builder).', on_delete=django.db.models.deletion.PROTECT, related_name='journey_steps', to='email_marketing.campaign', verbose_name='email')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='email_marketing.journey', verbose_name='journey')),
            ],
            options={
                'verbose_name': 'journey step',
                'verbose_name_plural': 'journey steps',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['site', 'status', 'trigger_event'], name='email_marke_site_id_c49fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='journeyenrollment',
            index=models.Index(fields=['status', 'next_step_at'], name='email_marke_status_48af25_idx'),
        ),
        migrations.AddIndex(
            model_name='journeyenrollment',
            index=models.Index(fields=['journey', 'subscriber'], name='email_marke_journey_dd5835_idx'),
        ),
        migrations.AddIndex(
            model_name='journeystep',
            index=models.Index(fields=['journey', 'order'], name='email_marke_journey_802ebf_idx'),
        ),
    ]
