# Generated by Django 5.2.17 on 2026-08-26 09:50, then hand-edited to reorder the
# operations around a data migration that converts each linear JourneyStep chain
# into an equivalent JourneyNode/JourneyEdge graph before the old model is dropped.

import uuid

import django.db.models.deletion
from django.db import migrations, models


def _linear_steps_to_graph(apps, schema_editor):
    """Convert every journey's ordered JourneyStep chain into a node graph.

    A journey of steps ``[(wait0, send0), (wait1, send1), …]`` becomes
    ``entry → wait0 → send0 → wait1 → send1 → … → exit`` joined by ``default``
    edges. In-flight enrollments (``current_step = N``) are re-pointed at the
    wait node for step N, preserving their pending ``next_step_at`` exactly.
    """
    Journey = apps.get_model("email_marketing", "Journey")
    JourneyStep = apps.get_model("email_marketing", "JourneyStep")
    JourneyNode = apps.get_model("email_marketing", "JourneyNode")
    JourneyEdge = apps.get_model("email_marketing", "JourneyEdge")
    JourneyEnrollment = apps.get_model("email_marketing", "JourneyEnrollment")

    for journey in Journey.objects.all():
        steps = list(JourneyStep.objects.filter(journey=journey).order_by("order"))

        entry = JourneyNode.objects.create(
            journey=journey, node_type="entry", pos_x=200, pos_y=40, config={}
        )
        prev = entry
        row = 1
        # The wait node that gates each step, indexed by the step's position, so
        # in-flight enrollments can be re-pointed at the right pause.
        wait_by_index = {}
        for i, step in enumerate(steps):
            wait = JourneyNode.objects.create(
                journey=journey,
                node_type="wait_delay",
                pos_x=200,
                pos_y=40 + row * 120,
                config={"value": step.delay_value, "unit": step.delay_unit},
            )
            wait_by_index[i] = wait
            JourneyEdge.objects.create(
                journey=journey, from_node=prev, to_node=wait, branch="default"
            )
            row += 1

            send = JourneyNode.objects.create(
                journey=journey,
                node_type="send_email",
                pos_x=200,
                pos_y=40 + row * 120,
                config={"campaign_id": str(step.campaign_id)},
            )
            JourneyEdge.objects.create(
                journey=journey, from_node=wait, to_node=send, branch="default"
            )
            prev = send
            row += 1

        exit_node = JourneyNode.objects.create(
            journey=journey, node_type="exit", pos_x=200, pos_y=40 + row * 120, config={}
        )
        JourneyEdge.objects.create(
            journey=journey, from_node=prev, to_node=exit_node, branch="default"
        )

        # Re-point active enrollments at the wait node for their pending step.
        for enr in JourneyEnrollment.objects.filter(journey=journey):
            target = wait_by_index.get(enr.current_step, exit_node)
            enr.current_node = target
            enr.save(update_fields=["current_node"])


class Migration(migrations.Migration):

    dependencies = [
        ("email_marketing", "0005_journey_journeyenrollment_journeystep_and_more"),
    ]

    operations = [
        # 1. Build the new graph tables + the enrollment pointer, keeping the old
        #    JourneyStep / current_step columns in place for the data migration.
        migrations.CreateModel(
            name="JourneyNode",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("node_type", models.CharField(choices=[("entry", "Entry"), ("send_email", "Send email"), ("wait_delay", "Wait"), ("branch", "Branch"), ("exit", "Exit")], db_index=True, max_length=16, verbose_name="type")),
                ("pos_x", models.IntegerField(default=0, verbose_name="canvas x")),
                ("pos_y", models.IntegerField(default=0, verbose_name="canvas y")),
                ("config", models.JSONField(blank=True, default=dict, help_text="Node-type-specific settings (campaign, wait, branch condition).", verbose_name="configuration")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("journey", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="nodes", to="email_marketing.journey", verbose_name="journey")),
            ],
            options={
                "verbose_name": "journey node",
                "verbose_name_plural": "journey nodes",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="JourneyEdge",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("branch", models.CharField(choices=[("default", "Default"), ("yes", "Yes"), ("no", "No")], default="default", max_length=8, verbose_name="path")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("journey", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="edges", to="email_marketing.journey", verbose_name="journey")),
                ("from_node", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="out_edges", to="email_marketing.journeynode", verbose_name="from")),
                ("to_node", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="in_edges", to="email_marketing.journeynode", verbose_name="to")),
            ],
            options={
                "verbose_name": "journey edge",
                "verbose_name_plural": "journey edges",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="journeyenrollment",
            name="current_node",
            field=models.ForeignKey(blank=True, help_text="The node the subscriber is currently sitting at.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="enrollments", to="email_marketing.journeynode", verbose_name="current node"),
        ),
        migrations.AlterField(
            model_name="journeyenrollment",
            name="next_step_at",
            field=models.DateTimeField(db_index=True, help_text="When the current node is due to run.", verbose_name="next step at"),
        ),
        migrations.AddIndex(
            model_name="journeynode",
            index=models.Index(fields=["journey", "node_type"], name="email_marke_journey_8f35c8_idx"),
        ),
        migrations.AddIndex(
            model_name="journeyedge",
            index=models.Index(fields=["journey"], name="email_marke_journey_53dc37_idx"),
        ),
        migrations.AddIndex(
            model_name="journeyedge",
            index=models.Index(fields=["from_node", "branch"], name="email_marke_from_no_b39010_idx"),
        ),
        # 2. Convert existing linear journeys → graphs (reads JourneyStep + current_step).
        migrations.RunPython(_linear_steps_to_graph, migrations.RunPython.noop),
        # 3. Drop the old linear model + column now that data has moved.
        migrations.RemoveField(
            model_name="journeyenrollment",
            name="current_step",
        ),
        migrations.DeleteModel(
            name="JourneyStep",
        ),
    ]
