# Generated by Django 5.2.17 on 2026-08-27 01:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_marketing', '0006_remove_journeyenrollment_current_step_and_more'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('slug', models.SlugField(max_length=60, verbose_name='slug')),
                ('color', models.CharField(blank=True, default='', help_text='Optional hex colour for the tag chip, e.g. #2563eb.', max_length=7, verbose_name='colour')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_tags', to='sites.site', verbose_name='site')),
            ],
            options={
                'verbose_name': 'subscriber tag',
                'verbose_name_plural': 'subscriber tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='subscriber',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Merchant-defined labels for organising and segmenting subscribers.', related_name='subscribers', to='email_marketing.subscribertag', verbose_name='tags'),
        ),
        migrations.AddConstraint(
            model_name='subscribertag',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='uniq_subscribertag_site_slug'),
        ),
    ]
