# Generated by Django 5.2.17 on 2026-08-27 03:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_marketing', '0008_subscriber_first_name_subscriber_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_type', models.CharField(choices=[('subject', 'Subject line'), ('content', 'Content')], default='subject', max_length=16, verbose_name='what to test')),
                ('winner_metric', models.CharField(choices=[('opens', 'Open rate'), ('clicks', 'Click rate')], default='opens', max_length=16, verbose_name='winner by')),
                ('sample_percent', models.PositiveSmallIntegerField(default=20, help_text='Share of the audience used for the test (split evenly across variants). The rest receives the winner. 100 = pure split test, no holdout.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)], verbose_name='test sample %')),
                ('test_window_hours', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)], verbose_name='test window (hours)')),
                ('auto_send_winner', models.BooleanField(default=True, verbose_name='auto-send winner')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('testing', 'Testing'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=16, verbose_name='status')),
                ('decide_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='decide at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decided at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ab_test', to='email_marketing.campaign', verbose_name='campaign')),
            ],
            options={
                'verbose_name': 'A/B test',
                'verbose_name_plural': 'A/B tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ABVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=4, verbose_name='label')),
                ('recipients', models.PositiveIntegerField(default=0, verbose_name='recipients')),
                ('opened', models.PositiveIntegerField(default=0, verbose_name='opened')),
                ('clicked', models.PositiveIntegerField(default=0, verbose_name='clicked')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('ab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='email_marketing.abtest', verbose_name='A/B test')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ab_variant', to='email_marketing.campaign', verbose_name='variant campaign')),
            ],
            options={
                'verbose_name': 'A/B variant',
                'verbose_name_plural': 'A/B variants',
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='abtest',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='email_marketing.abvariant', verbose_name='winner'),
        ),
        migrations.AddConstraint(
            model_name='abvariant',
            constraint=models.UniqueConstraint(fields=('ab_test', 'label'), name='uniq_abvariant_test_label'),
        ),
        migrations.AddIndex(
            model_name='abtest',
            index=models.Index(fields=['status', 'decide_at'], name='email_marke_status_277af3_idx'),
        ),
    ]
