# Generated by Django 5.2.17 on 2026-08-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_marketing', '0009_abtest_abvariant_abtest_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abtest',
            name='winner_confidence',
            field=models.FloatField(blank=True, help_text='Statistical confidence (0–1) that the winner beat the runner-up.', null=True, verbose_name='winner confidence'),
        ),
    ]
