# Generated by Django 5.2.17 on 2026-08-27 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_marketing', '0010_abtest_winner_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignschedule',
            name='ab_auto_send_winner',
            field=models.BooleanField(default=True, verbose_name='A/B auto-send winner'),
        ),
        migrations.AddField(
            model_name='campaignschedule',
            name='ab_sample_percent',
            field=models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)], verbose_name='A/B test sample %'),
        ),
        migrations.AddField(
            model_name='campaignschedule',
            name='ab_test_subjects',
            field=models.JSONField(blank=True, default=list, verbose_name='A/B subject lines'),
        ),
        migrations.AddField(
            model_name='campaignschedule',
            name='ab_test_window_hours',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)], verbose_name='A/B test window (hours)'),
        ),
        migrations.AddField(
            model_name='campaignschedule',
            name='ab_winner_metric',
            field=models.CharField(choices=[('opens', 'Open rate'), ('clicks', 'Click rate')], default='opens', max_length=16, verbose_name='A/B winner metric'),
        ),
    ]
