# Generated by Django 5.2.17 on 2026-08-27 07:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_marketing', '0011_campaignschedule_ab_auto_send_winner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyStepSend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant', models.CharField(max_length=4, verbose_name='variant')),
                ('outbox_id', models.UUIDField(db_index=True, verbose_name='outbox id')),
                ('opened', models.BooleanField(default=False, verbose_name='opened')),
                ('clicked', models.BooleanField(default=False, verbose_name='clicked')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='opened at')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='clicked at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_sends', to='email_marketing.journeyenrollment', verbose_name='enrollment')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_sends', to='email_marketing.journeynode', verbose_name='send node')),
            ],
            options={
                'verbose_name': 'journey step send',
                'verbose_name_plural': 'journey step sends',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['node', 'variant'], name='email_marke_node_id_0f6f84_idx')],
            },
        ),
    ]
