# Generated by Django 5.2.17 on 2026-08-28 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_marketing', '0012_journeystepsend'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppressionEntry',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this object has been soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this object was soft deleted', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email')),
                ('reason', models.CharField(choices=[('hard_bounce', 'Hard bounce'), ('complaint', 'Spam complaint'), ('soft_bounce', 'Repeated soft bounces'), ('manual', 'Manually blocked')], max_length=16, verbose_name='reason')),
                ('source', models.CharField(choices=[('smtp_reject', 'Rejected at send'), ('gateway_poll', 'Mail gateway'), ('webhook', 'Provider webhook'), ('manual', 'Added manually')], default='manual', max_length=16, verbose_name='source')),
                ('detail', models.TextField(blank=True, help_text='Bounce reason or note explaining the suppression.', verbose_name='detail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_suppressions', to='sites.site', verbose_name='site')),
            ],
            options={
                'verbose_name': 'suppressed address',
                'verbose_name_plural': 'suppressed addresses',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('site', 'email'), name='uniq_suppression_site_email')],
            },
        ),
    ]
