# Generated by Django 5.2.17 on 2026-08-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_marketing', '0013_suppressionentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsend',
            name='bounce_type',
            field=models.CharField(blank=True, max_length=16, verbose_name='bounce type'),
        ),
        migrations.AddField(
            model_name='campaignsend',
            name='bounced',
            field=models.BooleanField(default=False, verbose_name='bounced'),
        ),
        migrations.AddField(
            model_name='campaignsend',
            name='bounced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='bounced at'),
        ),
        migrations.AddField(
            model_name='campaignsend',
            name='complained',
            field=models.BooleanField(default=False, verbose_name='complained'),
        ),
        migrations.AddField(
            model_name='campaignsend',
            name='complained_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='complained at'),
        ),
    ]
