# Generated by Django 5.2.17 on 2026-08-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_marketing', '0014_campaignsend_bounce_type_campaignsend_bounced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeyenrollment',
            name='context',
            field=models.JSONField(blank=True, default=dict, verbose_name='trigger context'),
        ),
        migrations.AddField(
            model_name='journeyenrollment',
            name='trigger_ref',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='trigger reference'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='trigger_event',
            field=models.CharField(choices=[('customer_signup', 'Customer signs up'), ('order_placed', 'Order is placed'), ('first_order', 'First order is placed'), ('cart_abandoned', 'Cart abandoned'), ('win_back', 'Customer lapsed (win-back)'), ('order_delivered', 'Order delivered'), ('back_in_stock', 'Product back in stock')], db_index=True, help_text='The lifecycle event that starts this journey for a subscriber.', max_length=32, verbose_name='trigger'),
        ),
        migrations.AddIndex(
            model_name='journeyenrollment',
            index=models.Index(fields=['trigger_ref', 'status'], name='email_marke_trigger_640364_idx'),
        ),
    ]
