# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialSharingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_on_products', models.BooleanField(default=True, help_text='Automatically show share buttons on product detail pages', verbose_name='Enable on Products')),
                ('enable_on_categories', models.BooleanField(default=False, help_text='Automatically show share buttons on category pages', verbose_name='Enable on Categories')),
                ('enable_on_blog_posts', models.BooleanField(default=True, help_text='Automatically show share buttons on blog post pages', verbose_name='Enable on Blog Posts')),
                ('enable_on_pages', models.BooleanField(default=False, help_text='Automatically show share buttons on custom pages', verbose_name='Enable on Custom Pages')),
                ('placement_position', models.CharField(choices=[('above_content', 'Above Content'), ('below_content', 'Below Content'), ('sidebar', 'Sidebar'), ('floating', 'Floating (sticky)')], default='below_content', help_text='Where to display share buttons on the page', max_length=20, verbose_name='Placement Position')),
                ('button_style', models.CharField(choices=[('icon_only', 'Icon Only'), ('icon_label', 'Icon + Label'), ('label_only', 'Label Only')], default='icon_only', help_text='How share buttons are displayed', max_length=20, verbose_name='Button Style')),
                ('button_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', help_text='Size of the share buttons', max_length=10, verbose_name='Button Size')),
                ('layout_direction', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='horizontal', help_text='Arrange share buttons horizontally or vertically', max_length=12, verbose_name='Layout Direction')),
                ('show_title', models.BooleanField(default=True, help_text="Show the 'Share' heading above the buttons", verbose_name='Show Title')),
                ('mobile_visibility', models.CharField(choices=[('show', 'Always Show'), ('hide', 'Hide on Mobile'), ('mobile_only', 'Mobile Only')], default='show', help_text='Control whether share buttons appear on mobile devices', max_length=12, verbose_name='Mobile Visibility')),
                ('widget_slug', models.CharField(default='social_share_buttons', help_text='Slug of the widget package to use for rendering', max_length=100, verbose_name='Widget Slug')),
                ('default_config', models.JSONField(blank=True, default=dict, help_text='Override default widget configuration (display_style, button_size, etc.)', verbose_name='Default Widget Configuration')),
                ('enabled_platforms', models.JSONField(blank=True, default=list, help_text='List of enabled platforms. Leave empty to use widget defaults.', verbose_name='Enabled Platforms')),
                ('show_counts', models.BooleanField(default=True, help_text='Display number of shares for each platform', verbose_name='Show Share Counts')),
                ('track_shares', models.BooleanField(default=True, help_text='Track share events and award loyalty badges', verbose_name='Track Shares')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Social Sharing Settings',
                'verbose_name_plural': 'Social Sharing Settings',
            },
        ),
        migrations.CreateModel(
            name='ShareCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='object ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('email', 'Email')], max_length=20, verbose_name='platform')),
                ('count', models.PositiveIntegerField(default=0, help_text='Number of times shared on this platform', verbose_name='share count')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
            ],
            options={
                'verbose_name': 'Share Count',
                'verbose_name_plural': 'Share Counts',
                'db_table': 'social_share_counts',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='share_count_content'), models.Index(fields=['count'], name='share_count_value')],
                'unique_together': {('content_type', 'object_id', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='SocialShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='ID of the shared object', verbose_name='object ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('email', 'Email')], db_index=True, help_text='Social platform used for sharing', max_length=20, verbose_name='platform')),
                ('shared_url', models.URLField(help_text='URL that was shared', max_length=500, verbose_name='shared URL')),
                ('referrer', models.URLField(blank=True, help_text='Page from which share was initiated', max_length=500, verbose_name='referrer')),
                ('session_id', models.CharField(blank=True, help_text='Session identifier for anonymous users', max_length=255, verbose_name='session ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of sharer (for analytics and fraud detection)', null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string', verbose_name='user agent')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', help_text='Type of device used for sharing', max_length=20, verbose_name='device type')),
                ('shared_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the share occurred', verbose_name='shared at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('content_type', models.ForeignKey(help_text='Type of content shared (Product, Category, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
                ('user', models.ForeignKey(blank=True, help_text='User who shared (if logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_shares', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Social Share',
                'verbose_name_plural': 'Social Shares',
                'db_table': 'social_shares',
                'ordering': ['-shared_at'],
                'indexes': [models.Index(fields=['platform', 'shared_at'], name='social_share_platform_date'), models.Index(fields=['content_type', 'object_id'], name='social_share_content'), models.Index(fields=['user', 'shared_at'], name='social_share_user_date'), models.Index(fields=['session_id'], name='social_share_session'), models.Index(fields=['shared_at'], name='social_share_date')],
            },
        ),
    ]
