# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('component_updates', '0002_initial'),
        ('sites', '0002_alter_domain_unique'),
        ('translations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_key', models.CharField(blank=True, help_text="Provider identifier (e.g., 'builtin_smtp', 'gmail_api'). Required for built-in providers.", max_length=100, verbose_name='provider key')),
                ('name', models.CharField(help_text="Friendly name for this email account (e.g., 'Main Email Account')", max_length=255, verbose_name='account name')),
                ('from_email', models.EmailField(help_text='Default sender email address', max_length=254, verbose_name='from email')),
                ('from_name', models.CharField(blank=True, help_text='Default sender name', max_length=255, verbose_name='from name')),
                ('reply_to', models.EmailField(blank=True, help_text='Default reply-to email address', max_length=254, verbose_name='reply-to email')),
                ('credentials', models.BinaryField(help_text='Encrypted API credentials for this provider', verbose_name='encrypted credentials')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this email account is active and should be used for sending', verbose_name='active')),
                ('is_default', models.BooleanField(default=False, help_text='Use this account as default for sending emails', verbose_name='default account')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Provider-specific settings and configuration', verbose_name='provider settings')),
                ('connection_status', models.CharField(choices=[('unknown', 'Unknown'), ('connected', 'Connected'), ('error', 'Error')], default='unknown', help_text='Current connection status with provider', max_length=32, verbose_name='connection status')),
                ('connection_error', models.TextField(blank=True, help_text='Error message from last connection test', verbose_name='connection error')),
                ('last_tested_at', models.DateTimeField(blank=True, help_text='When connection was last tested', null=True, verbose_name='last tested at')),
                ('dns_validated', models.BooleanField(default=False, help_text='Whether DNS records (SPF/DKIM/DMARC) have been validated', verbose_name='DNS validated')),
                ('dns_validated_at', models.DateTimeField(blank=True, help_text='When DNS validation last passed', null=True, verbose_name='DNS validated at')),
                ('dns_domain', models.CharField(blank=True, help_text='Domain used for DNS validation (if different from email domain)', max_length=255, verbose_name='DNS domain')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('component', models.ForeignKey(blank=True, help_text='Email provider component from update system (null for built-in providers)', limit_choices_to={'component_type': 'email_provider'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_accounts', to='component_updates.componentregistry', verbose_name='provider component')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_accounts', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('site', models.ForeignKey(help_text='Site this email account belongs to', on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='site')),
            ],
            options={
                'verbose_name': 'email account',
                'verbose_name_plural': 'email accounts',
                'ordering': ['-is_default', '-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailDNSCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(help_text='Domain being validated', max_length=255, verbose_name='domain')),
                ('spf_status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('warn', 'Warning'), ('error', 'Error')], default='error', max_length=16, verbose_name='SPF status')),
                ('spf_record', models.TextField(blank=True, help_text='SPF TXT record value found', verbose_name='SPF record')),
                ('spf_errors', models.TextField(blank=True, help_text='SPF validation error messages', verbose_name='SPF errors')),
                ('dkim_status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('warn', 'Warning'), ('error', 'Error')], default='error', max_length=16, verbose_name='DKIM status')),
                ('dkim_record', models.TextField(blank=True, help_text='DKIM TXT record value found', verbose_name='DKIM record')),
                ('dkim_selector', models.CharField(blank=True, help_text='DKIM selector used for validation', max_length=255, verbose_name='DKIM selector')),
                ('dkim_errors', models.TextField(blank=True, help_text='DKIM validation error messages', verbose_name='DKIM errors')),
                ('dmarc_status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('warn', 'Warning'), ('error', 'Error')], default='error', max_length=16, verbose_name='DMARC status')),
                ('dmarc_record', models.TextField(blank=True, help_text='DMARC TXT record value found', verbose_name='DMARC record')),
                ('dmarc_errors', models.TextField(blank=True, help_text='DMARC validation error messages', verbose_name='DMARC errors')),
                ('resolvers_checked', models.JSONField(blank=True, default=dict, help_text="DNS resolver results (e.g., {'8.8.8.8': 'success', '1.1.1.1': 'success'})", verbose_name='resolvers checked')),
                ('propagation_status', models.CharField(choices=[('full', 'Fully Propagated'), ('partial', 'Partially Propagated'), ('none', 'Not Propagated'), ('error', 'Error')], default='error', help_text='DNS propagation status across multiple resolvers', max_length=16, verbose_name='propagation status')),
                ('overall_status', models.CharField(choices=[('pass', 'Pass'), ('warn', 'Warning'), ('fail', 'Fail')], default='fail', help_text='Overall DNS validation status', max_length=16, verbose_name='overall status')),
                ('checked_at', models.DateTimeField(auto_now_add=True, help_text='When this DNS check was performed', verbose_name='checked at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account', models.ForeignKey(help_text='Email account being validated', on_delete=django.db.models.deletion.CASCADE, related_name='dns_checks', to='email_system.emailaccount', verbose_name='email account')),
                ('checked_by', models.ForeignKey(blank=True, help_text='User who initiated this check', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='checked by')),
            ],
            options={
                'verbose_name': 'DNS check',
                'verbose_name_plural': 'DNS checks',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.EmailField(help_text='Recipient email address', max_length=254, verbose_name='to email')),
                ('from_email', models.EmailField(help_text='Sender email address', max_length=254, verbose_name='from email')),
                ('from_name', models.CharField(blank=True, max_length=255, verbose_name='from name')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('html_body', models.TextField(verbose_name='HTML body')),
                ('text_body', models.TextField(blank=True, verbose_name='text body')),
                ('reply_to', models.EmailField(blank=True, max_length=254, verbose_name='reply-to')),
                ('cc', models.JSONField(blank=True, default=list, help_text='CC email addresses', verbose_name='CC')),
                ('bcc', models.JSONField(blank=True, default=list, help_text='BCC email addresses', verbose_name='BCC')),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Custom email headers', verbose_name='headers')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Provider tags for categorization', verbose_name='tags')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='Attachment file references', verbose_name='attachments')),
                ('template_type', models.CharField(blank=True, help_text='Template used to generate this email', max_length=64, verbose_name='template type')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('skipped', 'Skipped')], default='queued', max_length=32, verbose_name='status')),
                ('skip_reason', models.CharField(blank=True, help_text="Reason why email was skipped (e.g., 'user_preference_disabled', 'unsubscribed')", max_length=100, verbose_name='skip reason')),
                ('provider_message_id', models.CharField(blank=True, help_text='Message ID from email provider', max_length=255, verbose_name='provider message ID')),
                ('error_message', models.TextField(blank=True, help_text='Error details if sending failed', verbose_name='error message')),
                ('priority', models.PositiveSmallIntegerField(default=5, help_text='Email priority (1=highest, 10=lowest). Lower priority emails are sent first.', verbose_name='priority')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of send attempts', verbose_name='retry count')),
                ('max_retries', models.PositiveIntegerField(default=3, help_text='Maximum number of retry attempts', verbose_name='max retries')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='queued at')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='failed at')),
                ('account', models.ForeignKey(help_text='Email account used to send this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to='email_system.emailaccount', verbose_name='email account')),
                ('site', models.ForeignKey(help_text='Site this email belongs to', on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='site')),
            ],
            options={
                'verbose_name': 'email outbox',
                'verbose_name_plural': 'email outbox',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('delivered', 'Delivered'), ('bounced', 'Bounced'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('complained', 'Complained'), ('unsubscribed', 'Unsubscribed')], max_length=32, verbose_name='event type')),
                ('event_data', models.JSONField(blank=True, default=dict, help_text='Provider-specific event details', verbose_name='event data')),
                ('bounce_type', models.CharField(blank=True, choices=[('hard', 'Hard Bounce'), ('soft', 'Soft Bounce'), ('transient', 'Transient')], max_length=32, verbose_name='bounce type')),
                ('bounce_reason', models.TextField(blank=True, verbose_name='bounce reason')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client information for opens/clicks', verbose_name='user agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address for opens/clicks', null=True, verbose_name='IP address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the event occurred (from provider)', verbose_name='occurred at')),
                ('email', models.ForeignKey(help_text='Email this event relates to', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='email_system.emailoutbox', verbose_name='email')),
            ],
            options={
                'verbose_name': 'email event',
                'verbose_name_plural': 'email events',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this object has been soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this object was soft deleted', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_type', models.CharField(choices=[('account_invitation', 'Account Invitation'), ('account_welcome', 'Account Welcome'), ('delivery_confirmation', 'Delivery Confirmation'), ('email_verification', 'Email Verification'), ('order_confirmation', 'Order Confirmation'), ('order_delay', 'Order Delay Notification'), ('password_reset', 'Password Reset'), ('payment_confirmation', 'Payment Confirmation'), ('refund_notification', 'Refund Notification'), ('review_request', 'Review Request'), ('shipping_confirmation', 'Shipping Confirmation'), ('shipping_delayed', 'Shipping: Delayed'), ('shipping_exception', 'Shipping: Exception'), ('shipping_tracking_milestone', 'Shipping: Tracking Milestone'), ('admin_new_order', 'Admin: New Order'), ('admin_payment_failed', 'Admin: Payment Failed'), ('admin_payment_sdk_failure', 'Admin: Payment SDK Failure'), ('admin_report_abandoned_carts_summary', 'Admin: Abandoned Carts Summary'), ('admin_report_customer_insights', 'Admin: Customer Insights'), ('admin_report_daily_sales', 'Admin: Daily Sales Report'), ('admin_report_low_stock_alert', 'Admin: Low Stock Alert'), ('admin_report_monthly_review', 'Admin: Monthly Review'), ('admin_report_revenue_forecast', 'Admin: Revenue Forecast'), ('admin_report_top_products', 'Admin: Top Products'), ('admin_report_weekly_digest', 'Admin: Weekly Digest'), ('affiliate_account_activated', 'Affiliate: Account Activated'), ('affiliate_account_approved', 'Affiliate: Account Approved'), ('affiliate_account_rejected', 'Affiliate: Account Rejected'), ('affiliate_account_suspended', 'Affiliate: Account Suspended'), ('affiliate_commission_approved', 'Affiliate: Commission Approved'), ('affiliate_commission_earned', 'Affiliate: Commission Earned'), ('affiliate_commission_rejected', 'Affiliate: Commission Rejected'), ('affiliate_commission_reversed', 'Affiliate: Commission Reversed'), ('affiliate_high_commission_alert', 'Affiliate: High Commission Alert'), ('affiliate_monthly_report', 'Affiliate: Monthly Report'), ('affiliate_payout_cancelled', 'Affiliate: Payout Cancelled'), ('affiliate_payout_completed', 'Affiliate: Payout Completed'), ('affiliate_payout_failed', 'Affiliate: Payout Failed'), ('affiliate_payout_processing', 'Affiliate: Payout Processing'), ('affiliate_payout_threshold_reached', 'Affiliate: Payout Threshold Reached'), ('affiliate_program_approved', 'Affiliate: Program Approved'), ('affiliate_program_rejected', 'Affiliate: Program Rejected'), ('backup_completed', 'Backup: Completed'), ('backup_failed', 'Backup: Failed'), ('backup_restore_completed', 'Backup: Restore Completed'), ('backup_restore_failed', 'Backup: Restore Failed'), ('backup_scheduled_missed', 'Backup: Scheduled Missed'), ('backup_size_warning', 'Backup: Size Warning'), ('backup_storage_quota_alert', 'Backup: Storage Quota Alert'), ('backup_weekly_report', 'Backup: Weekly Report'), ('admin_booking_cancelled', 'Admin: Booking Cancelled'), ('admin_new_booking', 'Admin: New Booking'), ('booking_cancelled', 'Booking: Cancelled'), ('booking_completed', 'Booking: Completed'), ('booking_confirmation', 'Booking: Confirmation'), ('booking_deposit_receipt', 'Booking: Deposit Receipt'), ('booking_no_show', 'Booking: No Show'), ('booking_pending_confirmation', 'Booking: Pending Confirmation'), ('booking_recurring_created', 'Booking: Recurring Series Created'), ('booking_reminder', 'Booking: Reminder'), ('booking_rescheduled', 'Booking: Rescheduled'), ('booking_waitlist_notification', 'Booking: Waitlist Notification'), ('blog_comment_approved', 'Blog: Comment Approved'), ('blog_comment_reply', 'Blog: Comment Reply'), ('blog_digest_weekly', 'Blog: Weekly Digest'), ('blog_post_published', 'Blog: Post Published'), ('blog_subscriber_welcome', 'Blog: Subscriber Welcome'), ('blog_subscription_confirmed', 'Blog: Subscription Confirmed'), ('cart_abandoned_1h', 'Cart: Abandoned (1 Hour)'), ('cart_abandoned_24h', 'Cart: Abandoned (24 Hours)'), ('cart_abandoned_48h', 'Cart: Abandoned (48 Hours)'), ('cart_abandoned_discount', 'Cart: Abandoned (Discount Offer)'), ('cart_recovered_thank_you', 'Cart: Recovery Thank You'), ('component_deprecated_warning', 'Component: Deprecated Warning'), ('component_incompatible_warning', 'Component: Incompatible Warning'), ('component_rollback_success', 'Component: Rollback Success'), ('component_security_update', 'Component: Security Update'), ('component_update_available', 'Component: Update Available'), ('component_update_failed', 'Component: Update Failed'), ('component_update_installed', 'Component: Update Installed'), ('dev_account_approved', 'Developer: Account Approved'), ('dev_account_rejected', 'Developer: Account Rejected'), ('dev_account_suspended', 'Developer: Account Suspended'), ('dev_component_published', 'Developer: Component Published'), ('dev_license_approved', 'Developer: License Approved'), ('dev_license_rejected', 'Developer: License Rejected'), ('dev_new_review', 'Developer: New Review'), ('dev_registration_ack', 'Developer: Registration Received'), ('dev_review_digest', 'Developer: Review Digest'), ('dev_revision_requested', 'Developer: Revision Requested'), ('dev_submission_approved', 'Developer: Submission Approved'), ('dev_submission_received', 'Developer: Submission Received'), ('dev_submission_rejected', 'Developer: Submission Rejected'), ('digital_product_delivery', 'Digital Product: Download Ready'), ('digital_product_download_expired', 'Digital Product: Download Link Expired'), ('digital_product_license_expired', 'Digital Product: License Expired'), ('digital_product_license_key', 'Digital Product: License Key'), ('form_submission_admin_notification', 'Form: Admin Notification'), ('form_submission_approved', 'Form: Submission Approved'), ('form_submission_auto_response', 'Form: Auto Response'), ('form_submission_confirmation', 'Form: Submission Confirmation'), ('form_submission_rejected', 'Form: Submission Rejected'), ('gift_card_delivery', 'Gift Card: Delivery Email'), ('loyalty_anniversary_bonus', 'Loyalty: Anniversary Bonus'), ('loyalty_birthday_bonus', 'Loyalty: Birthday Bonus'), ('loyalty_double_points_event', 'Loyalty: Double Points Event'), ('loyalty_points_earned', 'Loyalty: Points Earned'), ('loyalty_points_expiring', 'Loyalty: Points Expiring'), ('loyalty_referral_bonus', 'Loyalty: Referral Bonus'), ('loyalty_reward_available', 'Loyalty: Reward Available'), ('loyalty_tier_demotion_warning', 'Loyalty: Tier Demotion Warning'), ('loyalty_tier_upgrade', 'Loyalty: Tier Upgrade'), ('loyalty_welcome', 'Loyalty: Welcome'), ('newsletter', 'Newsletter'), ('pos_cash_discrepancy_alert', 'POS: Cash Discrepancy Alert'), ('pos_daily_z_report', 'POS: Daily Z-Report'), ('pos_high_value_transaction', 'POS: High Value Transaction'), ('pos_low_inventory_alert', 'POS: Low Inventory Alert'), ('pos_receipt', 'POS: Receipt'), ('pos_shift_closed_report', 'POS: Shift Closed Report'), ('pos_terminal_offline', 'POS: Terminal Offline'), ('feed_generation_completed', 'Feed: Generation Completed'), ('feed_generation_failed', 'Feed: Generation Failed'), ('feed_sync_failed', 'Feed: Sync Failed'), ('feed_sync_success', 'Feed: Sync Success'), ('feed_validation_errors', 'Feed: Validation Errors'), ('feed_weekly_report', 'Feed: Weekly Report'), ('referral_invitation', 'Referral: Invitation Email'), ('referral_reward_expiring', 'Referral: Reward Expiring Soon'), ('referral_reward_issued_referee', 'Referral: Reward Issued (Referee)'), ('referral_reward_issued_referrer', 'Referral: Reward Issued (Referrer)'), ('referral_successful', 'Referral: Successful Referral'), ('back_in_stock', 'Back In Stock: Notification'), ('back_in_stock_low_stock_warning', 'Back In Stock: Low Stock Warning'), ('back_in_stock_waitlist_confirmation', 'Back In Stock: Waitlist Confirmation'), ('subscription_addon_added', 'Subscription: Add-on Added'), ('subscription_addon_removed', 'Subscription: Add-on Removed'), ('subscription_canceled', 'Subscription: Canceled'), ('subscription_created', 'Subscription: Created'), ('subscription_dunning_final_notice', 'Subscription: Dunning Final Notice'), ('subscription_expired', 'Subscription: Expired'), ('subscription_paused', 'Subscription: Paused'), ('subscription_payment_failed', 'Subscription: Payment Failed'), ('subscription_payment_method_expiring', 'Subscription: Payment Method Expiring'), ('subscription_payment_success', 'Subscription: Payment Successful'), ('subscription_plan_downgraded', 'Subscription: Plan Downgraded'), ('subscription_plan_upgraded', 'Subscription: Plan Upgraded'), ('subscription_reactivated', 'Subscription: Reactivated'), ('subscription_renewal_reminder', 'Subscription: Renewal Reminder'), ('subscription_resumed', 'Subscription: Resumed'), ('subscription_trial_ending', 'Subscription: Trial Ending Soon'), ('system_health_critical', 'System: Critical Alert'), ('system_health_daily_report', 'System: Daily Health Report'), ('system_health_recovered', 'System: Issue Resolved'), ('system_health_warning', 'System: Warning'), ('system_performance_degraded', 'System: Performance Degraded'), ('translation_job_completed', 'Translation: Job Completed'), ('translation_job_failed', 'Translation: Job Failed'), ('translation_job_started', 'Translation: Job Started'), ('translation_quality_review_needed', 'Translation: Quality Review Needed'), ('wishlist_back_in_stock', 'Wishlist: Back In Stock'), ('wishlist_item_added_confirmation', 'Wishlist: Item Added'), ('wishlist_low_stock_warning', 'Wishlist: Low Stock Warning'), ('wishlist_price_drop', 'Wishlist: Price Drop'), ('wishlist_reminder_weekly', 'Wishlist: Weekly Reminder'), ('wishlist_shared_confirmation', 'Wishlist: Shared Confirmation')], help_text='Type of email (transactional or marketing)', max_length=64, verbose_name='template type')),
                ('language_code', models.CharField(default='en', help_text="Language code for this template (e.g., 'en', 'es', 'fr')", max_length=7, verbose_name='language code')),
                ('subject', models.CharField(help_text='Email subject line (supports {{ variables }})', max_length=255, verbose_name='subject')),
                ('html_content', models.TextField(help_text='HTML email content (MJML or plain HTML)', verbose_name='HTML content')),
                ('text_content', models.TextField(blank=True, help_text='Plain text version (auto-generated if empty)', verbose_name='text content')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active and should be used', verbose_name='active')),
                ('is_system', models.BooleanField(default=False, help_text='Pre-installed system template (can be customized)', verbose_name='system template')),
                ('version', models.IntegerField(default=1, help_text='Template version number', verbose_name='version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_templates', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('parent_template', models.ForeignKey(blank=True, help_text='Original template this was cloned from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='email_system.emailtemplate', verbose_name='parent template')),
                ('site', models.ForeignKey(help_text='Site this template belongs to', on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='site')),
            ],
            options={
                'verbose_name': 'email template',
                'verbose_name_plural': 'email templates',
                'ordering': ['template_type', 'language_code'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplateTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('ja', 'Japanese'), ('pt', 'Portuguese'), ('zh-hans', 'Chinese (Simplified)'), ('ar', 'Arabic'), ('ru', 'Russian')], help_text='Language code (ISO 639-1)', max_length=10)),
                ('subject', models.CharField(help_text='Translated email subject (Django template syntax)', max_length=255, verbose_name='subject')),
                ('html_content', models.TextField(help_text='Translated MJML/HTML template', verbose_name='HTML content')),
                ('text_content', models.TextField(help_text='Translated plain text version', verbose_name='text content')),
                ('is_verified', models.BooleanField(default=False, help_text='Has this translation been manually verified?', verbose_name='verified')),
                ('quality_score', models.FloatField(blank=True, help_text='Translation quality score (0-1) from AI service', null=True, verbose_name='quality score')),
                ('base_template_version', models.IntegerField(default=1, help_text='Version of base template this translation was created from', verbose_name='base template version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('template', models.ForeignKey(help_text='Template this translation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='email_system.emailtemplate')),
                ('translated_by', models.ForeignKey(blank=True, help_text='User who created/verified this translation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translated_email_templates', to=settings.AUTH_USER_MODEL)),
                ('translation_job', models.ForeignKey(blank=True, help_text='AI translation job that created this translation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_template_translations', to='translations.translationjob')),
            ],
            options={
                'verbose_name': 'email template translation',
                'verbose_name_plural': 'email template translations',
                'db_table': 'email_template_translations',
                'ordering': ['template', 'language_code'],
            },
        ),
        migrations.AddIndex(
            model_name='emailaccount',
            index=models.Index(fields=['site', 'is_active'], name='email_syste_site_id_b46655_idx'),
        ),
        migrations.AddIndex(
            model_name='emailaccount',
            index=models.Index(fields=['is_default'], name='email_syste_is_defa_3ad024_idx'),
        ),
        migrations.AddIndex(
            model_name='emailaccount',
            index=models.Index(fields=['connection_status'], name='email_syste_connect_e53e3d_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('site', 'is_default'), name='unique_default_email_account_per_site'),
        ),
        migrations.AddIndex(
            model_name='emaildnscheck',
            index=models.Index(fields=['account', '-checked_at'], name='email_syste_account_8cab36_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildnscheck',
            index=models.Index(fields=['domain', '-checked_at'], name='email_syste_domain_614da0_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildnscheck',
            index=models.Index(fields=['overall_status'], name='email_syste_overall_223179_idx'),
        ),
        migrations.AddIndex(
            model_name='emailoutbox',
            index=models.Index(fields=['site', 'status'], name='email_syste_site_id_aa6562_idx'),
        ),
        migrations.AddIndex(
            model_name='emailoutbox',
            index=models.Index(fields=['status', 'queued_at'], name='email_syste_status_5578f5_idx'),
        ),
        migrations.AddIndex(
            model_name='emailoutbox',
            index=models.Index(fields=['to_email'], name='email_syste_to_emai_fa4798_idx'),
        ),
        migrations.AddIndex(
            model_name='emailoutbox',
            index=models.Index(fields=['provider_message_id'], name='email_syste_provide_88be35_idx'),
        ),
        migrations.AddIndex(
            model_name='emailoutbox',
            index=models.Index(fields=['template_type'], name='email_syste_templat_ea453e_idx'),
        ),
        migrations.AddIndex(
            model_name='emailevent',
            index=models.Index(fields=['email', 'event_type'], name='email_syste_email_i_b68927_idx'),
        ),
        migrations.AddIndex(
            model_name='emailevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='email_syste_event_t_baecc8_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['site', 'template_type', 'language_code'], name='email_syste_site_id_543f15_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['is_active'], name='email_syste_is_acti_53e8ab_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['is_system', 'is_active'], name='email_syste_is_syst_450d68_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplatetranslation',
            index=models.Index(fields=['template', 'language_code'], name='email_templ_templat_8b87a4_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplatetranslation',
            index=models.Index(fields=['language_code'], name='email_templ_languag_500fa8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplatetranslation',
            unique_together={('template', 'language_code')},
        ),
    ]
