# Generated by Django 5.1.4 on 2026-03-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_system', '0004_alter_emailtemplate_template_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailoutbox',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('held', 'Held'), ('logged', 'Logged'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('skipped', 'Skipped')], default='queued', max_length=32, verbose_name='status'),
        ),
    ]
