# Generated by Django 5.2.17 on 2026-08-29 04:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_system', '0010_alter_emailtemplate_template_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProviderWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_slug', models.CharField(db_index=True, max_length=100, verbose_name='provider')),
                ('event_id', models.CharField(max_length=255, verbose_name='provider event id')),
                ('event_type', models.CharField(blank=True, max_length=64, verbose_name='event type')),
                ('payload', models.JSONField(default=dict, verbose_name='payload')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='headers')),
                ('signature_verified', models.BooleanField(default=False, verbose_name='signature verified')),
                ('processed', models.BooleanField(db_index=True, default=False, verbose_name='processed')),
                ('processing_error', models.TextField(blank=True, verbose_name='processing error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='received at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
            ],
            options={
                'verbose_name': 'email provider webhook',
                'verbose_name_plural': 'email provider webhooks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider_slug', 'event_type'], name='email_syste_provide_3f9509_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider_slug', 'event_id'), name='uniq_email_webhook_provider_event')],
            },
        ),
    ]
