# Generated by Django 5.2.17 on 2026-08-29 05:35

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_system', '0011_emailproviderwebhook'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emailoutbox',
            index=models.Index(django.db.models.functions.text.Upper('to_email'), name='email_outbox_to_email_ci'),
        ),
    ]
