# Generated by Django 5.2.17 on 2026-08-29 15:27

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    # CONCURRENTLY cannot run inside a transaction; EmailOutbox can be large, so build
    # the index without locking writes.
    atomic = False

    dependencies = [
        ("email_system", "0012_emailoutbox_email_outbox_to_email_ci"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="emailoutbox",
            index=models.Index(
                fields=["status", "priority", "queued_at"], name="email_outbox_sweep_idx"
            ),
        ),
    ]
