# Generated by Django 5.2.17 on 2026-08-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_system', '0013_emailoutbox_email_outbox_sweep_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailoutbox',
            name='attribution_campaign',
            field=models.CharField(blank=True, help_text='utm_campaign slug for revenue attribution; blank for transactional mail.', max_length=255, verbose_name='attribution campaign'),
        ),
    ]
