# Generated by Django 5.2.17 on 2026-09-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_system', '0014_emailoutbox_attribution_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='purpose',
            field=models.CharField(choices=[('transactional', 'Transactional only'), ('marketing', 'Marketing only'), ('both', 'Transactional & marketing')], db_index=True, default='both', help_text='Which mail this account sends. Configure a separate marketing account to keep campaign sending reputation from affecting transactional email such as order confirmations and password resets.', max_length=16, verbose_name='sending purpose'),
        ),
    ]
