# Generated by Django 5.2.16 on 2026-08-12 00:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliate', '0003_initial'),
        ('orders', '0005_alter_order_channel'),
        ('referrals', '0002_remove_referralreward_wallet_transaction_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_model', models.CharField(choices=[('last_non_direct', 'Last Non-Direct Click'), ('first_touch', 'First Touch'), ('linear', 'Linear'), ('time_decay', 'Time Decay'), ('position_based', 'Position Based (40/20/40)')], default='last_non_direct', help_text='Attribution model applied at resolution time.', max_length=32, verbose_name='active model')),
                ('lookback_days', models.PositiveIntegerField(default=90, help_text='How far before an order a touch may still receive credit.', verbose_name='lookback window (days)')),
                ('time_decay_half_life_days', models.PositiveIntegerField(default=7, help_text='Half-life for the time-decay model.', verbose_name='time-decay half-life (days)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'attribution settings',
                'verbose_name_plural': 'attribution settings',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(help_text='Used as the utm_campaign value on tagged links.', max_length=255, unique=True, verbose_name='slug')),
                ('channel_hint', models.CharField(blank=True, help_text='Default channel emitters use when tagging this campaign.', max_length=32, verbose_name='default channel')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'campaign',
                'verbose_name_plural': 'campaigns',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'created_at'], name='attribution_is_acti_7c0b7c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TouchPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_key', models.CharField(db_index=True, help_text='Stable anonymous id; survives session rotation.', max_length=64, verbose_name='visitor key')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='session key')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='occurred at')),
                ('channel', models.CharField(choices=[('affiliate', 'Affiliate'), ('referral', 'Refer a Friend'), ('paid_search', 'Paid Search'), ('paid_social', 'Paid Social'), ('email', 'Email'), ('campaign', 'Campaign'), ('organic_social', 'Organic Social'), ('organic_search', 'Organic Search'), ('referral_external', 'External Link'), ('loyalty', 'Loyalty'), ('direct', 'Direct'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=32, verbose_name='channel')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='utm source')),
                ('medium', models.CharField(blank=True, max_length=255, verbose_name='utm medium')),
                ('campaign', models.CharField(blank=True, max_length=255, verbose_name='utm campaign')),
                ('term', models.CharField(blank=True, max_length=255, verbose_name='utm term')),
                ('content', models.CharField(blank=True, max_length=255, verbose_name='utm content')),
                ('gclid', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='gclid')),
                ('fbclid', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='fbclid')),
                ('msclkid', models.CharField(blank=True, max_length=255, verbose_name='msclkid')),
                ('referrer_host', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='referrer host')),
                ('landing_path', models.CharField(blank=True, max_length=512, verbose_name='landing path')),
                ('consent_state', models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied'), ('unknown', 'Unknown')], default='unknown', help_text='Analytics-consent snapshot at capture time.', max_length=16, verbose_name='consent state')),
                ('is_bot', models.BooleanField(db_index=True, default=False, verbose_name='is bot')),
                ('device_type', models.CharField(blank=True, max_length=16, verbose_name='device type')),
                ('affiliate_click', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribution_touchpoints', to='affiliate.click', verbose_name='affiliate click')),
                ('campaign_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touchpoints', to='attribution.campaign', verbose_name='campaign')),
                ('customer', models.ForeignKey(blank=True, help_text='Backfilled when the visitor thread binds to a customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribution_touchpoints', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('referral_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribution_touchpoints', to='referrals.referralevent', verbose_name='referral event')),
            ],
            options={
                'verbose_name': 'touch point',
                'verbose_name_plural': 'touch points',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('affiliate', 'Affiliate'), ('referral', 'Refer a Friend'), ('paid_search', 'Paid Search'), ('paid_social', 'Paid Social'), ('email', 'Email'), ('campaign', 'Campaign'), ('organic_social', 'Organic Social'), ('organic_search', 'Organic Search'), ('referral_external', 'External Link'), ('loyalty', 'Loyalty'), ('direct', 'Direct'), ('unknown', 'Unknown')], db_index=True, max_length=32, verbose_name='channel')),
                ('model_version', models.CharField(db_index=True, help_text='Attribution model that produced this row.', max_length=32, verbose_name='model version')),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('assist', 'Assist')], db_index=True, default='primary', help_text='Primary weights sum to 1.0 per order; assist is a separate lens.', max_length=16, verbose_name='role')),
                ('weight', models.DecimalField(decimal_places=8, help_text='Share of the order (0..1) credited to this touch.', max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='weight')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount')),
                ('currency', models.CharField(blank=True, max_length=3, verbose_name='currency')),
                ('amount_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='base currency amount')),
                ('base_currency', models.CharField(blank=True, max_length=3, verbose_name='base currency')),
                ('exchange_rate_used', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='exchange rate used')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='orders.order', verbose_name='order')),
                ('campaign_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions', to='attribution.campaign', verbose_name='campaign')),
                ('touchpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions', to='attribution.touchpoint', verbose_name='touch point')),
            ],
            options={
                'verbose_name': 'attribution',
                'verbose_name_plural': 'attributions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_key', models.CharField(help_text='Opaque first-party visitor identifier (cookie-backed).', max_length=64, unique=True, verbose_name='visitor key')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='first seen')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='last seen')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribution_threads', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
            ],
            options={
                'verbose_name': 'visitor thread',
                'verbose_name_plural': 'visitor threads',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.AddIndex(
            model_name='touchpoint',
            index=models.Index(fields=['visitor_key', 'occurred_at'], name='attribution_visitor_e4710c_idx'),
        ),
        migrations.AddIndex(
            model_name='touchpoint',
            index=models.Index(fields=['customer', 'occurred_at'], name='attribution_custome_6c723c_idx'),
        ),
        migrations.AddIndex(
            model_name='touchpoint',
            index=models.Index(fields=['channel', 'occurred_at'], name='attribution_channel_f19d73_idx'),
        ),
        migrations.AddIndex(
            model_name='touchpoint',
            index=models.Index(fields=['campaign_ref', 'occurred_at'], name='attribution_campaig_f81cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='attribution',
            index=models.Index(fields=['order', 'model_version'], name='attribution_order_i_6ae7e2_idx'),
        ),
        migrations.AddIndex(
            model_name='attribution',
            index=models.Index(fields=['channel', 'created_at'], name='attribution_channel_31fbef_idx'),
        ),
        migrations.AddIndex(
            model_name='attribution',
            index=models.Index(fields=['model_version', 'role'], name='attribution_model_v_9943d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='attribution',
            constraint=models.UniqueConstraint(fields=('order', 'touchpoint', 'model_version', 'role'), name='uniq_attribution_order_touch_model_role'),
        ),
        migrations.AddIndex(
            model_name='visitorthread',
            index=models.Index(fields=['customer', 'last_seen'], name='attribution_custome_c7071a_idx'),
        ),
    ]
