# Generated by Django 5.2.16 on 2026-08-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0001_initial'),
        ('orders', '0005_alter_order_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribution',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True, verbose_name='current'),
        ),
        migrations.AddIndex(
            model_name='attribution',
            index=models.Index(fields=['is_current', 'channel'], name='attribution_is_curr_2539f4_idx'),
        ),
    ]
