# Generated by Django 5.1.4 on 2026-03-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the custom element', max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Optional description of what this element displays', verbose_name='Description')),
                ('target_model', models.CharField(blank=True, help_text='Model to bind data from (e.g., "catalog.Product"). Leave empty for static elements.', max_length=100, verbose_name='Target Model')),
                ('icon', models.CharField(default='fas fa-puzzle-piece', help_text='Font Awesome icon class', max_length=50, verbose_name='Icon')),
                ('category', models.CharField(default='custom', help_text='Category for grouping in element library', max_length=50, verbose_name='Category')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this element is available for use', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Custom Element',
                'verbose_name_plural': 'Custom Elements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ElementBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_field', models.CharField(help_text='Element content field to bind data to (e.g., "text", "src")', max_length=50, verbose_name='Content Field')),
                ('model_field', models.CharField(help_text='Model field to bind data from (e.g., "name", "get_price")', max_length=100, verbose_name='Model Field')),
                ('thumbnail_preset', models.CharField(blank=True, help_text='Thumbnail preset for image fields (e.g., "thumbnail", "medium")', max_length=50, verbose_name='Thumbnail Preset')),
            ],
            options={
                'verbose_name': 'Element Binding',
                'verbose_name_plural': 'Element Bindings',
            },
        ),
    ]
