# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('element_builder', '0001_initial'),
        ('page_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customelement',
            name='root_element',
            field=models.OneToOneField(blank=True, help_text='Root element of the custom element tree', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_element_definition', to='page_builder.element'),
        ),
        migrations.AddField(
            model_name='elementbinding',
            name='custom_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='element_builder.customelement', verbose_name='Custom Element'),
        ),
        migrations.AddField(
            model_name='elementbinding',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_bindings', to='page_builder.element', verbose_name='Element'),
        ),
        migrations.AddIndex(
            model_name='customelement',
            index=models.Index(fields=['target_model'], name='element_bui_target__6ce9ae_idx'),
        ),
        migrations.AddIndex(
            model_name='customelement',
            index=models.Index(fields=['is_active'], name='element_bui_is_acti_be17f6_idx'),
        ),
        migrations.AddIndex(
            model_name='customelement',
            index=models.Index(fields=['slug'], name='element_bui_slug_6c6db1_idx'),
        ),
        migrations.AddIndex(
            model_name='elementbinding',
            index=models.Index(fields=['custom_element'], name='element_bui_custom__03145c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='elementbinding',
            unique_together={('custom_element', 'element', 'content_field')},
        ),
    ]
