# Generated by Django 5.1.4 on 2026-03-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, default='', help_text='Fully qualified domain name (e.g., shop.example.com)', max_length=253, verbose_name='Domain')),
                ('previous_domain', models.CharField(blank=True, default='', help_text='Domain before the last change, for rollback tracking', max_length=253, verbose_name='Previous Domain')),
                ('ssl_mode', models.CharField(choices=[('none', 'None (HTTP only)'), ('letsencrypt', "Let's Encrypt (HTTP-01)"), ('letsencrypt_dns', "Let's Encrypt (DNS-01)"), ('cloudflare_origin', 'Cloudflare Origin CA'), ('custom', 'Custom Certificate'), ('self_signed', 'Self-Signed')], default='none', max_length=20, verbose_name='SSL Mode')),
                ('cert_domain', models.CharField(blank=True, default='', max_length=253, verbose_name='Certificate Domain')),
                ('cert_issuer', models.CharField(blank=True, default='', max_length=255, verbose_name='Certificate Issuer')),
                ('cert_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Certificate Expiry')),
                ('cert_obtained_at', models.DateTimeField(blank=True, null=True, verbose_name='Certificate Obtained')),
                ('is_wildcard', models.BooleanField(default=False, verbose_name='Wildcard Certificate')),
                ('cloudflare_api_token', models.TextField(blank=True, default='', help_text='API token for DNS-01 challenges or Origin CA', verbose_name='Cloudflare API Token')),
                ('cloudflare_zone_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Cloudflare Zone ID')),
                ('admin_email', models.EmailField(blank=True, default='', help_text="Contact email for Let's Encrypt notifications", max_length=254, verbose_name='Admin Email')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('validating_dns', 'Validating DNS'), ('configuring', 'Configuring'), ('obtaining_cert', 'Obtaining Certificate'), ('reloading', 'Reloading Services'), ('error', 'Error')], default='idle', max_length=20, verbose_name='Status')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Last Error')),
                ('task_id', models.CharField(blank=True, default='', help_text='Celery task ID for the current operation', max_length=255, verbose_name='Active Task ID')),
                ('auto_renew', models.BooleanField(default=True, help_text='Automatically renew certificates before expiry', verbose_name='Auto-Renew')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Domain Configuration',
                'verbose_name_plural': 'Domain Configuration',
            },
        ),
    ]
