# Generated by Django 5.1.4 on 2026-05-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_ssl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainconfiguration',
            name='ssl_mode',
            field=models.CharField(choices=[('none', 'None (HTTP only)'), ('letsencrypt', "Let's Encrypt (HTTP-01)"), ('letsencrypt_dns', "Let's Encrypt (DNS-01)"), ('cloudflare_origin', 'Cloudflare Origin CA'), ('custom', 'Custom Certificate'), ('self_signed', 'Self-Signed'), ('managed_externally', 'Managed Externally')], default='none', max_length=20, verbose_name='SSL Mode'),
        ),
    ]
