# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abandonedcart',
            name='recovery_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AddField(
            model_name='abandonedcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abandoned_carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='customercohort',
            index=models.Index(fields=['cohort_date'], name='customers_c_cohort__33e838_idx'),
        ),
        migrations.AddIndex(
            model_name='customercohort',
            index=models.Index(fields=['acquisition_channel'], name='customers_c_acquisi_664998_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customercohort',
            unique_together={('cohort_date', 'acquisition_channel', 'first_product_category')},
        ),
        migrations.AddField(
            model_name='cohortmetrics',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='customers.customercohort'),
        ),
        migrations.AddField(
            model_name='customermetrics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customernote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customernote',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='abandonedcart',
            index=models.Index(fields=['abandoned_at'], name='customers_a_abandon_314efa_idx'),
        ),
        migrations.AddIndex(
            model_name='abandonedcart',
            index=models.Index(fields=['recovered'], name='customers_a_recover_72d4db_idx'),
        ),
        migrations.AddIndex(
            model_name='abandonedcart',
            index=models.Index(fields=['user', '-abandoned_at'], name='customers_a_user_id_0e430a_idx'),
        ),
        migrations.AddIndex(
            model_name='cohortmetrics',
            index=models.Index(fields=['cohort', 'months_since_acquisition'], name='customers_c_cohort__2097e0_idx'),
        ),
        migrations.AddIndex(
            model_name='cohortmetrics',
            index=models.Index(fields=['calculated_at'], name='customers_c_calcula_f23cd4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cohortmetrics',
            unique_together={('cohort', 'months_since_acquisition')},
        ),
        migrations.AddIndex(
            model_name='customermetrics',
            index=models.Index(fields=['total_spent'], name='customers_c_total_s_fec26d_idx'),
        ),
        migrations.AddIndex(
            model_name='customermetrics',
            index=models.Index(fields=['lifetime_value'], name='customers_c_lifetim_efbe51_idx'),
        ),
        migrations.AddIndex(
            model_name='customermetrics',
            index=models.Index(fields=['last_purchase_date'], name='customers_c_last_pu_39935e_idx'),
        ),
        migrations.AddIndex(
            model_name='customermetrics',
            index=models.Index(fields=['last_calculated'], name='customers_c_last_ca_90213f_idx'),
        ),
        migrations.AddIndex(
            model_name='customermetrics',
            index=models.Index(fields=['cohort_month'], name='customers_c_cohort__9e19bb_idx'),
        ),
        migrations.AddIndex(
            model_name='customermetrics',
            index=models.Index(fields=['ltv_calculation_method'], name='customers_c_ltv_cal_1d2ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='customermetrics',
            index=models.Index(fields=['probability_alive'], name='customers_c_probabi_609e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='customernote',
            index=models.Index(fields=['customer', '-created_at'], name='customers_c_custome_9f167b_idx'),
        ),
        migrations.AddIndex(
            model_name='customernote',
            index=models.Index(fields=['requires_follow_up', 'follow_up_date'], name='customers_c_require_182a49_idx'),
        ),
        migrations.AddIndex(
            model_name='customernote',
            index=models.Index(fields=['note_type'], name='customers_c_note_ty_39282d_idx'),
        ),
    ]
