# Generated by Django 5.1.4 on 2026-07-20 01:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='source',
            field=models.CharField(choices=[('referral', 'Referral Reward'), ('refund', 'Order Refund'), ('promotion', 'Promotion'), ('manual', 'Manual Adjustment'), ('loyalty', 'Loyalty Reward'), ('order', 'Order Payment')], db_index=True, max_length=20, verbose_name='Source'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'loyalty')), fields=('source', 'reference_id'), name='wallet_txn_one_credit_per_loyalty_redemption'),
        ),
    ]
