# Generated by Django 5.1.4 on 2026-03-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseproduct',
            name='product_type',
            field=models.CharField(choices=[('trial', 'Free Trial'), ('license', 'Production License'), ('bundle', 'Bundle'), ('addon', 'Add-on')], max_length=20),
        ),
    ]
