# Generated by Django 5.1.4 on 2026-03-21 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_checkout', '0003_hosted_subscription_models'),
        ('payment_providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedbillinglog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hostedcheckoutrequest',
            name='billing_interval',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='hostedsubscription',
            index=models.Index(fields=['status', 'grace_period_end_date'], name='license_che_status_fed562_idx'),
        ),
        migrations.AddIndex(
            model_name='hostedsubscription',
            index=models.Index(fields=['status', 'termination_scheduled_at'], name='license_che_status_7c9f83_idx'),
        ),
    ]
