# Generated by Django 5.1.4 on 2026-03-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_checkout', '0004_qa_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedcheckoutrequest',
            name='company',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hostedsubscription',
            name='company',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
