# Generated by Django 5.1.4 on 2026-03-24 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_checkout', '0005_add_company_field'),
        ('payment_providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hostedsubscription',
            name='license_che_store_s_70a4b7_idx',
        ),
        migrations.AddField(
            model_name='hostedsubscription',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostedsubscription',
            name='store_slug',
            field=models.SlugField(max_length=63, unique=True),
        ),
        migrations.AddIndex(
            model_name='hostedsubscription',
            index=models.Index(fields=['suspended_at'], name='license_che_suspend_a96bfc_idx'),
        ),
        migrations.AddConstraint(
            model_name='hostedsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('license_key', ''), _negated=True), fields=('license_key',), name='unique_nonempty_license_key'),
        ),
    ]
