# Generated by Django 5.1.4 on 2026-03-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_checkout', '0006_qa_fixes_suspended_at_uniqueness'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedplan',
            name='introductory_discount_months',
            field=models.IntegerField(default=3, help_text='Number of months the introductory discount applies (0 = no intro offer)'),
        ),
        migrations.AddField(
            model_name='hostedplan',
            name='introductory_discount_percent',
            field=models.IntegerField(default=50, help_text='Percentage discount for introductory period (e.g. 50 = half price)'),
        ),
    ]
