# Generated by Django 5.1.4 on 2026-03-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_checkout', '0007_introductory_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostedplan',
            name='introductory_discount_months',
        ),
        migrations.RemoveField(
            model_name='hostedplan',
            name='introductory_discount_percent',
        ),
        migrations.AddField(
            model_name='hostedplan',
            name='intro_annual_discount_cycles',
            field=models.IntegerField(default=1, help_text='Number of annual billing cycles the discount applies (0 = no intro offer)'),
        ),
        migrations.AddField(
            model_name='hostedplan',
            name='intro_annual_discount_percent',
            field=models.IntegerField(default=30, help_text='Percentage discount for annual intro period (e.g. 30 = 30%% off)'),
        ),
        migrations.AddField(
            model_name='hostedplan',
            name='intro_monthly_discount_cycles',
            field=models.IntegerField(default=3, help_text='Number of monthly billing cycles the discount applies (0 = no intro offer)'),
        ),
        migrations.AddField(
            model_name='hostedplan',
            name='intro_monthly_discount_percent',
            field=models.IntegerField(default=50, help_text='Percentage discount for monthly intro period (e.g. 50 = half price)'),
        ),
    ]
