# Generated by Django 5.1.4 on 2026-03-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_checkout', '0008_split_intro_discount_monthly_annual'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensecheckoutrequest',
            name='company',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
