# Generated by Django 5.1.4 on 2026-03-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='visitorlocation',
            name='geoip_visit_session_7ff4ce_idx',
        ),
        migrations.AddField(
            model_name='visitorlocation',
            name='is_admin_traffic',
            field=models.BooleanField(db_index=True, default=False, help_text='Traffic originated from admin/staff pages'),
        ),
        migrations.AddField(
            model_name='visitorlocation',
            name='is_bot',
            field=models.BooleanField(db_index=True, default=False, help_text='Detected as bot, crawler, or headless browser'),
        ),
        migrations.AddIndex(
            model_name='visitorlocation',
            index=models.Index(fields=['session_key'], name='geoip_visit_session_837703_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlocation',
            index=models.Index(fields=['is_bot', 'first_seen'], name='geoip_visit_is_bot_d5acc9_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlocation',
            index=models.Index(fields=['is_admin_traffic', 'first_seen'], name='geoip_visit_is_admi_2f9211_idx'),
        ),
    ]
