# Generated by Django 5.1.4 on 2026-03-11 09:58

from django.db import migrations, models


def remove_duplicate_session_keys(apps, schema_editor):
    """Remove duplicate session_key rows before adding unique constraint.

    Keeps the most recent entry (highest id) for each session_key and
    deletes all older duplicates.
    """
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute("""
            DELETE FROM geoip_visitorlocation
            WHERE id NOT IN (
                SELECT MAX(id) FROM geoip_visitorlocation
                WHERE session_key IS NOT NULL
                GROUP BY session_key
            ) AND session_key IS NOT NULL
        """)
        deleted = cursor.rowcount
        if deleted:
            print(f"\n  Removed {deleted} duplicate session_key row(s).")


class Migration(migrations.Migration):

    dependencies = [
        ('geoip', '0002_add_is_bot_and_is_admin_traffic_to_visitorlocation'),
    ]

    operations = [
        migrations.RunPython(
            remove_duplicate_session_keys,
            migrations.RunPython.noop,
        ),
        migrations.RemoveIndex(
            model_name='visitorlocation',
            name='geoip_visit_session_837703_idx',
        ),
        migrations.AlterField(
            model_name='visitorlocation',
            name='session_key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
