# Generated by Django 5.1.4 on 2026-03-23 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoip', '0003_make_session_key_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTrafficStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('bot_views', models.PositiveIntegerField(default=0)),
                ('new_visitors', models.PositiveIntegerField(default=0)),
                ('returning_visitors', models.PositiveIntegerField(default=0)),
                ('desktop_views', models.PositiveIntegerField(default=0)),
                ('mobile_views', models.PositiveIntegerField(default=0)),
                ('tablet_views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Daily Traffic Stats',
                'verbose_name_plural': 'Daily Traffic Stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyPageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('url_path', models.CharField(db_index=True, max_length=500)),
                ('views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('bot_views', models.PositiveIntegerField(default=0)),
                ('entries', models.PositiveIntegerField(default=0, help_text='Times this was the landing page')),
            ],
            options={
                'verbose_name': 'Daily Page Stats',
                'verbose_name_plural': 'Daily Page Stats',
                'ordering': ['-date', '-views'],
                'constraints': [models.UniqueConstraint(fields=('date', 'url_path'), name='unique_daily_page_stats')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=100)),
                ('url', models.CharField(help_text='Full URL as sent by frontend', max_length=2048)),
                ('url_path', models.CharField(db_index=True, help_text='Normalized path without locale prefix or query params (e.g., /pricing)', max_length=500)),
                ('referrer', models.URLField(blank=True, max_length=2048)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_entry_page', models.BooleanField(db_index=True, default=False)),
                ('is_exit_page', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('source', models.CharField(choices=[('headless', 'Headless Frontend'), ('middleware', 'Direct Django')], default='middleware', max_length=20)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_view_set', to='geoip.visitorlocation')),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['url_path', 'timestamp'], name='geoip_pagev_url_pat_391853_idx'), models.Index(fields=['session_key', 'timestamp'], name='geoip_pagev_session_a61889_idx'), models.Index(fields=['is_bot', 'timestamp'], name='geoip_pagev_is_bot_7bdcfc_idx'), models.Index(fields=['is_entry_page', 'url_path'], name='geoip_pagev_is_entr_134212_idx')],
            },
        ),
    ]
