# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Announcement title - supports basic styling (bold, italic, color)')),
                ('body', models.TextField(blank=True, help_text='Optional detailed content for modal display')),
                ('image_display_mode', models.CharField(choices=[('banner', 'Banner Image (above content)'), ('background', 'Background Image (with overlay)')], default='banner', help_text='How to display the image in the modal', max_length=20)),
                ('image_overlay_opacity', models.DecimalField(decimal_places=2, default=0.5, help_text='Overlay opacity when image is used as background (0 = transparent, 1 = opaque)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('link_type', models.CharField(choices=[('none', 'No Link'), ('product', 'Product'), ('category', 'Category'), ('blog_post', 'Blog Post'), ('page', 'Page'), ('custom_url', 'Custom URL')], default='none', help_text='Type of link for this announcement', max_length=20)),
                ('custom_url', models.CharField(blank=True, help_text='Custom URL for the link', max_length=500)),
                ('link_text', models.CharField(blank=True, default='', help_text='Button text for modal link, e.g. "Shop Now"', max_length=100)),
                ('show_modal', models.BooleanField(default=False, help_text='If enabled, clicking the announcement opens a modal with full content. If disabled, clicking navigates directly to the link URL.')),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable or disable this announcement')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Announcement will automatically stop displaying after this date/time. Leave blank for no expiry.', null=True)),
                ('priority', models.IntegerField(default=0, help_text='Lower number = higher priority (displayed first)')),
                ('translations', models.JSONField(blank=True, default=dict, help_text='Translations for announcement content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
