# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0002_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='category_reference',
            field=models.ForeignKey(blank=True, help_text='Category to link to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='catalog.category'),
        ),
    ]
