# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0003_initial'),
        ('catalog', '0001_initial'),
        ('media_library', '0001_initial'),
        ('page_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Optional image for modal display', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='page_reference',
            field=models.ForeignKey(blank=True, help_text='Page to link to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='page_builder.page'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='product_reference',
            field=models.ForeignKey(blank=True, help_text='Product to link to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='visibility_rules',
            field=models.ManyToManyField(blank=True, help_text='Visibility rules for conditional display', related_name='announcements', to='page_builder.rulegroup'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_enabled', 'priority', 'expires_at'], name='announcemen_is_enab_fd099e_idx'),
        ),
    ]
