# Generated by Django 5.2.16 on 2026-08-15 15:40
#
# State-only: Announcement.visibility_rules now targets ``visibility.RuleGroup``
# (the engine moved out of page_builder). The M2M through table
# (announcements_announcement_visibility_rules) and its FK column are physically
# unchanged — the referenced table (page_builder_rulegroup) is the same one, now
# owned by the ``visibility`` app. So no database operations run.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_initial'),
        ('visibility', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='announcement',
                    name='visibility_rules',
                    field=models.ManyToManyField(blank=True, help_text='Visibility rules for conditional display', related_name='announcements', to='visibility.rulegroup'),
                ),
            ],
        ),
    ]
