# Generated by Django 5.1.4 on 2026-03-18 22:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0002_add_shopify_transform_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Descriptive name (e.g., 'Production Server', 'Staging')", max_length=200)),
                ('role', models.CharField(choices=[('production', 'Production'), ('staging', 'Staging'), ('backup', 'Backup'), ('other', 'Other')], default='other', help_text='Role of the remote instance', max_length=20)),
                ('remote_url', models.URLField(help_text='Base URL of the remote Spwig instance (e.g., https://merchant-store.com)')),
                ('auth_token', models.TextField(help_text='SyncToken for the remote instance (stored encrypted)')),
                ('remote_version', models.CharField(blank=True, help_text='Spwig version running on the remote instance', max_length=20)),
                ('remote_site_name', models.CharField(blank=True, help_text='Site name of the remote instance', max_length=200)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the connection has been verified')),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='Last successful connection test', null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last time a sync was performed using this connection', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this connection', on_delete=django.db.models.deletion.CASCADE, related_name='sync_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync Connection',
                'verbose_name_plural': 'Sync Connections',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('settings_sync', 'Settings Sync'), ('full_migration', 'Full System Migration')], help_text='Type of sync operation', max_length=20)),
                ('direction', models.CharField(choices=[('pull', 'Pull from Remote'), ('push', 'Push to Remote')], help_text='Direction of data flow', max_length=10)),
                ('selected_categories', models.JSONField(blank=True, default=list, help_text='List of sync category keys selected for this job')),
                ('sync_mode', models.CharField(choices=[('additive', 'Add & Update Only'), ('mirror', 'Full Mirror')], default='additive', help_text='Sync behaviour: additive (no deletions) or mirror (exact copy)', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('previewing', 'Generating Preview'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolling_back', 'Rolling Back'), ('rolled_back', 'Rolled Back'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the sync operation', max_length=25)),
                ('progress_percent', models.IntegerField(default=0, help_text='Overall progress percentage (0-100)')),
                ('current_step', models.CharField(blank=True, help_text='Name of the currently executing step', max_length=100)),
                ('diff_preview', models.JSONField(blank=True, default=dict, help_text='Structured diff from preview step')),
                ('production_confirmed', models.BooleanField(default=False, help_text='Whether the merchant confirmed production overwrite')),
                ('rollback_snapshot', models.JSONField(blank=True, default=dict, help_text='Pre-sync state snapshot for rollback')),
                ('can_rollback', models.BooleanField(default=True, help_text='Whether this job can be rolled back')),
                ('rollback_deadline', models.DateTimeField(blank=True, help_text='Deadline for rollback (24 hours after completion)', null=True)),
                ('items_total', models.IntegerField(default=0)),
                ('items_synced', models.IntegerField(default=0)),
                ('items_skipped', models.IntegerField(default=0)),
                ('items_failed', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('error_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(help_text='Connection to the remote instance', on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='migration.syncconnection')),
                ('created_by', models.ForeignKey(help_text='User who initiated this sync', on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync Job',
                'verbose_name_plural': 'Sync Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text="Sync category key (e.g., 'email_config', 'design_theme')", max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20)),
                ('items_total', models.IntegerField(default=0)),
                ('items_synced', models.IntegerField(default=0)),
                ('items_skipped', models.IntegerField(default=0)),
                ('items_failed', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('diff_data', models.JSONField(blank=True, default=dict, help_text='Diff data, created object IDs, or ID mappings for this step')),
                ('job', models.ForeignKey(help_text='Parent sync job', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='migration.syncjob')),
            ],
            options={
                'verbose_name': 'Sync Step',
                'verbose_name_plural': 'Sync Steps',
                'ordering': ['id'],
                'unique_together': {('job', 'category')},
            },
        ),
    ]
