# Generated by Django 5.1.4 on 2026-03-18 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0003_syncconnection_syncjob_syncstep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncconnection',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this connection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='syncjob',
            name='connection',
            field=models.ForeignKey(help_text='Connection to the remote instance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_jobs', to='migration.syncconnection'),
        ),
        migrations.AlterField(
            model_name='syncjob',
            name='created_by',
            field=models.ForeignKey(help_text='User who initiated this sync', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
