# Generated by Django 5.1.4 on 2026-03-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0004_alter_fk_on_delete_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncjob',
            name='activity_log',
            field=models.JSONField(blank=True, default=list, help_text='Recent activity log entries [{ts, msg}, ...] (last 50)'),
        ),
        migrations.AddField(
            model_name='syncstep',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Extra progress data for the UI (e.g., bytes transferred for media)'),
        ),
    ]
