# Generated by Django 5.1.4 on 2026-07-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0006_add_magento_transform_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('connecting', 'Testing Connection'), ('previewing', 'Previewing Data'), ('running', 'Importing'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolling_back', 'Rolling Back'), ('rolled_back', 'Rolled Back'), ('rollback_failed', 'Rollback Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
