# Generated by Django 5.1.4 on 2026-07-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0007_alter_migrationjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationjob',
            name='cancel_requested',
            field=models.BooleanField(db_index=True, default=False, help_text='Set when an operator asks for a running import to stop'),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='migrationjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('connecting', 'Testing Connection'), ('previewing', 'Previewing Data'), ('running', 'Importing'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('rolling_back', 'Rolling Back'), ('rolled_back', 'Rolled Back'), ('rollback_failed', 'Rollback Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='migrationstep',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled'), ('rolled_back', 'Rolled Back')], db_index=True, default='pending', max_length=20),
        ),
    ]
