# Generated by Django 5.1.4 on 2026-07-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0008_migrationjob_cancel_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationjob',
            name='auto_rollback_on_failure',
            field=models.BooleanField(default=False, help_text='If the import fails, automatically remove everything it imported'),
        ),
        migrations.AlterField(
            model_name='migrationjob',
            name='rollback_deadline',
            field=models.DateTimeField(blank=True, help_text='Point after which this migration can no longer be rolled back. Empty means it never expires.', null=True),
        ),
    ]
