# Generated by Django 5.1.4 on 2026-07-19 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0009_migrationjob_auto_rollback_on_failure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migrationjob',
            name='import_shipping_zones',
        ),
        migrations.RemoveField(
            model_name='migrationjob',
            name='import_tax_rates',
        ),
    ]
