# Generated by Django 5.1.4 on 2026-07-20 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0010_remove_migrationjob_import_shipping_zones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migrationjob',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='migrationstep',
            name='savepoint_id',
        ),
    ]
