# Generated by Django 5.1.4 on 2026-07-19 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0007_alter_migrationjob_status'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='migration_job',
            field=models.ForeignKey(blank=True, help_text='Migration job that created this plan, if it was imported', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_plans', to='migration.migrationjob'),
        ),
    ]
