# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('cart', '0003_initial'),
        ('catalog', '0001_initial'),
        ('media_library', '0002_initial'),
        ('migration', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='orders.order'),
        ),
        migrations.AddField(
            model_name='booking',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='bookingnote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingnote',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_notes', to='catalog.booking'),
        ),
        migrations.AddField(
            model_name='bookingavailabilityrule',
            name='resource',
            field=models.ForeignKey(blank=True, help_text='If set, rule applies to this resource only', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='catalog.bookingresource'),
        ),
        migrations.AddField(
            model_name='booking',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='catalog.bookingresource'),
        ),
        migrations.AddField(
            model_name='bookingresourceimage',
            name='media_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_resource_uses', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='bookingresourceimage',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.bookingresource'),
        ),
        migrations.AddField(
            model_name='bookingslotreservation',
            name='cart_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_slot_reservations', to='cart.cartitem'),
        ),
        migrations.AddField(
            model_name='bookingslotreservation',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_reservations', to='catalog.bookingresource'),
        ),
        migrations.AddField(
            model_name='bookingwaitlist',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_waitlist_entries', to='accounts.customerprofile'),
        ),
        migrations.AddField(
            model_name='category',
            name='banner_asset',
            field=models.ForeignKey(blank=True, help_text='Category page banner from media library', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_banners', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_asset',
            field=models.ForeignKey(blank=True, help_text='Main category image from media library', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_images', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='category',
            name='migration_job',
            field=models.ForeignKey(blank=True, help_text='Migration job that imported this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_categories', to='migration.migrationjob'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='configurationpreset',
            name='image_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_library.mediaasset', verbose_name='Preset Image'),
        ),
        migrations.AddField(
            model_name='compatibilityrule',
            name='target_slot',
            field=models.ForeignKey(help_text='...filter options in this slot.', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_rules', to='catalog.configurationslot', verbose_name='Target Slot'),
        ),
        migrations.AddField(
            model_name='configurationslotoption',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.configurationslot', verbose_name='Slot'),
        ),
        migrations.AddField(
            model_name='compatibilityrule',
            name='compatible_options',
            field=models.ManyToManyField(blank=True, help_text="Options in target slot affected by this rule. For 'requires': only these are shown. For 'excludes': these are hidden.", related_name='compatible_via_rules', to='catalog.configurationslotoption', verbose_name='Compatible Options'),
        ),
        migrations.AddField(
            model_name='compatibilityrule',
            name='source_option',
            field=models.ForeignKey(help_text='When this option is selected...', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_rules', to='catalog.configurationslotoption', verbose_name='Source Option'),
        ),
        migrations.AddField(
            model_name='customizationvalue',
            name='customization_option',
            field=models.ForeignKey(help_text='Which customization option this value is for', on_delete=django.db.models.deletion.PROTECT, related_name='values', to='catalog.customizationoption', verbose_name='Customization Option'),
        ),
        migrations.AddField(
            model_name='customizationvalue',
            name='file_value',
            field=models.ForeignKey(blank=True, help_text='Uploaded file asset', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customization_values', to='media_library.mediaasset', verbose_name='File Value'),
        ),
        migrations.AddField(
            model_name='customizationvalue',
            name='order_item',
            field=models.ForeignKey(help_text='Order item this customization applies to', on_delete=django.db.models.deletion.CASCADE, related_name='customization_values', to='orders.orderitem', verbose_name='Order Item'),
        ),
        migrations.AddField(
            model_name='digitalasset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_digital_assets', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='digitaldownload',
            name='digital_asset',
            field=models.ForeignKey(help_text='Asset that was downloaded', on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='catalog.digitalasset', verbose_name='Digital Asset'),
        ),
        migrations.AddField(
            model_name='digitaldownload',
            name='order_item',
            field=models.ForeignKey(help_text='Purchase that grants download access', on_delete=django.db.models.deletion.CASCADE, related_name='digital_downloads', to='orders.orderitem', verbose_name='Order Item'),
        ),
        migrations.AddField(
            model_name='digitaldownload',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who downloaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_downloads', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin who manually created this card', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gift_cards', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='order_item',
            field=models.ForeignKey(blank=True, help_text='Purchase that created this card', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_cards', to='orders.orderitem', verbose_name='Order Item'),
        ),
        migrations.AddField(
            model_name='giftcardtransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who performed this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_card_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='giftcardtransaction',
            name='gift_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='catalog.giftcard', verbose_name='Gift Card'),
        ),
        migrations.AddField(
            model_name='giftcardtransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_card_transactions', to='orders.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='licensekey',
            name='digital_asset',
            field=models.ForeignKey(blank=True, help_text='Digital asset this license is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_keys', to='catalog.digitalasset', verbose_name='Digital Asset'),
        ),
        migrations.AddField(
            model_name='licensekey',
            name='order_item',
            field=models.ForeignKey(blank=True, help_text='Purchase that generated this license', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_keys', to='orders.orderitem', verbose_name='Order Item'),
        ),
        migrations.AddField(
            model_name='licensekey',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who owns this license', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_keys', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='licenseactivation',
            name='license_key',
            field=models.ForeignKey(help_text='License that was activated', on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='catalog.licensekey', verbose_name='License Key'),
        ),
        migrations.AddField(
            model_name='externallicensesync',
            name='license_key',
            field=models.ForeignKey(help_text='Local license key being synced', on_delete=django.db.models.deletion.CASCADE, related_name='external_syncs', to='catalog.licensekey'),
        ),
        migrations.AddField(
            model_name='licensekeytemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_templates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licensepool',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_license_pools', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='licensepool',
            name='license_template',
            field=models.ForeignKey(blank=True, help_text="Template for generating keys. Uses product's template if not set.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_pools', to='catalog.licensekeytemplate', verbose_name='License Template'),
        ),
        migrations.AddField(
            model_name='licensekey',
            name='license_pool',
            field=models.ForeignKey(blank=True, help_text='License pool this key belongs to (if pre-generated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pool_keys', to='catalog.licensepool', verbose_name='License Pool'),
        ),
        migrations.AddField(
            model_name='licensepool',
            name='sync_to_provider',
            field=models.ForeignKey(blank=True, help_text='Automatically sync generated keys to this external provider', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synced_pools', to='catalog.licenseprovider', verbose_name='Sync to Provider'),
        ),
        migrations.AddField(
            model_name='externallicensesync',
            name='provider',
            field=models.ForeignKey(help_text='External provider this sync is for', on_delete=django.db.models.deletion.CASCADE, related_name='sync_operations', to='catalog.licenseprovider'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_product_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='license_provider',
            field=models.ForeignKey(blank=True, help_text='External provider to sync licenses to when orders are placed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licensed_products', to='catalog.licenseprovider', verbose_name='License Provider'),
        ),
        migrations.AddField(
            model_name='product',
            name='license_template',
            field=models.ForeignKey(blank=True, help_text='Custom license key format for digital products. If not set, uses default format.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.licensekeytemplate', verbose_name='License Key Template'),
        ),
        migrations.AddField(
            model_name='product',
            name='migration_job',
            field=models.ForeignKey(blank=True, help_text='Migration job that imported this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_products', to='migration.migrationjob'),
        ),
    ]
