# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0004_initial'),
        ('catalog', '0002_initial'),
        ('media_library', '0002_initial'),
        ('migration', '0001_initial'),
        ('orders', '0001_initial'),
        ('pos_app', '0001_initial'),
        ('shipping', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preferred_shipping_package',
            field=models.ForeignKey(blank=True, help_text='Default package to use for shipping this product. If set, package dimensions will be used instead of product dimensions for shipping calculations.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shipping.shippingpackage', verbose_name='Preferred Shipping Package'),
        ),
        migrations.AddField(
            model_name='product',
            name='subscription_plans',
            field=models.ManyToManyField(blank=True, help_text='Available subscription plans for this product. Customers can choose from these plans.', related_name='products', to='subscriptions.subscriptionplan', verbose_name='Subscription Plans'),
        ),
        migrations.AddField(
            model_name='licensepool',
            name='product',
            field=models.ForeignKey(help_text='Product these licenses are for', on_delete=django.db.models.deletion.CASCADE, related_name='license_pools', to='catalog.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='product',
            field=models.ForeignKey(help_text='Gift card product', limit_choices_to={'product_type': 'gift_card'}, on_delete=django.db.models.deletion.PROTECT, related_name='gift_cards', to='catalog.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='digitalasset',
            name='product',
            field=models.ForeignKey(help_text='Product this digital asset belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='digital_assets', to='catalog.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='customizationoption',
            name='product',
            field=models.ForeignKey(help_text='Product this customization option applies to', on_delete=django.db.models.deletion.CASCADE, related_name='customization_options', to='catalog.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='configurationslotoption',
            name='option_product',
            field=models.ForeignKey(help_text='The product offered as an option in this slot.', on_delete=django.db.models.deletion.PROTECT, related_name='configurator_slot_options', to='catalog.product', verbose_name='Option Product'),
        ),
        migrations.AddField(
            model_name='configurationslot',
            name='product',
            field=models.ForeignKey(limit_choices_to={'product_type': 'configurable'}, on_delete=django.db.models.deletion.CASCADE, related_name='configuration_slots', to='catalog.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='configurationpreset',
            name='product',
            field=models.ForeignKey(limit_choices_to={'product_type': 'configurable'}, on_delete=django.db.models.deletion.CASCADE, related_name='configuration_presets', to='catalog.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='compatibilityrule',
            name='configurable_product',
            field=models.ForeignKey(limit_choices_to={'product_type': 'configurable'}, on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_rules', to='catalog.product', verbose_name='Configurable Product'),
        ),
        migrations.AddField(
            model_name='collection',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='collections', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='bundleitem',
            name='bundle',
            field=models.ForeignKey(help_text='Bundle product this item belongs to', limit_choices_to={'product_type': 'bundle'}, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='bundleitem',
            name='component_product',
            field=models.ForeignKey(help_text='Product included in this bundle', on_delete=django.db.models.deletion.PROTECT, related_name='included_in_bundles', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='bookingwaitlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_waitlist', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='bookingslotreservation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_slot_reservations', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='bookingresource',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_resources', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='bookingrecurrencerule',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_recurrence_rules', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='bookingpersontype',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_person_types', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='bookingconfig',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_config', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='bookingavailabilityrule',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_availability_rules', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='booking',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(help_text='Attribute this value belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.productattribute'),
        ),
        migrations.AddField(
            model_name='productattributeassignment',
            name='allowed_values',
            field=models.ManyToManyField(help_text='Which values are available for this product', related_name='product_assignments', to='catalog.attributevalue'),
        ),
        migrations.AddField(
            model_name='productattributeassignment',
            name='attribute',
            field=models.ForeignKey(help_text='Attribute assigned to product', on_delete=django.db.models.deletion.CASCADE, related_name='product_assignments', to='catalog.productattribute'),
        ),
        migrations.AddField(
            model_name='productattributeassignment',
            name='product',
            field=models.ForeignKey(help_text='Product this attribute is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='attribute_assignments', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productdependency',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='catalog.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='productdependency',
            name='required_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='required_by', to='catalog.product', verbose_name='Required product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='media_asset',
            field=models.ForeignKey(help_text='Media asset for this product image', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_uses', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_prices', to='catalog.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='productregionvisibility',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_visibility', to='catalog.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='migration_job',
            field=models.ForeignKey(blank=True, help_text='Migration job that imported this review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_reviews', to='migration.migrationjob'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image_asset',
            field=models.ForeignKey(blank=True, help_text='Variant-specific image from media library', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variants', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='preferred_shipping_package',
            field=models.ForeignKey(blank=True, help_text="Package to use for shipping this variant (leave blank to use product's preferred package)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='shipping.shippingpackage', verbose_name='Preferred Shipping Package'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='selected_attributes',
            field=models.ManyToManyField(blank=True, help_text='Attribute values for this variant (e.g., Size: Large, Color: Red)', related_name='variants', to='catalog.attributevalue'),
        ),
        migrations.AddField(
            model_name='configurationslotoption',
            name='option_variant',
            field=models.ForeignKey(blank=True, help_text='Specific variant, if applicable.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configurator_slot_options', to='catalog.productvariant', verbose_name='Option Variant'),
        ),
        migrations.AddField(
            model_name='bundleitem',
            name='component_variant',
            field=models.ForeignKey(blank=True, help_text='Specific variant (if component is variable product)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='included_in_bundles', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='productvariantimage',
            name='media_asset',
            field=models.ForeignKey(help_text='Media asset for this variant image', on_delete=django.db.models.deletion.PROTECT, related_name='variant_uses', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='productvariantimage',
            name='variant',
            field=models.ForeignKey(help_text='Product variant this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='brands',
            field=models.ManyToManyField(blank=True, help_text="Brands to include (when Apply To is 'Specific Brands')", related_name='promotions', to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text="Categories to include (when Apply To is 'Specific Categories')", related_name='promotions', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='collections',
            field=models.ManyToManyField(blank=True, help_text="Collections to include (when Apply To is 'Specific Collections')", related_name='promotions', to='catalog.collection'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(blank=True, help_text="Specific products to include (when Apply To is 'Specific Products')", related_name='promotions', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productregionvisibility',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visible_products', to='catalog.salesregion', verbose_name='region'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='catalog.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Variant this stock is for (null for simple products)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='catalog.productvariant', verbose_name='variant'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.order', verbose_name='order'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='catalog.stockitem', verbose_name='stock item'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='stocknotification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_notifications', to='catalog.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='stocknotification',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Specific variant to notify about (null for base product)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_notifications', to='catalog.productvariant', verbose_name='variant'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='cart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='cart.cartitem', verbose_name='cart item'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='catalog.stockitem', verbose_name='stock item'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='region',
            field=models.ForeignKey(help_text='The region this warehouse serves', on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='catalog.salesregion', verbose_name='sales region'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='shipping_location',
            field=models.OneToOneField(blank=True, help_text='Link to pickup location if this warehouse supports customer pickup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse', to='shipping.location', verbose_name='shipping location'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='store_group',
            field=models.ForeignKey(blank=True, help_text='POS store group for settings inheritance (currency, language, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='pos_app.storegroup', verbose_name='store group'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='warehouse',
            field=models.ForeignKey(help_text='Warehouse the reservation is held at', on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='catalog.warehouse', verbose_name='warehouse'),
        ),
        migrations.AddField(
            model_name='stocknotification',
            name='preferred_warehouse',
            field=models.ForeignKey(blank=True, help_text='Preferred warehouse for regional notifications', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_notifications', to='catalog.warehouse', verbose_name='preferred warehouse'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='catalog.warehouse', verbose_name='warehouse'),
        ),
        migrations.AddField(
            model_name='webhooksubscription',
            name='product_filter',
            field=models.ManyToManyField(blank=True, help_text='Only send events for these products (empty = all products)', related_name='webhook_subscriptions', to='catalog.product'),
        ),
        migrations.AddIndex(
            model_name='bookingnote',
            index=models.Index(fields=['booking', '-created_at'], name='catalog_boo_booking_46ec84_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='catalog_cat_slug_695af4_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='catalog_cat_is_acti_7db955_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_featured'], name='catalog_cat_is_feat_bda135_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['sort_order'], name='catalog_cat_sort_or_af1199_idx'),
        ),
        migrations.AddIndex(
            model_name='customizationvalue',
            index=models.Index(fields=['order_item'], name='catalog_cus_order_i_6645b7_idx'),
        ),
        migrations.AddIndex(
            model_name='digitaldownload',
            index=models.Index(fields=['digital_asset', '-downloaded_at'], name='catalog_dig_digital_ced31d_idx'),
        ),
        migrations.AddIndex(
            model_name='digitaldownload',
            index=models.Index(fields=['order_item', '-downloaded_at'], name='catalog_dig_order_i_79f91b_idx'),
        ),
        migrations.AddIndex(
            model_name='digitaldownload',
            index=models.Index(fields=['user', '-downloaded_at'], name='catalog_dig_user_id_4efe57_idx'),
        ),
        migrations.AddIndex(
            model_name='digitaldownload',
            index=models.Index(fields=['status'], name='catalog_dig_status_7b1a7b_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcardtransaction',
            index=models.Index(fields=['gift_card', '-created_at'], name='catalog_gif_gift_ca_486f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcardtransaction',
            index=models.Index(fields=['transaction_type'], name='catalog_gif_transac_6d31e3_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseactivation',
            index=models.Index(fields=['license_key', 'is_active'], name='catalog_lic_license_3fc2e2_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseactivation',
            index=models.Index(fields=['device_identifier'], name='catalog_lic_device__29322e_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseactivation',
            index=models.Index(fields=['-activated_at'], name='catalog_lic_activat_0c6a5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='licenseactivation',
            unique_together={('license_key', 'device_identifier')},
        ),
        migrations.AddIndex(
            model_name='licensekey',
            index=models.Index(fields=['key'], name='catalog_lic_key_683fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='licensekey',
            index=models.Index(fields=['digital_asset', 'order_item'], name='catalog_lic_digital_3819eb_idx'),
        ),
        migrations.AddIndex(
            model_name='licensekey',
            index=models.Index(fields=['user', '-issued_at'], name='catalog_lic_user_id_de5df3_idx'),
        ),
        migrations.AddIndex(
            model_name='licensekey',
            index=models.Index(fields=['status'], name='catalog_lic_status_f0639c_idx'),
        ),
        migrations.AddIndex(
            model_name='externallicensesync',
            index=models.Index(fields=['external_id'], name='catalog_ext_externa_4031f7_idx'),
        ),
        migrations.AddIndex(
            model_name='externallicensesync',
            index=models.Index(fields=['sync_status'], name='catalog_ext_sync_st_e90b54_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='catalog_pro_slug_2b1eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='catalog_pro_sku_2c4c34_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='catalog_pro_status_521020_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='catalog_pro_is_feat_94b8d5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='catalog_pro_created_eee82f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['hs_code'], name='catalog_pro_hs_code_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['country_of_origin'], name='catalog_pro_country_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('slug',), name='unique_active_product_slug'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('sku',), name='unique_active_product_sku'),
        ),
        migrations.AddIndex(
            model_name='licensepool',
            index=models.Index(fields=['product', 'status'], name='catalog_lic_product_bfe920_idx'),
        ),
        migrations.AddIndex(
            model_name='licensepool',
            index=models.Index(fields=['created_at'], name='catalog_lic_created_a3cb00_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['code'], name='catalog_gif_code_18c500_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['recipient_email'], name='catalog_gif_recipie_bd0da7_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['is_active', 'expires_at'], name='catalog_gif_is_acti_d48886_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['scheduled_send_at', 'issued_at'], name='catalog_gif_schedul_6ac1e9_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalasset',
            index=models.Index(fields=['product', 'is_active'], name='catalog_dig_product_c4ef5d_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalasset',
            index=models.Index(fields=['version'], name='catalog_dig_version_fe22b9_idx'),
        ),
        migrations.AddIndex(
            model_name='customizationoption',
            index=models.Index(fields=['product', 'sort_order'], name='catalog_cus_product_f19ff0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customizationoption',
            unique_together={('product', 'slug')},
        ),
        migrations.AddIndex(
            model_name='configurationslot',
            index=models.Index(fields=['product', 'sort_order'], name='catalog_con_product_c047f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='configurationslot',
            unique_together={('product', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='configurationpreset',
            unique_together={('product', 'slug')},
        ),
        migrations.AddIndex(
            model_name='compatibilityrule',
            index=models.Index(fields=['configurable_product'], name='catalog_com_configu_0cd63e_idx'),
        ),
        migrations.AddIndex(
            model_name='compatibilityrule',
            index=models.Index(fields=['source_option', 'target_slot'], name='catalog_com_source__8982f9_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingslotreservation',
            index=models.Index(fields=['product', 'start_datetime', 'end_datetime'], name='catalog_boo_product_5ab8e6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['product', 'start_datetime', 'status'], name='catalog_boo_product_24353b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'start_datetime'], name='catalog_boo_status_94b61c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('attribute', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='productattributeassignment',
            unique_together={('product', 'attribute')},
        ),
        migrations.AlterUniqueTogether(
            name='productdependency',
            unique_together={('product', 'required_product')},
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['product', 'currency', 'is_active'], name='catalog_pro_product_4e1dc7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together={('product', 'currency')},
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('product', 'user')},
        ),
        migrations.AddIndex(
            model_name='configurationslotoption',
            index=models.Index(fields=['slot', 'sort_order'], name='catalog_con_slot_id_7e3ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='configurationslotoption',
            index=models.Index(fields=['option_product'], name='catalog_con_option__59c5df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='configurationslotoption',
            unique_together={('slot', 'option_product', 'option_variant')},
        ),
        migrations.AddIndex(
            model_name='bundleitem',
            index=models.Index(fields=['bundle'], name='catalog_bun_bundle__448bd9_idx'),
        ),
        migrations.AddIndex(
            model_name='bundleitem',
            index=models.Index(fields=['component_product'], name='catalog_bun_compone_ea69cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bundleitem',
            unique_together={('bundle', 'component_product', 'component_variant')},
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active', 'start_date', 'end_date'], name='catalog_pro_is_acti_e256db_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['-priority'], name='catalog_pro_priorit_86ce10_idx'),
        ),
        migrations.AddIndex(
            model_name='productregionvisibility',
            index=models.Index(fields=['region', 'is_visible'], name='catalog_pro_region__a6bd5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productregionvisibility',
            unique_together={('product', 'region')},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stock_item', '-created_at'], name='catalog_sto_stock_i_219b43_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', '-created_at'], name='catalog_sto_movemen_7bcb98_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['order'], name='catalog_sto_order_i_b2c821_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['region', 'is_active'], name='catalog_war_region__b5f141_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['code'], name='catalog_war_code_0c1835_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['expires_at'], name='catalog_sto_expires_be2040_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['cart_item'], name='catalog_sto_cart_it_516268_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockreservation',
            unique_together={('stock_item', 'cart_item')},
        ),
        migrations.AddIndex(
            model_name='stocknotification',
            index=models.Index(fields=['product', 'notified_at'], name='catalog_sto_product_5b11a1_idx'),
        ),
        migrations.AddIndex(
            model_name='stocknotification',
            index=models.Index(fields=['email'], name='catalog_sto_email_2bab0a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stocknotification',
            unique_together={('email', 'product', 'variant')},
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['product', 'warehouse', 'variant'], name='catalog_sto_product_ff6e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['warehouse', 'on_hand'], name='catalog_sto_warehou_7d6412_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('product', 'warehouse', 'variant')},
        ),
    ]
