# Generated by Django 5.1.4 on 2026-07-19 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_giftcard_tender_hardening'),
        ('orders', '0004_add_gift_card_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='issue_index',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Position of this card within its order line; enforces one-mint-per-slot', null=True, verbose_name='Issue Index'),
        ),
        migrations.AddConstraint(
            model_name='giftcard',
            constraint=models.UniqueConstraint(condition=models.Q(('issue_index__isnull', False), ('order_item__isnull', False)), fields=('order_item', 'issue_index'), name='uniq_giftcard_order_item_issue_index'),
        ),
    ]
