# Generated by Django 5.2.16 on 2026-07-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_giftcard_issue_idempotency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='agent_visible',
            field=models.BooleanField(db_index=True, default=True, help_text='When off, AI shopping agents cannot see or buy this product, even while it stays visible on the storefront.', verbose_name='Visible to AI shopping agents'),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('refurbished', 'Refurbished'), ('used', 'Used')], db_index=True, default='new', help_text='Item condition reported to AI shopping agents.', max_length=16, verbose_name='Condition'),
        ),
    ]
