# Generated by Django 5.2.16 on 2026-08-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_untrack_digital_product_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='region_restriction_mode',
            field=models.CharField(choices=[('all', 'Available in all regions'), ('only_in', 'Only in selected regions'), ('all_except', 'All regions except selected')], db_index=True, default='all', help_text="Where this product is sold. Choose the regions in 'Region availability' below; 'Only in' shows it there exclusively, 'All except' hides it there.", max_length=12, verbose_name='Region availability'),
        ),
    ]
