# Generated by Django 5.2.16 on 2026-08-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_migrate_region_visibility_modes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdisplaysettings',
            name='region_restricted_action',
            field=models.CharField(choices=[('hide', 'Hide from listings'), ('show_unavailable', 'Show, marked as unavailable')], default='show_unavailable', help_text='What to do on storefront listings with products that aren\'t sold in the shopper\'s region: hide them, or show them marked "Does not ship to [region]" (with a filter to hide them).', max_length=20, verbose_name='region-restricted display'),
        ),
    ]
