# Generated by Django 5.2.16 on 2026-08-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_stockdisplaysettings_region_restricted_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesregion',
            name='slug',
            field=models.SlugField(blank=True, help_text='Optional URL segment that gives this region its own storefront address — e.g. "nz" serves it at /nz/en/… . Leave blank if the region is not a separate storefront. The highest-priority region is the default market and is always served without a prefix.', max_length=20, verbose_name='market URL slug'),
        ),
        migrations.AddConstraint(
            model_name='salesregion',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('slug',), name='unique_market_slug'),
        ),
    ]
