# Generated by Django 5.2.16 on 2026-08-15 15:40
#
# State-only counterpart to visibility/migrations/0001: the visibility-rule
# models moved OUT of page_builder into the ``visibility`` app without moving
# data. Here we only remove them from page_builder's migration STATE and repoint
# Element.visibility_rules at ``visibility.RuleGroup``. No database operations run
# — the tables (page_builder_visibilityrule / _rulegroup / _rulegroupmember and
# the page_builder_element_visibility_rules through table) are physically
# untouched; only the app that owns them in Django's state changes.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_alter_announcement_visibility_rules'),
        ('page_builder', '0002_rename_maintenance_hero'),
        ('visibility', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='rulegroupmember',
                    name='rule_group',
                ),
                migrations.AlterUniqueTogether(
                    name='rulegroupmember',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='rulegroupmember',
                    name='rule',
                ),
                migrations.AlterField(
                    model_name='element',
                    name='visibility_rules',
                    field=models.ManyToManyField(blank=True, help_text='Advanced visibility rules for conditional display', related_name='elements', to='visibility.rulegroup'),
                ),
                migrations.DeleteModel(
                    name='RuleGroup',
                ),
                migrations.DeleteModel(
                    name='RuleGroupMember',
                ),
                migrations.DeleteModel(
                    name='VisibilityRule',
                ),
            ],
        ),
    ]
