# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this object has been soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this object was soft deleted', null=True)),
                ('name', models.CharField(help_text='Display name for this group of fields', max_length=100, verbose_name='group name')),
                ('slug', models.SlugField(help_text='URL-safe identifier (auto-generated from name)', max_length=100, verbose_name='slug')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)', verbose_name='sort order')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive groups are hidden from forms but data is preserved', verbose_name='active')),
                ('show_on_storefront', models.BooleanField(default=False, help_text='Whether this group should be visible on the customer-facing storefront', verbose_name='show on storefront')),
                ('translations', models.JSONField(blank=True, default=dict, help_text='Translated group names by language code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('content_type', models.ForeignKey(help_text='Which model this group belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_groups', to='contenttypes.contenttype', verbose_name='model')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'custom field group',
                'verbose_name_plural': 'custom field groups',
                'ordering': ['content_type', 'sort_order', 'name'],
                'unique_together': {('slug', 'content_type')},
            },
        ),
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this object has been soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this object was soft deleted', null=True)),
                ('name', models.CharField(help_text='Display label shown in forms', max_length=100, verbose_name='field name')),
                ('slug', models.SlugField(help_text='JSON key used to store the value (auto-generated from name)', max_length=100, verbose_name='slug')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number (integer)'), ('decimal', 'Decimal'), ('boolean', 'Yes/No'), ('date', 'Date'), ('datetime', 'Date & Time'), ('url', 'URL'), ('email', 'Email'), ('select', 'Dropdown (single)'), ('multiselect', 'Dropdown (multiple)'), ('color', 'Color picker')], help_text='Determines the input widget and validation rules', max_length=20, verbose_name='field type')),
                ('help_text_value', models.CharField(blank=True, help_text='Hint shown below the field in forms', max_length=255, verbose_name='help text')),
                ('default_value', models.JSONField(blank=True, default=None, help_text='Default value for new records (JSON format)', null=True, verbose_name='default value')),
                ('validation_config', models.JSONField(blank=True, default=dict, help_text='Type-specific validation. Text: {"min_length": 0, "max_length": 500, "regex": "..."}. Number: {"min": 0, "max": 9999}. Select: {"choices": [{"value": "sm", "label": "Small"}, ...]}', verbose_name='validation rules')),
                ('is_required', models.BooleanField(default=False, help_text='Whether this field must be filled in', verbose_name='required')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive fields are hidden from forms but data is preserved', verbose_name='active')),
                ('show_on_storefront', models.BooleanField(default=False, help_text='Whether this field is visible on the customer-facing storefront', verbose_name='show on storefront')),
                ('is_translatable', models.BooleanField(default=False, help_text='Allow translation of this field value (text/textarea only)', verbose_name='translatable')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order within the group', verbose_name='sort order')),
                ('translations', models.JSONField(blank=True, default=dict, help_text='Translated field names and help text by language code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('content_type', models.ForeignKey(help_text='Which model this field belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_definitions', to='contenttypes.contenttype', verbose_name='model')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='Which group this field belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='custom_fields.customfieldgroup', verbose_name='group')),
            ],
            options={
                'verbose_name': 'custom field definition',
                'verbose_name_plural': 'custom field definitions',
                'ordering': ['group__sort_order', 'sort_order', 'name'],
                'unique_together': {('content_type', 'slug')},
            },
        ),
    ]
