# Generated by Django 5.1.4 on 2026-07-18 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchercode',
            name='issued_to',
            field=models.ForeignKey(blank=True, help_text='Restrict this code to one customer. Used for codes earned by a specific person (loyalty redemptions, referral rewards). Leave blank for a general promotional code.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='Issued To'),
        ),
    ]
