# Generated by Django 5.1.7 on 2026-07-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_add_voucher_issued_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchercode',
            name='currency',
            field=models.CharField(blank=True, help_text='Currency this voucher was issued in. It can only be applied to orders in the same currency.', max_length=3, verbose_name='Issued Currency'),
        ),
    ]
