# Generated by Django 5.2.16 on 2026-08-12 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0003_backfill_is_current'),
        ('vouchers', '0004_backfill_voucher_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchercode',
            name='attribution_campaign',
            field=models.ForeignKey(blank=True, help_text='Redeeming this code credits this campaign in revenue attribution.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_codes', to='attribution.campaign', verbose_name='attribution campaign'),
        ),
    ]
