# Generated by Django 5.1.4 on 2026-03-15 22:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component_updates', '0003_add_translation_provider_account'),
        ('translations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationjob',
            name='content_type',
            field=models.CharField(blank=True, help_text='Content type for the object being translated', max_length=100, null=True, verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='translationjob',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='translations.translationprovider', verbose_name='Translation Provider'),
        ),
        migrations.CreateModel(
            name='TranslationProviderAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, help_text='Friendly name for this connection (e.g., "My DeepL Account")', max_length=128, verbose_name='display name')),
                ('credentials_encrypted', models.JSONField(default=dict, help_text='Encrypted API credentials (never stored in plain text)', verbose_name='credentials')),
                ('settings', models.JSONField(default=dict, help_text='Provider-specific configuration (rate limits, timeouts, language mappings)', verbose_name='settings')),
                ('signup_url', models.URLField(blank=True, help_text='Link for merchants to create a provider account', verbose_name='signup URL')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this provider is active for translations', verbose_name='is active')),
                ('is_default', models.BooleanField(default=False, help_text='Use this provider as default for external translations', verbose_name='is default')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority providers are tried first (0 = lowest)', verbose_name='priority')),
                ('last_tested_at', models.DateTimeField(blank=True, help_text='Last successful connection test', null=True, verbose_name='last tested at')),
                ('connection_status', models.CharField(choices=[('unknown', 'Unknown'), ('connected', 'Connected'), ('error', 'Connection Error')], default='unknown', max_length=20, verbose_name='connection status')),
                ('connection_error', models.TextField(blank=True, help_text='Last connection error message', verbose_name='connection error')),
                ('total_translations', models.PositiveIntegerField(default=0, verbose_name='total translations')),
                ('total_characters', models.BigIntegerField(default=0, verbose_name='total characters translated')),
                ('total_errors', models.PositiveIntegerField(default=0, verbose_name='total errors')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('component', models.ForeignKey(help_text='Installed translation provider component', limit_choices_to={'component_type': 'translation_provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='translation_provider_accounts', to='component_updates.componentregistry', verbose_name='component')),
                ('user', models.ForeignKey(help_text='User who configured this provider account', on_delete=django.db.models.deletion.CASCADE, related_name='translation_providers', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Translation Provider Account',
                'verbose_name_plural': 'Translation Provider Accounts',
                'ordering': ['-priority', 'display_name'],
            },
        ),
        migrations.AddField(
            model_name='translationjob',
            name='provider_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='translations.translationprovideraccount', verbose_name='Provider Account'),
        ),
        migrations.AddIndex(
            model_name='translationprovideraccount',
            index=models.Index(fields=['is_active', 'priority'], name='translation_is_acti_ab8cd3_idx'),
        ),
    ]
