# Generated by Django 5.1.4 on 2026-03-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_add_translation_provider_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationprovider',
            name='provider_type',
            field=models.CharField(choices=[('local', 'Local AI (CTranslate2)'), ('custom', 'Custom API')], default='local', max_length=20, verbose_name='Provider Type'),
        ),
    ]
