# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedgiftcard',
            name='gift_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_applications', to='catalog.giftcard', verbose_name='Gift Card'),
        ),
        migrations.AddField(
            model_name='cart',
            name='pos_manual_discount_applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_cart_discounts', to=settings.AUTH_USER_MODEL, verbose_name='POS discount applied by'),
        ),
        migrations.AddField(
            model_name='cart',
            name='pos_manual_discount_approved_by',
            field=models.ForeignKey(blank=True, help_text='Manager who approved the discount if it exceeded staff limit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_cart_discount_approvals', to=settings.AUTH_USER_MODEL, verbose_name='POS discount approved by'),
        ),
    ]
