# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_initial'),
        ('catalog', '0001_initial'),
        ('media_library', '0002_initial'),
        ('orders', '0001_initial'),
        ('payment_providers', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts_as_shipping', to='orders.address', verbose_name='Shipping Address'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='appliedgiftcard',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_gift_cards', to='cart.cart', verbose_name='Cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart', verbose_name='Cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='manual_discount_applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_item_discounts', to=settings.AUTH_USER_MODEL, verbose_name='discount applied by'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='manual_discount_approved_by',
            field=models.ForeignKey(blank=True, help_text='Manager who approved the discount if it exceeded staff limit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_item_discount_approvals', to=settings.AUTH_USER_MODEL, verbose_name='discount approved by'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='parent_bundle',
            field=models.ForeignKey(blank=True, help_text='If this is a bundle component, reference to bundle CartItem', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_items', to='cart.cartitem', verbose_name='Parent Bundle'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='payment_token',
            field=models.ForeignKey(blank=True, help_text='Saved payment method for subscription billing (required for subscriptions)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.paymenttoken', verbose_name='Payment Token'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='pricing_tier',
            field=models.ForeignKey(blank=True, help_text='Selected pricing tier (billing frequency) for subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.planpricingtier', verbose_name='Pricing Tier'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, help_text='Selected subscription plan for recurring billing', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplan', verbose_name='Subscription Plan'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.productvariant', verbose_name='Variant'),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions_as_billing', to='orders.address', verbose_name='Billing Address'),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_session', to='cart.cart', verbose_name='Cart'),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='payment_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to='payment_providers.paymentprovideraccount', verbose_name='Payment Provider'),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions_as_shipping', to='orders.address', verbose_name='Shipping Address'),
        ),
        migrations.AddField(
            model_name='recentlyviewed',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='recentlyviewed',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Custom shipping method image from media library. If provided, this takes priority over icon.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_method_uses', to='media_library.mediaasset', verbose_name='Image'),
        ),
    ]
