# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0003_initial'),
        ('catalog', '0002_initial'),
        ('shipping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='pickup_locations',
            field=models.ManyToManyField(blank=True, help_text="Locations where customers can pick up orders using this shipping method. Only applies to 'local_pickup' method type.", related_name='pickup_methods', to='shipping.location', verbose_name='Pickup Locations'),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='zones',
            field=models.ManyToManyField(blank=True, help_text='Zones where this shipping method is available. If empty, legacy country/state restrictions apply.', related_name='shipping_methods', to='shipping.shippingzone', verbose_name='Shipping Zones'),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='selected_shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.shippingmethod', verbose_name='Selected Shipping Method'),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.shippingmethod', verbose_name='Shipping Method'),
        ),
        migrations.AddField(
            model_name='taxpresetrate',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='cart.taxpresetgroup', verbose_name='Preset Group'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='exempt_categories',
            field=models.ManyToManyField(blank=True, help_text='Categories exempt from this tax', to='catalog.category', verbose_name='Exempt Categories'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.productvariant', verbose_name='Variant'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.wishlist', verbose_name='Wishlist'),
        ),
        migrations.AlterUniqueTogether(
            name='appliedgiftcard',
            unique_together={('cart', 'gift_card')},
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart'], name='cart_cartit_cart_id_4fb076_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['product'], name='cart_cartit_product_985dba_idx'),
        ),
        migrations.AddIndex(
            model_name='recentlyviewed',
            index=models.Index(fields=['user', '-viewed_at'], name='cart_recent_user_id_0ae27b_idx'),
        ),
        migrations.AddIndex(
            model_name='recentlyviewed',
            index=models.Index(fields=['session_key', '-viewed_at'], name='cart_recent_session_13e17e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recentlyviewed',
            unique_together={('user', 'session_key', 'product')},
        ),
        migrations.AddIndex(
            model_name='shippingmethod',
            index=models.Index(fields=['is_active', 'sort_order'], name='cart_shippi_is_acti_c845f3_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingmethod',
            index=models.Index(fields=['method_type', 'is_active'], name='cart_shippi_method__73ceac_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutsession',
            index=models.Index(fields=['cart'], name='cart_checko_cart_id_f7a8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutsession',
            index=models.Index(fields=['expires_at'], name='cart_checko_expires_820cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='cart_cart_user_id_b645f9_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_key'], name='cart_cart_session_5e1af5_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['updated_at'], name='cart_cart_updated_c46eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['shipping_method', 'shipping_address'], name='cart_cart_shippin_8c83d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'session_key')},
        ),
        migrations.AddIndex(
            model_name='taxpresetrate',
            index=models.Index(fields=['group', 'country'], name='cart_taxpre_group_i_242f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['country', 'state', 'city'], name='cart_taxrat_country_392c67_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['is_active', '-priority'], name='cart_taxrat_is_acti_62d465_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('wishlist', 'product', 'variant')},
        ),
    ]
