# Generated by Django 5.1.4 on 2026-05-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingmethod',
            name='max_order_value',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='max_order_value_currency',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='max_weight',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='min_order_value',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='min_order_value_currency',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='min_weight',
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='method_type',
            field=models.CharField(choices=[('flat_rate', 'Flat Rate'), ('real_time', 'Real-Time Carrier Rates'), ('local_pickup', 'Local Pickup'), ('table_rate', 'Table Rate')], max_length=20, verbose_name='Method Type'),
        ),
    ]
