# Generated by Django 5.1.4 on 2026-05-31 23:21

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def consolidate_duplicate_carts(apps, schema_editor):
    """
    Consolidate any pre-existing duplicate Cart rows that share the same
    (user IS NULL, session_key) or the same user. Items are merged into the
    keeper cart (the one with the most items, then highest id), and the
    losers are deleted. Vouchers and gift cards are preserved when the
    keeper doesn't already have them.

    This logic mirrors CartService._merge_duplicate_carts but is duplicated
    here so the migration is self-contained and doesn't depend on service
    code that may evolve.
    """
    Cart = apps.get_model('cart', 'Cart')
    CartItem = apps.get_model('cart', 'CartItem')
    AppliedGiftCard = apps.get_model('cart', 'AppliedGiftCard')
    AppliedVoucher = apps.get_model('vouchers', 'AppliedVoucher')

    # We only enforce uniqueness for anonymous carts (one per session_key)
    # because license_checkout / marketplace_checkout / developer_portal
    # intentionally create separate user-bound carts. We still merge any
    # accidental duplicates of the *regular shopping cart* (user=X,
    # session_key IS NULL) as a hygiene pass, since that's the cart
    # CartService.get_or_create_cart returns for authenticated visits.

    def merge_group(carts):
        """Merge a list of duplicate carts into one keeper."""
        # Pick keeper = cart with most items, then highest id
        carts_with_counts = [(c, c.items.count()) for c in carts]
        keeper = max(carts_with_counts, key=lambda pair: (pair[1], pair[0].id))[0]
        losers = [c for c in carts if c.id != keeper.id]

        for loser in losers:
            # Move/merge each parent item from loser into keeper
            for item in list(loser.items.all()):
                if item.parent_bundle_id is not None:
                    continue  # children follow their parent
                match = None
                for existing in keeper.items.filter(
                    product=item.product,
                    variant=item.variant,
                    parent_bundle__isnull=True,
                ):
                    if existing.customizations == item.customizations:
                        match = existing
                        break
                if match:
                    match.quantity += item.quantity
                    match.save(update_fields=['quantity', 'updated_at'])
                    item.delete()
                else:
                    CartItem.objects.filter(parent_bundle=item).update(cart=keeper)
                    item.cart = keeper
                    item.save(update_fields=['cart', 'updated_at'])

            # Preserve vouchers / gift cards not already on keeper
            for v in AppliedVoucher.objects.filter(cart=loser):
                if not AppliedVoucher.objects.filter(
                    cart=keeper, voucher=v.voucher
                ).exists():
                    v.cart = keeper
                    v.save(update_fields=['cart'])
            for g in AppliedGiftCard.objects.filter(cart=loser):
                if not AppliedGiftCard.objects.filter(
                    cart=keeper, gift_card=g.gift_card
                ).exists():
                    g.cart = keeper
                    g.save(update_fields=['cart'])

            loser.delete()

        keeper.save(update_fields=['updated_at'])

    # 1. Anonymous duplicates: same session_key, user IS NULL
    anon_dupes = (
        Cart.objects
        .filter(user__isnull=True)
        .exclude(session_key__isnull=True)
        .exclude(session_key='')
        .values('session_key')
        .annotate(n=Count('id'))
        .filter(n__gt=1)
        .values_list('session_key', flat=True)
    )
    for session_key in list(anon_dupes):
        group = list(
            Cart.objects.filter(user__isnull=True, session_key=session_key)
        )
        if len(group) > 1:
            merge_group(group)

    # 2. Regular-shopping-cart duplicates per user (session_key IS NULL).
    # We don't touch user-bound carts that have a session_key set — those
    # are isolated checkout carts (license / marketplace / developer) and
    # are expected to exist alongside the regular cart.
    user_dupes = (
        Cart.objects
        .filter(user__isnull=False, session_key__isnull=True)
        .values('user_id')
        .annotate(n=Count('id'))
        .filter(n__gt=1)
        .values_list('user_id', flat=True)
    )
    for user_id in list(user_dupes):
        group = list(
            Cart.objects.filter(user_id=user_id, session_key__isnull=True)
        )
        if len(group) > 1:
            merge_group(group)


def reverse_consolidate(apps, schema_editor):
    """No-op reverse — merging is destructive and not undoable."""
    pass


class Migration(migrations.Migration):

    # Non-atomic so the RunPython data-fix commits before AddConstraint
    # tries to build the unique index. PostgreSQL refuses to CREATE INDEX
    # on a table with pending trigger events from the same transaction.
    atomic = False

    dependencies = [
        ('cart', '0005_remove_shippingmethod_max_order_value_and_more'),
        ('orders', '0003_order_language_field'),
        ('vouchers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: clear out the (non-functional) unique_together
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        # Step 2: collapse pre-existing duplicate carts before adding the
        # partial unique constraints, otherwise constraint creation fails.
        migrations.RunPython(
            consolidate_duplicate_carts,
            reverse_consolidate,
        ),
        # Step 3: add the partial unique constraint that actually works
        # in PostgreSQL when columns may be NULL. Only enforces one
        # anonymous cart per session — user-bound carts are intentionally
        # allowed to be multiple (regular shopping cart + isolated
        # license/marketplace/developer checkout carts).
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('user__isnull', True),
                    models.Q(('session_key', ''), _negated=True),
                ),
                fields=('session_key',),
                name='cart_unique_anon_per_session',
            ),
        ),
    ]
