# Generated by Django 5.1.4 on 2026-07-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_applied_gift_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='gift_card_data',
            field=models.JSONField(blank=True, default=dict, help_text='Gift card purchase details: {recipient_email, recipient_name, sender_name, message, scheduled_send_at, amount}', verbose_name='Gift Card Data'),
        ),
    ]
