# Generated by Django 5.1.4 on 2026-07-19 11:50

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_add_gift_card_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrate',
            name='exempt_product_types',
            field=models.JSONField(blank=True, default=cart.models.default_exempt_product_types, help_text='Product types exempt from this tax. Gift cards are exempt by default: selling stored value is not a taxable supply in most jurisdictions, and tax falls due when the card is spent. Confirm with your accountant.', verbose_name='Exempt Product Types'),
        ),
    ]
