# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Sender's name", max_length=200, verbose_name='Name')),
                ('email', models.EmailField(help_text="Sender's email address", max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text="Sender's phone number (optional)", max_length=30, verbose_name='Phone')),
                ('subject', models.CharField(help_text='Message subject', max_length=300, verbose_name='Subject')),
                ('message', models.TextField(help_text='Message content', verbose_name='Message')),
                ('message_type', models.CharField(choices=[('general', 'General Inquiry'), ('support', 'Support Request'), ('order', 'Order Related'), ('product', 'Product Question'), ('other', 'Other')], default='general', max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], db_index=True, default='unread', max_length=20, verbose_name='Status')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('reply_text', models.TextField(blank=True, help_text='Staff reply to the customer', verbose_name='Reply Text')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Replied At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Customer Message',
                'verbose_name_plural': 'Customer Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique identifier for the device', max_length=255, verbose_name='Device ID')),
                ('push_token', models.CharField(help_text='APNs/FCM token for push notifications', max_length=500, verbose_name='Push Token')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10, verbose_name='Platform')),
                ('notify_new_orders', models.BooleanField(default=True, help_text='Receive notifications for new orders', verbose_name='Notify New Orders')),
                ('notify_low_stock', models.BooleanField(default=True, help_text='Receive notifications for low stock alerts', verbose_name='Notify Low Stock')),
                ('notify_customer_messages', models.BooleanField(default=True, help_text='Receive notifications for customer messages', verbose_name='Notify Customer Messages')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this device should receive notifications', verbose_name='Is Active')),
                ('last_notification_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Notification At')),
                ('failed_attempts', models.PositiveIntegerField(default=0, help_text='Number of consecutive failed push attempts', verbose_name='Failed Attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Device Registration',
                'verbose_name_plural': 'Device Registrations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Token')),
                ('token_type', models.CharField(choices=[('access', 'Access Token'), ('refresh', 'Refresh Token'), ('2fa_pending', '2FA Pending Token')], max_length=12, verbose_name='Token Type')),
                ('device_id', models.CharField(help_text='Unique identifier for the device', max_length=255, verbose_name='Device ID')),
                ('device_name', models.CharField(blank=True, help_text='Human-readable device name (e.g., "iPhone 15 Pro")', max_length=255, verbose_name='Device Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Used At')),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Last Used IP')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='Is Revoked')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked At')),
                ('revoked_reason', models.CharField(blank=True, max_length=255, verbose_name='Revocation Reason')),
            ],
            options={
                'verbose_name': 'Mobile Auth Token',
                'verbose_name_plural': 'Mobile Auth Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminAPIAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('action', models.CharField(db_index=True, help_text='Action performed (e.g., "order.update_status")', max_length=100, verbose_name='Action')),
                ('resource_type', models.CharField(help_text='Type of resource (e.g., "order", "product")', max_length=50, verbose_name='Resource Type')),
                ('resource_id', models.CharField(help_text='ID of the affected resource', max_length=100, verbose_name='Resource ID')),
                ('old_value', models.JSONField(blank=True, default=dict, help_text='Previous state before the change', verbose_name='Old Value')),
                ('new_value', models.JSONField(blank=True, default=dict, help_text='New state after the change', verbose_name='New Value')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('device_id', models.CharField(blank=True, max_length=255, verbose_name='Device ID')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('success', models.BooleanField(default=True, help_text='Whether the operation succeeded', verbose_name='Success')),
                ('error_message', models.TextField(blank=True, help_text='Error details if the operation failed', verbose_name='Error Message')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_api_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Admin API Audit Log',
                'verbose_name_plural': 'Admin API Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
