# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_api', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customermessage',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Related order (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_messages', to='orders.order'),
        ),
        migrations.AddField(
            model_name='customermessage',
            name='read_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_customer_messages', to=settings.AUTH_USER_MODEL, verbose_name='Read By'),
        ),
        migrations.AddField(
            model_name='customermessage',
            name='replied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_customer_messages', to=settings.AUTH_USER_MODEL, verbose_name='Replied By'),
        ),
        migrations.AddField(
            model_name='customermessage',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Linked customer account (set when submitted while logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_messages', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_devices', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='mobileauthtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='adminapiauditlog',
            index=models.Index(fields=['user', '-timestamp'], name='admin_api_a_user_id_37f6ac_idx'),
        ),
        migrations.AddIndex(
            model_name='adminapiauditlog',
            index=models.Index(fields=['action', '-timestamp'], name='admin_api_a_action_93895c_idx'),
        ),
        migrations.AddIndex(
            model_name='adminapiauditlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='admin_api_a_resourc_3b3d46_idx'),
        ),
        migrations.AddIndex(
            model_name='adminapiauditlog',
            index=models.Index(fields=['-timestamp'], name='admin_api_a_timesta_43f287_idx'),
        ),
        migrations.AddIndex(
            model_name='customermessage',
            index=models.Index(fields=['status', '-created_at'], name='admin_api_c_status_15ea90_idx'),
        ),
        migrations.AddIndex(
            model_name='customermessage',
            index=models.Index(fields=['email', '-created_at'], name='admin_api_c_email_a8f5ca_idx'),
        ),
        migrations.AddIndex(
            model_name='customermessage',
            index=models.Index(fields=['user', '-created_at'], name='idx_customermsg_user_created'),
        ),
        migrations.AddIndex(
            model_name='deviceregistration',
            index=models.Index(fields=['user', 'is_active'], name='admin_api_d_user_id_4fb2ff_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceregistration',
            index=models.Index(fields=['platform', 'is_active'], name='admin_api_d_platfor_008409_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deviceregistration',
            unique_together={('user', 'device_id')},
        ),
        migrations.AddIndex(
            model_name='mobileauthtoken',
            index=models.Index(fields=['token', 'token_type'], name='admin_api_m_token_a9c214_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileauthtoken',
            index=models.Index(fields=['user', 'device_id'], name='admin_api_m_user_id_e6c03b_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileauthtoken',
            index=models.Index(fields=['user', 'token_type', 'is_revoked'], name='admin_api_m_user_id_e6019f_idx'),
        ),
    ]
