# Generated by Django 5.1.4 on 2026-03-19 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of the invited staff member', max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Invitation Token')),
                ('group_ids', models.JSONField(default=list, help_text='List of StaffRole IDs to assign upon acceptance', verbose_name='Role IDs')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Accepted')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Accepted At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invited By')),
            ],
            options={
                'verbose_name': 'Staff Invitation',
                'verbose_name_plural': 'Staff Invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'is_accepted'], name='admin_api_s_email_f3ec02_idx'), models.Index(fields=['token'], name='admin_api_s_token_1cede2_idx')],
            },
        ),
    ]
