# Generated by Django 5.1.4 on 2026-03-20 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_existing_replies(apps, schema_editor):
    """Convert existing single-reply data into MessageReply rows."""
    CustomerMessage = apps.get_model('admin_api', 'CustomerMessage')
    MessageReply = apps.get_model('admin_api', 'MessageReply')

    messages_with_replies = CustomerMessage.objects.exclude(
        reply_text=''
    ).exclude(reply_text__isnull=True)

    for msg in messages_with_replies:
        MessageReply.objects.create(
            message=msg,
            sender_type='staff',
            sender_user=msg.replied_by,
            content=msg.reply_text,
            email_sent=True,
            created_at=msg.replied_at or msg.updated_at,
        )
        msg.reply_count = 1
        msg.last_reply_at = msg.replied_at or msg.updated_at
        msg.last_reply_by = 'staff'
        msg.save(update_fields=['reply_count', 'last_reply_at', 'last_reply_by'])


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0003_staffinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customermessage',
            name='last_reply_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent reply', null=True, verbose_name='Last Reply At'),
        ),
        migrations.AddField(
            model_name='customermessage',
            name='last_reply_by',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('staff', 'Staff')], help_text='Who sent the last reply in this thread', max_length=10, verbose_name='Last Reply By'),
        ),
        migrations.AddField(
            model_name='customermessage',
            name='reply_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of replies in this thread', verbose_name='Reply Count'),
        ),
        migrations.CreateModel(
            name='MessageReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff')], max_length=10, verbose_name='Sender Type')),
                ('content', models.TextField(help_text='Reply message content', verbose_name='Content')),
                ('email_sent', models.BooleanField(default=False, help_text='Whether this reply was sent to the customer via email', verbose_name='Email Sent')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Email Sent At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='admin_api.customermessage', verbose_name='Message')),
                ('sender_user', models.ForeignKey(blank=True, help_text='Staff user or customer user who sent this reply', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_replies', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Message Reply',
                'verbose_name_plural': 'Message Replies',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['message', 'created_at'], name='admin_api_m_message_b97bea_idx')],
            },
        ),
        migrations.RunPython(
            migrate_existing_replies,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
