# Generated by Django 5.1.4 on 2026-03-21 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0004_message_threading'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('contact_form', 'Contact Form'), ('order_note', 'Order Note')], max_length=20, verbose_name='Source')),
                ('object_id', models.PositiveIntegerField(help_text='ID of the CustomerMessage or OrderNote', verbose_name='Object ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='Read At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_read_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Read By')),
            ],
            options={
                'verbose_name': 'Message Read Receipt',
                'verbose_name_plural': 'Message Read Receipts',
                'indexes': [models.Index(fields=['source', 'object_id'], name='admin_api_m_source_601a44_idx'), models.Index(fields=['user', 'source'], name='admin_api_m_user_id_bc8063_idx')],
                'unique_together': {('source', 'object_id', 'user')},
            },
        ),
    ]
