# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Human-readable name shown in the admin', max_length=100, verbose_name='display name')),
                ('description', models.TextField(blank=True, help_text='What this role is intended for', verbose_name='description')),
                ('icon', models.CharField(default='fas fa-user', help_text='Font Awesome icon class', max_length=50, verbose_name='icon')),
                ('color', models.CharField(choices=[('primary', 'Blue'), ('success', 'Green'), ('warning', 'Orange'), ('error', 'Red'), ('info', 'Teal'), ('default', 'Gray')], default='primary', max_length=20, verbose_name='badge color')),
                ('is_predefined', models.BooleanField(default=False, help_text='Predefined roles cannot be deleted, but can be customized', verbose_name='system role')),
                ('permission_categories', models.JSONField(blank=True, default=dict, help_text='High-level permission settings by category. Format: {"catalog": "full", "orders": "view"}', verbose_name='permission categories')),
                ('pos_permissions', models.JSONField(blank=True, default=dict, help_text='POS-specific permission flags', verbose_name='POS permissions')),
                ('can_access_admin', models.BooleanField(default=True, help_text='Whether this role can log into the admin backend', verbose_name='can access admin panel')),
                ('can_access_pos', models.BooleanField(default=False, help_text='Whether this role can use POS terminals', verbose_name='can access POS')),
                ('sort_order', models.IntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_role', to='auth.group', verbose_name='permission group')),
            ],
            options={
                'verbose_name': 'Staff Role',
                'verbose_name_plural': 'Staff Roles',
                'ordering': ['sort_order', 'display_name'],
            },
        ),
    ]
