# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable or disable search functionality globally', verbose_name='Search Enabled')),
                ('min_query_length', models.PositiveIntegerField(default=2, help_text='Minimum number of characters required to trigger search', verbose_name='Minimum Query Length')),
                ('autocomplete_enabled', models.BooleanField(default=True, help_text='Show predictive search suggestions as user types', verbose_name='Autocomplete Enabled')),
                ('autocomplete_max_results', models.PositiveIntegerField(default=8, help_text='Maximum number of suggestions per content type', verbose_name='Autocomplete Max Results')),
                ('autocomplete_debounce_ms', models.PositiveIntegerField(default=300, help_text='Delay in milliseconds before triggering autocomplete', verbose_name='Autocomplete Debounce (ms)')),
                ('show_thumbnails', models.BooleanField(default=True, help_text='Display product/content thumbnails in search results', verbose_name='Show Thumbnails')),
                ('autocomplete_product_thumbnail', models.BooleanField(default=True, help_text='Display product images in autocomplete dropdown', verbose_name='Show Product Thumbnail')),
                ('autocomplete_product_description', models.BooleanField(default=False, help_text='Display short description in autocomplete dropdown', verbose_name='Show Product Description')),
                ('autocomplete_product_price', models.BooleanField(default=True, help_text='Display price in autocomplete dropdown', verbose_name='Show Product Price')),
                ('autocomplete_product_sku', models.BooleanField(default=True, help_text='Display SKU in autocomplete dropdown', verbose_name='Show Product SKU')),
                ('autocomplete_product_stock_status', models.BooleanField(default=False, help_text='Display stock availability badge in autocomplete dropdown', verbose_name='Show Product Stock Status')),
                ('autocomplete_blog_thumbnail', models.BooleanField(default=True, help_text='Display featured image in blog post autocomplete results', verbose_name='Show Blog Featured Image')),
                ('autocomplete_blog_excerpt', models.BooleanField(default=True, help_text='Display excerpt in blog post autocomplete results', verbose_name='Show Blog Excerpt')),
                ('autocomplete_blog_excerpt_length', models.PositiveIntegerField(default=60, help_text='Maximum characters to show for blog excerpts', verbose_name='Blog Excerpt Length')),
                ('autocomplete_category_thumbnail', models.BooleanField(default=False, help_text='Display category image in autocomplete dropdown', verbose_name='Show Category Thumbnail')),
                ('autocomplete_category_product_count', models.BooleanField(default=True, help_text='Display product count in category autocomplete results', verbose_name='Show Category Product Count')),
                ('autocomplete_brand_logo', models.BooleanField(default=False, help_text='Display brand logo in autocomplete dropdown', verbose_name='Show Brand Logo')),
                ('autocomplete_brand_product_count', models.BooleanField(default=True, help_text='Display product count in brand autocomplete results', verbose_name='Show Brand Product Count')),
                ('search_products', models.BooleanField(default=True, help_text='Include products in search results', verbose_name='Search Products')),
                ('search_categories', models.BooleanField(default=True, help_text='Include categories in search results', verbose_name='Search Categories')),
                ('search_brands', models.BooleanField(default=True, help_text='Include brands in search results', verbose_name='Search Brands')),
                ('search_blog_posts', models.BooleanField(default=True, help_text='Include blog posts in search results', verbose_name='Search Blog Posts')),
                ('index_skus', models.BooleanField(default=True, help_text='Include product SKUs in search', verbose_name='Index SKUs')),
                ('index_attributes', models.BooleanField(default=True, help_text='Include product attributes (color, size, etc.) in search', verbose_name='Index Attributes')),
                ('index_custom_fields', models.BooleanField(default=True, help_text='Include custom product fields in search', verbose_name='Index Custom Fields')),
                ('index_reviews', models.BooleanField(default=True, help_text='Include product review content in search', verbose_name='Index Reviews')),
                ('index_documents', models.BooleanField(default=False, help_text='Index text content from digital asset documents (PDFs, Office files)', verbose_name='Index Documents')),
                ('fuzzy_enabled', models.BooleanField(default=True, help_text='Enable typo tolerance in search queries', verbose_name='Fuzzy Matching Enabled')),
                ('fuzzy_threshold', models.DecimalField(decimal_places=2, default=0.8, help_text='Similarity threshold for fuzzy matching (0-1, higher = stricter)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Fuzzy Threshold')),
                ('fuzzy_max_edits', models.PositiveIntegerField(default=2, help_text='Maximum character edits allowed for fuzzy matching', verbose_name='Fuzzy Max Edits')),
                ('weight_name', models.DecimalField(decimal_places=2, default=1.5, help_text='Relevance weight for product/item names', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Name Weight')),
                ('weight_sku', models.DecimalField(decimal_places=2, default=1.2, help_text='Relevance weight for SKUs', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='SKU Weight')),
                ('weight_description', models.DecimalField(decimal_places=2, default=0.8, help_text='Relevance weight for descriptions', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Description Weight')),
                ('weight_attributes', models.DecimalField(decimal_places=2, default=0.7, help_text='Relevance weight for product attributes and custom fields', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Attributes Weight')),
                ('weight_reviews', models.DecimalField(decimal_places=2, default=0.5, help_text='Relevance weight for review content', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Reviews Weight')),
                ('weight_categories', models.DecimalField(decimal_places=2, default=0.8, help_text='Relevance weight for category names', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Categories Weight')),
                ('weight_brands', models.DecimalField(decimal_places=2, default=0.7, help_text='Relevance weight for brand names', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Brands Weight')),
                ('weight_blog_posts', models.DecimalField(decimal_places=2, default=0.6, help_text='Relevance weight for blog post content', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Blog Posts Weight')),
                ('cache_autocomplete_ttl', models.PositiveIntegerField(default=60, help_text='Time to live for autocomplete cache in seconds', verbose_name='Autocomplete Cache TTL')),
                ('cache_results_ttl', models.PositiveIntegerField(default=300, help_text='Time to live for full search results cache in seconds', verbose_name='Results Cache TTL')),
                ('track_search_queries', models.BooleanField(default=True, help_text='Store search queries for analytics and trending searches', verbose_name='Track Search Queries')),
                ('track_clicks', models.BooleanField(default=True, help_text='Track clicks on search results for analytics', verbose_name='Track Clicks')),
                ('track_zero_results', models.BooleanField(default=True, help_text='Flag and track queries that return no results', verbose_name='Track Zero Results')),
                ('results_per_page', models.PositiveIntegerField(default=20, help_text='Number of results to display per page', verbose_name='Results Per Page')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Search Settings',
                'verbose_name_plural': 'Search Settings',
            },
        ),
        migrations.CreateModel(
            name='SearchEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Engine name (e.g., "Shop Search", "Blog Search")', max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(help_text='URL-safe identifier', max_length=100, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this search engine', verbose_name='Active')),
                ('content_types', models.JSONField(blank=True, default=list, help_text='List of searchable content types for this engine (e.g., ["product", "category"])', verbose_name='Content Types')),
                ('weight_overrides', models.JSONField(blank=True, default=dict, help_text='Engine-specific weight adjustments (e.g., {"weight_name": 2.0})', verbose_name='Weight Overrides')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('excluded_brands', models.ManyToManyField(blank=True, help_text='Brands to exclude from this engine', related_name='excluded_from_engines', to='catalog.brand', verbose_name='Excluded Brands')),
                ('excluded_categories', models.ManyToManyField(blank=True, help_text='Categories to exclude from this engine', related_name='excluded_from_engines', to='catalog.category', verbose_name='Excluded Categories')),
            ],
            options={
                'verbose_name': 'Search Engine',
                'verbose_name_plural': 'Search Engines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text='Original search query', max_length=500, verbose_name='Query')),
                ('query_normalized', models.CharField(db_index=True, help_text='Lowercase, trimmed query for aggregation', max_length=500, verbose_name='Normalized Query')),
                ('result_count', models.PositiveIntegerField(default=0, help_text='Number of results returned', verbose_name='Result Count')),
                ('session_key', models.CharField(blank=True, help_text='For anonymous user tracking', max_length=40, verbose_name='Session Key')),
                ('language', models.CharField(default='en', help_text='Language code of the search', max_length=10, verbose_name='Language')),
                ('is_zero_result', models.BooleanField(default=False, help_text='Whether this query returned no results', verbose_name='Zero Results')),
                ('response_time_ms', models.PositiveIntegerField(default=0, help_text='Search response time in milliseconds', verbose_name='Response Time (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='search.searchengine', verbose_name='Search Engine')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Search Query',
                'verbose_name_plural': 'Search Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('position', models.PositiveIntegerField(default=0, help_text='Position of the clicked item in search results', verbose_name='Position')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Session Key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_clicks', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='search.searchquery', verbose_name='Search Query')),
            ],
            options={
                'verbose_name': 'Search Click',
                'verbose_name_plural': 'Search Clicks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='Search term to trigger redirect', max_length=200, verbose_name='Search Term')),
                ('match_type', models.CharField(choices=[('exact', 'Exact Match'), ('contains', 'Contains'), ('starts_with', 'Starts With'), ('regex', 'Regular Expression')], default='exact', help_text='How to match the search term', max_length=20, verbose_name='Match Type')),
                ('redirect_url', models.CharField(help_text='Target URL (can be relative like /products/sale/ or absolute)', max_length=500, verbose_name='Redirect URL')),
                ('redirect_type', models.CharField(choices=[('temporary', 'Temporary (302)'), ('permanent', 'Permanent (301)')], default='temporary', help_text='HTTP redirect status code', max_length=20, verbose_name='Redirect Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('hit_count', models.PositiveIntegerField(default=0, help_text='Number of times this redirect was triggered', verbose_name='Hit Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('engine', models.ForeignKey(blank=True, help_text='Apply to specific engine only. Leave blank for all engines.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to='search.searchengine', verbose_name='Search Engine')),
            ],
            options={
                'verbose_name': 'Search Redirect',
                'verbose_name_plural': 'Search Redirects',
                'ordering': ['-hit_count', 'term'],
            },
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='Original search term', max_length=100, verbose_name='Term')),
                ('synonyms', models.JSONField(default=list, help_text='List of equivalent terms (e.g., ["sweater", "pullover"])', verbose_name='Synonyms')),
                ('is_bidirectional', models.BooleanField(default=True, help_text='Apply mapping both ways (e.g., jumper ↔ sweater)', verbose_name='Bidirectional')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('language', models.CharField(blank=True, help_text='Language code (e.g., "en", "es"). Leave blank for all languages.', max_length=10, null=True, verbose_name='Language')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('engine', models.ForeignKey(blank=True, help_text='Apply to specific engine only. Leave blank for all engines.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='search.searchengine', verbose_name='Search Engine')),
            ],
            options={
                'verbose_name': 'Synonym',
                'verbose_name_plural': 'Synonyms',
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('extracted_text', models.TextField(blank=True, help_text='Text content extracted from the document', verbose_name='Extracted Text')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('xlsx', 'Excel Spreadsheet'), ('txt', 'Text File'), ('other', 'Other')], default='other', max_length=10, verbose_name='File Type')),
                ('checksum', models.CharField(blank=True, help_text='File checksum for change detection', max_length=64, verbose_name='Checksum')),
                ('indexed_at', models.DateTimeField(auto_now=True, verbose_name='Indexed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
            ],
            options={
                'verbose_name': 'Search Index',
                'verbose_name_plural': 'Search Indexes',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='search_sear_content_97a989_idx'), models.Index(fields=['file_type'], name='search_sear_file_ty_e62dc1_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['query_normalized', 'created_at'], name='search_sear_query_n_d295cc_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['is_zero_result', 'created_at'], name='search_sear_is_zero_00a142_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['language', 'created_at'], name='search_sear_languag_172021_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['created_at'], name='search_sear_created_819524_idx'),
        ),
        migrations.AddIndex(
            model_name='searchclick',
            index=models.Index(fields=['search_query', 'created_at'], name='search_sear_search__3fafb0_idx'),
        ),
        migrations.AddIndex(
            model_name='searchclick',
            index=models.Index(fields=['content_type', 'object_id'], name='search_sear_content_630234_idx'),
        ),
        migrations.AddIndex(
            model_name='searchredirect',
            index=models.Index(fields=['term', 'match_type', 'is_active'], name='search_sear_term_46d6f4_idx'),
        ),
        migrations.AddIndex(
            model_name='synonym',
            index=models.Index(fields=['term', 'is_active'], name='search_syno_term_2ae8c9_idx'),
        ),
        migrations.AddIndex(
            model_name='synonym',
            index=models.Index(fields=['language', 'is_active'], name='search_syno_languag_b34280_idx'),
        ),
    ]
