# Generated by Django 5.1.4 on 2026-03-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(help_text="Base currency code (e.g., 'USD')", max_length=3, verbose_name='Base Currency')),
                ('target_currency', models.CharField(help_text="Target currency code (e.g., 'EUR')", max_length=3, verbose_name='Target Currency')),
                ('rate', models.DecimalField(decimal_places=6, help_text='Exchange rate from base to target (e.g., 0.85 means 1 USD = 0.85 EUR)', max_digits=18, verbose_name='Exchange Rate')),
                ('fetched_at', models.DateTimeField(auto_now=True, help_text='When this rate was last fetched from provider', verbose_name='Fetched At')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3, verbose_name='Base Currency')),
                ('target_currency', models.CharField(max_length=3, verbose_name='Target Currency')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Exchange Rate')),
                ('provider_name', models.CharField(help_text='Name of exchange rate provider used', max_length=255, verbose_name='Provider Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this rate snapshot was created', verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Exchange Rate History',
                'verbose_name_plural': 'Exchange Rate History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateProviderAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly name for this provider account (e.g., 'Main Exchange Rate Provider')", max_length=255, verbose_name='Account Name')),
                ('credentials', models.BinaryField(help_text='Encrypted API credentials for this provider', verbose_name='Encrypted Credentials')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this provider account is active and should be used for rate fetching', verbose_name='Active')),
                ('is_primary', models.BooleanField(default=False, help_text='Use this provider as primary source for exchange rates', verbose_name='Primary Provider')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Priority for fallback chain (lower = higher priority)', verbose_name='Priority')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Provider-specific settings and configuration', verbose_name='Provider Settings')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='When rates were last successfully fetched', null=True, verbose_name='Last Sync At')),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=32, verbose_name='Sync Status')),
                ('sync_error_message', models.TextField(blank=True, help_text='Error message from last sync attempt', verbose_name='Sync Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exchange Rate Provider Account',
                'verbose_name_plural': 'Exchange Rate Provider Accounts',
                'ordering': ['-is_primary', '-is_active', 'priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ManualExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(help_text="Base currency code (e.g., 'USD')", max_length=3, verbose_name='Base Currency')),
                ('target_currency', models.CharField(help_text="Target currency code (e.g., 'EUR')", max_length=3, verbose_name='Target Currency')),
                ('rate', models.DecimalField(decimal_places=6, help_text='Exchange rate from base to target (e.g., 0.85 means 1 base = 0.85 target)', max_digits=18, verbose_name='Exchange Rate')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this manual rate is active and should be used for conversions', verbose_name='Active')),
                ('exclude_from_auto_sync', models.BooleanField(default=False, help_text='When enabled, this rate will not be overwritten by provider sync operations. Use for rates you manage manually.', verbose_name='Locked (Exclude from Auto-Sync)')),
                ('notes', models.TextField(blank=True, help_text="Optional notes about this rate (e.g., 'Fixed rate for wholesale customers')", verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manual Exchange Rate',
                'verbose_name_plural': 'Manual Exchange Rates',
                'ordering': ['base_currency', 'target_currency'],
            },
        ),
    ]
