# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('component_updates', '0002_initial'),
        ('exchange_rates', '0001_initial'),
        ('orders', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeratehistory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_rate_snapshots', to='orders.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='exchangerateprovideraccount',
            name='component',
            field=models.ForeignKey(help_text='Exchange rate provider component from update system', limit_choices_to={'component_type': 'exchange_rate_provider'}, on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rate_accounts', to='component_updates.componentregistry', verbose_name='Provider Component'),
        ),
        migrations.AddField(
            model_name='exchangerateprovideraccount',
            name='site',
            field=models.ForeignKey(help_text='Site this provider account belongs to', on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='provider_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_rates', to='exchange_rates.exchangerateprovideraccount', verbose_name='Provider Account'),
        ),
        migrations.AddField(
            model_name='manualexchangerate',
            name='site',
            field=models.ForeignKey(help_text='Site this manual rate belongs to', on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Site'),
        ),
        migrations.AddIndex(
            model_name='exchangeratehistory',
            index=models.Index(fields=['base_currency', 'target_currency', 'created_at'], name='exchange_ra_base_cu_a9dd97_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangeratehistory',
            index=models.Index(fields=['order'], name='exchange_ra_order_i_f16ccc_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerateprovideraccount',
            index=models.Index(fields=['site', 'is_active'], name='exchange_ra_site_id_d7a9da_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerateprovideraccount',
            index=models.Index(fields=['priority'], name='exchange_ra_priorit_b3ca14_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerateprovideraccount',
            index=models.Index(fields=['is_primary'], name='exchange_ra_is_prim_50f1e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='exchangerateprovideraccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('site', 'is_primary'), name='unique_primary_provider_per_site'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['base_currency', 'target_currency'], name='exchange_ra_base_cu_59d42c_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['fetched_at'], name='exchange_ra_fetched_f26108_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('provider_account', 'base_currency', 'target_currency')},
        ),
        migrations.AddIndex(
            model_name='manualexchangerate',
            index=models.Index(fields=['base_currency', 'target_currency'], name='exchange_ra_base_cu_f7a70b_idx'),
        ),
        migrations.AddIndex(
            model_name='manualexchangerate',
            index=models.Index(fields=['is_active'], name='exchange_ra_is_acti_d6fda8_idx'),
        ),
        migrations.AddIndex(
            model_name='manualexchangerate',
            index=models.Index(fields=['site', 'is_active'], name='exchange_ra_site_id_b9ce6b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='manualexchangerate',
            unique_together={('site', 'base_currency', 'target_currency')},
        ),
    ]
