# Generated by Django 5.1.4 on 2026-05-03 14:35

import django.db.models.deletion
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_remove_shippingratetable_zones_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingpromotion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipping_promotions', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='shippingpromotion',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Promotion is active until this date/time', null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='shippingpromotion',
            name='first_time_customers_only',
            field=models.BooleanField(default=False, help_text='Promotion only applies to customers with no previous orders', verbose_name='first-time customers only'),
        ),
        migrations.AlterField(
            model_name='shippingpromotion',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this promotion is currently active', verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='shippingpromotion',
            name='max_cart_value',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', help_text='Promotion applies if cart subtotal is at most this amount', max_digits=10, null=True, verbose_name='maximum cart value'),
        ),
        migrations.AlterField(
            model_name='shippingpromotion',
            name='max_cart_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Promotion applies if total cart weight is at most this amount', max_digits=10, null=True, verbose_name='maximum cart weight (kg)'),
        ),
        migrations.AlterField(
            model_name='shippingpromotion',
            name='max_item_count',
            field=models.PositiveIntegerField(blank=True, help_text='Promotion applies if cart has at most this many items', null=True, verbose_name='maximum item count'),
        ),
        migrations.AlterField(
            model_name='shippingpromotion',
            name='min_cart_value',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', help_text='Promotion applies if cart subtotal is at least this amount', max_digits=10, null=True, verbose_name='minimum cart value'),
        ),
        migrations.AlterField(
            model_name='shippingpromotion',
            name='min_cart_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Promotion applies if total cart weight is at least this amount', max_digits=10, null=True, verbose_name='minimum cart weight (kg)'),
        ),
        migrations.AlterField(
            model_name='shippingpromotion',
            name='min_item_count',
            field=models.PositiveIntegerField(blank=True, help_text='Promotion applies if cart has at least this many items', null=True, verbose_name='minimum item count'),
        ),
        migrations.AlterField(
            model_name='shippingpromotion',
            name='priority',
            field=models.IntegerField(default=0, help_text='Promotions are evaluated in priority order (higher = evaluated first)', verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='shippingpromotion',
            name='promotion_value',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', help_text='Amount or percentage value for this promotion', max_digits=10, null=True, verbose_name='promotion value'),
        ),
        migrations.AlterField(
            model_name='shippingpromotion',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Promotion is active starting from this date/time', null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='shippingpromotion',
            name='stop_further_promotions',
            field=models.BooleanField(default=False, help_text='If this promotion matches, do not evaluate lower priority promotions', verbose_name='stop further promotions'),
        ),
        migrations.AlterModelTable(
            name='shippingpromotion',
            table='shipping_shippingrule',
        ),
    ]
