# Generated by Django 5.2.16 on 2026-08-09 23:43

import form_builder.fields
from django.db import migrations


def encrypt_existing_secrets(apps, schema_editor):
    """Encrypt any secrets already stored in plaintext (one-time). Reading yields
    the plaintext (no marker prefix) and saving re-writes it through
    EncryptedCharField.get_prep_value, which encrypts it."""
    Form = apps.get_model("form_builder", "Form")
    for form in Form.objects.exclude(recaptcha_secret_key=""):
        form.save(update_fields=["recaptcha_secret_key"])


def noop_reverse(apps, schema_editor):
    """Irreversible in practice — leave encrypted values as-is on reverse."""


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='recaptcha_secret_key',
            field=form_builder.fields.EncryptedCharField(blank=True, help_text='Required when using reCAPTCHA protection', max_length=512, verbose_name='reCAPTCHA Secret Key'),
        ),
        migrations.RunPython(encrypt_existing_secrets, noop_reverse),
    ]
