# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_initial'),
        ('migration', '0001_initial'),
        ('orders', '0001_initial'),
        ('payment_providers', '0001_initial'),
        ('pos_app', '0001_initial'),
        ('shipping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.ForeignKey(blank=True, help_text='Carrier used for shipment (links to shipping app for logo, tracking URL template)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shipping.carrierpreset', verbose_name='shipping carrier'),
        ),
        migrations.AddField(
            model_name='order',
            name='cashier',
            field=models.ForeignKey(blank=True, help_text='Staff member who processed this order (POS orders only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='migration_job',
            field=models.ForeignKey(blank=True, help_text='Migration job that imported this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_orders', to='migration.migrationjob'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.ForeignKey(blank=True, help_text='Payment provider account used for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payment_providers.paymentprovideraccount', verbose_name='payment provider'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_location',
            field=models.ForeignKey(blank=True, help_text='Location where customer will pick up this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_orders', to='shipping.location', verbose_name='Pickup Location'),
        ),
        migrations.AddField(
            model_name='order',
            name='pos_terminal',
            field=models.ForeignKey(blank=True, help_text='Terminal where this order was processed (POS orders only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pos_app.posterminal'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_ref',
            field=models.ForeignKey(blank=True, help_text='Reference to saved address used for shipping (for audit trail)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_shipping', to='orders.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='parent_bundle',
            field=models.ForeignKey(blank=True, help_text='If this is a bundle component, reference to bundle OrderItem', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_items', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse from which this item will be/was fulfilled', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.warehouse'),
        ),
        migrations.AddField(
            model_name='ordernote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordernote',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_notes', to='orders.order'),
        ),
        migrations.AddField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(help_text='Order being refunded', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order'),
        ),
        migrations.AddField(
            model_name='refund',
            name='pos_terminal',
            field=models.ForeignKey(blank=True, help_text='POS terminal where this refund was processed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='pos_app.posterminal'),
        ),
        migrations.AddField(
            model_name='refund',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who processed the refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who approved the return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='inspected_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who inspected the return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='order',
            field=models.ForeignKey(help_text='Order being returned', on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refund',
            field=models.OneToOneField(blank=True, help_text='Associated refund (created after inspection)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_request', to='orders.refund'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='return_shipment',
            field=models.ForeignKey(blank=True, help_text='Return shipment tracking (customer to warehouse)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_for_shipment', to='shipping.shipment'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='user',
            field=models.ForeignKey(help_text='Customer requesting the return', on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', 'is_default'], name='orders_addr_user_id_ff04bb_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', 'is_active'], name='orders_addr_user_id_3af5eb_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['original_address', 'version'], name='orders_addr_origina_72064c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='orders_orde_user_id_0ae59f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['source'], name='orders_orde_source_e5e59d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['source', '-created_at'], name='orders_orde_source_bb9690_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='orders_orde_order_i_5d347b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='orders_orde_product_32ff41_idx'),
        ),
        migrations.AddIndex(
            model_name='ordernote',
            index=models.Index(fields=['order', '-created_at'], name='orders_orde_order_i_acd406_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['order', '-created_at'], name='orders_refu_order_i_42a972_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status'], name='orders_refu_status_b87fcd_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['reason'], name='orders_refu_reason_230c88_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['-created_at'], name='orders_refu_created_6de148_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['pos_terminal', '-processed_at'], name='orders_refu_pos_ter_4a838d_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['order', '-requested_at'], name='orders_retu_order_i_1302d5_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['user', '-requested_at'], name='orders_retu_user_id_71c0a6_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status'], name='orders_retu_status_1e9e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['reason'], name='orders_retu_reason_be8b9f_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['-requested_at'], name='orders_retu_request_5c1b37_idx'),
        ),
    ]
