# Generated by Django 5.1.4 on 2026-03-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='language',
            field=models.CharField(blank=True, default='en', help_text='Language the customer was browsing in when placing the order', max_length=10, verbose_name='Language'),
        ),
    ]
