# Generated by Django 5.1.4 on 2026-07-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_language_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='gift_card_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
