# Generated by Django 5.2.16 on 2026-07-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_gift_card_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='channel',
            field=models.CharField(choices=[('web', 'Online Store'), ('pos', 'Point of Sale'), ('agent', 'AI Assistant')], db_index=True, default='web', help_text='Channel where this order was placed', max_length=20),
        ),
    ]
