# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customizable_product', '0001_initial'),
        ('media_library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clipartasset',
            name='media_asset',
            field=models.ForeignKey(help_text='PNG or SVG file for the clipart.', on_delete=django.db.models.deletion.PROTECT, related_name='clipart_usages', to='media_library.mediaasset', verbose_name='Image Asset'),
        ),
        migrations.AddField(
            model_name='clipartasset',
            name='product',
            field=models.ForeignKey(blank=True, help_text="Only set when scope is 'Specific Product Only'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clipart_assets', to='catalog.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='clipartasset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='customizable_product.clipartcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='customfont',
            name='bold',
            field=models.ForeignKey(blank=True, help_text='WOFF2 or TTF file for bold weight.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media_library.mediaasset', verbose_name='Bold'),
        ),
        migrations.AddField(
            model_name='customfont',
            name='bold_italic',
            field=models.ForeignKey(blank=True, help_text='WOFF2 or TTF file for bold italic style.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media_library.mediaasset', verbose_name='Bold Italic'),
        ),
        migrations.AddField(
            model_name='customfont',
            name='italic',
            field=models.ForeignKey(blank=True, help_text='WOFF2 or TTF file for italic style.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media_library.mediaasset', verbose_name='Italic'),
        ),
        migrations.AddField(
            model_name='customfont',
            name='regular',
            field=models.ForeignKey(blank=True, help_text='WOFF2 or TTF file for regular weight.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media_library.mediaasset', verbose_name='Regular'),
        ),
        migrations.AddField(
            model_name='designdraft',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_drafts', to='catalog.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='designdraft',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design_drafts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
