# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customizable_product', '0002_initial'),
        ('media_library', '0002_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='designsnapshot',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design_snapshot', to='orders.orderitem', verbose_name='Order Item'),
        ),
        migrations.AddField(
            model_name='designtemplate',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_thumbnails', to='media_library.mediaasset', verbose_name='Thumbnail'),
        ),
        migrations.AddField(
            model_name='designtemplateelement',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='customizable_product.designtemplate', verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='productdesignconfig',
            name='product',
            field=models.OneToOneField(limit_choices_to={'product_type': 'customizable'}, on_delete=django.db.models.deletion.CASCADE, related_name='design_config', to='catalog.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='designtemplate',
            name='design_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='customizable_product.productdesignconfig', verbose_name='Design Configuration'),
        ),
        migrations.AddField(
            model_name='productsurface',
            name='design_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surfaces', to='customizable_product.productdesignconfig', verbose_name='Design Configuration'),
        ),
        migrations.AddField(
            model_name='productsurface',
            name='mockup_image',
            field=models.ForeignKey(blank=True, help_text='Product photo showing this surface/angle.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surface_mockups', to='media_library.mediaasset', verbose_name='Mockup Image'),
        ),
        migrations.AddField(
            model_name='designtemplateelement',
            name='surface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_elements', to='customizable_product.productsurface', verbose_name='Surface'),
        ),
        migrations.AddField(
            model_name='saveddesign',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_designs', to='catalog.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='saveddesign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_designs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='designdraft',
            index=models.Index(fields=['token'], name='customizabl_token_c67bfb_idx'),
        ),
        migrations.AddIndex(
            model_name='designdraft',
            index=models.Index(fields=['expires_at'], name='customizabl_expires_3c9a52_idx'),
        ),
        migrations.AddIndex(
            model_name='designdraft',
            index=models.Index(fields=['session_key'], name='customizabl_session_4fb704_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='designtemplate',
            unique_together={('design_config', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='productsurface',
            unique_together={('design_config', 'slug')},
        ),
    ]
