# Generated by Django 5.1.4 on 2026-05-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizable_product', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designdraft',
            name='session_key',
            field=models.CharField(blank=True, help_text='Session key for anonymous users.', max_length=40, verbose_name='Session Key'),
        ),
    ]
