# Generated by Django 5.2.16 on 2026-07-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenticSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Master switch. When off, the store exposes no agentic surface at all — discovery, catalog, and checkout endpoints return 404.', verbose_name='Agentic commerce enabled')),
                ('kill_switch_engaged', models.BooleanField(default=False, help_text='Immediately halts all agent activity while leaving configuration intact. Use in a pinch; clear it to resume.', verbose_name='Emergency stop engaged')),
                ('ucp_enabled', models.BooleanField(default=True, verbose_name='UCP enabled')),
                ('acp_enabled', models.BooleanField(default=False, verbose_name='ACP enabled')),
                ('mcp_storefront_enabled', models.BooleanField(default=True, verbose_name='Storefront MCP enabled')),
                ('allow_unverified_read', models.BooleanField(default=True, verbose_name='Allow unverified read')),
                ('allow_unverified_checkout', models.BooleanField(default=False, verbose_name='Allow unverified checkout')),
                ('merchant_display_name', models.CharField(blank=True, max_length=255, verbose_name='Display name')),
                ('support_url', models.URLField(blank=True, max_length=2048, verbose_name='Support URL')),
                ('terms_url', models.URLField(blank=True, max_length=2048, verbose_name='Terms URL')),
                ('privacy_url', models.URLField(blank=True, max_length=2048, verbose_name='Privacy URL')),
                ('return_policy_url', models.URLField(blank=True, max_length=2048, verbose_name='Return policy URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Agentic Commerce Settings',
                'verbose_name_plural': 'Agentic Commerce Settings',
            },
        ),
    ]
