# Generated by Django 5.2.16 on 2026-07-25 06:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('transport', 'Transport signing (Web Bot Auth)'), ('ap2_mandate', 'AP2 mandate signing')], max_length=16, verbose_name='Purpose')),
                ('kty', models.CharField(max_length=8, verbose_name='Key type')),
                ('alg', models.CharField(max_length=16, verbose_name='Algorithm')),
                ('crv', models.CharField(max_length=16, verbose_name='Curve')),
                ('kid', models.CharField(max_length=64, unique=True, verbose_name='Key ID')),
                ('public_jwk', models.JSONField(default=dict, verbose_name='Public JWK')),
                ('private_key_encrypted', models.BinaryField(verbose_name='Encrypted private key')),
                ('status', models.CharField(choices=[('active', 'Active'), ('rotating', 'Rotating (published, not yet signing)'), ('retired', 'Retired')], db_index=True, default='active', max_length=12, verbose_name='Status')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Activated at')),
                ('retire_after', models.DateTimeField(blank=True, help_text='A retired key stays published in the JWKS until this time.', null=True, verbose_name='Retire after')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Agent Signing Key',
                'verbose_name_plural': 'Agent Signing Keys',
                'indexes': [models.Index(fields=['purpose', 'status'], name='agentic_age_purpose_d4cb9e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('kty', 'OKP'), ('purpose', 'transport')), models.Q(('kty', 'EC'), ('purpose', 'ap2_mandate')), _connector='OR'), name='agentic_agentkey_purpose_kty')],
            },
        ),
    ]
