# Generated by Django 5.2.16 on 2026-07-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentic', '0002_agentkey'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agentkey',
            name='agentic_agentkey_purpose_kty',
        ),
        migrations.AddConstraint(
            model_name='agentkey',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('alg', 'EdDSA'), ('crv', 'Ed25519'), ('kty', 'OKP'), ('purpose', 'transport')), models.Q(('alg', 'ES256'), ('crv', 'P-256'), ('kty', 'EC'), ('purpose', 'ap2_mandate')), _connector='OR'), name='agentic_agentkey_crypto_policy'),
        ),
    ]
