# Generated by Django 5.2.16 on 2026-08-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentic', '0005_mandate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentevent',
            name='event_type',
            field=models.CharField(choices=[('sig_verified', 'Signature verified'), ('sig_failed', 'Signature verification failed'), ('agent_seen', 'Agent seen (first use)'), ('agent_blocked', 'Agent blocked'), ('agent_unblocked', 'Agent unblocked'), ('agent_verified', 'Agent promoted to verified'), ('policy_changed', 'Policy changed')], db_index=True, max_length=24, verbose_name='Event type'),
        ),
    ]
