# Generated by Django 5.2.16 on 2026-08-15 15:40
#
# State-only extraction: VisibilityRule / RuleGroup / RuleGroupMember were moved
# out of ``page_builder`` into this app WITHOUT moving data. The tables
# (page_builder_visibilityrule / _rulegroup / _rulegroupmember) already exist and
# are left exactly as-is — this migration only teaches Django's migration STATE
# that the ``visibility`` app now owns them (see ``SeparateDatabaseAndState`` with
# an empty ``database_operations``). The matching removal from page_builder's
# state is in page_builder/migrations/0003, which depends on this one.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='RuleGroup',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=200)),
                        ('description', models.TextField(blank=True)),
                        ('logic_operator', models.CharField(choices=[('AND', 'All conditions must match'), ('OR', 'Any condition matches')], default='AND', help_text='How to combine rules in this group', max_length=3)),
                        ('is_active', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_groups', to='visibility.rulegroup')),
                    ],
                    options={
                        'verbose_name': 'Rule Group',
                        'verbose_name_plural': 'Rule Groups',
                        'db_table': 'page_builder_rulegroup',
                        'ordering': ['name'],
                    },
                ),
                migrations.CreateModel(
                    name='VisibilityRule',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(help_text='Descriptive name for this rule', max_length=200)),
                        ('description', models.TextField(blank=True, help_text='Optional description of what this rule does')),
                        ('rule_type', models.CharField(choices=[('geo_country', 'Country'), ('geo_region', 'Region/State'), ('geo_city', 'City'), ('geo_timezone', 'Time Zone'), ('user_logged_in', 'Logged In Status'), ('user_group', 'User Group'), ('user_segment', 'Customer Segment'), ('user_lifetime_value', 'Customer Lifetime Value'), ('user_order_count', 'Order Count'), ('device_type', 'Device Type'), ('browser', 'Browser'), ('operating_system', 'Operating System'), ('screen_size', 'Screen Size'), ('connection_speed', 'Connection Speed'), ('date_range', 'Date Range'), ('time_range', 'Time of Day'), ('day_of_week', 'Day of Week'), ('business_hours', 'Business Hours'), ('first_visit', 'First Time Visitor'), ('visit_count', 'Visit Count'), ('page_views', 'Page Views in Session'), ('time_on_site', 'Time on Site'), ('referrer', 'Referrer Source'), ('utm_campaign', 'UTM Campaign'), ('cart_value', 'Cart Value'), ('cart_items', 'Cart Item Count'), ('has_purchased', 'Has Purchased Before'), ('abandoned_cart', 'Has Abandoned Cart'), ('wishlist_items', 'Has Wishlist Items'), ('browser_language', 'Browser Language'), ('selected_language', 'Selected Language'), ('selected_currency', 'Selected Currency')], help_text='Type of condition to check', max_length=50)),
                        ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('contains', 'Contains'), ('not_contains', 'Does Not Contain'), ('greater_than', 'Greater Than'), ('less_than', 'Less Than'), ('in_list', 'In List'), ('not_in_list', 'Not In List'), ('is_true', 'Is True'), ('is_false', 'Is False'), ('between', 'Between'), ('regex', 'Matches Regex')], default='equals', help_text='How to compare the value', max_length=20)),
                        ('value', models.JSONField(default=dict, help_text='Value or values to compare against')),
                        ('is_active', models.BooleanField(default=True)),
                        ('priority', models.IntegerField(default=0, help_text='Higher priority rules are evaluated first')),
                        ('cache_duration', models.IntegerField(default=300, help_text='How long to cache rule evaluation results (seconds)')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'verbose_name': 'Visibility Rule',
                        'verbose_name_plural': 'Visibility Rules',
                        'db_table': 'page_builder_visibilityrule',
                        'ordering': ['-priority', 'name'],
                        'indexes': [models.Index(fields=['rule_type', 'is_active'], name='page_builde_rule_ty_5484d9_idx'), models.Index(fields=['priority', 'is_active'], name='page_builde_priorit_064b9a_idx')],
                    },
                ),
                migrations.CreateModel(
                    name='RuleGroupMember',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('order', models.IntegerField(default=0)),
                        ('rule_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visibility.rulegroup')),
                        ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visibility.visibilityrule')),
                    ],
                    options={
                        'db_table': 'page_builder_rulegroupmember',
                        'ordering': ['order'],
                        'unique_together': {('rule_group', 'rule')},
                    },
                ),
                migrations.AddField(
                    model_name='rulegroup',
                    name='rules',
                    field=models.ManyToManyField(related_name='groups', through='visibility.RuleGroupMember', to='visibility.visibilityrule'),
                ),
            ],
        ),
    ]
