# Generated by Django 5.2.16 on 2026-08-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visibility', '0002_move_content_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulegroup',
            name='priority',
            field=models.IntegerField(default=0, help_text='Order among sibling groups in the builder (lower shown first)'),
        ),
    ]
