# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('component_updates', '0002_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedProviderAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly name for this feed configuration (e.g., 'Google Shopping - US')", max_length=255, verbose_name='Account Name')),
                ('credentials', models.BinaryField(blank=True, help_text='Encrypted API credentials for this provider', null=True, verbose_name='Encrypted Credentials')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Feed configuration including attribute mapping and product filters', verbose_name='Feed Configuration')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this feed is active and should be synced', verbose_name='Active')),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary feed for this provider type', verbose_name='Primary Feed')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Sort order when displaying feeds (lower = first)', verbose_name='Priority')),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=20, verbose_name='Sync Status')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='When feed was last successfully synced', null=True, verbose_name='Last Sync At')),
                ('next_sync_at', models.DateTimeField(blank=True, help_text='When next scheduled sync should occur', null=True, verbose_name='Next Sync At')),
                ('sync_error_message', models.TextField(blank=True, help_text='Error message from last sync attempt', verbose_name='Sync Error Message')),
                ('last_error_at', models.DateTimeField(blank=True, help_text='When last error occurred', null=True, verbose_name='Last Error At')),
                ('products_in_feed', models.PositiveIntegerField(default=0, help_text='Number of products in the current feed', verbose_name='Products in Feed')),
                ('feed_url', models.CharField(blank=True, help_text='URL where feed is hosted for provider to fetch', max_length=500, verbose_name='Feed URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(help_text='Product feed provider component from update system', limit_choices_to={'component_type': 'product_feed_provider'}, on_delete=django.db.models.deletion.PROTECT, related_name='feed_provider_accounts', to='component_updates.componentregistry', verbose_name='Provider Component')),
                ('site', models.ForeignKey(help_text='Site this feed provider account belongs to', on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Feed Provider Account',
                'verbose_name_plural': 'Feed Provider Accounts',
                'ordering': ['-is_primary', '-is_active', 'priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_format', models.CharField(choices=[('xml', 'XML'), ('csv', 'CSV'), ('json', 'JSON')], max_length=10, verbose_name='Feed Format')),
                ('content', models.TextField(blank=True, help_text='Feed content for smaller feeds', verbose_name='Feed Content')),
                ('file_path', models.CharField(blank=True, help_text='File path for large feeds stored on disk', max_length=500, verbose_name='File Path')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes', verbose_name='File Size')),
                ('product_count', models.PositiveIntegerField(default=0, help_text='Number of products in this feed', verbose_name='Product Count')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('expires_at', models.DateTimeField(help_text='When this cached feed expires', verbose_name='Expires At')),
                ('stats', models.JSONField(blank=True, default=dict, help_text='Feed statistics and validation results', verbose_name='Statistics')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Download Count')),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Downloaded At')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='product_feeds.feedprovideraccount', verbose_name='Provider Account')),
            ],
            options={
                'verbose_name': 'Product Feed',
                'verbose_name_plural': 'Product Feeds',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (seconds)')),
                ('products_synced', models.PositiveIntegerField(default=0, verbose_name='Products Synced')),
                ('products_failed', models.PositiveIntegerField(default=0, verbose_name='Products Failed')),
                ('products_skipped', models.PositiveIntegerField(default=0, verbose_name='Products Skipped')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('error_details', models.JSONField(blank=True, default=dict, help_text='Detailed error information, including per-product errors', verbose_name='Error Details')),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('incremental', 'Incremental'), ('manual', 'Manual'), ('scheduled', 'Scheduled')], default='full', max_length=20, verbose_name='Sync Type')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='product_feeds.feedprovideraccount', verbose_name='Provider Account')),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='product_feeds.productfeed', verbose_name='Generated Feed')),
            ],
            options={
                'verbose_name': 'Feed Sync Log',
                'verbose_name_plural': 'Feed Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='feedprovideraccount',
            index=models.Index(fields=['site', 'is_active'], name='product_fee_site_id_8e7a5a_idx'),
        ),
        migrations.AddIndex(
            model_name='feedprovideraccount',
            index=models.Index(fields=['priority'], name='product_fee_priorit_00dcc7_idx'),
        ),
        migrations.AddIndex(
            model_name='feedprovideraccount',
            index=models.Index(fields=['is_primary'], name='product_fee_is_prim_fe25ab_idx'),
        ),
        migrations.AddIndex(
            model_name='feedprovideraccount',
            index=models.Index(fields=['sync_status'], name='product_fee_sync_st_074a91_idx'),
        ),
        migrations.AddIndex(
            model_name='feedprovideraccount',
            index=models.Index(fields=['next_sync_at'], name='product_fee_next_sy_9acbe4_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedprovideraccount',
            constraint=models.UniqueConstraint(fields=('site', 'component', 'name'), name='unique_feed_account_per_site_component'),
        ),
        migrations.AddIndex(
            model_name='productfeed',
            index=models.Index(fields=['account', '-generated_at'], name='product_fee_account_3c8308_idx'),
        ),
        migrations.AddIndex(
            model_name='productfeed',
            index=models.Index(fields=['expires_at'], name='product_fee_expires_a63c27_idx'),
        ),
        migrations.AddIndex(
            model_name='feedsynclog',
            index=models.Index(fields=['account', '-started_at'], name='product_fee_account_e7ebbf_idx'),
        ),
        migrations.AddIndex(
            model_name='feedsynclog',
            index=models.Index(fields=['status'], name='product_fee_status_9cc73a_idx'),
        ),
    ]
