# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import media_library.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSizePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(blank=True, help_text="Human-readable name (e.g., 'Small', 'Product Listing')", max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('width', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('crop_mode', models.CharField(choices=[('contain', 'Contain - Fit within dimensions'), ('cover', 'Cover - Fill dimensions'), ('crop', 'Crop - Exact dimensions'), ('pad', 'Pad - Fit and add padding (preserves all content)'), ('smart', 'Smart Crop - Focus on important areas')], default='cover', max_length=20)),
                ('padding_color', models.CharField(choices=[('transparent', 'Transparent'), ('white', 'White'), ('black', 'Black')], default='transparent', help_text='Padding color when using "pad" crop mode. Use "transparent" for logos.', max_length=20)),
                ('quality', models.IntegerField(default=85, help_text='WebP quality (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_preset', models.BooleanField(default=False, editable=False, help_text='System presets cannot be deleted or have their names/slugs changed')),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MediaFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('path', models.CharField(editable=False, max_length=500, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='MediaProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('upload', 'File Upload'), ('convert_video', 'Video Conversion'), ('generate_thumbnails', 'Thumbnail Generation'), ('optimize_image', 'Image Optimization')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('processing', 'Processing'), ('converting', 'Converting Video'), ('generating_thumbnails', 'Generating Thumbnails'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status_message', models.CharField(blank=True, max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_preset', models.CharField(max_length=50)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('file', models.ImageField(upload_to=media_library.models.thumbnail_upload_path)),
                ('webp_file', models.ImageField(blank=True, null=True, upload_to=media_library.models.thumbnail_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['size_preset'],
            },
        ),
        migrations.CreateModel(
            name='MediaUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this object has been soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this object was soft deleted', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='Original media ID from source platform', max_length=100)),
                ('original_file', models.FileField(help_text='Original uploaded file', upload_to=media_library.models.media_upload_path)),
                ('webp_file', models.FileField(blank=True, help_text='WebP version of the image', null=True, upload_to=media_library.models.media_upload_path)),
                ('converted_video', models.FileField(blank=True, help_text='Optimized/converted video file', null=True, upload_to=media_library.models.media_upload_path)),
                ('poster_image', models.ImageField(blank=True, help_text='Video poster/thumbnail image', null=True, upload_to=media_library.models.media_upload_path)),
                ('duration', models.FloatField(blank=True, help_text='Video duration in seconds', null=True)),
                ('frame_rate', models.FloatField(blank=True, help_text='Video frame rate (fps)', null=True)),
                ('bitrate', models.IntegerField(blank=True, help_text='Video bitrate in bits/sec', null=True)),
                ('video_codec', models.CharField(blank=True, help_text='Video codec (e.g., h264, av1, vp9)', max_length=50)),
                ('audio_codec', models.CharField(blank=True, help_text='Audio codec (e.g., aac, opus, vorbis)', max_length=50)),
                ('file_size', models.PositiveIntegerField()),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(choices=[('image/jpeg', 'JPEG'), ('image/png', 'PNG'), ('image/gif', 'GIF'), ('image/webp', 'WebP'), ('image/svg+xml', 'SVG'), ('video/mp4', 'MP4'), ('video/webm', 'WebM'), ('video/quicktime', 'MOV'), ('video/x-matroska', 'MKV'), ('video/x-msvideo', 'AVI'), ('model/gltf-binary', 'GLB'), ('model/gltf+json', 'glTF'), ('image/hdr', 'HDR')], max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='EXIF data and other metadata')),
                ('translations', models.JSONField(blank=True, default=dict, help_text='Translations for title, alt_text, and description')),
                ('focal_point_x', models.FloatField(default=0.5, help_text='X coordinate of focal point (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('focal_point_y', models.FloatField(default=0.5, help_text='Y coordinate of focal point (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.PositiveIntegerField(default=0, editable=False)),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
