# Generated by Django 5.1.4 on 2026-03-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
        ('migration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='migration_job',
            field=models.ForeignKey(blank=True, help_text='Migration job that imported this media asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_media', to='migration.migrationjob'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediafolder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediafolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='media_library.mediafolder'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='media_library.mediafolder'),
        ),
        migrations.AddField(
            model_name='mediaprocessingjob',
            name='media_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='mediaprocessingjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediathumbnail',
            name='media_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='mediausage',
            name='media_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='assets', to='media_library.tag'),
        ),
        migrations.AddIndex(
            model_name='mediaprocessingjob',
            index=models.Index(fields=['status', 'created_at'], name='media_libra_status_cba306_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaprocessingjob',
            index=models.Index(fields=['user', 'status'], name='media_libra_user_id_d4a105_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mediathumbnail',
            unique_together={('media_asset', 'size_preset')},
        ),
        migrations.AlterUniqueTogether(
            name='mediausage',
            unique_together={('media_asset', 'content_type', 'object_id', 'field_name')},
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['mime_type'], name='media_libra_mime_ty_df5233_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['created_at'], name='media_libra_created_2f9af3_idx'),
        ),
    ]
