# Generated by Django 5.2.16 on 2026-07-27 11:38

import media_library.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='avif_file',
            field=models.FileField(blank=True, help_text='AVIF version of the image', null=True, upload_to=media_library.models.media_upload_path),
        ),
        migrations.AddField(
            model_name='mediathumbnail',
            name='avif_file',
            field=models.ImageField(blank=True, null=True, upload_to=media_library.models.thumbnail_upload_path),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='mime_type',
            field=models.CharField(choices=[('image/jpeg', 'JPEG'), ('image/png', 'PNG'), ('image/gif', 'GIF'), ('image/webp', 'WebP'), ('image/avif', 'AVIF'), ('image/svg+xml', 'SVG'), ('video/mp4', 'MP4'), ('video/webm', 'WebM'), ('video/quicktime', 'MOV'), ('video/x-matroska', 'MKV'), ('video/x-msvideo', 'AVI'), ('model/gltf-binary', 'GLB'), ('model/gltf+json', 'glTF'), ('image/hdr', 'HDR')], max_length=50),
        ),
    ]
